Repository elastic/integrations, pull requests merged in 2020-07, with the labels that each got.

#140 Remove os.* vars from integrations
  packages/mongodb/dataset/log/manifest.yml
  packages/nginx/dataset/access/manifest.yml
  packages/nginx/dataset/error/manifest.yml
  packages/nginx/dataset/ingress_controller/manifest.yml
  packages/redis/dataset/log/manifest.yml
  packages/system/dataset/auth/manifest.yml
  packages/system/dataset/syslog/manifest.yml
Labels: Team:Integrations, deprecation

#147 Define missing categories
  CONTRIBUTING.md
  packages/apache/manifest.yml
  packages/aws/manifest.yml
  packages/cisco/manifest.yml
  packages/kafka/manifest.yml
  packages/kubernetes/manifest.yml
  packages/log/manifest.yml
  packages/mongodb/manifest.yml
  packages/mysql/manifest.yml
  packages/netflow/manifest.yml
  packages/nginx/manifest.yml
  packages/postgresql/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/redis/manifest.yml
  packages/system/manifest.yml
  packages/windows/manifest.yml
Labels: Team:Integrations

#146 Rename logs to logfile
  dev/import-beats/packages.go
  dev/import-beats/streams.go
  packages/apache/dataset/access/manifest.yml
  packages/apache/dataset/error/manifest.yml
  packages/apache/manifest.yml
  packages/cisco/dataset/asa/manifest.yml
  packages/cisco/dataset/ftd/manifest.yml
  packages/cisco/dataset/ios/manifest.yml
  packages/cisco/manifest.yml
  packages/kafka/dataset/log/manifest.yml
  packages/kafka/manifest.yml
  packages/log/dataset/log/manifest.yml
  packages/log/manifest.yml
  packages/mongodb/dataset/log/manifest.yml
  packages/mongodb/manifest.yml
  packages/mysql/dataset/error/manifest.yml
  packages/mysql/dataset/slowlog/manifest.yml
  packages/mysql/manifest.yml
  packages/nginx/dataset/access/manifest.yml
  packages/nginx/dataset/error/manifest.yml
  packages/nginx/dataset/ingress_controller/manifest.yml
  packages/nginx/manifest.yml
  packages/postgresql/dataset/log/manifest.yml
  packages/postgresql/manifest.yml
  packages/rabbitmq/dataset/log/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/redis/dataset/log/manifest.yml
  packages/redis/manifest.yml
  packages/system/dataset/auth/manifest.yml
  packages/system/dataset/syslog/manifest.yml
  packages/system/manifest.yml
Labels: Team:Integrations

#149 Use constraints instead of requirements
  dev/import-beats/conditions.go
  dev/import-beats/packages.go
  go.mod
  go.sum
  packages/apache/manifest.yml
  packages/aws/manifest.yml
  packages/cisco/manifest.yml
  packages/kafka/manifest.yml
  packages/kubernetes/manifest.yml
  packages/mongodb/manifest.yml
  packages/mysql/manifest.yml
  packages/netflow/manifest.yml
  packages/nginx/manifest.yml
  packages/postgresql/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/redis/manifest.yml
  packages/system/manifest.yml
  packages/windows/manifest.yml
  vendor/github.com/elastic/package-registry/util/dataset.go
  vendor/github.com/elastic/package-registry/util/package.go
  vendor/modules.txt
Labels: Team:Integrations, bug

#152 Set required kibana version to ^7.9.0
  CONTRIBUTING.md
  dev/import-beats/conditions.go
  dev/import-beats/packages.go
  packages/apache/manifest.yml
  packages/aws/manifest.yml
  packages/cisco/manifest.yml
  packages/kafka/manifest.yml
  packages/kubernetes/manifest.yml
  packages/mongodb/manifest.yml
  packages/mysql/manifest.yml
  packages/netflow/manifest.yml
  packages/nginx/manifest.yml
  packages/postgresql/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/redis/manifest.yml
  packages/system/manifest.yml
  packages/windows/manifest.yml
Labels: Team:Integrations

#154 Assign owners to packages
  CONTRIBUTING.md
  dev/import-beats/packages.go
  packages/apache/manifest.yml
  packages/aws/manifest.yml
  packages/cisco/manifest.yml
  packages/kafka/manifest.yml
  packages/kubernetes/manifest.yml
  packages/log/manifest.yml
  packages/mongodb/manifest.yml
  packages/mysql/manifest.yml
  packages/netflow/manifest.yml
  packages/nginx/manifest.yml
  packages/postgresql/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/redis/manifest.yml
  packages/system/manifest.yml
  packages/windows/manifest.yml
Labels: Team:Integrations, enhancement

#143 Define pipeline test cases for nginx.access
  packages/nginx/dataset/access/test/test-access-events.json
  packages/nginx/dataset/access/test/test-access-expected.json
Labels: Team:Integrations, enhancement

#162 Add Zookeeper integration
  dev/import-beats-resources/zookeeper/docs/README.md
  packages/zookeeper/dataset/connection/agent/stream/stream.yml.hbs
  packages/zookeeper/dataset/connection/fields/base-fields.yml
  packages/zookeeper/dataset/connection/fields/fields.yml
  packages/zookeeper/dataset/connection/manifest.yml
  packages/zookeeper/dataset/connection/sample_event.json
  packages/zookeeper/dataset/mntr/agent/stream/stream.yml.hbs
  packages/zookeeper/dataset/mntr/fields/base-fields.yml
  packages/zookeeper/dataset/mntr/fields/ecs.yml
  packages/zookeeper/dataset/mntr/fields/fields.yml
  packages/zookeeper/dataset/mntr/manifest.yml
  packages/zookeeper/dataset/mntr/sample_event.json
  packages/zookeeper/dataset/server/agent/stream/stream.yml.hbs
  packages/zookeeper/dataset/server/fields/base-fields.yml
  packages/zookeeper/dataset/server/fields/fields.yml
  packages/zookeeper/dataset/server/manifest.yml
  packages/zookeeper/dataset/server/sample_event.json
  packages/zookeeper/docs/README.md
  packages/zookeeper/img/metricbeat-zookeeper.png
  packages/zookeeper/img/zookeeper.svg
  packages/zookeeper/kibana/dashboard/467207a0-231e-11e9-bb66-8baac426dfd4-ecs.json
  packages/zookeeper/kibana/visualization/1c2f8930-231a-11e9-bb66-8baac426dfd4-ecs.json
  packages/zookeeper/kibana/visualization/8d3b7770-2319-11e9-bb66-8baac426dfd4-ecs.json
  packages/zookeeper/kibana/visualization/c0be43c0-2319-11e9-bb66-8baac426dfd4-ecs.json
  packages/zookeeper/kibana/visualization/d2f52b50-231c-11e9-bb66-8baac426dfd4-ecs.json
  packages/zookeeper/kibana/visualization/ddb13c60-231b-11e9-bb66-8baac426dfd4-ecs.json
  packages/zookeeper/manifest.yml
Labels: Beta1, Team:Integrations

#164 Update link IDs in system dashboards
  packages/system/kibana/visualization/3d65d450-a9c3-11e7-af20-67db8aecb295-ecs.json
  packages/system/kibana/visualization/855899e0-1b1c-11e7-b09e-037021c4f8df-ecs.json
  packages/system/kibana/visualization/System-Navigation-ecs.json
  packages/system/kibana/visualization/fe064790-1b1f-11e7-bec4-a5e9ec5cab8b-ecs.json
  packages/system/manifest.yml
Labels: Team:Integrations, bug

#114 Migrate Prometheus Module to Package
  dev/import-beats-resources/prometheus/docs/README.md
  packages/prometheus/dataset/collector/agent/stream/stream.yml.hbs
  packages/prometheus/dataset/collector/fields/base-fields.yml
  packages/prometheus/dataset/collector/fields/fields.yml
  packages/prometheus/dataset/collector/manifest.yml
  packages/prometheus/dataset/collector/sample_event.json
  packages/prometheus/dataset/query/agent/stream/stream.yml.hbs
  packages/prometheus/dataset/query/fields/base-fields.yml
  packages/prometheus/dataset/query/fields/fields.yml
  packages/prometheus/dataset/query/manifest.yml
  packages/prometheus/dataset/query/sample_event.json
  packages/prometheus/dataset/remote_write/agent/stream/stream.yml.hbs
  packages/prometheus/dataset/remote_write/fields/base-fields.yml
  packages/prometheus/dataset/remote_write/fields/fields.yml
  packages/prometheus/dataset/remote_write/manifest.yml
  packages/prometheus/dataset/remote_write/sample_event.json
  packages/prometheus/docs/README.md
  packages/prometheus/img/logo_prometheus.svg
  packages/prometheus/img/metricbeat-prometheus-overview.png
  packages/prometheus/kibana/dashboard/6a9b80c0-b2ed-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/0b356630-b308-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/138704c0-b2f8-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/19886730-b2e7-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/79345b00-b2e5-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/d7740b40-b2fc-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/edd33100-b305-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/f77c5900-b2e4-11e9-9a23-67ee28886a4b.json
  packages/prometheus/kibana/visualization/ffb70040-b2ec-11e9-9a23-67ee28886a4b.json
  packages/prometheus/manifest.yml
Labels: Team:Integrations

#170 fix nginx search asset id
  packages/nginx/kibana/search/Filebeat-Nginx-module-ecs.json
Labels: bug

#168 Change datasources to config_templates in manifest.yml
  packages/mongodb/manifest.yml
Labels: Team:Platforms

#174 Use minimum kibana version
  CONTRIBUTING.md
  dev/import-beats/conditions.go
  packages/apache/manifest.yml
  packages/aws/manifest.yml
  packages/cisco/manifest.yml
  packages/iis/manifest.yml
  packages/kafka/manifest.yml
  packages/kubernetes/manifest.yml
  packages/mongodb/manifest.yml
  packages/mysql/manifest.yml
  packages/netflow/manifest.yml
  packages/nginx/manifest.yml
  packages/postgresql/manifest.yml
  packages/prometheus/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/redis/manifest.yml
  packages/system/manifest.yml
  packages/windows/manifest.yml
  packages/zookeeper/manifest.yml
Labels: bug

#176 Mark packages as experimental + bump minor versions
  packages/apache/manifest.yml
  packages/aws/manifest.yml
  packages/cisco/manifest.yml
  packages/iis/manifest.yml
  packages/kafka/manifest.yml
  packages/kubernetes/manifest.yml
  packages/log/manifest.yml
  packages/mongodb/manifest.yml
  packages/mysql/manifest.yml
  packages/netflow/manifest.yml
  packages/nginx/manifest.yml
  packages/postgresql/manifest.yml
  packages/prometheus/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/redis/manifest.yml
  packages/system/manifest.yml
  packages/windows/manifest.yml
  packages/zookeeper/manifest.yml
Labels: Team:Integrations

#166 Add queue_url as a parameter for each individual log dataset
  packages/aws/dataset/cloudtrail/manifest.yml
  packages/aws/dataset/cloudwatch_logs/manifest.yml
  packages/aws/dataset/ec2_logs/manifest.yml
  packages/aws/dataset/elb_logs/manifest.yml
  packages/aws/dataset/s3access/manifest.yml
  packages/aws/dataset/vpcflow/manifest.yml
  packages/aws/manifest.yml
Labels: Team:Platforms

#180 Fix nanocore sum for non default intervals on Kubernetes Overview Dashboard
  packages/kubernetes/kibana/visualization/44f12b40-2bf4-11e7-859b-f78b612cde28-ecs.json
  packages/kubernetes/manifest.yml
Labels: Team:Platforms

#187 Do not use volumes, but rebuild container
  CONTRIBUTING.md
  magefile.go
  testing/environments/Dockerfile.package-registry
  testing/environments/package-registry.config.yml
  testing/environments/snapshot.yml
Labels: enhancement

#188 Fix markdown link to Nginx home page
  dev/import-beats-resources/nginx/docs/README.md
  packages/nginx/docs/README.md
Labels: bug

#190 Fix minor capitalisation issue
  packages/kubernetes/dataset/apiserver/manifest.yml
  packages/kubernetes/dataset/container/manifest.yml
  packages/kubernetes/dataset/node/manifest.yml
  packages/kubernetes/dataset/pod/manifest.yml
  packages/kubernetes/dataset/system/manifest.yml
  packages/kubernetes/dataset/volume/manifest.yml
  packages/kubernetes/manifest.yml
Labels: Team:Platforms

#192 Fix mongodb package service.address field and metrics description
  packages/mongodb/dataset/collstats/fields/base-fields.yml
  packages/mongodb/dataset/collstats/manifest.yml
  packages/mongodb/dataset/dbstats/fields/base-fields.yml
  packages/mongodb/dataset/dbstats/manifest.yml
  packages/mongodb/dataset/log/manifest.yml
  packages/mongodb/dataset/metrics/fields/base-fields.yml
  packages/mongodb/dataset/metrics/manifest.yml
  packages/mongodb/dataset/replstatus/fields/base-fields.yml
  packages/mongodb/dataset/replstatus/manifest.yml
  packages/mongodb/dataset/status/fields/base-fields.yml
  packages/mongodb/dataset/status/manifest.yml
  packages/mongodb/docs/README.md
  packages/mongodb/kibana/search/MongoDB-search-ecs.json
  packages/mongodb/kibana/search/bfc96a60-0a80-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/search/e49fe000-0a7e-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/visualization/0fef5710-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Read-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Write-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Engine-ampersand-Version-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-WiredTiger-Cache-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-asserts-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-hosts-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-memory-stats-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-operation-counters-ecs.json
  packages/mongodb/manifest.yml
Labels: Team:Platforms, bug

#194 Add optional config parameters for mongodb metrics collection
  packages/mongodb/manifest.yml
Labels: Team:Platforms

#193 Remove redundant [Metrics MongoDB] ECS from visualization titles
  packages/mongodb/kibana/dashboard/mongodb-Metrics-MongoDB-ecs.json
  packages/mongodb/kibana/dashboard/mongodb-abcf35b0-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/search/MongoDB-search-ecs.json
  packages/mongodb/kibana/search/bfc96a60-0a80-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/search/e49fe000-0a7e-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/visualization/0fef5710-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Read-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Write-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Engine-ampersand-Version-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-WiredTiger-Cache-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-asserts-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-hosts-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-memory-stats-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-operation-counters-ecs.json
Labels: Team:Platforms

#195 MongoDB: Improve field definitions
  packages/mongodb/manifest.yml
Labels: enhancement

#197 Add period options for state_* and scheduler datasets
  packages/kubernetes/dataset/scheduler/manifest.yml
  packages/kubernetes/dataset/state_container/manifest.yml
  packages/kubernetes/dataset/state_cronjob/manifest.yml
  packages/kubernetes/dataset/state_deployment/manifest.yml
  packages/kubernetes/dataset/state_node/manifest.yml
  packages/kubernetes/dataset/state_persistentvolume/manifest.yml
  packages/kubernetes/dataset/state_persistentvolumeclaim/manifest.yml
  packages/kubernetes/dataset/state_pod/manifest.yml
  packages/kubernetes/dataset/state_replicaset/manifest.yml
  packages/kubernetes/dataset/state_resourcequota/manifest.yml
  packages/kubernetes/dataset/state_service/manifest.yml
  packages/kubernetes/dataset/state_statefulset/manifest.yml
  packages/kubernetes/dataset/state_storageclass/manifest.yml
  packages/kubernetes/manifest.yml
Labels: Team:Platforms

#200 Fix UpdatePackageStorage to support 3 branches model
  dev/update-package-storage/git.go
  dev/update-package-storage/github.go
  dev/update-package-storage/main.go
  dev/update-package-storage/packages.go
  packages/base/docs/README.md
  packages/base/elasticsearch/component_template/events-mappings.json
  packages/base/elasticsearch/component_template/events-settings.json
  packages/base/elasticsearch/component_template/logs-mappings.json
  packages/base/elasticsearch/component_template/logs-settings.json
  packages/base/elasticsearch/component_template/metrics-mappings.json
  packages/base/elasticsearch/component_template/metrics-settings.json
  packages/base/elasticsearch/ilm_policy/events-default.json
  packages/base/elasticsearch/ilm_policy/logs-default.json
  packages/base/elasticsearch/ilm_policy/metrics-default.json
  packages/base/elasticsearch/index_template/events.json
  packages/base/elasticsearch/index_template/logs.json
  packages/base/elasticsearch/index_template/metrics.json
  packages/base/manifest.yml
Labels: Team:Integrations, bug

#148 Add HAProxy integration
  dev/import-beats-resources/haproxy/docs/README.md
  packages/haproxy/dataset/info/agent/stream/stream.yml.hbs
  packages/haproxy/dataset/info/fields/base-fields.yml
  packages/haproxy/dataset/info/fields/ecs.yml
  packages/haproxy/dataset/info/fields/fields.yml
  packages/haproxy/dataset/info/manifest.yml
  packages/haproxy/dataset/info/sample_event.json
  packages/haproxy/dataset/log/agent/stream/log.yml.hbs
  packages/haproxy/dataset/log/agent/stream/syslog.yml.hbs
  packages/haproxy/dataset/log/elasticsearch/ingest_pipeline/default.yml
  packages/haproxy/dataset/log/fields/base-fields.yml
  packages/haproxy/dataset/log/fields/ecs.yml
  packages/haproxy/dataset/log/fields/fields.yml
  packages/haproxy/dataset/log/fields/package-fields.yml
  packages/haproxy/dataset/log/manifest.yml
  packages/haproxy/dataset/stat/agent/stream/stream.yml.hbs
  packages/haproxy/dataset/stat/fields/base-fields.yml
  packages/haproxy/dataset/stat/fields/ecs.yml
  packages/haproxy/dataset/stat/fields/fields.yml
  packages/haproxy/dataset/stat/manifest.yml
  packages/haproxy/dataset/stat/sample_event.json
  packages/haproxy/docs/README.md
  packages/haproxy/img/kibana-haproxy-overview.png
  packages/haproxy/img/logo_haproxy.svg
  packages/haproxy/kibana/dashboard/0836a4b0-47bd-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/dashboard/3560d580-aa34-11e8-9c06-877f0445e3e0-ecs.json
  packages/haproxy/kibana/dashboard/4b555c30-47dd-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/dashboard/8cc50a50-47e0-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/dashboard/9151c900-471d-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/dashboard/d5878d00-47c5-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/dashboard/e9057ae0-47c5-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/0751ed00-479c-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/11f8b9c0-aa32-11e8-9c06-877f0445e3e0-ecs.json
  packages/haproxy/kibana/visualization/30956d00-47d7-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/40bed190-473b-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/55251360-aa32-11e8-9c06-877f0445e3e0-ecs.json
  packages/haproxy/kibana/visualization/68af8ef0-aa33-11e8-9c06-877f0445e3e0-ecs.json
  packages/haproxy/kibana/visualization/72e84b00-47e1-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/79350d50-47db-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/794b6cd0-471d-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/7fb671f0-aa32-11e8-9c06-877f0445e3e0-ecs.json
  packages/haproxy/kibana/visualization/86159190-47c5-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/8c8f0300-47dc-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/976b0910-47e4-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/981d1040-47be-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/a64b4fd0-471c-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/b3463670-47a1-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/bb0ab500-4735-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/f1e27ed0-47dc-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/kibana/visualization/fcbdfa60-47bd-11e8-bc13-1397384faad3-ecs.json
  packages/haproxy/manifest.yml
Labels: Team:Integrations

#207 Fix: properly handle first release
  dev/update-package-storage/main.go
Labels: bug

#209 Use elastic-package to build integrations
  go.mod
  go.sum
  magefile.go
  magefile_mapstr.go
  packages/log/manifest.yml
  vendor/github.com/magefile/mage/LICENSE
  vendor/github.com/magefile/mage/mg/color.go
  vendor/github.com/magefile/mage/mg/color_string.go
  vendor/github.com/magefile/mage/mg/runtime.go
  vendor/github.com/magefile/mage/sh/cmd.go
  vendor/modules.txt
Labels: Team:Integrations, enhancement

#208 [system] fix readme in system package
  dev/import-beats-resources/system/docs/README.md
  packages/system/docs/README.md
  packages/system/manifest.yml
Labels: bug, documentation
