Repository elastic/integrations, pull requests merged in 2020-12, with the labels that each got.

#426 Fix typo in aws integration
  packages/aws/manifest.yml
Labels: Team:Platforms, bug

#416 Add system test for Cisco IOS
  packages/cisco/_dev/deploy/docker/Dockerfile
  packages/cisco/_dev/deploy/docker/cisco-ios.log
  packages/cisco/_dev/deploy/docker/docker-compose.yml
  packages/cisco/data_stream/ios/_dev/test/system/config.yml
  packages/cisco/data_stream/ios/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/ios/agent/stream/syslog.yml.hbs
  packages/cisco/data_stream/ios/fields/agent.yml
  packages/cisco/data_stream/ios/fields/ecs.yml
  packages/cisco/data_stream/ios/fields/fields.yml
  packages/cisco/data_stream/ios/manifest.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations

#436 [aws package] change fileset.name to data_stream.dataset
  packages/aws/kibana/map/aws-0edf0640-3e7e-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/search/aws-5e5a3c90-bac0-11e9-9f70-1f7bda85a5eb.json
  packages/aws/kibana/search/aws-c1aee600-4487-11ea-ad63-791a5dc86f10.json
  packages/aws/kibana/visualization/aws-219c1850-3e82-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/visualization/aws-73970bc0-3e86-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/visualization/aws-75853f20-4484-11ea-ad63-791a5dc86f10.json
  packages/aws/kibana/visualization/aws-76af8140-3e84-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/visualization/aws-b6a308f0-3e82-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/visualization/aws-bad8c910-4485-11ea-ad63-791a5dc86f10.json
  packages/aws/kibana/visualization/aws-bd37d720-3e84-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/visualization/aws-ceb7c030-3e86-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/visualization/aws-d8b1e830-3e82-11ea-bb0a-69c3ca1d410f.json
  packages/aws/kibana/visualization/aws-e50c51e0-3e7f-11ea-bb0a-69c3ca1d410f.json
Labels: Team:Platforms

#440 Add santa integration
  packages/santa/_dev/build/docs/README.md
  packages/santa/_dev/deploy/docker/Dockerfile
  packages/santa/_dev/deploy/docker/docker-compose.yml
  packages/santa/_dev/deploy/docker/santa.log
  packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log
  packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-config.json
  packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
  packages/santa/data_stream/log/_dev/test/system/config.yml
  packages/santa/data_stream/log/agent/stream/log.yml.hbs
  packages/santa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/santa/data_stream/log/fields/agent.yml
  packages/santa/data_stream/log/fields/base-fields.yml
  packages/santa/data_stream/log/fields/ecs.yml
  packages/santa/data_stream/log/fields/package-fields.yml
  packages/santa/data_stream/log/manifest.yml
  packages/santa/data_stream/log/sample_event.json
  packages/santa/docs/README.md
  packages/santa/img/icon.svg
  packages/santa/img/kibana-santa-log-overview.png
  packages/santa/kibana/dashboard/santa-161855f0-ff6a-11e8-93c5-d5ecd1b3e307.json
  packages/santa/kibana/search/santa-6d56a010-ff6a-11e8-93c5-d5ecd1b3e307.json
  packages/santa/kibana/visualization/santa-11858000-ff6d-11e8-93c5-d5ecd1b3e307.json
  packages/santa/kibana/visualization/santa-1579d690-ff6b-11e8-93c5-d5ecd1b3e307.json
  packages/santa/kibana/visualization/santa-30962fe0-ff6c-11e8-93c5-d5ecd1b3e307.json
  packages/santa/kibana/visualization/santa-51677b80-ff6b-11e8-93c5-d5ecd1b3e307.json
  packages/santa/kibana/visualization/santa-b06c0460-ff6c-11e8-93c5-d5ecd1b3e307.json
  packages/santa/kibana/visualization/santa-dad521d0-ff69-11e8-93c5-d5ecd1b3e307.json
  packages/santa/manifest.yml
Labels: Team:Security-External Integrations, [zube]: In Review, enhancement

#435 Drop fields in aws vpcflow data stream when value equals to "-"
  packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-tcp-flag-sequence.log
  packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-tcp-flag-sequence.log-expected.json
  packages/aws/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
  packages/aws/manifest.yml
Labels: Team:Platforms

#430 Nginx: refactor integration
  packages/nginx/_dev/build/docs/README.md
  packages/nginx/_dev/deploy/docker/Dockerfile
  packages/nginx/_dev/deploy/docker/docker-compose.yml
  packages/nginx/_dev/deploy/docker/nginx.conf
  packages/nginx/_dev/deploy/variants.yml
  packages/nginx/data_stream/access/_dev/test/system/config.yml
  packages/nginx/data_stream/access/fields/ecs.yml
  packages/nginx/data_stream/access/fields/fields.yml
  packages/nginx/data_stream/access/sample_event.json
  packages/nginx/data_stream/error/_dev/test/system/config.yml
  packages/nginx/data_stream/error/fields/ecs.yml
  packages/nginx/data_stream/error/sample_event.json
  packages/nginx/data_stream/ingress_controller/fields/fields.yml
  packages/nginx/data_stream/stubstatus/_dev/test/system/config.yml
  packages/nginx/data_stream/stubstatus/fields/ecs.yml
  packages/nginx/data_stream/stubstatus/sample_event.json
  packages/nginx/docs/README.md
  packages/nginx/kibana/dashboard/nginx-0b3dba40-f341-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/dashboard/nginx-dfbc0840-f340-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/search/nginx-a832bcf0-f342-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/search/nginx-d20d4ea0-f342-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-1aa782a0-f345-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-78738850-f342-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-a3bf1ce0-f347-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-afd506b0-f348-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-ba138ab0-f344-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-c37e2770-f341-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-ee250270-f344-11ea-a3fd-1b45ec532bb3.json
  packages/nginx/kibana/visualization/nginx-f137cb40-f345-11ea-a3fd-1b45ec532bb3.json
Labels: Team:Services

#441 Apache: refactor integration (part II)
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-config.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-darwin.log
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-darwin.log-config.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-darwin.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ssl-request.log
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ssl-request.log-config.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ssl-request.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ubuntu.log
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ubuntu.log-config.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ubuntu.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-vhost.log
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-vhost.log-config.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-vhost.log-expected.json
  packages/apache/data_stream/access/fields/ecs.yml
  packages/apache/data_stream/access/sample_event.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-basic.log
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-basic.log-config.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-basic.log-expected.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-darwin.log
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-darwin.log-config.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-darwin.log-expected.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-ubuntu.log
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-ubuntu.log-config.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-ubuntu.log-expected.json
  packages/apache/data_stream/error/fields/ecs.yml
  packages/apache/data_stream/error/sample_event.json
  packages/apache/data_stream/status/fields/ecs.yml
  packages/apache/data_stream/status/fields/fields.yml
  packages/apache/data_stream/status/sample_event.json
  packages/apache/docs/README.md
  packages/apache/kibana/visualization/apache-HTTPD-CPU.json
  packages/apache/kibana/visualization/apache-HTTPD-Hostname-list.json
  packages/apache/kibana/visualization/apache-HTTPD-Load1-slash-5-slash-15.json
  packages/apache/kibana/visualization/apache-HTTPD-Scoreboard.json
  packages/apache/kibana/visualization/apache-HTTPD-Workers.json
Labels: Team:Services

#452 Add system test for Okta System
  packages/okta/_dev/deploy/docker/Dockerfile
  packages/okta/_dev/deploy/docker/docker-compose.yml
  packages/okta/_dev/deploy/docker/okta-system.json.log
  packages/okta/data_stream/system/_dev/test/system/config.yml
  packages/okta/data_stream/system/fields/ecs.yml
  packages/okta/docs/README.md
  packages/okta/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#447 Add system test for Microsoft DHCP
  packages/microsoft/_dev/deploy/docker/Dockerfile
  packages/microsoft/_dev/deploy/docker/docker-compose.yml
  packages/microsoft/_dev/deploy/docker/microsoft-dhcp.log
  packages/microsoft/data_stream/dhcp/_dev/test/system/config.yml
  packages/microsoft/data_stream/dhcp/agent/stream/log.yml.hbs
  packages/microsoft/data_stream/dhcp/fields/ecs.yml
  packages/microsoft/data_stream/dhcp/manifest.yml
  packages/microsoft/docs/README.md
  packages/microsoft/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#446 Add Iptables integration
  packages/iptables/_dev/build/docs/README.md
  packages/iptables/_dev/deploy/docker/Dockerfile
  packages/iptables/_dev/deploy/docker/docker-compose.yml
  packages/iptables/_dev/deploy/docker/iptables.log
  packages/iptables/data_stream/log/_dev/test/pipeline/test-iptables-raw.log
  packages/iptables/data_stream/log/_dev/test/pipeline/test-iptables-raw.log-config.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-iptables-raw.log-expected.json
  packages/iptables/data_stream/log/_dev/test/system/config.yml
  packages/iptables/data_stream/log/agent/stream/log.yml.hbs
  packages/iptables/data_stream/log/agent/stream/syslog.yml.hbs
  packages/iptables/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/iptables/data_stream/log/fields/agent.yml
  packages/iptables/data_stream/log/fields/base-fields.yml
  packages/iptables/data_stream/log/fields/ecs.yml
  packages/iptables/data_stream/log/fields/fields.yml
  packages/iptables/data_stream/log/manifest.yml
  packages/iptables/data_stream/log/sample_event.json
  packages/iptables/docs/README.md
  packages/iptables/img/kibana-iptables-ubiquiti.png
  packages/iptables/img/kibana-iptables.png
  packages/iptables/img/linux.svg
  packages/iptables/kibana/dashboard/iptables-ceefb9e0-1f51-11e9-93ed-f7e068f4aebb.json
  packages/iptables/kibana/dashboard/iptables-d39f0980-1ff3-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/search/iptables-7862cab0-1fdb-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/search/iptables-9f7d97c0-1fe9-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/search/iptables-b3f1b010-1f26-11e9-8ec4-cf5d91a864b3.json
  packages/iptables/kibana/search/iptables-c4e80aa0-1fd4-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/visualization/iptables-190bcb50-1ff6-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/visualization/iptables-1ba82fd0-1ff0-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/visualization/iptables-2599f5e0-1e98-11e9-8ec4-cf5d91a864b3.json
  packages/iptables/kibana/visualization/iptables-35fe0910-1f26-11e9-8ec4-cf5d91a864b3.json
  packages/iptables/kibana/visualization/iptables-4c913eb0-1f51-11e9-93ed-f7e068f4aebb.json
  packages/iptables/kibana/visualization/iptables-5bd53050-1fe9-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/visualization/iptables-683402b0-1f29-11e9-8ec4-cf5d91a864b3.json
  packages/iptables/kibana/visualization/iptables-758b3620-1fda-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/visualization/iptables-8853aa20-1fef-11e9-ae2a-939083c6a64e.json
  packages/iptables/kibana/visualization/iptables-b57b7370-1f1d-11e9-8ec4-cf5d91a864b3.json
  packages/iptables/kibana/visualization/iptables-c4394ec0-1efd-11e9-8ec4-cf5d91a864b3.json
  packages/iptables/kibana/visualization/iptables-d8cea010-1efd-11e9-8ec4-cf5d91a864b3.json
  packages/iptables/kibana/visualization/iptables-fdea1ad0-1ff4-11e9-ae2a-939083c6a64e.json
  packages/iptables/manifest.yml
Labels: Team:Security-External Integrations, [zube]: In Review, enhancement

#429 Add system test for CrowdStrike Falcon
  packages/crowdstrike/_dev/deploy/docker/Dockerfile
  packages/crowdstrike/_dev/deploy/docker/docker-compose.yml
  packages/crowdstrike/_dev/deploy/docker/falcon-audit-events.log
  packages/crowdstrike/_dev/deploy/docker/falcon-events.log
  packages/crowdstrike/_dev/deploy/docker/falcon-sample.log
  packages/crowdstrike/data_stream/falcon/_dev/test/system/config.yml
  packages/crowdstrike/data_stream/falcon/agent/stream/log.yml.hbs
  packages/crowdstrike/data_stream/falcon/fields/fields.yml
  packages/crowdstrike/docs/README.md
Labels: Team:Security-External Integrations

#432 Add system test for Fortinet client endpoint
  packages/fortinet/_dev/deploy/docker/Dockerfile
  packages/fortinet/_dev/deploy/docker/docker-compose.yml
  packages/fortinet/_dev/deploy/docker/fortinet-clientendpoint.log
  packages/fortinet/data_stream/clientendpoint/_dev/test/system/config.yml
  packages/fortinet/data_stream/clientendpoint/fields/ecs.yml
  packages/fortinet/docs/README.md
Labels: Team:Security-External Integrations, enhancement

#437 Add pipeline test for Fortinet Firewall
  packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log
  packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log-config.json
  packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log-expected.json
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/event.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/traffic.yml
Labels: Team:Security-External Integrations, enhancement

#443 Add pipeline test for Juniper SRX
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-config.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-config.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-config.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-config.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-config.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-config.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/flow.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/utm.yml
  packages/juniper/data_stream/srx/fields/fields.yml
  packages/juniper/manifest.yml
Labels: Team:Security-External Integrations

#444 Add system test for Juniper Netscreen
  packages/juniper/_dev/deploy/docker/Dockerfile
  packages/juniper/_dev/deploy/docker/docker-compose.yml
  packages/juniper/_dev/deploy/docker/juniper-netscreen.log
  packages/juniper/data_stream/netscreen/_dev/test/system/config.yml
  packages/juniper/data_stream/netscreen/agent/stream/log.yml.hbs
  packages/juniper/data_stream/netscreen/fields/ecs.yml
  packages/juniper/data_stream/netscreen/manifest.yml
  packages/juniper/docs/README.md
  packages/juniper/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#456 Nginx: refactor dashboards
  packages/nginx/kibana/dashboard/nginx-023d2930-f1a5-11e7-a9ef-93c69af7b129.json
  packages/nginx/kibana/dashboard/nginx-046212a0-a2a1-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/dashboard/nginx-55a9e6e0-a29e-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/search/nginx-6d9e66d0-a1f0-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/search/nginx-9eb25600-a1f0-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/search/nginx-Logs-Nginx-integration.json
  packages/nginx/kibana/visualization/nginx-0dd6f320-a29f-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/visualization/nginx-1cfb1a80-a1f4-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/visualization/nginx-46322e50-a1f6-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/visualization/nginx-47a8e0f0-f1a4-11e7-a9ef-93c69af7b129.json
  packages/nginx/kibana/visualization/nginx-555df8a0-f1a1-11e7-a9ef-93c69af7b129.json
  packages/nginx/kibana/visualization/nginx-7cc9ea40-3af8-11eb-94b7-0dab91df36a6.json
  packages/nginx/kibana/visualization/nginx-823b3c80-3af9-11eb-94b7-0dab91df36a6.json
  packages/nginx/kibana/visualization/nginx-9184fa00-a1f5-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/visualization/nginx-9484ecf0-3af5-11eb-94b7-0dab91df36a6.json
  packages/nginx/kibana/visualization/nginx-97109780-a2a5-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/visualization/nginx-Access-Browsers.json
  packages/nginx/kibana/visualization/nginx-Access-Map.json
  packages/nginx/kibana/visualization/nginx-Access-OSes.json
  packages/nginx/kibana/visualization/nginx-a1d92240-f1a1-11e7-a9ef-93c69af7b129.json
  packages/nginx/kibana/visualization/nginx-b70b1b20-a1f4-11e7-928f-5dbe6f6f5519.json
  packages/nginx/kibana/visualization/nginx-d763a570-f1a1-11e7-a9ef-93c69af7b129.json
  packages/nginx/kibana/visualization/nginx-dcbffe30-f1a4-11e7-a9ef-93c69af7b129.json
  packages/nginx/kibana/visualization/nginx-e302b5a0-3afb-11eb-94b7-0dab91df36a6.json
  packages/nginx/kibana/visualization/nginx-ea7f9e10-3af6-11eb-94b7-0dab91df36a6.json
Labels: Team:Integrations

#460 Apache: update screenshots
  packages/apache/img/apache-logs-overview.png
  packages/apache/img/apache-metrics-overview.png
  packages/apache/img/apache_httpd_server_status.png
  packages/apache/img/kibana-apache.png
  packages/apache/manifest.yml
Labels: Team:Integrations, enhancement

#414 Add pipeline tests to Cisco ASA
  go.mod
  go.sum
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/asa/fields/agent.yml
  packages/cisco/data_stream/asa/fields/ecs.yml
  packages/cisco/data_stream/asa/fields/fields.yml
  packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations

#438 Add system test for Fortinet Fortimail
  packages/fortinet/_dev/deploy/docker/Dockerfile
  packages/fortinet/_dev/deploy/docker/fortinet-fortimail.log
  packages/fortinet/data_stream/fortimail/_dev/test/system/config.yml
  packages/fortinet/data_stream/fortimail/fields/ecs.yml
  packages/fortinet/data_stream/fortimail/manifest.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#439 Add system test for Fortinet Fortimanager
  packages/fortinet/_dev/deploy/docker/Dockerfile
  packages/fortinet/_dev/deploy/docker/fortinet-fortimanager.log
  packages/fortinet/data_stream/fortimanager/_dev/test/system/config.yml
  packages/fortinet/data_stream/fortimanager/fields/ecs.yml
  packages/fortinet/data_stream/fortimanager/manifest.yml
  packages/fortinet/docs/README.md
Labels: Team:Security-External Integrations, enhancement

#461 Nginx: update screenshots
  packages/nginx/img/kibana-nginx.png
  packages/nginx/img/metricbeat-nginx.png
  packages/nginx/img/nginx-logs-access-error.png
  packages/nginx/img/nginx-logs-overview.png
  packages/nginx/img/nginx-metrics-overview.png
  packages/nginx/manifest.yml
Labels: Team:Integrations

#457 Add system and pipeline tests for Suricata EVE
  packages/suricata/_dev/deploy/docker/Dockerfile
  packages/suricata/_dev/deploy/docker/docker-compose.yml
  packages/suricata/_dev/deploy/docker/eve-alerts.ndjson
  packages/suricata/_dev/deploy/docker/eve-dns-4.1.4.ndjson
  packages/suricata/_dev/deploy/docker/eve-small.ndjson
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-events.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-events.json-config.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-events.json-expected.json
  packages/suricata/data_stream/eve/_dev/test/system/config.yml
  packages/suricata/data_stream/eve/agent/stream/log.yml.hbs
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/dns-answer-v1.yml
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/dns-answer-v2.yml
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/dns.yml
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/tls.yml
  packages/suricata/data_stream/eve/fields/ecs.yml
  packages/suricata/docs/README.md
  packages/suricata/manifest.yml
Labels: Team:Security-External Integrations

#454 Add system and pipeline test for Palo Alto PAN-OS
  packages/panw/_dev/deploy/docker/Dockerfile
  packages/panw/_dev/deploy/docker/docker-compose.yml
  packages/panw/_dev/deploy/docker/panw-panos-inc-other.log
  packages/panw/_dev/deploy/docker/panw-panos-inc-threat.log
  packages/panw/_dev/deploy/docker/panw-panos-inc-traffic.log
  packages/panw/_dev/deploy/docker/panw-panos-threat.log
  packages/panw/_dev/deploy/docker/panw-panos-traffic.log
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-config.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
  packages/panw/data_stream/panos/_dev/test/system/config.yml
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/data_stream/panos/fields/ecs.yml
  packages/panw/data_stream/panos/fields/fields.yml
  packages/panw/docs/README.md
  packages/panw/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#463 Add pipeline test for System Auth
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log-config.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log-expected.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth.log
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth.log-config.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth.log-expected.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-secure-rhel7.log
  packages/system/data_stream/auth/_dev/test/pipeline/test-secure-rhel7.log-config.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-secure-rhel7.log-expected.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-timestamp.log
  packages/system/data_stream/auth/_dev/test/pipeline/test-timestamp.log-config.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-timestamp.log-expected.json
  packages/system/data_stream/auth/fields/ecs.yml
  packages/system/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#449 Add system test for Office 365 audit
  packages/o365/_dev/deploy/docker/01-exchange-admin.log
  packages/o365/_dev/deploy/docker/02-exchange-item.log
  packages/o365/_dev/deploy/docker/04-sharepoint.log
  packages/o365/_dev/deploy/docker/06-sharepointfileop.log
  packages/o365/_dev/deploy/docker/08-azuread.log
  packages/o365/_dev/deploy/docker/11-dlp-sharepoint.log
  packages/o365/_dev/deploy/docker/13-dlp-exchange.log
  packages/o365/_dev/deploy/docker/14-sp-sharing-op.log
  packages/o365/_dev/deploy/docker/15-azuread-sts-logon.log
  packages/o365/_dev/deploy/docker/22-yammer.log
  packages/o365/_dev/deploy/docker/25-ms-teams.log
  packages/o365/_dev/deploy/docker/40-sec-comp-alerts.log
  packages/o365/_dev/deploy/docker/52-data-insights-api.log
  packages/o365/_dev/deploy/docker/Dockerfile
  packages/o365/_dev/deploy/docker/docker-compose.yml
  packages/o365/_dev/deploy/docker/ip-formats.log
  packages/o365/data_stream/audit/_dev/test/system/config.yml
  packages/o365/data_stream/audit/agent/stream/log.yml.hbs
  packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
  packages/o365/data_stream/audit/agent/stream/pipeline.js
  packages/o365/data_stream/audit/fields/fields.yml
  packages/o365/docs/README.md
  packages/o365/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#458 Apache: replace total_kbytes with total_bytes
  packages/apache/data_stream/status/fields/fields.yml
  packages/apache/data_stream/status/sample_event.json
  packages/apache/docs/README.md
  packages/apache/kibana/visualization/apache-99666080-3a20-11eb-8946-296aab7b13db.json
  packages/apache/manifest.yml
Labels: Team:Integrations, enhancement

#462 [Fleet] Add Elastic agent integration
  packages/elastic_agent/data_stream/elastic_agent/fields/agent.yml
  packages/elastic_agent/data_stream/elastic_agent/fields/base-fields.yml
  packages/elastic_agent/data_stream/elastic_agent/fields/fields.yml
  packages/elastic_agent/data_stream/elastic_agent/manifest.yml
  packages/elastic_agent/docs/README.md
  packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
  packages/elastic_agent/kibana/visualization/elastic_agent-47d87552-8421-4cfc-bc5d-4a7205f5b007.json
  packages/elastic_agent/kibana/visualization/elastic_agent-93a8a11d-b2da-4ef3-81dc-c7040560ffde.json
  packages/elastic_agent/kibana/visualization/elastic_agent-a11c250a-865f-4eb2-9441-882d229313be.json
  packages/elastic_agent/manifest.yml
Labels: Team:Ingest Management

#469 Update rsa2elk packages with domain processor
  packages/cisco/data_stream/meraki/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/meraki/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/meraki/fields/ecs.yml
  packages/cisco/data_stream/nexus/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/nexus/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/nexus/fields/ecs.yml
  packages/cisco/diff
  packages/cisco/docs/README.md
  packages/cisco/fields.missing
  packages/cisco/manifest.yml
  packages/fortinet/data_stream/clientendpoint/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/clientendpoint/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/clientendpoint/fields/ecs.yml
  packages/fortinet/data_stream/fortimail/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimail/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimail/fields/ecs.yml
  packages/fortinet/data_stream/fortimanager/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimanager/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimanager/fields/ecs.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
  packages/juniper/data_stream/junos/agent/stream/stream.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/junos/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/junos/fields/ecs.yml
  packages/juniper/data_stream/netscreen/agent/stream/log.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/netscreen/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/netscreen/fields/ecs.yml
  packages/juniper/docs/README.md
  packages/juniper/manifest.yml
  packages/microsoft/data_stream/dhcp/agent/stream/log.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/tcp.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/udp.yml.hbs
  packages/microsoft/data_stream/dhcp/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft/data_stream/dhcp/fields/ecs.yml
  packages/microsoft/docs/README.md
  packages/microsoft/manifest.yml
Labels: Team:Security-External Integrations, enhancement
