Repository elastic/integrations, pull requests merged in 2020-09, with the labels that each got.

#251 fix links in system dashboard
  packages/system/kibana/dashboard/system-Metricbeat-system-overview-ecs.json
  packages/system/manifest.yml
Labels: bug

#266 Adjust integrations to pass linting
  go.mod
  go.sum
  magefile.go
  packages/apache/manifest.yml
  packages/checkpoint/manifest.yml
  packages/crowdstrike/manifest.yml
  packages/haproxy/manifest.yml
  packages/iis/manifest.yml
  packages/log/dataset/log/manifest.yml
  packages/microsoft/manifest.yml
  packages/mongodb/manifest.yml
  packages/netflow/dataset/log/manifest.yml
  packages/prometheus/manifest.yml
  packages/rabbitmq/manifest.yml
  packages/synthetics/manifest.yml
  packages/system/dataset/process/manifest.yml
  packages/system/dataset/socket/manifest.yml
  packages/windows/manifest.yml
Labels: Team:Integrations, enhancement

#268 Update package registry version to v0.11.0
  go.mod
  go.sum
Labels: Team:Integrations

#271 Fix a few docs issues in the system integration
  dev/import-beats-resources/system/docs/README.md
  packages/system/dataset/diskio/manifest.yml
  packages/system/dataset/socket/manifest.yml
  packages/system/docs/README.md
  packages/system/manifest.yml
Labels: documentation

#278 Parse out system Integration, create Linux integration
  dev/import-beats-resources/linux/docs/README.md
  dev/import-beats-resources/system/docs/README.md
  packages/linux/dataset/entropy/agent/stream/stream.yml.hbs
  packages/linux/dataset/entropy/fields/base-fields.yml
  packages/linux/dataset/entropy/fields/fields.yml
  packages/linux/dataset/entropy/manifest.yml
  packages/linux/dataset/network_summary/agent/stream/stream.yml.hbs
  packages/linux/dataset/network_summary/fields/base-fields.yml
  packages/linux/dataset/network_summary/fields/fields.yml
  packages/linux/dataset/network_summary/manifest.yml
  packages/linux/dataset/raid/agent/stream/stream.yml.hbs
  packages/linux/dataset/raid/fields/base-fields.yml
  packages/linux/dataset/raid/fields/fields.yml
  packages/linux/dataset/raid/manifest.yml
  packages/linux/dataset/service/agent/stream/stream.yml.hbs
  packages/linux/dataset/service/fields/base-fields.yml
  packages/linux/dataset/service/fields/ecs.yml
  packages/linux/dataset/service/fields/fields.yml
  packages/linux/dataset/service/manifest.yml
  packages/linux/dataset/socket/agent/stream/stream.yml.hbs
  packages/linux/dataset/socket/fields/base-fields.yml
  packages/linux/dataset/socket/fields/ecs.yml
  packages/linux/dataset/socket/fields/fields.yml
  packages/linux/dataset/socket/manifest.yml
  packages/linux/dataset/users/agent/stream/stream.yml.hbs
  packages/linux/dataset/users/fields/base-fields.yml
  packages/linux/dataset/users/fields/fields.yml
  packages/linux/dataset/users/manifest.yml
  packages/linux/docs/README.md
  packages/linux/img/metricbeat-services-host.png
  packages/linux/kibana/dashboard/system-c431f410-f9ac-11e9-90e8-1fb18e796788.json
  packages/linux/kibana/visualization/4b254630-f998-11e9-90e8-1fb18e796788.json
  packages/linux/kibana/visualization/8c071e20-f999-11e9-90e8-1fb18e796788.json
  packages/linux/kibana/visualization/9c69cad0-f9b0-11e9-90e8-1fb18e796788.json
  packages/linux/kibana/visualization/a30871f0-f98f-11e9-90e8-1fb18e796788.json
  packages/linux/kibana/visualization/bb3a8720-f991-11e9-90e8-1fb18e796788.json
  packages/linux/kibana/visualization/d3f51850-f9b6-11e9-90e8-1fb18e796788.json
  packages/linux/kibana/visualization/e6e639e0-f992-11e9-90e8-1fb18e796788.json
  packages/linux/manifest.yml
  packages/system/dataset/filesystem/manifest.yml
  packages/system/dataset/fsstat/manifest.yml
  packages/system/docs/README.md
  packages/system/kibana/visualization/825fdb80-4d1d-11e7-b5f2-2b7c1895bf32-ecs.json
  packages/system/manifest.yml
Labels: Team:Integrations, enhancement
