Repository elastic/integrations, pull requests merged in 2020-06, with the labels that each got.

#42 dev tool: update package-storage with integrations
  dev/update-package-storage/git.go
  dev/update-package-storage/main.go
  dev/update-package-storage/packages.go
  go.sum
  magefile.go
Labels: Team:Integrations

#47 Fix issues with dashboards
  packages/mysql/dataset/slowlog/fields/fields.yml
  packages/mysql/kibana/search/Logs-MySQL-Slow-log-ecs.json
  packages/mysql/kibana/search/Logs-MySQL-error-log-ecs.json
  packages/mysql/manifest.yml
  packages/nginx/dataset/access/fields/fields.yml
  packages/nginx/dataset/error/fields/fields.yml
  packages/nginx/dataset/ingress_controller/fields/fields.yml
  packages/nginx/manifest.yml
  packages/redis/dataset/info/fields/fields.yml
  packages/redis/dataset/log/fields/fields.yml
  packages/redis/dataset/slowlog/fields/fields.yml
  packages/redis/dataset/slowlog/manifest.yml
  packages/redis/kibana/search/73613570-4791-11e7-be88-2ddb32f3df97-ecs.json
  packages/redis/manifest.yml
Labels: Team:Integrations

#53 Update dependency to only validate fields
  go.mod
  go.sum
  packages/log/dataset/log/fields/base-fields.yml
  vendor/modules.txt
Labels: Team:Integrations

#54 Fix: handle mod error
  magefile.go
Labels: Team:Integrations

#55 import-beats: create base fields
  dev/import-beats/datasets.go
  dev/import-beats/fields_base_fields.go
Labels: Team:Integrations

#57 Release integration only on version bump
  dev/update-package-storage/git.go
  dev/update-package-storage/main.go
  dev/update-package-storage/packages.go
Labels: Team:Integrations

#59 Open pull request using Github API
  dev/update-package-storage/README.md
  dev/update-package-storage/git.go
  dev/update-package-storage/github.go
  dev/update-package-storage/main.go
  dev/update-package-storage/packages.go
Labels: Team:Integrations

#75 Combine snapshot and local docker-compose definitions
  CONTRIBUTING.md
  testing/environments/README.md
  testing/environments/kibana.config.yml
  testing/environments/local.yml
  testing/environments/snapshot.yml
Labels: Team:Integrations

#67 Fix system metricsets
  packages/system/dataset/core/manifest.yml
  packages/system/dataset/cpu/manifest.yml
  packages/system/dataset/diskio/manifest.yml
  packages/system/dataset/entropy/manifest.yml
  packages/system/dataset/filesystem/manifest.yml
  packages/system/dataset/fsstat/manifest.yml
  packages/system/dataset/load/manifest.yml
  packages/system/dataset/memory/manifest.yml
  packages/system/dataset/network/manifest.yml
  packages/system/dataset/network_summary/manifest.yml
  packages/system/dataset/process/manifest.yml
  packages/system/dataset/process_summary/manifest.yml
  packages/system/dataset/raid/manifest.yml
  packages/system/dataset/service/manifest.yml
  packages/system/dataset/socket/manifest.yml
  packages/system/dataset/socket_summary/manifest.yml
  packages/system/dataset/uptime/manifest.yml
  packages/system/dataset/users/manifest.yml
Labels: Alpha1, Team:Integrations, bug

#73 Do not use dev/generator to build integrations
  go.mod
  go.sum
  magefile.go
  magefile_mapstr.go
  vendor/github.com/elastic/package-registry/util/dataset.go
  vendor/github.com/elastic/package-registry/util/mapstr.go
  vendor/github.com/elastic/package-registry/util/package.go
  vendor/github.com/elastic/package-registry/util/packages.go
  vendor/modules.txt
Labels: Team:Integrations

#74 Use build directory
  dev/update-package-storage/main.go
  dev/update-package-storage/packages.go
  go.mod
  go.sum
  magefile.go
  vendor/github.com/elastic/package-registry/util/package.go
  vendor/modules.txt
Labels: Team:Integrations

#81 Update packages to release stream-to-dataset renaming
  packages/aws/manifest.yml
  packages/cisco/manifest.yml
  packages/kafka/manifest.yml
  packages/mysql/manifest.yml
  packages/netflow/manifest.yml
  packages/nginx/manifest.yml
  packages/redis/manifest.yml
Labels: Team:Integrations

#85 change getUsername so we get the upstream user
  dev/update-package-storage/git.go
Labels: Team:Ingest Management, bug

#92 Update version requirements to recent changes
  dev/import-beats/requirement.go
Labels: Team:Integrations

#100 Define static encryption key
  go.mod
  go.sum
  testing/environments/kibana.config.yml
  vendor/github.com/Masterminds/semver/v3/.gitignore
  vendor/github.com/Masterminds/semver/v3/.golangci.yml
  vendor/github.com/Masterminds/semver/v3/CHANGELOG.md
  vendor/github.com/Masterminds/semver/v3/LICENSE.txt
  vendor/github.com/Masterminds/semver/v3/Makefile
  vendor/github.com/Masterminds/semver/v3/README.md
  vendor/github.com/Masterminds/semver/v3/collection.go
  vendor/github.com/Masterminds/semver/v3/constraints.go
  vendor/github.com/Masterminds/semver/v3/doc.go
  vendor/github.com/Masterminds/semver/v3/fuzz.go
  vendor/github.com/Masterminds/semver/v3/go.mod
  vendor/github.com/Masterminds/semver/v3/version.go
  vendor/github.com/elastic/package-registry/util/dataset.go
  vendor/github.com/elastic/package-registry/util/helper.go
  vendor/github.com/elastic/package-registry/util/package.go
  vendor/github.com/elastic/package-registry/util/packages.go
  vendor/modules.txt
Labels: Team:Integrations

#118 Adjust import-beats script to avoid empty package-fields.yml files
  dev/import-beats/datasets.go
Labels: Team:Integrations

#105 feat: build docker image
  .ci/Jenkinsfile
  .ci/distribution/Dockerfile
Labels: ci, enhancement, team:automation

#120 Add Tips section
  CONTRIBUTING.md
Labels: Team:Integrations

#121 fix: the distribution copy and mount path
  .ci/Jenkinsfile
  .ci/integrations/Dockerfile
Labels: bug, ci, team:automation

#83 Migrate PostgreSQL modules
  dev/import-beats-resources/postgresql/docs/README.md
  packages/postgresql/dataset/activity/agent/stream/stream.yml.hbs
  packages/postgresql/dataset/activity/fields/base-fields.yml
  packages/postgresql/dataset/activity/fields/fields.yml
  packages/postgresql/dataset/activity/fields/package-fields.yml
  packages/postgresql/dataset/activity/manifest.yml
  packages/postgresql/dataset/bgwriter/agent/stream/stream.yml.hbs
  packages/postgresql/dataset/bgwriter/fields/base-fields.yml
  packages/postgresql/dataset/bgwriter/fields/fields.yml
  packages/postgresql/dataset/bgwriter/fields/package-fields.yml
  packages/postgresql/dataset/bgwriter/manifest.yml
  packages/postgresql/dataset/database/agent/stream/stream.yml.hbs
  packages/postgresql/dataset/database/fields/base-fields.yml
  packages/postgresql/dataset/database/fields/fields.yml
  packages/postgresql/dataset/database/fields/package-fields.yml
  packages/postgresql/dataset/database/manifest.yml
  packages/postgresql/dataset/log/agent/stream/log.yml.hbs
  packages/postgresql/dataset/log/elasticsearch/ingest-pipeline/default.yml
  packages/postgresql/dataset/log/fields/base-fields.yml
  packages/postgresql/dataset/log/fields/ecs.yml
  packages/postgresql/dataset/log/fields/fields.yml
  packages/postgresql/dataset/log/fields/package-fields.yml
  packages/postgresql/dataset/log/manifest.yml
  packages/postgresql/dataset/statement/agent/stream/stream.yml.hbs
  packages/postgresql/dataset/statement/fields/base-fields.yml
  packages/postgresql/dataset/statement/fields/fields.yml
  packages/postgresql/dataset/statement/fields/package-fields.yml
  packages/postgresql/dataset/statement/manifest.yml
  packages/postgresql/docs/README.md
  packages/postgresql/img/filebeat-postgresql-overview.png
  packages/postgresql/img/filebeat-postgresql-slowlog-overview.png
  packages/postgresql/img/logo_postgres.svg
  packages/postgresql/img/metricbeat-postgresql-overview.png
  packages/postgresql/kibana/dashboard/158be870-87f4-11e7-ad9c-db80de0bf8d3-ecs.json
  packages/postgresql/kibana/dashboard/4288b790-b79f-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/dashboard/e4c5f230-87f3-11e7-ad9c-db80de0bf8d3-ecs.json
  packages/postgresql/kibana/search/PostgreSQL All Logs-ecs.json
  packages/postgresql/kibana/search/PostgreSQL Query Durations-ecs.json
  packages/postgresql/kibana/search/Slow PostgreSQL Queries-ecs.json
  packages/postgresql/kibana/visualization/0cb65170-b909-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/147875b0-b903-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/20931ef0-b79a-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/3dbd5370-87f3-11e7-ad9c-db80de0bf8d3-ecs.json
  packages/postgresql/kibana/visualization/570973a0-b798-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/66d67200-b799-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/960ecdf0-b79a-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/98e6b0a0-b79b-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/PostgreSQL Log Level Count-ecs.json
  packages/postgresql/kibana/visualization/PostgreSQL Query Count and Duration-ecs.json
  packages/postgresql/kibana/visualization/d733c630-b797-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/e2b28ce0-b908-11e9-a579-f5c0a5d81340.json
  packages/postgresql/kibana/visualization/fbfa67e0-b796-11e9-a579-f5c0a5d81340.json
  packages/postgresql/manifest.yml
Labels: Team:Integrations

#98 Build apache integration
  dev/import-beats-resources/apache/docs/README.md
  packages/apache/dataset/access/agent/stream/log.yml.hbs
  packages/apache/dataset/access/elasticsearch/ingest-pipeline/default.yml
  packages/apache/dataset/access/fields/base-fields.yml
  packages/apache/dataset/access/fields/ecs.yml
  packages/apache/dataset/access/fields/fields.yml
  packages/apache/dataset/access/manifest.yml
  packages/apache/dataset/error/agent/stream/log.yml.hbs
  packages/apache/dataset/error/elasticsearch/ingest-pipeline/default.yml
  packages/apache/dataset/error/fields/base-fields.yml
  packages/apache/dataset/error/fields/ecs.yml
  packages/apache/dataset/error/fields/fields.yml
  packages/apache/dataset/error/manifest.yml
  packages/apache/dataset/status/agent/stream/stream.yml.hbs
  packages/apache/dataset/status/fields/base-fields.yml
  packages/apache/dataset/status/fields/fields.yml
  packages/apache/dataset/status/manifest.yml
  packages/apache/docs/README.md
  packages/apache/img/apache_httpd_server_status.png
  packages/apache/img/kibana-apache.png
  packages/apache/img/logo_apache.svg
  packages/apache/kibana/dashboard/Logs-Apache-Dashboard-ecs.json
  packages/apache/kibana/dashboard/Metrics-Apache-HTTPD-server-status-ecs.json
  packages/apache/kibana/search/Apache-HTTPD-ecs.json
  packages/apache/kibana/search/Apache-access-logs-ecs.json
  packages/apache/kibana/search/Apache-errors-log-ecs.json
  packages/apache/kibana/visualization/Apache-HTTPD-CPU-ecs.json
  packages/apache/kibana/visualization/Apache-HTTPD-Hostname-list-ecs.json
  packages/apache/kibana/visualization/Apache-HTTPD-Load1-slash-5-slash-15-ecs.json
  packages/apache/kibana/visualization/Apache-HTTPD-Scoreboard-ecs.json
  packages/apache/kibana/visualization/Apache-HTTPD-Total-accesses-and-kbytes-ecs.json
  packages/apache/kibana/visualization/Apache-HTTPD-Uptime-ecs.json
  packages/apache/kibana/visualization/Apache-HTTPD-Workers-ecs.json
  packages/apache/kibana/visualization/Apache-access-unique-IPs-map-ecs.json
  packages/apache/kibana/visualization/Apache-browsers-ecs.json
  packages/apache/kibana/visualization/Apache-error-logs-over-time-ecs.json
  packages/apache/kibana/visualization/Apache-operating-systems-ecs.json
  packages/apache/kibana/visualization/Apache-response-codes-of-top-URLs-ecs.json
  packages/apache/kibana/visualization/Apache-response-codes-over-time-ecs.json
  packages/apache/manifest.yml
  packages/nginx/manifest.yml
Labels: Team:Integrations

#122 Fix: typo in custom logs
  packages/log/manifest.yml
Labels: Team:Integrations

#99 Build rabbitmq integration
  dev/import-beats-resources/rabbitmq/docs/README.md
  packages/rabbitmq/dataset/connection/agent/stream/stream.yml.hbs
  packages/rabbitmq/dataset/connection/fields/base-fields.yml
  packages/rabbitmq/dataset/connection/fields/ecs.yml
  packages/rabbitmq/dataset/connection/fields/fields.yml
  packages/rabbitmq/dataset/connection/fields/package-fields.yml
  packages/rabbitmq/dataset/connection/manifest.yml
  packages/rabbitmq/dataset/exchange/agent/stream/stream.yml.hbs
  packages/rabbitmq/dataset/exchange/fields/base-fields.yml
  packages/rabbitmq/dataset/exchange/fields/ecs.yml
  packages/rabbitmq/dataset/exchange/fields/fields.yml
  packages/rabbitmq/dataset/exchange/fields/package-fields.yml
  packages/rabbitmq/dataset/exchange/manifest.yml
  packages/rabbitmq/dataset/log/agent/stream/log.yml.hbs
  packages/rabbitmq/dataset/log/elasticsearch/ingest-pipeline/default.yml
  packages/rabbitmq/dataset/log/fields/base-fields.yml
  packages/rabbitmq/dataset/log/fields/fields.yml
  packages/rabbitmq/dataset/log/manifest.yml
  packages/rabbitmq/dataset/node/agent/stream/stream.yml.hbs
  packages/rabbitmq/dataset/node/fields/base-fields.yml
  packages/rabbitmq/dataset/node/fields/fields.yml
  packages/rabbitmq/dataset/node/fields/package-fields.yml
  packages/rabbitmq/dataset/node/manifest.yml
  packages/rabbitmq/dataset/queue/agent/stream/stream.yml.hbs
  packages/rabbitmq/dataset/queue/fields/base-fields.yml
  packages/rabbitmq/dataset/queue/fields/fields.yml
  packages/rabbitmq/dataset/queue/fields/package-fields.yml
  packages/rabbitmq/dataset/queue/manifest.yml
  packages/rabbitmq/docs/README.md
  packages/rabbitmq/img/logo_rabbitmq.svg
  packages/rabbitmq/kibana/dashboard/AV4YobKIge1VCbKU_qVo-ecs.json
  packages/rabbitmq/kibana/search/Metrics-Rabbitmq-ecs.json
  packages/rabbitmq/kibana/visualization/RabbitMQ-Erlang-Process-Usage-ecs.json
  packages/rabbitmq/kibana/visualization/RabbitMQ-Memory-Usage-ecs.json
  packages/rabbitmq/kibana/visualization/RabbitMQ-Queue-Index-Operations-ecs.json
  packages/rabbitmq/kibana/visualization/Rabbitmq-Number-of-Nodes-ecs.json
  packages/rabbitmq/manifest.yml
Labels: Team:Integrations

#124 Generate docs from existing package content
  dev/generate-docs/README.md
  dev/generate-docs/doc_template.go
  dev/generate-docs/exported_fields.go
  dev/generate-docs/main.go
  dev/generate-docs/packages.go
  dev/generate-docs/sample_event.go
  dev/import-beats-resources/aws/docs/README.md
  dev/import-beats-resources/cisco/docs/README.md
  dev/import-beats-resources/netflow/docs/README.md
  dev/import-beats-resources/nginx/docs/README.md
  magefile.go
  packages/apache/docs/README.md
  packages/cisco/docs/README.md
  packages/netflow/docs/README.md
  packages/nginx/dataset/stubstatus/sample_event.json
  packages/nginx/docs/README.md
Labels: Team:Integrations

#131 Add inline code for dataset names in README.md
  dev/generate-docs/sample_event.go
  packages/nginx/docs/README.md
Labels: Team:Platforms

#91 Add support for the windows package
  dev/import-beats-resources/windows/docs/README.md
  packages/windows/dataset/perfmon/agent/stream/stream.yml.hbs
  packages/windows/dataset/perfmon/fields/base-fields.yml
  packages/windows/dataset/perfmon/fields/fields.yml
  packages/windows/dataset/perfmon/manifest.yml
  packages/windows/dataset/service/agent/stream/stream.yml.hbs
  packages/windows/dataset/service/fields/base-fields.yml
  packages/windows/dataset/service/fields/fields.yml
  packages/windows/dataset/service/manifest.yml
  packages/windows/docs/README.md
  packages/windows/img/logo_windows.svg
  packages/windows/img/metricbeat-windows-service.png
  packages/windows/kibana/dashboard/d9eba730-c991-11e7-9835-2f31fe08873b-ecs.json
  packages/windows/kibana/search/b6b7ccc0-c98d-11e7-9835-2f31fe08873b-ecs.json
  packages/windows/kibana/visualization/23a5fff0-c98e-11e7-9835-2f31fe08873b-ecs.json
  packages/windows/kibana/visualization/35f5ad60-c996-11e7-9835-2f31fe08873b-ecs.json
  packages/windows/kibana/visualization/830c45f0-c991-11e7-9835-2f31fe08873b-ecs.json
  packages/windows/kibana/visualization/c36b2ba0-ca29-11e7-9835-2f31fe08873b-ecs.json
  packages/windows/kibana/visualization/eb8277d0-c98c-11e7-9835-2f31fe08873b-ecs.json
  packages/windows/manifest.yml
Labels: Team:Integrations

#137 Add tips for fields files
  CONTRIBUTING.md
Labels: Team:Integrations

#123 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team:Integrations

#110 Import mongodb package
  dev/import-beats-resources/mongodb/docs/README.md
  packages/mongodb/dataset/collstats/agent/stream/stream.yml.hbs
  packages/mongodb/dataset/collstats/fields/base-fields.yml
  packages/mongodb/dataset/collstats/fields/fields.yml
  packages/mongodb/dataset/collstats/manifest.yml
  packages/mongodb/dataset/collstats/sample_event.json
  packages/mongodb/dataset/dbstats/agent/stream/stream.yml.hbs
  packages/mongodb/dataset/dbstats/fields/base-fields.yml
  packages/mongodb/dataset/dbstats/fields/fields.yml
  packages/mongodb/dataset/dbstats/manifest.yml
  packages/mongodb/dataset/dbstats/sample_event.json
  packages/mongodb/dataset/log/agent/stream/log.yml.hbs
  packages/mongodb/dataset/log/elasticsearch/ingest-pipeline/default.yml
  packages/mongodb/dataset/log/fields/base-fields.yml
  packages/mongodb/dataset/log/fields/ecs.yml
  packages/mongodb/dataset/log/fields/fields.yml
  packages/mongodb/dataset/log/manifest.yml
  packages/mongodb/dataset/log/sample_event.json
  packages/mongodb/dataset/metrics/agent/stream/stream.yml.hbs
  packages/mongodb/dataset/metrics/fields/base-fields.yml
  packages/mongodb/dataset/metrics/fields/fields.yml
  packages/mongodb/dataset/metrics/manifest.yml
  packages/mongodb/dataset/metrics/sample_event.json
  packages/mongodb/dataset/replstatus/agent/stream/stream.yml.hbs
  packages/mongodb/dataset/replstatus/fields/base-fields.yml
  packages/mongodb/dataset/replstatus/fields/fields.yml
  packages/mongodb/dataset/replstatus/manifest.yml
  packages/mongodb/dataset/replstatus/sample_event.json
  packages/mongodb/dataset/status/agent/stream/stream.yml.hbs
  packages/mongodb/dataset/status/fields/base-fields.yml
  packages/mongodb/dataset/status/fields/ecs.yml
  packages/mongodb/dataset/status/fields/fields.yml
  packages/mongodb/dataset/status/manifest.yml
  packages/mongodb/dataset/status/sample_event.json
  packages/mongodb/docs/README.md
  packages/mongodb/img/filebeat-mongodb-overview.png
  packages/mongodb/img/logo_mongodb.svg
  packages/mongodb/kibana/dashboard/Metrics-MongoDB-ecs.json
  packages/mongodb/kibana/dashboard/abcf35b0-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/search/MongoDB-search-ecs.json
  packages/mongodb/kibana/search/bfc96a60-0a80-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/search/e49fe000-0a7e-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/visualization/0fef5710-0a82-11e8-bffe-ff7d4f68cf94-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Read-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Concurrent-transactions-Write-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-Engine-ampersand-Version-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-WiredTiger-Cache-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-asserts-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-hosts-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-memory-stats-ecs.json
  packages/mongodb/kibana/visualization/MongoDB-operation-counters-ecs.json
  packages/mongodb/manifest.yml
Labels: Team:Integrations

#139 Fix: add request.body.version
  dev/import-beats/kibana.go
Labels: Team:Integrations
