Repository elastic/integrations, pull requests merged in 2020-11, with the labels that each got.

#272 Add support for azure logs integration
  packages/azure/data_stream/activitylogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/activitylogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
  packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/activitylogs/fields/base-fields.yml
  packages/azure/data_stream/activitylogs/fields/fields.yml
  packages/azure/data_stream/activitylogs/fields/package-fields.yml
  packages/azure/data_stream/activitylogs/manifest.yml
  packages/azure/data_stream/auditlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/auditlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
  packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/auditlogs/fields/base-fields.yml
  packages/azure/data_stream/auditlogs/fields/fields.yml
  packages/azure/data_stream/auditlogs/fields/package-fields.yml
  packages/azure/data_stream/auditlogs/manifest.yml
  packages/azure/data_stream/signinlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/signinlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
  packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/signinlogs/fields/base-fields.yml
  packages/azure/data_stream/signinlogs/fields/fields.yml
  packages/azure/data_stream/signinlogs/fields/package-fields.yml
  packages/azure/data_stream/signinlogs/manifest.yml
  packages/azure/docs/README.md
  packages/azure/img/filebeat-azure-overview.png
  packages/azure/img/logo_azure.svg
  packages/azure/kibana/dashboard/azure-0f559cc0-f0d5-11e9-90ec-112a988266d5.json
  packages/azure/kibana/dashboard/azure-41e84340-ec20-11e9-90ec-112a988266d5.json
  packages/azure/kibana/dashboard/azure-87095750-f05a-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-097d74d0-f044-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-0dd135c0-f0cc-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-46544960-f0d5-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-52c2a4e0-ec1f-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-52da1700-f05d-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-6db84660-53e9-11ea-b1b7-7de801e1c297.json
  packages/azure/kibana/visualization/azure-6ece76d0-f0cc-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-709995e0-ec16-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-71b62ca0-ec1a-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-9ed46680-f0ce-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-b0471750-f05b-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-bc65e840-ec1e-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-c43855e0-f05a-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-c704b050-f0de-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-d91ce8d0-53e8-11ea-b1b7-7de801e1c297.json
  packages/azure/kibana/visualization/azure-da67d650-ec14-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-e0203fc0-f05f-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-e37cd3d0-ec23-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-e4c7f4b0-f045-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-f684a750-ec23-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-fe24ac90-f05a-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-ffe22180-ec1c-11e9-90ec-112a988266d5.json
  packages/azure/manifest.yml
Labels: Team:Integrations, [zube]: In Progress

#375 Remove cgroups from system/process
  packages/system/data_stream/process/agent/stream/stream.yml.hbs
  packages/system/data_stream/process/manifest.yml
  packages/system/kibana/dashboard/system-CPU-slash-Memory-per-container.json
  packages/system/kibana/visualization/system-Container-Block-IO.json
  packages/system/kibana/visualization/system-Container-CPU-usage.json
  packages/system/kibana/visualization/system-Container-Memory-stats.json
  packages/system/kibana/visualization/system-Navigation.json
  packages/system/manifest.yml
Labels: enhancement

#376 Add more missing ECS fields to rsa2elk packages
  packages/cisco/data_stream/meraki/fields/base-fields.yml
  packages/cisco/data_stream/meraki/fields/ecs.yml
  packages/cisco/data_stream/nexus/fields/base-fields.yml
  packages/cisco/data_stream/nexus/fields/ecs.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
  packages/fortinet/data_stream/clientendpoint/fields/base-fields.yml
  packages/fortinet/data_stream/clientendpoint/fields/ecs.yml
  packages/fortinet/data_stream/fortimail/fields/base-fields.yml
  packages/fortinet/data_stream/fortimail/fields/ecs.yml
  packages/fortinet/data_stream/fortimanager/fields/base-fields.yml
  packages/fortinet/data_stream/fortimanager/fields/ecs.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
  packages/juniper/data_stream/junos/fields/base-fields.yml
  packages/juniper/data_stream/junos/fields/ecs.yml
  packages/juniper/data_stream/netscreen/fields/base-fields.yml
  packages/juniper/data_stream/netscreen/fields/ecs.yml
  packages/juniper/docs/README.md
  packages/juniper/manifest.yml
  packages/microsoft/data_stream/dhcp/fields/base-fields.yml
  packages/microsoft/data_stream/dhcp/fields/ecs.yml
  packages/microsoft/docs/README.md
  packages/microsoft/manifest.yml
Labels: Team:Security-External Integrations, bug

#382 Add host.ip to zeek/suricata/nginx
  packages/nginx/data_stream/access/fields/ecs.yml
  packages/nginx/data_stream/error/fields/ecs.yml
  packages/nginx/data_stream/ingress_controller/fields/ecs.yml
  packages/nginx/data_stream/stubstatus/fields/ecs.yml
  packages/nginx/docs/README.md
  packages/nginx/manifest.yml
  packages/suricata/data_stream/eve/fields/ecs.yml
  packages/suricata/docs/README.md
  packages/suricata/manifest.yml
  packages/zeek/data_stream/capture_loss/fields/ecs.yml
  packages/zeek/data_stream/connection/fields/ecs.yml
  packages/zeek/data_stream/dce_rpc/fields/ecs.yml
  packages/zeek/data_stream/dhcp/fields/ecs.yml
  packages/zeek/data_stream/dnp3/fields/ecs.yml
  packages/zeek/data_stream/dns/fields/ecs.yml
  packages/zeek/data_stream/dpd/fields/ecs.yml
  packages/zeek/data_stream/files/fields/ecs.yml
  packages/zeek/data_stream/ftp/fields/ecs.yml
  packages/zeek/data_stream/http/fields/ecs.yml
  packages/zeek/data_stream/intel/fields/ecs.yml
  packages/zeek/data_stream/irc/fields/ecs.yml
  packages/zeek/data_stream/kerberos/fields/ecs.yml
  packages/zeek/data_stream/modbus/fields/ecs.yml
  packages/zeek/data_stream/mysql/fields/ecs.yml
  packages/zeek/data_stream/notice/fields/ecs.yml
  packages/zeek/data_stream/ntlm/fields/ecs.yml
  packages/zeek/data_stream/ocsp/fields/ecs.yml
  packages/zeek/data_stream/pe/fields/ecs.yml
  packages/zeek/data_stream/radius/fields/ecs.yml
  packages/zeek/data_stream/rdp/fields/ecs.yml
  packages/zeek/data_stream/rfb/fields/ecs.yml
  packages/zeek/data_stream/sip/fields/ecs.yml
  packages/zeek/data_stream/smb_cmd/fields/ecs.yml
  packages/zeek/data_stream/smb_files/fields/ecs.yml
  packages/zeek/data_stream/smb_mapping/fields/ecs.yml
  packages/zeek/data_stream/smtp/fields/ecs.yml
  packages/zeek/data_stream/snmp/fields/ecs.yml
  packages/zeek/data_stream/socks/fields/ecs.yml
  packages/zeek/data_stream/ssh/fields/ecs.yml
  packages/zeek/data_stream/ssl/fields/ecs.yml
  packages/zeek/data_stream/stats/fields/ecs.yml
  packages/zeek/data_stream/syslog/fields/ecs.yml
  packages/zeek/data_stream/traceroute/fields/ecs.yml
  packages/zeek/data_stream/tunnel/fields/ecs.yml
  packages/zeek/data_stream/weird/fields/ecs.yml
  packages/zeek/data_stream/x509/fields/ecs.yml
  packages/zeek/docs/README.md
  packages/zeek/manifest.yml
Labels: bug

#383 Add readme for Azure integration
  dev/import-beats-resources/azure/docs/README.md
  packages/azure/data_stream/activitylogs/manifest.yml
  packages/azure/data_stream/activitylogs/sample_event.json
  packages/azure/data_stream/auditlogs/manifest.yml
  packages/azure/data_stream/auditlogs/sample_event.json
  packages/azure/data_stream/signinlogs/manifest.yml
  packages/azure/data_stream/signinlogs/sample_event.json
  packages/azure/docs/README.md
  packages/azure/kibana/visualization/azure-46544960-f0d5-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-c43855e0-f05a-11e9-90ec-112a988266d5.json
  packages/azure/kibana/visualization/azure-fe24ac90-f05a-11e9-90ec-112a988266d5.json
  packages/azure/manifest.yml
Labels: Team:Platforms, [zube]: In Review

#386 Fix for azure Overview dashboard
  dev/import-beats-resources/azure/docs/README.md
  packages/azure/docs/README.md
  packages/azure/kibana/dashboard/azure-41e84340-ec20-11e9-90ec-112a988266d5.json
  packages/azure/manifest.yml
Labels: Team:Platforms, [zube]: In Review

#389 ci: move jobs to ingest-manager folder
  .ci/jobs/folders.yml
  .ci/jobs/integrations.yml
Labels: automation, ci, team:automation

#393 ci: Update Package Storage only on master branch
  .ci/Jenkinsfile
Labels: automation, ci, team:automation

#396 Add auditd log package
  dev/import-beats-resources/auditd/docs/README.md
  packages/auditd/_dev/deploy/docker/Dockerfile
  packages/auditd/_dev/deploy/docker/audit.log
  packages/auditd/_dev/deploy/docker/docker-compose.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-config.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/_dev/test/system/config.yml
  packages/auditd/data_stream/log/agent/stream/log.yml.hbs
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/data_stream/log/fields/agent.yml
  packages/auditd/data_stream/log/fields/base-fields.yml
  packages/auditd/data_stream/log/fields/ecs.yml
  packages/auditd/data_stream/log/fields/fields.yml
  packages/auditd/data_stream/log/fields/package-fields.yml
  packages/auditd/data_stream/log/manifest.yml
  packages/auditd/data_stream/log/sample_event.json
  packages/auditd/docs/README.md
  packages/auditd/img/kibana-audit-auditd.png
  packages/auditd/img/linux.svg
  packages/auditd/kibana/dashboard/auditd-dfbb49f0-0a0f-11e7-8a62-2d05eaaac5cb.json
  packages/auditd/kibana/search/auditd-4ac0a370-0a11-11e7-8b04-eb22a5669f27.json
  packages/auditd/kibana/visualization/auditd-2bb0fa70-0a11-11e7-9e84-43da493ad0c7.json
  packages/auditd/kibana/visualization/auditd-5ebdbe50-0a0f-11e7-825f-6748cda7d858.json
  packages/auditd/kibana/visualization/auditd-6295bdd0-0a0e-11e7-825f-6748cda7d858.json
  packages/auditd/kibana/visualization/auditd-c5411910-0a87-11e7-8b04-eb22a5669f27.json
  packages/auditd/kibana/visualization/auditd-d1726930-0a7f-11e7-8b04-eb22a5669f27.json
  packages/auditd/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#405 Deprecate testing/environment in favor of elastic-package stack
  CONTRIBUTING.md
  magefile.go
  testing/environments/7.9.0.yml
  testing/environments/Dockerfile.package-registry
  testing/environments/README.md
  testing/environments/agent.yml
  testing/environments/kibana.config.yml
  testing/environments/package-registry.config.yml
  testing/environments/snapshot.yml
Labels: deprecation, enhancement

#410 Use "elastic-package build" to render README.md files.
  .gitignore
  CONTRIBUTING.md
  dev/generate-docs/README.md
  dev/generate-docs/doc_template.go
  dev/generate-docs/exported_fields.go
  dev/generate-docs/main.go
  dev/generate-docs/packages.go
  dev/generate-docs/sample_event.go
  dev/import-beats/packages.go
  go.mod
  go.sum
  magefile.go
  packages/apache/_dev/build/docs/README.md
  packages/apache/docs/README.md
  packages/auditd/_dev/build/docs/README.md
  packages/auditd/docs/README.md
  packages/aws/_dev/build/docs/README.md
  packages/aws/docs/README.md
  packages/azure/_dev/build/docs/README.md
  packages/azure/docs/README.md
  packages/checkpoint/_dev/build/docs/README.md
  packages/cisco/_dev/build/docs/README.md
  packages/crowdstrike/_dev/build/docs/README.md
  packages/fortinet/_dev/build/docs/README.md
  packages/haproxy/_dev/build/docs/README.md
  packages/haproxy/docs/README.md
  packages/iis/_dev/build/docs/README.md
  packages/iis/docs/README.md
  packages/juniper/_dev/build/docs/README.md
  packages/kafka/_dev/build/docs/README.md
  packages/kafka/docs/README.md
  packages/kubernetes/_dev/build/docs/README.md
  packages/kubernetes/docs/README.md
  packages/linux/_dev/build/docs/README.md
  packages/microsoft/_dev/build/docs/README.md
  packages/mongodb/_dev/build/docs/README.md
  packages/mongodb/docs/README.md
  packages/mysql/_dev/build/docs/README.md
  packages/mysql/docs/README.md
  packages/netflow/_dev/build/docs/README.md
  packages/nginx/_dev/build/docs/README.md
  packages/nginx/docs/README.md
  packages/o365/_dev/build/docs/README.md
  packages/okta/_dev/build/docs/README.md
  packages/panw/_dev/build/docs/README.md
  packages/postgresql/_dev/build/docs/README.md
  packages/postgresql/docs/README.md
  packages/prometheus/_dev/build/docs/README.md
  packages/prometheus/docs/README.md
  packages/rabbitmq/_dev/build/docs/README.md
  packages/rabbitmq/docs/README.md
  packages/redis/_dev/build/docs/README.md
  packages/redis/docs/README.md
  packages/suricata/_dev/build/docs/README.md
  packages/system/_dev/build/docs/README.md
  packages/windows/_dev/build/docs/README.md
  packages/zeek/_dev/build/docs/README.md
  packages/zookeeper/_dev/build/docs/README.md
  packages/zookeeper/docs/README.md
  packages/zoom/_dev/build/docs/README.md
Labels: Team:Integrations

#409 Add pipeline tests for CheckPoint Firewall
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-config.json
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-expected.json
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-config.json
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
  packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/checkpoint/data_stream/firewall/fields/fields.yml
  packages/checkpoint/docs/README.md
  packages/checkpoint/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#402 Add `unit` and `metric_type` meta to system fields.yml
  packages/system/data_stream/core/fields/fields.yml
  packages/system/data_stream/cpu/fields/fields.yml
  packages/system/data_stream/diskio/fields/fields.yml
  packages/system/data_stream/filesystem/fields/fields.yml
  packages/system/data_stream/fsstat/fields/fields.yml
  packages/system/data_stream/load/fields/fields.yml
  packages/system/data_stream/memory/fields/fields.yml
  packages/system/data_stream/network/fields/fields.yml
  packages/system/data_stream/process/fields/fields.yml
  packages/system/data_stream/process_summary/fields/fields.yml
  packages/system/data_stream/socket_summary/fields/fields.yml
  packages/system/data_stream/uptime/fields/fields.yml
  packages/system/docs/README.md
  packages/system/manifest.yml
Labels: Team:Integrations, enhancement

#401 Fix Office 365 package configuration
  packages/o365/_dev/build/docs/README.md
  packages/o365/data_stream/audit/agent/stream/log.yml.hbs
  packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
  packages/o365/data_stream/audit/manifest.yml
  packages/o365/docs/README.md
  packages/o365/manifest.yml
Labels: Team:Security-External Integrations, bug

#412 Strip mage targets from Magefile
  .ci/Jenkinsfile
  .gitignore
  CONTRIBUTING.md
  dev/update-package-storage/README.md
  magefile.go
Labels: enhancement

#419 In the nginx ingress_controller datastream the source.address is never set
  packages/nginx/data_stream/ingress_controller/_dev/test/pipeline/test-ingest-raw.log
  packages/nginx/data_stream/ingress_controller/_dev/test/pipeline/test-ingest-raw.log-expected.json
  packages/nginx/data_stream/ingress_controller/elasticsearch/ingest_pipeline/default.yml
  packages/nginx/data_stream/ingress_controller/fields/ecs.yml
  packages/nginx/docs/README.md
  packages/nginx/manifest.yml
Labels: Team:Platforms

#417 Add support for azure pipeline tests
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-config.json
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
  packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/activitylogs/fields/ecs.yml
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-config.json
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-expected.json
  packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/auditlogs/fields/ecs.yml
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-config.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-liftr-raw.log
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-liftr-raw.log-config.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-liftr-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-config.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-expected.json
  packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/platformlogs/fields/ecs.yml
  packages/azure/data_stream/platformlogs/fields/fields.yml
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-config.json
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
  packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/signinlogs/fields/ecs.yml
  packages/azure/data_stream/signinlogs/fields/fields.yml
  packages/azure/docs/README.md
  packages/azure/manifest.yml
Labels: Team:Platforms, [zube]: In Review

#423 Remove unneeded action item
  .github/ISSUE_TEMPLATE/package-checklist.md
Labels: Team:Integrations

#420 Apache: refactor integration
  packages/apache/_dev/build/docs/README.md
  packages/apache/_dev/deploy/docker/Dockerfile
  packages/apache/_dev/deploy/docker/httpd.conf
  packages/apache/_dev/deploy/variants.yml
  packages/apache/data_stream/status/fields/ecs.yml
  packages/apache/data_stream/status/manifest.yml
  packages/apache/docs/README.md
Labels: Team:Integrations, enhancement

#424 Support invalid json in LIFTR azure platform logs
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-liftr-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-expected.json
  packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
  packages/azure/manifest.yml
Labels: Team:Platforms, [zube]: In Review
