Repository elastic/integrations, pull requests merged in 2020-08, with the labels that each got.

#210 Do not open another PR for the same package
  dev/update-package-storage/github.go
  dev/update-package-storage/main.go
Labels: Team:Integrations, enhancement

#211 Fix: markdown links
  dev/import-beats-resources/kafka/docs/README.md
  dev/import-beats-resources/redis/docs/README.md
  packages/kafka/docs/README.md
  packages/kafka/manifest.yml
  packages/mysql/manifest.yml
  packages/nginx/manifest.yml
  packages/redis/docs/README.md
  packages/redis/manifest.yml
Labels: bug

#212 Update config option in the windows manifest file
  packages/windows/manifest.yml
Labels: Team:Ingest Management

#214 Fix: markdown links
  dev/import-beats-resources/apache/docs/README.md
  dev/import-beats-resources/rabbitmq/docs/README.md
  packages/apache/docs/README.md
  packages/apache/manifest.yml
  packages/rabbitmq/docs/README.md
  packages/rabbitmq/manifest.yml
Labels: Team:Integrations

#182 Add CrowdStrike filebeat module
  dev/import-beats-resources/crowdstrike/docs/README.md
  packages/crowdstrike/dataset/falcon/agent/stream/log.yml.hbs
  packages/crowdstrike/dataset/falcon/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/dataset/falcon/fields/base-fields.yml
  packages/crowdstrike/dataset/falcon/fields/beats.yml
  packages/crowdstrike/dataset/falcon/fields/ecs.yml
  packages/crowdstrike/dataset/falcon/fields/fields.yml
  packages/crowdstrike/dataset/falcon/manifest.yml
  packages/crowdstrike/dataset/falcon/test/pipeline/falcon-audit-events.log
  packages/crowdstrike/dataset/falcon/test/pipeline/falcon-audit-events.log-expected.json
  packages/crowdstrike/dataset/falcon/test/pipeline/falcon-events.log
  packages/crowdstrike/dataset/falcon/test/pipeline/falcon-events.log-expected.json
  packages/crowdstrike/dataset/falcon/test/pipeline/falcon-sample.log
  packages/crowdstrike/dataset/falcon/test/pipeline/falcon-sample.log-expected.json
  packages/crowdstrike/docs/README.md
  packages/crowdstrike/img/logo-integrations-crowdstrike.svg
  packages/crowdstrike/img/siem-alerts-cs.jpg
  packages/crowdstrike/img/siem-events-cs.jpg
  packages/crowdstrike/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#186 Add Suricata package
  dev/import-beats-resources/suricata/docs/README.md
  packages/suricata/dataset/eve/agent/stream/log.yml.hbs
  packages/suricata/dataset/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/dataset/eve/fields/base-fields.yml
  packages/suricata/dataset/eve/fields/ecs.yml
  packages/suricata/dataset/eve/fields/fields.epr.yml
  packages/suricata/dataset/eve/fields/fields.yml
  packages/suricata/dataset/eve/manifest.yml
  packages/suricata/docs/README.md
  packages/suricata/img/filebeat-suricata-alerts.png
  packages/suricata/img/filebeat-suricata-events.png
  packages/suricata/img/suricata.svg
  packages/suricata/kibana/dashboard/05268ee0-86d1-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/dashboard/78289c40-86da-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/search/13dd22f0-86cc-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/search/1c2bcec0-86d1-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/search/d57a2db0-86ca-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/0a0aa630-86db-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/0a363820-86dd-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/16033310-86d3-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/169c0600-d297-11ea-90e3-8767fe7ccf14.json
  packages/suricata/kibana/visualization/2ccdc1a0-86d8-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/494fa290-86d2-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/5f99eb50-86dc-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/728f64c0-86db-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/85fed080-86d7-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/8e7f88d0-86dc-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/908e8c90-d296-11ea-90e3-8767fe7ccf14.json
  packages/suricata/kibana/visualization/9d5b5b50-86db-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/a09ca070-86d7-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/c7b8b8f0-86d8-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/visualization/c7d46c60-86da-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/manifest.yml
Labels: enhancement

#223 Fix a crash during module conversion
  dev/import-beats/streams_config_parser.go
Labels: bug

#224 Trigger update storage
  .ci/Jenkinsfile
  .ci/integrations/Dockerfile
  .ci/jenkins-go-agent/Dockerfile
  dev/update-package-storage/github.go
  dev/update-package-storage/main.go
  dev/update-package-storage/packages.go
Labels: enhancement

#235 Fix: check if requested team has been assigned to the PR
  dev/update-package-storage/github.go
Labels: bug

#228 Fortinet/Firewall Filebeat Module
  dev/import-beats-resources/fortinet/docs/README.md
  packages/fortinet/dataset/firewall/agent/stream/log.yml.hbs
  packages/fortinet/dataset/firewall/agent/stream/tcp.yml.hbs
  packages/fortinet/dataset/firewall/agent/stream/udp.yml.hbs
  packages/fortinet/dataset/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/dataset/firewall/elasticsearch/ingest_pipeline/event.yml
  packages/fortinet/dataset/firewall/elasticsearch/ingest_pipeline/traffic.yml
  packages/fortinet/dataset/firewall/elasticsearch/ingest_pipeline/utm.yml
  packages/fortinet/dataset/firewall/fields/base-fields.yml
  packages/fortinet/dataset/firewall/fields/beats.yml
  packages/fortinet/dataset/firewall/fields/ecs.yml
  packages/fortinet/dataset/firewall/fields/fields.yml
  packages/fortinet/dataset/firewall/manifest.yml
  packages/fortinet/docs/README.md
  packages/fortinet/img/fortinet-logo.svg
  packages/fortinet/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#220 Checkpoint Filebeat Module
  dev/import-beats-resources/checkpoint/docs/README.md
  packages/checkpoint/dataset/firewall/agent/stream/log.yml.hbs
  packages/checkpoint/dataset/firewall/agent/stream/syslog.yml.hbs
  packages/checkpoint/dataset/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/checkpoint/dataset/firewall/fields/base-fields.yml
  packages/checkpoint/dataset/firewall/fields/beats.yml
  packages/checkpoint/dataset/firewall/fields/ecs.yml
  packages/checkpoint/dataset/firewall/fields/fields.yml
  packages/checkpoint/dataset/firewall/manifest.yml
  packages/checkpoint/docs/README.md
  packages/checkpoint/img/checkpoint-logo.svg
  packages/checkpoint/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#230 Filebeat O365 Package
  dev/import-beats-resources/o365/docs/README.md
  packages/o365/dataset/audit/agent/stream/log.yml.hbs
  packages/o365/dataset/audit/agent/stream/o365audit.yml.hbs
  packages/o365/dataset/audit/agent/stream/pipeline.js
  packages/o365/dataset/audit/elasticsearch/ingest_pipeline/default.yml
  packages/o365/dataset/audit/fields/base-fields.yml
  packages/o365/dataset/audit/fields/beats.yml
  packages/o365/dataset/audit/fields/ecs.yml
  packages/o365/dataset/audit/fields/fields.yml
  packages/o365/dataset/audit/manifest.yml
  packages/o365/docs/README.md
  packages/o365/img/filebeat-o365-audit.png
  packages/o365/img/filebeat-o365-azure-permissions.png
  packages/o365/img/logo-integrations-microsoft-365.svg
  packages/o365/kibana/dashboard/712e2c00-685d-11ea-8d6a-292ef5d68366.json
  packages/o365/kibana/map/dbae13c0-685c-11ea-8d6a-292ef5d68366.json
  packages/o365/kibana/search/8b8e5a10-6886-11ea-8d6a-292ef5d68366.json
  packages/o365/kibana/search/fdc14020-6859-11ea-8d6a-292ef5d68366.json
  packages/o365/kibana/visualization/0be1adb0-6860-11ea-8d6a-292ef5d68366.json
  packages/o365/kibana/visualization/897d0c70-6869-11ea-8d6a-292ef5d68366.json
  packages/o365/kibana/visualization/8b033510-685a-11ea-8d6a-292ef5d68366.json
  packages/o365/kibana/visualization/d43c95a0-6864-11ea-8d6a-292ef5d68366.json
  packages/o365/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#227 Add cisco/nexus dataset
  dev/import-beats-resources/cisco/docs/README.md
  packages/cisco/dataset/nexus/agent/stream/stream.yml.hbs
  packages/cisco/dataset/nexus/agent/stream/tcp.yml.hbs
  packages/cisco/dataset/nexus/agent/stream/udp.yml.hbs
  packages/cisco/dataset/nexus/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/dataset/nexus/fields/base-fields.yml
  packages/cisco/dataset/nexus/fields/ecs.yml
  packages/cisco/dataset/nexus/fields/fields.yml
  packages/cisco/dataset/nexus/manifest.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#231 Add microsoft package
  dev/import-beats-resources/microsoft/docs/README.md
  packages/microsoft/dataset/dhcp/agent/stream/stream.yml.hbs
  packages/microsoft/dataset/dhcp/agent/stream/tcp.yml.hbs
  packages/microsoft/dataset/dhcp/agent/stream/udp.yml.hbs
  packages/microsoft/dataset/dhcp/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft/dataset/dhcp/fields/base-fields.yml
  packages/microsoft/dataset/dhcp/fields/ecs.yml
  packages/microsoft/dataset/dhcp/fields/fields.yml
  packages/microsoft/dataset/dhcp/manifest.yml
  packages/microsoft/docs/README.md
  packages/microsoft/img/logo.svg
  packages/microsoft/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#233 Add Palo Alto package
  dev/import-beats-resources/panw/docs/README.md
  packages/panw/dataset/panos/agent/stream/log.yml.hbs
  packages/panw/dataset/panos/agent/stream/syslog.yml.hbs
  packages/panw/dataset/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/dataset/panos/fields/base-fields.yml
  packages/panw/dataset/panos/fields/beats.yml
  packages/panw/dataset/panos/fields/ecs.yml
  packages/panw/dataset/panos/fields/fields.yml
  packages/panw/dataset/panos/manifest.yml
  packages/panw/docs/README.md
  packages/panw/img/filebeat-panw-threat.png
  packages/panw/img/filebeat-panw-traffic.png
  packages/panw/img/logo-integrations-paloalto-networks.svg
  packages/panw/kibana/dashboard/772964e0-7591-11e9-aacf-79a3704914a0.json
  packages/panw/kibana/dashboard/e40ba240-7572-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/search/290685e0-7569-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/search/3cea1360-7569-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/0407a3e0-756f-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/091fe860-756a-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/0bd2a0c0-7574-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/135930b0-7570-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/3eca1070-7589-11e9-aacf-79a3704914a0.json
  packages/panw/kibana/visualization/5bd32b20-7575-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/6dce7930-758c-11e9-aacf-79a3704914a0.json
  packages/panw/kibana/visualization/78e7e820-756d-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/87f30f60-7569-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/90ce3300-758a-11e9-aacf-79a3704914a0.json
  packages/panw/kibana/visualization/a95aaf20-758a-11e9-aacf-79a3704914a0.json
  packages/panw/kibana/visualization/d9cab170-756f-11e9-976e-65a8f47cc4c1.json
  packages/panw/kibana/visualization/e46331c0-756a-11e9-976e-65a8f47cc4c1.json
  packages/panw/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#239 Add owner information to microsoft package
  packages/microsoft/manifest.yml
Labels: enhancement

#240 Add fortinet/clientendpoint dataset
  dev/import-beats-resources/fortinet/docs/README.md
  packages/fortinet/dataset/clientendpoint/agent/stream/log.yml.hbs
  packages/fortinet/dataset/clientendpoint/agent/stream/tcp.yml.hbs
  packages/fortinet/dataset/clientendpoint/agent/stream/udp.yml.hbs
  packages/fortinet/dataset/clientendpoint/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/dataset/clientendpoint/fields/base-fields.yml
  packages/fortinet/dataset/clientendpoint/fields/ecs.yml
  packages/fortinet/dataset/clientendpoint/fields/fields.yml
  packages/fortinet/dataset/clientendpoint/manifest.yml
  packages/fortinet/dataset/firewall/agent/stream/log.yml.hbs
  packages/fortinet/dataset/firewall/agent/stream/tcp.yml.hbs
  packages/fortinet/dataset/firewall/agent/stream/udp.yml.hbs
  packages/fortinet/dataset/firewall/manifest.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
Labels: Team:SIEM, enhancement

#232 Add Okta integration
  dev/import-beats-resources/okta/docs/README.md
  packages/okta/dataset/system/agent/stream/httpjson.yml.hbs
  packages/okta/dataset/system/agent/stream/log.yml.hbs
  packages/okta/dataset/system/elasticsearch/ingest_pipeline/default.yml
  packages/okta/dataset/system/fields/base-fields.yml
  packages/okta/dataset/system/fields/beats.yml
  packages/okta/dataset/system/fields/ecs.yml
  packages/okta/dataset/system/fields/fields.yml
  packages/okta/dataset/system/manifest.yml
  packages/okta/docs/README.md
  packages/okta/img/filebeat-okta-dashboard.png
  packages/okta/img/okta-logo.svg
  packages/okta/kibana/dashboard/749203a0-67b1-11ea-a76f-bf44814e437d.json
  packages/okta/kibana/map/281ca660-67b1-11ea-a76f-bf44814e437d.json
  packages/okta/kibana/search/21028750-67ca-11ea-a76f-bf44814e437d.json
  packages/okta/kibana/visualization/0a784b30-67c7-11ea-a76f-bf44814e437d.json
  packages/okta/kibana/visualization/545d6a00-67ae-11ea-a76f-bf44814e437d.json
  packages/okta/kibana/visualization/7c6ec080-67c6-11ea-a76f-bf44814e437d.json
  packages/okta/kibana/visualization/cda883a0-67c6-11ea-a76f-bf44814e437d.json
  packages/okta/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#247 AWS cloudtrail version 0.2.6
  packages/aws/dataset/cloudtrail/elasticsearch/ingest_pipeline/default.yml
  packages/aws/dataset/cloudtrail/fields/ecs.yml
  packages/aws/dataset/cloudtrail/fields/fields.yml
  packages/aws/docs/README.md
  packages/aws/manifest.yml
Labels: Team:SIEM, enhancement

#253 Add documentation for AWS credentials
  dev/import-beats-resources/aws/docs/README.md
  packages/aws/dataset/billing/agent/stream/stream.yml.hbs
  packages/aws/dataset/cloudtrail/agent/stream/s3.yml.hbs
  packages/aws/dataset/cloudtrail/fields/ecs.yml
  packages/aws/dataset/cloudtrail/fields/fields.yml
  packages/aws/dataset/cloudwatch_logs/agent/stream/s3.yml.hbs
  packages/aws/dataset/cloudwatch_metrics/agent/stream/stream.yml.hbs
  packages/aws/dataset/dynamodb/agent/stream/stream.yml.hbs
  packages/aws/dataset/ebs/agent/stream/stream.yml.hbs
  packages/aws/dataset/ec2_logs/agent/stream/s3.yml.hbs
  packages/aws/dataset/ec2_metrics/agent/stream/stream.yml.hbs
  packages/aws/dataset/elb_logs/agent/stream/s3.yml.hbs
  packages/aws/dataset/elb_metrics/agent/stream/stream.yml.hbs
  packages/aws/dataset/lambda/agent/stream/stream.yml.hbs
  packages/aws/dataset/natgateway/agent/stream/stream.yml.hbs
  packages/aws/dataset/rds/agent/stream/stream.yml.hbs
  packages/aws/dataset/s3_daily_storage/agent/stream/stream.yml.hbs
  packages/aws/dataset/s3_request/agent/stream/stream.yml.hbs
  packages/aws/dataset/s3access/agent/stream/s3.yml.hbs
  packages/aws/dataset/sns/agent/stream/stream.yml.hbs
  packages/aws/dataset/sqs/agent/stream/stream.yml.hbs
  packages/aws/dataset/transitgateway/agent/stream/stream.yml.hbs
  packages/aws/dataset/usage/agent/stream/stream.yml.hbs
  packages/aws/dataset/vpcflow/agent/stream/s3.yml.hbs
  packages/aws/dataset/vpn/agent/stream/stream.yml.hbs
  packages/aws/docs/README.md
  packages/aws/manifest.yml
Labels: Team:Platforms

#256 remove duplicate LIstGroupsForUser
  packages/aws/dataset/cloudtrail/elasticsearch/ingest_pipeline/default.yml
  packages/aws/manifest.yml
Labels: bug

#261 Add object field types in prometheus package
  packages/prometheus/dataset/collector/fields/fields.yml
  packages/prometheus/dataset/query/fields/fields.yml
  packages/prometheus/dataset/remote_write/fields/fields.yml
  packages/prometheus/manifest.yml
Labels: Team:Platforms

#262 Enable pipeline tests
  go.mod
  go.sum
  magefile.go
  packages/nginx/dataset/access/_dev/test/pipeline/test-access-event.json
  packages/nginx/dataset/access/_dev/test/pipeline/test-access-event.json-expected.json
  packages/nginx/dataset/access/_dev/test/pipeline/test-access-raw.log
  packages/nginx/dataset/access/_dev/test/pipeline/test-access-raw.log-config.json
  packages/nginx/dataset/access/_dev/test/pipeline/test-access-raw.log-expected.json
  packages/nginx/dataset/access/test/pipeline/test-access.log-expected.json
  packages/nginx/dataset/error/_dev/test/pipeline/test-error-raw.log
  packages/nginx/dataset/error/_dev/test/pipeline/test-error-raw.log-expected.json
  packages/nginx/dataset/ingress_controller/_dev/test/pipeline/test-ingest-raw.log
  packages/nginx/dataset/ingress_controller/_dev/test/pipeline/test-ingest-raw.log-expected.json
Labels: enhancement

#243 Update Prometheus package to leverage types in remote write
  dev/import-beats-resources/prometheus/docs/README.md
  packages/prometheus/dataset/remote_write/agent/stream/stream.yml.hbs
  packages/prometheus/dataset/remote_write/fields/fields.yml
  packages/prometheus/dataset/remote_write/manifest.yml
  packages/prometheus/docs/README.md
  packages/prometheus/manifest.yml
Labels: Team:Platforms
