Repository elastic/integrations, pull requests merged in 2020-10, with the labels that each got.

#282 Complete Linux Integration
  packages/linux/dataset/conntrack/agent/stream/stream.yml.hbs
  packages/linux/dataset/conntrack/fields/base-fields.yml
  packages/linux/dataset/conntrack/fields/fields.yml
  packages/linux/dataset/conntrack/manifest.yml
  packages/linux/dataset/ksm/agent/stream/stream.yml.hbs
  packages/linux/dataset/ksm/fields/base-fields.yml
  packages/linux/dataset/ksm/fields/fields.yml
  packages/linux/dataset/ksm/manifest.yml
  packages/linux/dataset/pageinfo/agent/stream/stream.yml.hbs
  packages/linux/dataset/pageinfo/fields/base-fields.yml
  packages/linux/dataset/pageinfo/fields/fields.yml
  packages/linux/dataset/pageinfo/manifest.yml
  packages/linux/manifest.yml
Labels: enhancement

#283 Fix zeek kerberos pipeline
  packages/zeek/dataset/kerberos/elasticsearch/ingest_pipeline/default.yml
  packages/zeek/manifest.yml
Labels: Team:SIEM, bug

#284 Import zoom module from Filebeat
  dev/import-beats-resources/zoom/docs/README.md
  packages/zoom/data_stream/webhook/agent/stream/http_endpoint.yml.hbs
  packages/zoom/data_stream/webhook/agent/stream/log.yml.hbs
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/account.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/chat_channel.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/chat_message.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/default.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/meeting.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/phone.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/recording.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/user.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/webinar.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/zoomroom.yml
  packages/zoom/data_stream/webhook/fields/base-fields.yml
  packages/zoom/data_stream/webhook/fields/fields.yml
  packages/zoom/data_stream/webhook/manifest.yml
  packages/zoom/docs/README.md
  packages/zoom/img/zoom_blue.svg
  packages/zoom/manifest.yml
Labels: Team:SIEM, enhancement

#285 Fix image reference for EPR distribution
  testing/environments/Dockerfile.package-registry
Labels: bug

#287 Add missing ECS fields to Zoom package
  packages/zoom/data_stream/webhook/fields/ecs.yml
  packages/zoom/docs/README.md
Labels: bug

#290 Update Windows package
  dev/import-beats-resources/windows/docs/README.md
  packages/windows/data_stream/application/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/application/elasticsearch/ingest_pipeline/default.yml
  packages/windows/data_stream/application/fields/base-fields.yml
  packages/windows/data_stream/application/fields/ecs.yml
  packages/windows/data_stream/application/fields/winlog.yml
  packages/windows/data_stream/application/manifest.yml
  packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/security/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/system/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/windows/data_stream/system/fields/base-fields.yml
  packages/windows/data_stream/system/fields/ecs.yml
  packages/windows/data_stream/system/fields/winlog.yml
  packages/windows/data_stream/system/manifest.yml
  packages/windows/docs/README.md
  packages/windows/manifest.yml
Labels: Team:SIEM, enhancement

#263 Adding system test files for Apache package
  go.mod
  go.sum
  magefile.go
  packages/apache/_dev/deploy/docker/Dockerfile
  packages/apache/_dev/deploy/docker/docker-compose.yml
  packages/apache/_dev/deploy/docker/httpd.conf
  packages/apache/_dev/deploy/variants.yml
  packages/apache/data_stream/access/_dev/test/system/config.yml
  packages/apache/data_stream/error/_dev/test/system/config.yml
  packages/apache/data_stream/status/_dev/test/system/config.yml
Labels: Team:Integrations

#293 Fix: properly handle removed files
  dev/update-package-storage/github.go
  dev/update-package-storage/main.go
  dev/update-package-storage/packages.go
  packages/windows/manifest.yml
Labels: bug

#288 Add data_stream srx to juniper package
  dev/import-beats-resources/juniper/docs/README.md
  packages/juniper/data_stream/junos/agent/stream/stream.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/junos/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/junos/fields/base-fields.yml
  packages/juniper/data_stream/junos/fields/ecs.yml
  packages/juniper/data_stream/junos/fields/fields.yml
  packages/juniper/data_stream/junos/manifest.yml
  packages/juniper/data_stream/netscreen/agent/stream/stream.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/netscreen/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/netscreen/fields/base-fields.yml
  packages/juniper/data_stream/netscreen/fields/ecs.yml
  packages/juniper/data_stream/netscreen/fields/fields.yml
  packages/juniper/data_stream/netscreen/manifest.yml
  packages/juniper/data_stream/srx/agent/stream/log.yml.hbs
  packages/juniper/data_stream/srx/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/srx/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/atp.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/flow.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/idp.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/ids.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/secintel.yml
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/utm.yml
  packages/juniper/data_stream/srx/fields/base-fields.yml
  packages/juniper/data_stream/srx/fields/ecs.yml
  packages/juniper/data_stream/srx/fields/fields.yml
  packages/juniper/data_stream/srx/manifest.yml
  packages/juniper/docs/README.md
  packages/juniper/img/logo.svg
  packages/juniper/manifest.yml
Labels: Team:SIEM, enhancement

#295 Update GH team name to security-external-integrations
  packages/checkpoint/manifest.yml
  packages/cisco/manifest.yml
  packages/crowdstrike/manifest.yml
  packages/fortinet/manifest.yml
  packages/juniper/manifest.yml
  packages/microsoft/manifest.yml
  packages/o365/manifest.yml
  packages/okta/manifest.yml
  packages/panw/manifest.yml
  packages/suricata/manifest.yml
  packages/zeek/manifest.yml
  packages/zoom/manifest.yml
Labels: Team:Security-External Integrations

#301 Add common host inventory fields into aws and system package
  packages/aws/data_stream/ec2_metrics/fields/fields.yml
  packages/aws/docs/README.md
  packages/system/data_stream/cpu/fields/fields.yml
  packages/system/data_stream/diskio/fields/fields.yml
  packages/system/data_stream/network/fields/fields.yml
  packages/system/docs/README.md
Labels: Team:Platforms

#303 Fix mongodb ssl.enabled type
  packages/mongodb/manifest.yml
Labels: Team:Platforms

#302 Add fips_enabled config parameter to log data streams
  packages/aws/data_stream/cloudtrail/agent/stream/s3.yml.hbs
  packages/aws/data_stream/cloudtrail/manifest.yml
  packages/aws/data_stream/cloudwatch_logs/agent/stream/s3.yml.hbs
  packages/aws/data_stream/cloudwatch_logs/manifest.yml
  packages/aws/data_stream/ec2_logs/agent/stream/s3.yml.hbs
  packages/aws/data_stream/ec2_logs/manifest.yml
  packages/aws/data_stream/elb_logs/agent/stream/s3.yml.hbs
  packages/aws/data_stream/elb_logs/manifest.yml
  packages/aws/data_stream/s3access/agent/stream/s3.yml.hbs
  packages/aws/data_stream/s3access/manifest.yml
  packages/aws/data_stream/vpcflow/agent/stream/s3.yml.hbs
  packages/aws/data_stream/vpcflow/manifest.yml
Labels: Team:Platforms

#300 Remove unfinished synthetics package
  packages/synthetics/data_stream/monitor/agent/stream/stream.yml.hbs
  packages/synthetics/data_stream/monitor/fields/base-fields.yml
  packages/synthetics/data_stream/monitor/fields/ecs.yml
  packages/synthetics/data_stream/monitor/fields/fields.yml
  packages/synthetics/data_stream/monitor/manifest.yml
  packages/synthetics/docs/README.md
  packages/synthetics/img/uptime-logo-color-64px.svg
  packages/synthetics/manifest.yml
Labels: deprecation

#304 Add support for additional fields from V2 ALB logs
  go.mod
  go.sum
  packages/aws/data_stream/elb_logs/_dev/test/pipeline/test-alb.log
  packages/aws/data_stream/elb_logs/_dev/test/pipeline/test-alb.log-expected.json
  packages/aws/data_stream/elb_logs/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/elb_logs/fields/fields.yml
  packages/aws/docs/README.md
  packages/aws/manifest.yml
  packages/nginx/data_stream/error/_dev/test/pipeline/test-error-raw.log-expected.json
  packages/nginx/data_stream/ingress_controller/_dev/test/pipeline/test-ingest-raw.log-expected.json
Labels: Team:Platforms

#307 Update dependency on elastic-package
  go.mod
  go.sum
  packages/apache/_dev/deploy/docker/httpd.conf
Labels: Team:Integrations

#309 Recommend 7.10 as the baseline
  CONTRIBUTING.md
Labels: Team:Integrations

#311 Promote system package for 7.10.0
  packages/system/manifest.yml
Labels: [zube]: (7.10) Planned for release

#313 Add ECS host fields to system package log data streams
  packages/system/data_stream/auth/fields/ecs.yml
  packages/system/data_stream/syslog/fields/ecs.yml
  packages/system/manifest.yml
Labels: Team:Services, bug

#322 Fix import-beats: prepend module names to Kibana dashboards
  dev/import-beats/kibana.go
  dev/import-beats/packages.go
Labels: bug

#326 sync crowdstrike package with beat module
  packages/crowdstrike/data_stream/falcon/agent/stream/log.yml.hbs
  packages/crowdstrike/manifest.yml
Labels: Team:SIEM, Team:Security-External Integrations, enhancement

#324 Sync checkpoint package with beats module
  packages/checkpoint/data_stream/firewall/agent/stream/log.yml.hbs
  packages/checkpoint/data_stream/firewall/agent/stream/syslog.yml.hbs
  packages/checkpoint/manifest.yml
Labels: Team:SIEM, Team:Security-External Integrations, enhancement

#316 Sync Suricata package with Beats
  packages/suricata/data_stream/eve/agent/stream/log.yml.hbs
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/data_stream/eve/fields/base-fields.yml
  packages/suricata/data_stream/eve/fields/ecs.yml
  packages/suricata/docs/README.md
  packages/suricata/kibana/search/13dd22f0-86cc-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/search/1c2bcec0-86d1-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/kibana/search/d57a2db0-86ca-11e8-b59d-21efb914e65c-ecs.json
  packages/suricata/manifest.yml
Labels: Team:Security-External Integrations, bug, enhancement

#325 Sync fortinet package with Beats
  packages/fortinet/data_stream/clientendpoint/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/clientendpoint/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/clientendpoint/fields/base-fields.yml
  packages/fortinet/data_stream/clientendpoint/fields/ecs.yml
  packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/event.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/utm.yml
  packages/fortinet/data_stream/firewall/fields/base-fields.yml
  packages/fortinet/data_stream/firewall/fields/ecs.yml
  packages/fortinet/data_stream/firewall/fields/fields.yml
  packages/fortinet/data_stream/fortimail/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimail/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimail/fields/ecs.yml
  packages/fortinet/data_stream/fortimanager/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimanager/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimanager/fields/ecs.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#328 Sync Panw package with Beats
  packages/panw/data_stream/panos/agent/stream/log.yml.hbs
  packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/data_stream/panos/fields/base-fields.yml
  packages/panw/data_stream/panos/fields/beats.yml
  packages/panw/data_stream/panos/fields/ecs.yml
  packages/panw/data_stream/panos/fields/fields.yml
  packages/panw/docs/README.md
  packages/panw/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#330 Windows event log data stream fixes
  packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/forwarded/fields/ecs.yml
  packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell/fields/ecs.yml
  packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell_operational/fields/ecs.yml
  packages/windows/data_stream/security/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/security/fields/ecs.yml
  packages/windows/data_stream/security/fields/winlog.yml
  packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/sysmon_operational/fields/ecs.yml
  packages/windows/docs/README.md
  packages/windows/manifest.yml
Labels: Team:Security-External Integrations, bug

#332 Bump o365 ecs version to 1.6.0
  packages/o365/data_stream/audit/agent/stream/log.yml.hbs
  packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
  packages/o365/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#331 Bump okta ecs version to 1.6.0
  packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/okta/data_stream/system/agent/stream/log.yml.hbs
  packages/okta/manifest.yml
Labels: Team:SIEM, Team:Security-External Integrations, enhancement

#305 Add memory and iostat datasets
  packages/linux/data_stream/iostat/agent/stream/stream.yml.hbs
  packages/linux/data_stream/iostat/fields/base-fields.yml
  packages/linux/data_stream/iostat/fields/fields.yml
  packages/linux/data_stream/iostat/manifest.yml
  packages/linux/data_stream/memory/agent/stream/stream.yml.hbs
  packages/linux/data_stream/memory/fields/base-fields.yml
  packages/linux/data_stream/memory/fields/fields.yml
  packages/linux/data_stream/memory/manifest.yml
  packages/system/data_stream/diskio/fields/ecs.yml
  packages/system/docs/README.md
Labels: Team:Services, [zube]: (7.10) Planned for release, enhancement

#337 [filebeat][cisco] Add cisco meraki updates
  packages/cisco/data_stream/meraki/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/meraki/fields/ecs.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#336 [filebeat][suricata] Change file.x509 mappings to tls.server.x509
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/data_stream/eve/fields/ecs.yml
  packages/suricata/docs/README.md
  packages/suricata/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#315 [CI] Collect tests results
  .ci/Jenkinsfile
  go.mod
  go.sum
  magefile.go
Labels: Team:Integrations, team:automation

#349 Update rsa2elk packages fields and config
  packages/cisco/data_stream/meraki/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/meraki/fields/base-fields.yml
  packages/cisco/data_stream/meraki/fields/ecs.yml
  packages/cisco/data_stream/nexus/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/nexus/fields/base-fields.yml
  packages/cisco/data_stream/nexus/fields/ecs.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
  packages/fortinet/data_stream/clientendpoint/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/clientendpoint/fields/ecs.yml
  packages/fortinet/data_stream/fortimail/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimail/fields/base-fields.yml
  packages/fortinet/data_stream/fortimail/fields/ecs.yml
  packages/fortinet/data_stream/fortimanager/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimanager/fields/base-fields.yml
  packages/fortinet/data_stream/fortimanager/fields/ecs.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
  packages/juniper/data_stream/junos/agent/stream/stream.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/junos/fields/base-fields.yml
  packages/juniper/data_stream/junos/fields/ecs.yml
  packages/juniper/data_stream/netscreen/agent/stream/stream.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/netscreen/fields/base-fields.yml
  packages/juniper/data_stream/netscreen/fields/ecs.yml
  packages/juniper/docs/README.md
  packages/juniper/manifest.yml
  packages/microsoft/data_stream/dhcp/agent/stream/stream.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/tcp.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/udp.yml.hbs
  packages/microsoft/data_stream/dhcp/fields/base-fields.yml
  packages/microsoft/data_stream/dhcp/fields/ecs.yml
  packages/microsoft/docs/README.md
  packages/microsoft/manifest.yml
Labels: Team:Security-External Integrations, bug

#351 Update CheckPoint package with RFC 5424 parsing fix
  packages/checkpoint/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/checkpoint/data_stream/firewall/fields/base-fields.yml
  packages/checkpoint/data_stream/firewall/fields/ecs.yml
  packages/checkpoint/data_stream/firewall/manifest.yml
  packages/checkpoint/docs/README.md
  packages/checkpoint/manifest.yml
Labels: Team:Security-External Integrations, enhancement
