Repository elastic/integrations, pull requests merged in 2021-11, with the labels that each got.

#2072 [AbuseCH] Bump min version
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/manifest.yml
Labels: Team:Security-External Integrations

#2058 kibana: changes for unified integration UI
  packages/kibana/changelog.yml
  packages/kibana/manifest.yml
Labels: Team:Integrations

#2061 linux: changes for unified integration UI
  packages/linux/changelog.yml
  packages/linux/manifest.yml
Labels: Team:Integrations

#2001 apache: changes for unified integration UI
  packages/apache/changelog.yml
  packages/apache/manifest.yml
Labels: Team:Integrations

#2044 zscaler: changes for unified integration UI
  packages/zscaler/changelog.yml
  packages/zscaler/manifest.yml
Labels: Team:Security-External Integrations

#2018 barracuda: changes for unified integration UI
  packages/barracuda/changelog.yml
  packages/barracuda/manifest.yml
Labels: Team:Security-External Integrations

#2019 bluecoat: changes for unified integration UI
  packages/bluecoat/changelog.yml
  packages/bluecoat/manifest.yml
Labels: Team:Security-External Integrations

#2022 crowdstrike: changes for unified integration UI
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/manifest.yml
Labels: Team:Security-External Integrations

#2075 Add 'elastic-package create' to developer workflow docs
  docs/developer_workflow_design_build_test_integration.md
Labels: documentation, enhancement

#2023 cyberark: changes for unified integration UI
  packages/cyberark/changelog.yml
Labels: Team:Security-External Integrations

#2059 log: changes for unified integration UI
  packages/log/changelog.yml
  packages/log/manifest.yml
Labels: Team:Integrations

#2060 logstash: changes for unified integration UI
  packages/logstash/changelog.yml
  packages/logstash/manifest.yml
Labels: Team:Integrations

#2118 Set kube proxy default hosts to localhost
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/proxy/_dev/test/system/test-default-config.yml
  packages/kubernetes/data_stream/proxy/manifest.yml
  packages/kubernetes/manifest.yml
Labels: bug, Team:Integrations

#2113 Fix processors configuration in windows and o365 packages
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
  packages/o365/data_stream/audit/manifest.yml
  packages/o365/manifest.yml
  packages/windows/changelog.yml
  packages/windows/data_stream/forwarded/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell_operational/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
  packages/windows/manifest.yml
Labels: bug, Team:Security-External Integrations

#2110 netscout: changes for unified integration UI
  packages/netscout/changelog.yml
  packages/netscout/manifest.yml
  packages/zeek/changelog.yml
Labels: Team:Security-External Integrations

#2111 synthetics: changes for unified integration UI
  packages/synthetics/changelog.yml
  packages/synthetics/manifest.yml
Labels: Team:Uptime

#2092 panw_cortex_xdr: changes for unified integration UI
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/manifest.yml
Labels: Team:Security-External Integrations

#2077 zerofox: changes for unified integration UI
  packages/zerofox/changelog.yml
  packages/zerofox/manifest.yml
Labels: Team:Security-External Integrations

#2052 nginx: changes for unified integration UI
  packages/nginx/changelog.yml
  packages/nginx/manifest.yml
Labels: Team:Integrations

#2078 zeek: changes for unified integration UI
  packages/zeek/changelog.yml
  packages/zeek/manifest.yml
Labels: Team:Security-External Integrations

#2045 zoom: changes for unified integration UI
  packages/zoom/changelog.yml
  packages/zoom/manifest.yml
Labels: Team:Security-External Integrations

#2020 cloudflare: changes for unified integration UI
  packages/cloudflare/changelog.yml
  packages/cloudflare/manifest.yml
Labels: Team:Security-External Integrations

#2107 fortinet: changes for unified integration UI
  packages/fortinet/changelog.yml
  packages/fortinet/manifest.yml
Labels: Team:Security-External Integrations

#2091 pfsense: changes for unified integration UI
  packages/pfsense/changelog.yml
  packages/pfsense/manifest.yml
Labels: Team:Security-External Integrations

#2090 proofpoint: changes for unified integration UI
  packages/proofpoint/changelog.yml
  packages/proofpoint/manifest.yml
Labels: Team:Security-External Integrations

#2089 radware: changes for unified integration UI
  packages/radware/changelog.yml
  packages/radware/manifest.yml
Labels: Team:Security-External Integrations

#2088 santa: changes for unified integration UI
  packages/santa/changelog.yml
  packages/santa/manifest.yml
Labels: Team:Security-External Integrations

#2087 sonicwall: changes for unified integration UI
  packages/sonicwall/changelog.yml
  packages/sonicwall/manifest.yml
Labels: Team:Security-External Integrations

#2086 sophos: changes for unified integration UI
  packages/sophos/changelog.yml
  packages/sophos/manifest.yml
Labels: Team:Security-External Integrations

#2083 suricata: changes for unified integration UI
  packages/suricata/changelog.yml
  packages/suricata/manifest.yml
Labels: Team:Security-External Integrations

#2081 tomcat: changes for unified integration UI
  packages/tomcat/changelog.yml
  packages/tomcat/manifest.yml
Labels: Team:Security-External Integrations

#2079 winlog: changes for unified integration UI
  packages/winlog/changelog.yml
  packages/winlog/manifest.yml
Labels: Team:Security-External Integrations

#2085 squid: changes for unified integration UI
  packages/squid/changelog.yml
  packages/squid/manifest.yml
Labels: Team:Security-External Integrations

#2097 network_traffic: changes for unified integration UI
  packages/network_traffic/changelog.yml
  packages/network_traffic/manifest.yml
Labels: Team:Security-External Integrations

#2041 Fixes conditions of kubernetes data_streams that are based on k8s labels
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/container/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/container_logs/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/controllermanager/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/controllermanager/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/event/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/node/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/pod/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/scheduler/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/scheduler/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_container/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_cronjob/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_daemonset/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_deployment/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_job/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_node/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_persistentvolume/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_pod/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_replicaset/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_resourcequota/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_service/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_statefulset/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/state_storageclass/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/data_stream/volume/elasticsearch/ingest_pipeline/default.yml
  packages/kubernetes/manifest.yml
Labels: Team:Integrations

#2106 google_workspace: changes for unified integration UI
  packages/google_workspace/changelog.yml
  packages/google_workspace/manifest.yml
Labels: Team:Security-External Integrations

#2108 f5: changes for unified integration UI
  packages/f5/changelog.yml
  packages/f5/manifest.yml
Labels: Team:Security-External Integrations

#2128 Run daily jobs with 7.16 and 8.0 snapshots
  .ci/schedule-daily.groovy
Labels: Team:Automation, Team:Ecosystem

#2123 Osquery_manager: Update to GA. Reduce the number of explicitly mapped text/keyword osquery fields.
  packages/osquery_manager/changelog.yml
  packages/osquery_manager/data_stream/result/fields/ecs.yml
  packages/osquery_manager/data_stream/result/fields/osquery.yml
  packages/osquery_manager/docs/README.md
  packages/osquery_manager/manifest.yml
Labels: enhancement, Team:Asset Mgt

#2129 Make Cassandra GA
  packages/cassandra/changelog.yml
  packages/cassandra/data_stream/log/manifest.yml
  packages/cassandra/data_stream/metrics/manifest.yml
  packages/cassandra/manifest.yml
Labels: Team:Integrations

#2094 osquery: changes for unified integration UI
  packages/osquery/changelog.yml
  packages/osquery/manifest.yml
Labels: Team:Security-External Integrations

#2100 juniper: changes for unified integration UI
  packages/juniper/changelog.yml
  packages/juniper/manifest.yml
Labels: Team:Security-External Integrations

#2103 imperva: changes for unified integration UI
  packages/imperva/changelog.yml
  packages/imperva/manifest.yml
Labels: Team:Security-External Integrations

#2102 infoblox: changes for unified integration UI
  packages/infoblox/changelog.yml
  packages/infoblox/manifest.yml
Labels: Team:Security-External Integrations

#2101 iptables: changes for unified integration UI
  packages/iptables/changelog.yml
  packages/iptables/manifest.yml
Labels: Team:Security-External Integrations

#2095 okta: changes for unified integration UI
  packages/okta/changelog.yml
  packages/okta/manifest.yml
Labels: Team:Security-External Integrations

#2096 o365: changes for unified integration UI
  packages/o365/changelog.yml
  packages/o365/manifest.yml
Labels: Team:Security-External Integrations

#2084 stan: changes for unified integration UI
  packages/stan/changelog.yml
  packages/stan/manifest.yml
Labels: Team:Integrations

#2082 system: changes for unified integration UI
  packages/system/changelog.yml
  packages/system/manifest.yml
Labels: Team:Integrations

#2098 netflow: changes for unified integration UI
  packages/netflow/changelog.yml
  packages/netflow/manifest.yml
Labels: Team:Security-External Integrations

#2104 iis: changes for unified integration UI
  packages/iis/changelog.yml
  packages/iis/manifest.yml
Labels: Team:Integrations

#2139 Replace logfile input type with filestream type for container logs
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/container_logs/manifest.yml
  packages/kubernetes/manifest.yml
Labels: enhancement, Team:Integrations

#2148 [system] Add missing null check in security pipeline
  packages/system/changelog.yml
  packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
  packages/system/manifest.yml
Labels: bug, Team:Security-External Integrations

#2105 hashicorp_vault: changes for unified integration UI
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/manifest.yml
Labels: Team:Security-External Integrations

#2080 windows: changes for unified integration UI
  packages/windows/changelog.yml
  packages/windows/manifest.yml
Labels: Team:Integrations

#2149 [AbuseCH Package] Adding dashboards and minor tweaks
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malware/elasticsearch/ingest_pipeline/default.yml
  packages/ti_abusech/data_stream/malware/manifest.yml
  packages/ti_abusech/data_stream/malware/sample_event.json
  packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malwarebazaar/elasticsearch/ingest_pipeline/default.yml
  packages/ti_abusech/data_stream/malwarebazaar/manifest.yml
  packages/ti_abusech/data_stream/malwarebazaar/sample_event.json
  packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
  packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
  packages/ti_abusech/data_stream/url/manifest.yml
  packages/ti_abusech/data_stream/url/sample_event.json
  packages/ti_abusech/kibana/dashboard/ti_abusech-2457fb50-3bc3-11ec-ae8c-7d00429ad420.json
  packages/ti_abusech/kibana/dashboard/ti_abusech-6a90c980-3b32-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_abusech/kibana/dashboard/ti_abusech-c0d8d1f0-3b20-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_abusech/kibana/tag/ti_abusech-320c5c80-3b0c-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_abusech/kibana/tag/ti_abusech-73511520-3b32-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_abusech/manifest.yml
Labels: Team:Security-External Integrations, 8.0 candidate

#1762 New Integration - Cybersixgill
  packages/ti_cybersixgill/_dev/build/build.yml
  packages/ti_cybersixgill/_dev/build/docs/README.md
  packages/ti_cybersixgill/_dev/deploy/docker/docker-compose.yml
  packages/ti_cybersixgill/_dev/deploy/docker/sample_logs/test-cybersixgill-threat.ndjson.log
  packages/ti_cybersixgill/changelog.yml
  packages/ti_cybersixgill/data_stream/threat/_dev/test/pipeline/test-common-config.yml
  packages/ti_cybersixgill/data_stream/threat/_dev/test/pipeline/test-cybersixgill.json
  packages/ti_cybersixgill/data_stream/threat/_dev/test/pipeline/test-cybersixgill.json-expected.json
  packages/ti_cybersixgill/data_stream/threat/_dev/test/system/test-webhook-http-config.yml
  packages/ti_cybersixgill/data_stream/threat/_dev/test/system/test-webhook-https-config.yml
  packages/ti_cybersixgill/data_stream/threat/agent/stream/http_endpoint.yml.hbs
  packages/ti_cybersixgill/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
  packages/ti_cybersixgill/data_stream/threat/fields/agent.yml
  packages/ti_cybersixgill/data_stream/threat/fields/base-fields.yml
  packages/ti_cybersixgill/data_stream/threat/fields/ecs.yml
  packages/ti_cybersixgill/data_stream/threat/fields/fields.yml
  packages/ti_cybersixgill/data_stream/threat/manifest.yml
  packages/ti_cybersixgill/data_stream/threat/sample_event.json
  packages/ti_cybersixgill/docs/README.md
  packages/ti_cybersixgill/img/cybersixgill.svg
  packages/ti_cybersixgill/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate, Integration:Cybersixgill

#1894 Add support for azure-eventhub input in integrations
  packages/azure/_dev/build/docs/eventhub.md
  packages/azure/changelog.yml
  packages/azure/data_stream/eventhub/_dev/test/pipeline/test-eventhub-raw.log
  packages/azure/data_stream/eventhub/_dev/test/pipeline/test-eventhub-raw.log-config.yml
  packages/azure/data_stream/eventhub/_dev/test/pipeline/test-eventhub-raw.log-expected.json
  packages/azure/data_stream/eventhub/agent/stream/stream.yml.hbs
  packages/azure/data_stream/eventhub/elasticsearch/ingest_pipeline/azure-shared-pipeline.yml
  packages/azure/data_stream/eventhub/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/eventhub/elasticsearch/ingest_pipeline/parsed-message.yml
  packages/azure/data_stream/eventhub/fields/agent.yml
  packages/azure/data_stream/eventhub/fields/base-fields.yml
  packages/azure/data_stream/eventhub/fields/ecs.yml
  packages/azure/data_stream/eventhub/fields/fields.yml
  packages/azure/data_stream/eventhub/fields/package-fields.yml
  packages/azure/data_stream/eventhub/manifest.yml
  packages/azure/data_stream/eventhub/sample_event.json
  packages/azure/docs/eventhub.md
  packages/azure/img/eventhub.png
  packages/azure/manifest.yml
Labels: Team:Integrations, Integration:Azure

#1931 packages/windows/data_stream/powershell_operations: don't split tokens on hyphen
  packages/windows/changelog.yml
  packages/windows/data_stream/forwarded/fields/fields.yml
  packages/windows/data_stream/forwarded/manifest.yml
  packages/windows/data_stream/powershell/fields/fields.yml
  packages/windows/data_stream/powershell/manifest.yml
  packages/windows/data_stream/powershell_operational/fields/fields.yml
  packages/windows/data_stream/powershell_operational/manifest.yml
  packages/windows/manifest.yml
Labels: bug, Team:Security-External Integrations, 7.16-candidate

#2025 cylance: changes for unified integration UI
  packages/cylance/changelog.yml
  packages/cylance/manifest.yml
Labels: Team:Security-External Integrations

#2026 fleet_server: changes for unified integration UI
  packages/fleet_server/changelog.yml
  packages/fleet_server/manifest.yml
Labels: Team:Integrations, Team:Elastic-Agent

#2024 cyberarkpas: changes for unified integration UI
  packages/cyberarkpas/changelog.yml
  packages/cyberarkpas/manifest.yml
Labels: Team:Security-External Integrations

#2160 Add support for the azure billing package
  packages/azure_billing/_dev/build/build.yml
  packages/azure_billing/_dev/build/docs/README.md
  packages/azure_billing/changelog.yml
  packages/azure_billing/data_stream/billing/agent/stream/stream.yml.hbs
  packages/azure_billing/data_stream/billing/fields/agent.yml
  packages/azure_billing/data_stream/billing/fields/base-fields.yml
  packages/azure_billing/data_stream/billing/fields/ecs.yml
  packages/azure_billing/data_stream/billing/fields/fields.yml
  packages/azure_billing/data_stream/billing/fields/package-fields.yml
  packages/azure_billing/data_stream/billing/manifest.yml
  packages/azure_billing/data_stream/billing/sample_event.json
  packages/azure_billing/docs/README.md
  packages/azure_billing/img/azure-billing-overview.png
  packages/azure_billing/img/billing.png
  packages/azure_billing/kibana/dashboard/azure_billing-d3efeb30-c1c7-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/kibana/visualization/azure_billing-05d5b3e0-c1c9-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/kibana/visualization/azure_billing-6ffa7e20-c1da-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/kibana/visualization/azure_billing-82a51dd0-c1d7-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/kibana/visualization/azure_billing-9142aca0-c1c7-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/kibana/visualization/azure_billing-b18053b0-c1da-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/kibana/visualization/azure_billing-c8016f70-c1da-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/manifest.yml
  packages/azure_metrics/kibana/visualization/azure_metrics-e4b25ee0-32f6-11ea-a83e-25b8612d00cc.json
Labels: Team:Integrations, Integration:Azure

#2122 Release Apache for Kibana 8
  packages/apache/changelog.yml
  packages/apache/manifest.yml
Labels: Team:Integrations

#2189 Release prometheus package for v8.0.0
  packages/prometheus/changelog.yml
  packages/prometheus/manifest.yml
Labels: enhancement, Team:Integrations

#2190 Release haproxy package for v8.0.0
  packages/haproxy/changelog.yml
  packages/haproxy/manifest.yml
Labels: enhancement, Team:Integrations

#1609 Make Kafka GA
  packages/kafka/changelog.yml
  packages/kafka/data_stream/broker/manifest.yml
  packages/kafka/data_stream/consumergroup/manifest.yml
  packages/kafka/data_stream/log/manifest.yml
  packages/kafka/data_stream/partition/manifest.yml
  packages/kafka/manifest.yml
Labels: enhancement, Team:Integrations

#1608 Make HAProxy GA
  packages/haproxy/changelog.yml
  packages/haproxy/data_stream/info/manifest.yml
  packages/haproxy/data_stream/log/manifest.yml
  packages/haproxy/data_stream/stat/manifest.yml
  packages/haproxy/manifest.yml
Labels: enhancement, Team:Integrations

#2156 [System] Fix AccessList & AccessMask processing in security data_stream
  packages/system/changelog.yml
  packages/system/data_stream/security/_dev/test/pipeline/test-4663.json
  packages/system/data_stream/security/_dev/test/pipeline/test-4663.json-expected.json
  packages/system/data_stream/security/_dev/test/pipeline/test-4674.json
  packages/system/data_stream/security/_dev/test/pipeline/test-4674.json-expected.json
  packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/security/fields/winlog.yml
  packages/system/docs/README.md
  packages/system/manifest.yml
Labels: bug, Team:Security-External Integrations

#2076 Add some dimensions to the kubernetes integration
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/apiserver/fields/fields.yml
  packages/kubernetes/data_stream/container/fields/agent.yml
  packages/kubernetes/data_stream/container/fields/base-fields.yml
  packages/kubernetes/data_stream/container_logs/fields/agent.yml
  packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
  packages/kubernetes/data_stream/controllermanager/fields/fields.yml
  packages/kubernetes/data_stream/event/fields/fields.yml
  packages/kubernetes/data_stream/node/fields/base-fields.yml
  packages/kubernetes/data_stream/pod/fields/base-fields.yml
  packages/kubernetes/data_stream/proxy/fields/fields.yml
  packages/kubernetes/data_stream/scheduler/fields/fields.yml
  packages/kubernetes/data_stream/state_container/fields/agent.yml
  packages/kubernetes/data_stream/state_container/fields/base-fields.yml
  packages/kubernetes/data_stream/state_cronjob/fields/base-fields.yml
  packages/kubernetes/data_stream/state_cronjob/fields/fields.yml
  packages/kubernetes/data_stream/state_daemonset/fields/base-fields.yml
  packages/kubernetes/data_stream/state_daemonset/fields/fields.yml
  packages/kubernetes/data_stream/state_deployment/fields/base-fields.yml
  packages/kubernetes/data_stream/state_job/fields/base-fields.yml
  packages/kubernetes/data_stream/state_job/fields/fields.yml
  packages/kubernetes/data_stream/state_node/fields/base-fields.yml
  packages/kubernetes/data_stream/state_persistentvolume/fields/fields.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/fields/base-fields.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/fields/fields.yml
  packages/kubernetes/data_stream/state_pod/fields/base-fields.yml
  packages/kubernetes/data_stream/state_replicaset/fields/base-fields.yml
  packages/kubernetes/data_stream/state_resourcequota/fields/base-fields.yml
  packages/kubernetes/data_stream/state_resourcequota/fields/fields.yml
  packages/kubernetes/data_stream/state_service/fields/base-fields.yml
  packages/kubernetes/data_stream/state_service/fields/fields.yml
  packages/kubernetes/data_stream/state_statefulset/fields/base-fields.yml
  packages/kubernetes/data_stream/state_storageclass/fields/fields.yml
  packages/kubernetes/data_stream/system/fields/base-fields.yml
  packages/kubernetes/data_stream/system/fields/fields.yml
  packages/kubernetes/data_stream/volume/fields/base-fields.yml
  packages/kubernetes/data_stream/volume/fields/fields.yml
  packages/kubernetes/manifest.yml
Labels: Team:Integrations, Team:Ecosystem

#2064 Fix parsing of apache trace log levels
  packages/apache/changelog.yml
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-trace.log
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-trace.log-expected.json
  packages/apache/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/apache/manifest.yml
Labels: Team:Integrations

#2068 [Juniper] Split Juniper SRX datastream into separate package
  packages/juniper_srx/_dev/build/build.yml
  packages/juniper_srx/_dev/build/docs/README.md
  packages/juniper_srx/_dev/deploy/docker/docker-compose.yml
  packages/juniper_srx/_dev/deploy/docker/sample_logs/juniper-srx.log
  packages/juniper_srx/changelog.yml
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-atp.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-flow.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-idp.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-ids.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-secintel.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-utm.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/juniper_srx/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/juniper_srx/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/juniper_srx/data_stream/log/agent/stream/logfile.yml.hbs
  packages/juniper_srx/data_stream/log/agent/stream/tcp.yml.hbs
  packages/juniper_srx/data_stream/log/agent/stream/udp.yml.hbs
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/atp.yml
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/flow.yml
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/idp.yml
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/ids.yml
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/secintel.yml
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/utm.yml
  packages/juniper_srx/data_stream/log/fields/agent.yml
  packages/juniper_srx/data_stream/log/fields/base-fields.yml
  packages/juniper_srx/data_stream/log/fields/ecs.yml
  packages/juniper_srx/data_stream/log/fields/fields.yml
  packages/juniper_srx/data_stream/log/manifest.yml
  packages/juniper_srx/docs/README.md
  packages/juniper_srx/img/logo.svg
  packages/juniper_srx/manifest.yml
Labels: Team:Security-External Integrations

#2173 Release CockroachDB for Kibana 8
  packages/cockroachdb/changelog.yml
  packages/cockroachdb/manifest.yml
Labels: Team:Integrations

#2179 Release Windows for Kibana 8
  packages/windows/changelog.yml
  packages/windows/manifest.yml
Labels: Team:Integrations

#2178 Release IIS for Kibana 8
  packages/iis/changelog.yml
  packages/iis/manifest.yml
Labels: Team:Integrations

#2201 fix version strings, hostfs
  packages/linux/changelog.yml
  packages/linux/data_stream/conntrack/agent/stream/stream.yml.hbs
  packages/linux/data_stream/entropy/agent/stream/stream.yml.hbs
  packages/linux/data_stream/iostat/agent/stream/stream.yml.hbs
  packages/linux/data_stream/ksm/agent/stream/stream.yml.hbs
  packages/linux/data_stream/memory/agent/stream/stream.yml.hbs
  packages/linux/data_stream/pageinfo/agent/stream/stream.yml.hbs
  packages/linux/data_stream/raid/agent/stream/stream.yml.hbs
  packages/linux/data_stream/service/agent/stream/stream.yml.hbs
  packages/linux/data_stream/socket/agent/stream/stream.yml.hbs
  packages/linux/data_stream/users/agent/stream/stream.yml.hbs
  packages/linux/manifest.yml
  packages/system/changelog.yml
  packages/system/data_stream/core/agent/stream/stream.yml.hbs
  packages/system/data_stream/cpu/agent/stream/stream.yml.hbs
  packages/system/data_stream/diskio/agent/stream/stream.yml.hbs
  packages/system/data_stream/filesystem/agent/stream/stream.yml.hbs
  packages/system/data_stream/fsstat/agent/stream/stream.yml.hbs
  packages/system/data_stream/memory/agent/stream/stream.yml.hbs
  packages/system/manifest.yml
Labels: Team:Integrations

#2172 [New Package] TCP Input
  packages/tcp/_dev/build/build.yml
  packages/tcp/_dev/build/docs/README.md
  packages/tcp/_dev/deploy/docker/docker-compose.yml
  packages/tcp/_dev/deploy/docker/sample_logs/test-tcp.log
  packages/tcp/changelog.yml
  packages/tcp/data_stream/generic/_dev/test/system/test-tcp-config.yml
  packages/tcp/data_stream/generic/agent/stream/tcp.yml.hbs
  packages/tcp/data_stream/generic/fields/base-fields.yml
  packages/tcp/data_stream/generic/fields/beats.yml
  packages/tcp/data_stream/generic/fields/ecs.yml
  packages/tcp/data_stream/generic/manifest.yml
  packages/tcp/data_stream/generic/sample_event.json
  packages/tcp/docs/README.md
  packages/tcp/img/icon.svg
  packages/tcp/manifest.yml
Labels: Team:Integrations, Team:Security-External Integrations

#2170 [New Package] UDP Input
  packages/udp/_dev/build/build.yml
  packages/udp/_dev/build/docs/README.md
  packages/udp/_dev/deploy/docker/docker-compose.yml
  packages/udp/_dev/deploy/docker/sample_logs/test-udp.log
  packages/udp/changelog.yml
  packages/udp/data_stream/generic/_dev/test/system/test-udp-config.yml
  packages/udp/data_stream/generic/agent/stream/udp.yml.hbs
  packages/udp/data_stream/generic/fields/base-fields.yml
  packages/udp/data_stream/generic/fields/beats.yml
  packages/udp/data_stream/generic/fields/ecs.yml
  packages/udp/data_stream/generic/manifest.yml
  packages/udp/data_stream/generic/sample_event.json
  packages/udp/docs/README.md
  packages/udp/img/icon.svg
  packages/udp/manifest.yml
Labels: enhancement, Team:Integrations, Team:Security-External Integrations

#2070 [Juniper] Split Juniper NetScreen datastream into separate package
  packages/juniper_netscreen/_dev/build/build.yml
  packages/juniper_netscreen/_dev/build/docs/README.md
  packages/juniper_netscreen/_dev/deploy/docker/docker-compose.yml
  packages/juniper_netscreen/_dev/deploy/docker/sample_logs/juniper-netscreen.log
  packages/juniper_netscreen/changelog.yml
  packages/juniper_netscreen/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/juniper_netscreen/data_stream/log/_dev/test/pipeline/test-generated.log
  packages/juniper_netscreen/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper_netscreen/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/juniper_netscreen/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/juniper_netscreen/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/juniper_netscreen/data_stream/log/agent/stream/logfile.yml.hbs
  packages/juniper_netscreen/data_stream/log/agent/stream/tcp.yml.hbs
  packages/juniper_netscreen/data_stream/log/agent/stream/udp.yml.hbs
  packages/juniper_netscreen/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/juniper_netscreen/data_stream/log/fields/agent.yml
  packages/juniper_netscreen/data_stream/log/fields/base-fields.yml
  packages/juniper_netscreen/data_stream/log/fields/ecs.yml
  packages/juniper_netscreen/data_stream/log/fields/fields.yml
  packages/juniper_netscreen/data_stream/log/manifest.yml
  packages/juniper_netscreen/data_stream/log/sample_event.json
  packages/juniper_netscreen/docs/README.md
  packages/juniper_netscreen/img/logo.svg
  packages/juniper_netscreen/manifest.yml
Labels: Team:Security-External Integrations

#2069 [Juniper] Split Juniper JunOS datastream into separate package
  packages/juniper_junos/_dev/build/build.yml
  packages/juniper_junos/_dev/build/docs/README.md
  packages/juniper_junos/_dev/deploy/docker/docker-compose.yml
  packages/juniper_junos/_dev/deploy/docker/sample_logs/juniper-junos.log
  packages/juniper_junos/changelog.yml
  packages/juniper_junos/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/juniper_junos/data_stream/log/_dev/test/pipeline/test-generated.log
  packages/juniper_junos/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper_junos/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/juniper_junos/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/juniper_junos/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/juniper_junos/data_stream/log/agent/stream/stream.yml.hbs
  packages/juniper_junos/data_stream/log/agent/stream/tcp.yml.hbs
  packages/juniper_junos/data_stream/log/agent/stream/udp.yml.hbs
  packages/juniper_junos/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/juniper_junos/data_stream/log/fields/agent.yml
  packages/juniper_junos/data_stream/log/fields/base-fields.yml
  packages/juniper_junos/data_stream/log/fields/ecs.yml
  packages/juniper_junos/data_stream/log/fields/fields.yml
  packages/juniper_junos/data_stream/log/manifest.yml
  packages/juniper_junos/data_stream/log/sample_event.json
  packages/juniper_junos/docs/README.md
  packages/juniper_junos/img/logo.svg
  packages/juniper_junos/manifest.yml
Labels: Team:Security-External Integrations

#2217 [ML] Fix Apache ML module manifest query to ignore frozen and cold tiers
  packages/apache/changelog.yml
  packages/apache/kibana/ml_module/apache-Logs-ml.json
  packages/apache/manifest.yml
Labels: bug, Integration:Apache

#2219 [ML] Fix Nginx ML module manifest query to ignore frozen and cold tiers
  packages/nginx/changelog.yml
  packages/nginx/kibana/ml_module/nginx-Logs-ml.json
  packages/nginx/manifest.yml
Labels: bug, Integration:NGINX

#2214 [1password] Add 8.0.0 constraint
  packages/1password/changelog.yml
  packages/1password/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2280 Update checkbox in template for version constraint guidelines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team:Integrations, Team:Ecosystem

#2220 [netflow] Add 8.0.0 constraint
  packages/netflow/changelog.yml
  packages/netflow/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2221 [panw] Add 8.0.0 constraint
  packages/panw/changelog.yml
  packages/panw/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2223 [cyberarkpas] Add 8.0.0 constraint
  packages/cyberarkpas/changelog.yml
  packages/cyberarkpas/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2224 [network_traffic] Add 8.0.0 constraint
  packages/network_traffic/changelog.yml
  packages/network_traffic/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2198 [crowdstrike] Add support to parse the custom notification format provided by Crowdstrike
  packages/crowdstrike/_dev/build/docs/README.md
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log
  packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log-expected.json
  packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
  packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/data_stream/fdr/fields/ecs.yml
  packages/crowdstrike/data_stream/fdr/fields/fields.yml
  packages/crowdstrike/data_stream/fdr/manifest.yml
  packages/crowdstrike/docs/README.md
  packages/crowdstrike/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Crowdstrike
