Repository elastic/integrations, pull requests merged in 2021-10, with the labels that each got.

#1708 [stan] Update ECS to 1.12
  packages/stan/_dev/build/build.yml
  packages/stan/changelog.yml
  packages/stan/data_stream/channels/fields/ecs.yml
  packages/stan/data_stream/channels/sample_event.json
  packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
  packages/stan/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/stan/data_stream/log/sample_event.json
  packages/stan/data_stream/stats/fields/ecs.yml
  packages/stan/data_stream/stats/sample_event.json
  packages/stan/data_stream/subscriptions/fields/ecs.yml
  packages/stan/data_stream/subscriptions/sample_event.json
  packages/stan/docs/README.md
  packages/stan/manifest.yml
Labels: enhancement, Team:Integrations

#1685 [activemq] Update ECS to 1.12
  packages/activemq/_dev/build/build.yml
  packages/activemq/changelog.yml
  packages/activemq/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/activemq/data_stream/audit/agent/stream/log.yml.hbs
  packages/activemq/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/activemq/data_stream/audit/sample_event.json
  packages/activemq/data_stream/broker/sample_event.json
  packages/activemq/data_stream/log/_dev/test/pipeline/test-activemq.log-expected.json
  packages/activemq/data_stream/log/agent/stream/log.yml.hbs
  packages/activemq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/activemq/data_stream/log/sample_event.json
  packages/activemq/data_stream/queue/sample_event.json
  packages/activemq/data_stream/topic/sample_event.json
  packages/activemq/docs/README.md
  packages/activemq/manifest.yml
Labels: enhancement, Team:Integrations

#1703 [osquery_manager] Update ECS to 1.12
  packages/osquery_manager/_dev/build/build.yml
  packages/osquery_manager/changelog.yml
  packages/osquery_manager/data_stream/result/fields/ecs.yml
  packages/osquery_manager/manifest.yml
Labels: enhancement, Team:Integrations

#1788 [cisco] Update ECS to 1.12
  packages/cisco/_dev/build/build.yml
  packages/cisco/changelog.yml
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/meraki/_dev/test/pipeline/test-generated.log-expected.json
  packages/cisco/data_stream/meraki/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/nexus/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1787 [cisco_umbrella] Update ECS to 1.12
  packages/cisco_umbrella/changelog.yml
  packages/cisco_umbrella/data_stream/log/sample_event.json
  packages/cisco_umbrella/docs/README.md
  packages/cisco_umbrella/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1786 [cisco_nexus] Update ECS to 1.12
  packages/cisco_nexus/_dev/build/build.yml
  packages/cisco_nexus/changelog.yml
  packages/cisco_nexus/data_stream/log/_dev/test/pipeline/test-nexus.log-expected.json
  packages/cisco_nexus/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_nexus/data_stream/log/sample_event.json
  packages/cisco_nexus/docs/README.md
  packages/cisco_nexus/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1785 [cisco_meraki] Update ECS to 1.12
  packages/cisco_meraki/_dev/build/build.yml
  packages/cisco_meraki/changelog.yml
  packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_meraki/data_stream/log/sample_event.json
  packages/cisco_meraki/docs/README.md
  packages/cisco_meraki/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1784 [cisco_ios] Update ECS to 1.12
  packages/cisco_ios/_dev/build/build.yml
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/data_stream/log/sample_event.json
  packages/cisco_ios/docs/README.md
  packages/cisco_ios/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1783 [cisco_ftd] Update ECS to 1.12
  packages/cisco_ftd/_dev/build/build.yml
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ftd/data_stream/log/sample_event.json
  packages/cisco_ftd/docs/README.md
  packages/cisco_ftd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1782 [cisco_asa] Update ECS to 1.12
  packages/cisco_asa/_dev/build/build.yml
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_asa/data_stream/log/sample_event.json
  packages/cisco_asa/docs/README.md
  packages/cisco_asa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1781 [microsoft] Update ECS to 1.12
  packages/microsoft/_dev/build/build.yml
  packages/microsoft/changelog.yml
  packages/microsoft/data_stream/defender_atp/_dev/test/pipeline/test-defenderatp.log-expected.json
  packages/microsoft/data_stream/defender_atp/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft/data_stream/dhcp/_dev/test/pipeline/test-generated.log-expected.json
  packages/microsoft/data_stream/dhcp/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft/docs/README.md
  packages/microsoft/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1669 [network_traffic] Update ECS to 1.12
  packages/network_traffic/_dev/build/build.yml
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/amqp/fields/ecs.yml
  packages/network_traffic/data_stream/cassandra/fields/ecs.yml
  packages/network_traffic/data_stream/dhcpv4/fields/ecs.yml
  packages/network_traffic/data_stream/dns/fields/ecs.yml
  packages/network_traffic/data_stream/flow/fields/ecs.yml
  packages/network_traffic/data_stream/http/fields/ecs.yml
  packages/network_traffic/data_stream/icmp/fields/ecs.yml
  packages/network_traffic/data_stream/memcached/fields/ecs.yml
  packages/network_traffic/data_stream/mongodb/fields/ecs.yml
  packages/network_traffic/data_stream/mysql/fields/ecs.yml
  packages/network_traffic/data_stream/nfs/fields/ecs.yml
  packages/network_traffic/data_stream/pgsql/fields/ecs.yml
  packages/network_traffic/data_stream/redis/fields/ecs.yml
  packages/network_traffic/data_stream/sip/fields/ecs.yml
  packages/network_traffic/data_stream/thrift/fields/ecs.yml
  packages/network_traffic/data_stream/tls/fields/ecs.yml
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1814 [cyberarkpas] Fix contains check for forwarded tag
  packages/cyberarkpas/changelog.yml
  packages/cyberarkpas/data_stream/audit/agent/stream/log.yml.hbs
  packages/cyberarkpas/data_stream/audit/agent/stream/tcp.yml.hbs
  packages/cyberarkpas/data_stream/audit/agent/stream/udp.yml.hbs
  packages/cyberarkpas/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1813 [cyberark] Fix contains check for forwarded tag
  packages/cyberark/changelog.yml
  packages/cyberark/data_stream/corepas/agent/stream/stream.yml.hbs
  packages/cyberark/data_stream/corepas/agent/stream/tcp.yml.hbs
  packages/cyberark/data_stream/corepas/agent/stream/udp.yml.hbs
  packages/cyberark/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1812 [crowdstrike] Fix contains check for forwarded tag
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/falcon/agent/stream/log.yml.hbs
  packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
  packages/crowdstrike/data_stream/fdr/agent/stream/stream.yml.hbs
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1811 [cloudflare] Fix contains check for forwarded tag
  packages/cloudflare/changelog.yml
  packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs
  packages/cloudflare/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1810 [cisco_umbrella] Fix contains check for forwarded tag
  packages/cisco_umbrella/changelog.yml
  packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
  packages/cisco_umbrella/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1809 [cisco_nexus] Fix contains check for forwarded tag
  packages/cisco_nexus/changelog.yml
  packages/cisco_nexus/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_nexus/data_stream/log/agent/stream/tcp.yml.hbs
  packages/cisco_nexus/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_nexus/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1808 [cisco_meraki] Fix contains check for forwarded tag
  packages/cisco_meraki/changelog.yml
  packages/cisco_meraki/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_meraki/data_stream/log/agent/stream/tcp.yml.hbs
  packages/cisco_meraki/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_meraki/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1807 [cisco_ios] Fix contains check for forwarded tag
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ios/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ios/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1806 [cisco_ftd] Fix contains check for forwarded tag
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ftd/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ftd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1804 [cisco] Fix contains check for forwarded tag
  packages/cisco/changelog.yml
  packages/cisco/data_stream/asa/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/asa/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/ftd/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/ftd/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/ios/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/ios/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/udp.yml.hbs
  packages/cisco/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1801 [carbonblack_edr] Fix contains check for forwarded tag
  packages/carbonblack_edr/changelog.yml
  packages/carbonblack_edr/data_stream/log/agent/stream/http_endpoint.yml.hbs
  packages/carbonblack_edr/data_stream/log/agent/stream/log.yml.hbs
  packages/carbonblack_edr/data_stream/log/agent/stream/tcpudp.yml.hbs
  packages/carbonblack_edr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1800 [bluecoat] Fix contains check for forwarded tag
  packages/bluecoat/changelog.yml
  packages/bluecoat/data_stream/director/agent/stream/stream.yml.hbs
  packages/bluecoat/data_stream/director/agent/stream/tcp.yml.hbs
  packages/bluecoat/data_stream/director/agent/stream/udp.yml.hbs
  packages/bluecoat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1798 [azure] Fix contains check for forwarded tag
  packages/azure/changelog.yml
  packages/azure/data_stream/activitylogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/activitylogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/auditlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/auditlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/platformlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/platformlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/signinlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/signinlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/springcloudlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/springcloudlogs/agent/stream/log.yml.hbs
  packages/azure/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1797 [aws] Fix contains check for forwarded tag
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/cloudtrail/agent/stream/httpjson.yml.hbs
  packages/aws/data_stream/cloudwatch_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/ec2_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/elb_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/s3access/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/s3access/agent/stream/log.yml.hbs
  packages/aws/data_stream/vpcflow/agent/stream/aws-s3.yml.hbs
  packages/aws/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1796 [auditd] Fix contains check for forwarded tag
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/agent/stream/log.yml.hbs
  packages/auditd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1794 [apache] Fix contains check for forwarded tag
  packages/apache/changelog.yml
  packages/apache/data_stream/access/agent/stream/httpjson.yml.hbs
  packages/apache/data_stream/access/agent/stream/log.yml.hbs
  packages/apache/data_stream/error/agent/stream/httpjson.yml.hbs
  packages/apache/data_stream/error/agent/stream/log.yml.hbs
  packages/apache/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1864 [zscaler] Fix contains check for forwarded tag
  packages/zscaler/changelog.yml
  packages/zscaler/data_stream/zia/agent/stream/stream.yml.hbs
  packages/zscaler/data_stream/zia/agent/stream/tcp.yml.hbs
  packages/zscaler/data_stream/zia/agent/stream/udp.yml.hbs
  packages/zscaler/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1863 [zoom] Fix contains check for forwarded tag
  packages/zoom/changelog.yml
  packages/zoom/data_stream/webhook/agent/stream/http_endpoint.yml.hbs
  packages/zoom/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1862 [zerofox] Fix contains check for forwarded tag
  packages/zerofox/changelog.yml
  packages/zerofox/data_stream/alerts/agent/stream/httpjson.yml.hbs
  packages/zerofox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1860 [winlog] Fix contains check for forwarded tag
  packages/winlog/changelog.yml
  packages/winlog/data_stream/winlog/agent/stream/httpjson.yml.hbs
  packages/winlog/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1859 [windows] Fix contains check for forwarded tag
  packages/windows/changelog.yml
  packages/windows/data_stream/forwarded/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/powershell_operational/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
  packages/windows/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1858 [vsphere] Fix contains check for forwarded tag
  packages/vsphere/changelog.yml
  packages/vsphere/data_stream/log/agent/stream/tcpudp.yml.hbs
  packages/vsphere/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1857 [traefik] Fix contains check for forwarded tag
  packages/traefik/changelog.yml
  packages/traefik/data_stream/access/agent/stream/log.yml.hbs
  packages/traefik/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1856 [tomcat] Fix contains check for forwarded tag
  packages/tomcat/changelog.yml
  packages/tomcat/data_stream/log/agent/stream/stream.yml.hbs
  packages/tomcat/data_stream/log/agent/stream/tcp.yml.hbs
  packages/tomcat/data_stream/log/agent/stream/udp.yml.hbs
  packages/tomcat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1855 [system] Fix contains check for forwarded tag
  packages/system/changelog.yml
  packages/system/data_stream/application/agent/stream/httpjson.yml.hbs
  packages/system/data_stream/security/agent/stream/httpjson.yml.hbs
  packages/system/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/system/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1854 [suricata] Fix contains check for forwarded tag
  packages/suricata/changelog.yml
  packages/suricata/data_stream/eve/agent/stream/log.yml.hbs
  packages/suricata/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1853 [stan] Fix contains check for forwarded tag
  packages/stan/changelog.yml
  packages/stan/data_stream/log/agent/stream/log.yml.hbs
  packages/stan/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1852 [squid] Fix contains check for forwarded tag
  packages/squid/changelog.yml
  packages/squid/data_stream/log/agent/stream/stream.yml.hbs
  packages/squid/data_stream/log/agent/stream/tcp.yml.hbs
  packages/squid/data_stream/log/agent/stream/udp.yml.hbs
  packages/squid/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1851 [sophos] Fix contains check for forwarded tag
  packages/sophos/changelog.yml
  packages/sophos/data_stream/utm/agent/stream/stream.yml.hbs
  packages/sophos/data_stream/utm/agent/stream/tcp.yml.hbs
  packages/sophos/data_stream/utm/agent/stream/udp.yml.hbs
  packages/sophos/data_stream/xg/agent/stream/log.yml.hbs
  packages/sophos/data_stream/xg/agent/stream/tcp.yml.hbs
  packages/sophos/data_stream/xg/agent/stream/udp.yml.hbs
  packages/sophos/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1850 [sonicwall] Fix contains check for forwarded tag
  packages/sonicwall/changelog.yml
  packages/sonicwall/data_stream/firewall/agent/stream/stream.yml.hbs
  packages/sonicwall/data_stream/firewall/agent/stream/tcp.yml.hbs
  packages/sonicwall/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/sonicwall/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1849 [snort] Fix contains check for forwarded tag
  packages/snort/changelog.yml
  packages/snort/data_stream/log/agent/stream/log.yml.hbs
  packages/snort/data_stream/log/agent/stream/udp.yml.hbs
  packages/snort/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1848 [santa] Fix contains check for forwarded tag
  packages/santa/changelog.yml
  packages/santa/data_stream/log/agent/stream/log.yml.hbs
  packages/santa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1847 [redis] Fix contains check for forwarded tag
  packages/redis/changelog.yml
  packages/redis/data_stream/log/agent/stream/stream.yml.hbs
  packages/redis/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1846 [radware] Fix contains check for forwarded tag
  packages/radware/changelog.yml
  packages/radware/data_stream/defensepro/agent/stream/stream.yml.hbs
  packages/radware/data_stream/defensepro/agent/stream/tcp.yml.hbs
  packages/radware/data_stream/defensepro/agent/stream/udp.yml.hbs
  packages/radware/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1845 [rabbitmq] Fix contains check for forwarded tag
  packages/rabbitmq/changelog.yml
  packages/rabbitmq/data_stream/log/agent/stream/log.yml.hbs
  packages/rabbitmq/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1844 [proofpoint] Fix contains check for forwarded tag
  packages/proofpoint/changelog.yml
  packages/proofpoint/data_stream/emailsecurity/agent/stream/stream.yml.hbs
  packages/proofpoint/data_stream/emailsecurity/agent/stream/tcp.yml.hbs
  packages/proofpoint/data_stream/emailsecurity/agent/stream/udp.yml.hbs
  packages/proofpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1843 [postgresql] Fix contains check for forwarded tag
  packages/postgresql/changelog.yml
  packages/postgresql/data_stream/log/agent/stream/log.yml.hbs
  packages/postgresql/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1842 [pfsense] Fix contains check for forwarded tag
  packages/pfsense/changelog.yml
  packages/pfsense/data_stream/log/agent/stream/udp.yml.hbs
  packages/pfsense/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1841 [panw_cortex_xdr] Fix contains check for forwarded tag
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/data_stream/alerts/agent/stream/httpjson.yml.hbs
  packages/panw_cortex_xdr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1840 [panw] Fix contains check for forwarded tag
  packages/panw/changelog.yml
  packages/panw/data_stream/panos/agent/stream/logfile.yml.hbs
  packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
  packages/panw/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1839 [osquery] Fix contains check for forwarded tag
  packages/osquery/changelog.yml
  packages/osquery/data_stream/result/agent/stream/log.yml.hbs
  packages/osquery/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1838 [okta] Fix contains check for forwarded tag
  packages/okta/changelog.yml
  packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/okta/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1837 [o365] Fix contains check for forwarded tag
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
  packages/o365/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1836 [nginx_ingress_controller] Fix contains check for forwarded tag
  packages/nginx_ingress_controller/changelog.yml
  packages/nginx_ingress_controller/data_stream/access/agent/stream/stream.yml.hbs
  packages/nginx_ingress_controller/data_stream/error/agent/stream/stream.yml.hbs
  packages/nginx_ingress_controller/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1835 [nginx] Fix contains check for forwarded tag
  packages/nginx/changelog.yml
  packages/nginx/data_stream/access/agent/stream/httpjson.yml.hbs
  packages/nginx/data_stream/access/agent/stream/stream.yml.hbs
  packages/nginx/data_stream/error/agent/stream/httpjson.yml.hbs
  packages/nginx/data_stream/error/agent/stream/stream.yml.hbs
  packages/nginx/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1834 [netscout] Fix contains check for forwarded tag
  packages/netscout/changelog.yml
  packages/netscout/data_stream/sightline/agent/stream/stream.yml.hbs
  packages/netscout/data_stream/sightline/agent/stream/tcp.yml.hbs
  packages/netscout/data_stream/sightline/agent/stream/udp.yml.hbs
  packages/netscout/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1833 [netflow] Fix contains check for forwarded tag
  packages/netflow/changelog.yml
  packages/netflow/data_stream/log/agent/stream/netflow.yml.hbs
  packages/netflow/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1832 [nats] Fix contains check for forwarded tag
  packages/nats/changelog.yml
  packages/nats/data_stream/log/agent/stream/log.yml.hbs
  packages/nats/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1831 [mongodb] Fix contains check for forwarded tag
  packages/mongodb/changelog.yml
  packages/mongodb/data_stream/log/agent/stream/log.yml.hbs
  packages/mongodb/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1830 [modsecurity] Fix contains check for forwarded tag
  packages/modsecurity/changelog.yml
  packages/modsecurity/data_stream/auditlog/agent/stream/stream.yml.hbs
  packages/modsecurity/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1829 [microsoft_defender_endpoint] Fix contains check for forwarded tag
  packages/microsoft_defender_endpoint/changelog.yml
  packages/microsoft_defender_endpoint/data_stream/log/agent/stream/httpjson.yml.hbs
  packages/microsoft_defender_endpoint/data_stream/log/agent/stream/log.yml.hbs
  packages/microsoft_defender_endpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1828 [microsoft] Fix contains check for forwarded tag
  packages/microsoft/changelog.yml
  packages/microsoft/data_stream/defender_atp/agent/stream/httpjson.yml.hbs
  packages/microsoft/data_stream/defender_atp/agent/stream/log.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/log.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/tcp.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/udp.yml.hbs
  packages/microsoft/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1827 [kafka] Fix contains check for forwarded tag
  packages/kafka/changelog.yml
  packages/kafka/data_stream/log/agent/stream/log.yml.hbs
  packages/kafka/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1826 [juniper] Fix contains check for forwarded tag
  packages/juniper/changelog.yml
  packages/juniper/data_stream/junos/agent/stream/stream.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/logfile.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/srx/agent/stream/logfile.yml.hbs
  packages/juniper/data_stream/srx/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/srx/agent/stream/udp.yml.hbs
  packages/juniper/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1825 [iptables] Fix contains check for forwarded tag
  packages/iptables/changelog.yml
  packages/iptables/data_stream/log/agent/stream/log.yml.hbs
  packages/iptables/data_stream/log/agent/stream/udp.yml.hbs
  packages/iptables/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1824 [infoblox] Fix contains check for forwarded tag
  packages/infoblox/changelog.yml
  packages/infoblox/data_stream/nios/agent/stream/stream.yml.hbs
  packages/infoblox/data_stream/nios/agent/stream/tcp.yml.hbs
  packages/infoblox/data_stream/nios/agent/stream/udp.yml.hbs
  packages/infoblox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1823 [imperva] Fix contains check for forwarded tag
  packages/imperva/changelog.yml
  packages/imperva/data_stream/securesphere/agent/stream/stream.yml.hbs
  packages/imperva/data_stream/securesphere/agent/stream/tcp.yml.hbs
  packages/imperva/data_stream/securesphere/agent/stream/udp.yml.hbs
  packages/imperva/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1822 [iis] Fix contains check for forwarded tag
  packages/iis/changelog.yml
  packages/iis/data_stream/access/agent/stream/log.yml.hbs
  packages/iis/data_stream/error/agent/stream/log.yml.hbs
  packages/iis/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1821 [hashicorp_vault] Fix contains check for forwarded tag
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/data_stream/audit/agent/stream/logfile.yml.hbs
  packages/hashicorp_vault/data_stream/audit/agent/stream/tcp.yml.hbs
  packages/hashicorp_vault/data_stream/log/agent/stream/logfile.yml.hbs
  packages/hashicorp_vault/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1820 [haproxy] Fix contains check for forwarded tag
  packages/haproxy/changelog.yml
  packages/haproxy/data_stream/log/agent/stream/log.yml.hbs
  packages/haproxy/data_stream/log/agent/stream/syslog.yml.hbs
  packages/haproxy/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1818 [gcp] Fix contains check for forwarded tag
  packages/gcp/changelog.yml
  packages/gcp/data_stream/audit/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/firewall/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/vpcflow/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1817 [fortinet] Fix contains check for forwarded tag
  packages/fortinet/changelog.yml
  packages/fortinet/data_stream/clientendpoint/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/udp.yml.hbs
  packages/fortinet/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1816 [f5] Fix contains check for forwarded tag
  packages/f5/changelog.yml
  packages/f5/data_stream/bigipafm/agent/stream/stream.yml.hbs
  packages/f5/data_stream/bigipafm/agent/stream/tcp.yml.hbs
  packages/f5/data_stream/bigipafm/agent/stream/udp.yml.hbs
  packages/f5/data_stream/bigipapm/agent/stream/stream.yml.hbs
  packages/f5/data_stream/bigipapm/agent/stream/tcp.yml.hbs
  packages/f5/data_stream/bigipapm/agent/stream/udp.yml.hbs
  packages/f5/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1815 [cylance] Fix contains check for forwarded tag
  packages/cylance/changelog.yml
  packages/cylance/data_stream/protect/agent/stream/stream.yml.hbs
  packages/cylance/data_stream/protect/agent/stream/tcp.yml.hbs
  packages/cylance/data_stream/protect/agent/stream/udp.yml.hbs
  packages/cylance/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1805 [cisco_asa] Fix contains check for forwarded tag
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_asa/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_asa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1819 [google_workspace] Fix contains check for forwarded tag
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
  packages/google_workspace/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1793 [Microsoft_DHCP] New package replacing old RSA2ELK DHCP package
  packages/microsoft_dhcp/_dev/build/build.yml
  packages/microsoft_dhcp/_dev/build/docs/README.md
  packages/microsoft_dhcp/_dev/deploy/docker/docker-compose.yml
  packages/microsoft_dhcp/_dev/deploy/docker/sample_logs/test-dhcp.log
  packages/microsoft_dhcp/changelog.yml
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-log.log
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/microsoft_dhcp/data_stream/log/_dev/test/system/test-default-config.yml
  packages/microsoft_dhcp/data_stream/log/agent/stream/logfile.yml.hbs
  packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_dhcp/data_stream/log/fields/agent.yml
  packages/microsoft_dhcp/data_stream/log/fields/base-fields.yml
  packages/microsoft_dhcp/data_stream/log/fields/ecs.yml
  packages/microsoft_dhcp/data_stream/log/fields/fields.yml
  packages/microsoft_dhcp/data_stream/log/manifest.yml
  packages/microsoft_dhcp/data_stream/log/sample_event.json
  packages/microsoft_dhcp/docs/README.md
  packages/microsoft_dhcp/img/logo.svg
  packages/microsoft_dhcp/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate, Integration:Microsoft_dhcp

#1872 [windows] prevent pipeline script error
  packages/windows/changelog.yml
  packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
  packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/sysmon_operational.yml
  packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
  packages/windows/manifest.yml
Labels: bug, Team:Security-External Integrations

#1871 [aws] Prevent pipeline script error
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-cloudtrail-digest-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
  packages/aws/manifest.yml
Labels: bug, Team:Security-External Integrations

#1869 [system] prevent pipeline script error
  packages/system/changelog.yml
  packages/system/data_stream/security/_dev/test/pipeline/test-unknown.json
  packages/system/data_stream/security/_dev/test/pipeline/test-unknown.json-expected.json
  packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
  packages/system/manifest.yml
Labels: bug, Team:Security-External Integrations

#1890 Remove deprecated lines from kubernetes package readme
  packages/kubernetes/_dev/build/docs/README.md
  packages/kubernetes/changelog.yml
  packages/kubernetes/docs/README.md
  packages/kubernetes/manifest.yml
Labels: bug, Team:Integrations

#1921 [Panw XDR] Fixing duplicated events
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr-bioc.log-expected.json
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr.log-expected.json
  packages/panw_cortex_xdr/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
  packages/panw_cortex_xdr/manifest.yml
Labels: Team:Security-External Integrations

#1923 Make daily job fail if the invoked job fails
  .ci/schedule-daily.groovy
Labels: Team:Automation, Team:Ecosystem

#1939 [AbuseCH package] update image icon
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/img/abusech.svg
  packages/ti_abusech/img/abusech2.svg
  packages/ti_abusech/manifest.yml
Labels: Team:Security-External Integrations

#1948 [bluecoat] update title and description
  packages/bluecoat/changelog.yml
  packages/bluecoat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1952 [cisco_asa] update title and description
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1955 [cisco_ios] update title and description
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1958 [cisco_secure_endpoint] update title and description
  packages/cisco_secure_endpoint/changelog.yml
  packages/cisco_secure_endpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1961 [crowdstrike] update title and description
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1968 [imperva] update title and description
  packages/imperva/changelog.yml
  packages/imperva/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1977 [okta] update title and description
  packages/okta/changelog.yml
  packages/okta/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1983 [radware] update title and description
  packages/radware/changelog.yml
  packages/radware/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1988 [squid] update title and description
  packages/squid/changelog.yml
  packages/squid/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1989 [suricata] update title and description
  packages/suricata/changelog.yml
  packages/suricata/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1990 [tomcat] update title and description
  packages/tomcat/changelog.yml
  packages/tomcat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1991 [winlog] update title and description
  packages/winlog/changelog.yml
  packages/winlog/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1945 [Synthetics] update README to include instructions
  packages/synthetics/changelog.yml
  packages/synthetics/docs/README.md
  packages/synthetics/manifest.yml
Labels: enhancement, 7.16-candidate, 7.15-candidate

#2067 update splunk input desc for windows integrations
  packages/windows/_dev/build/docs/README.md
  packages/windows/changelog.yml
  packages/windows/docs/README.md
  packages/windows/manifest.yml
  packages/winlog/_dev/build/docs/README.md
  packages/winlog/changelog.yml
  packages/winlog/docs/README.md
  packages/winlog/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2027 [Synthetics] update mappings
  packages/synthetics/changelog.yml
  packages/synthetics/data_stream/browser/fields/synthetics.yml
  packages/synthetics/data_stream/browser_network/fields/synthetics.yml
  packages/synthetics/data_stream/browser_screenshot/fields/synthetics.yml
  packages/synthetics/manifest.yml
Labels: Team:Uptime, v8.0.0, v7.16.0
