Repository elastic/integrations, pull requests merged in 2021-01, with the labels that each got.

#492 nginx_ingress_controller: use event.created in the ingest pipeline
  packages/nginx_ingress_controller/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/nginx_ingress_controller/manifest.yml
Labels: Team:Integrations

#494 Ignore "@timestamp" in some pipeline tests
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-config.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-config.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-iptables-raw.log-config.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log-config.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth.log-config.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-secure-rhel7.log-config.json
Labels: bug

#495 Remove unnecessary files from Cisco package
  packages/cisco/diff
  packages/cisco/fields.missing
Labels: bug

#498 Fix conditional in load dataset
  packages/system/data_stream/load/agent/stream/stream.yml.hbs
  packages/system/manifest.yml
Labels: bug, v7.11.0

#502 update system package version to 0.10.6 for new process/host fields
  packages/system/manifest.yml
Labels: Team:Integrations

#474 Run "check" and "test" only for affected packages in PRs
  .ci/Jenkinsfile
Labels: Team:Services

#508 Update panw integration to ECS 1.7
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json
  packages/panw/data_stream/panos/agent/stream/log.yml.hbs
  packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/data_stream/panos/fields/agent.yml
  packages/panw/data_stream/panos/fields/beats.yml
  packages/panw/data_stream/panos/fields/ecs.yml
  packages/panw/data_stream/panos/manifest.yml
  packages/panw/docs/README.md
  packages/panw/manifest.yml
Labels: Team:Security-External Integrations

#509 Update checkpoint integration to ECS 1.7
  packages/checkpoint/data_stream/firewall/agent/stream/log.yml.hbs
  packages/checkpoint/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/checkpoint/data_stream/firewall/fields/agent.yml
  packages/checkpoint/data_stream/firewall/fields/beats.yml
  packages/checkpoint/data_stream/firewall/fields/ecs.yml
  packages/checkpoint/docs/README.md
  packages/checkpoint/manifest.yml
Labels: Team:Security-External Integrations

#510 Update fortinet/firewall integration to ECS 1.7
  packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log-expected.json
  packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/event.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/utm.yml
  packages/fortinet/data_stream/firewall/fields/agent.yml
  packages/fortinet/data_stream/firewall/fields/beats.yml
  packages/fortinet/data_stream/firewall/fields/ecs.yml
  packages/fortinet/data_stream/firewall/manifest.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
Labels: Team:Security-External Integrations

#525 Ensure all composed services are up for nats cluster testing
  packages/nats/_dev/deploy/docker/docker-compose.yml
  packages/nats/data_stream/route/_dev/test/system/test-default-config.yml
  packages/nats/data_stream/routes/_dev/test/system/test-default-config.yml
Labels: Team:Integrations

#529 Update Azure dashboard text
  packages/azure/kibana/dashboard/azure-0f559cc0-f0d5-11e9-90ec-112a988266d5.json
  packages/azure/kibana/dashboard/azure-41e84340-ec20-11e9-90ec-112a988266d5.json
  packages/azure/kibana/dashboard/azure-87095750-f05a-11e9-90ec-112a988266d5.json
  packages/azure/manifest.yml
Labels: Integration:Azure

#535 CI: Collect Elastic stack logs
  .ci/Jenkinsfile
  go.mod
  go.sum
Labels: Team:Integrations

#532 Add stan package
  packages/stan/_dev/build/docs/README.md
  packages/stan/_dev/deploy/docker/Dockerfile
  packages/stan/_dev/deploy/docker/docker-compose.yml
  packages/stan/_dev/deploy/docker/healthcheck.sh
  packages/stan/_dev/deploy/docker/run.sh
  packages/stan/_dev/deploy/variants.yml
  packages/stan/data_stream/channels/_dev/test/system/test-default-config.yml
  packages/stan/data_stream/channels/agent/stream/stream.yml.hbs
  packages/stan/data_stream/channels/fields/base-fields.yml
  packages/stan/data_stream/channels/fields/ecs.yml
  packages/stan/data_stream/channels/fields/fields.yml
  packages/stan/data_stream/channels/fields/package-fields.yml
  packages/stan/data_stream/channels/manifest.yml
  packages/stan/data_stream/channels/sample_event.json
  packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log
  packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log-config.json
  packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
  packages/stan/data_stream/log/_dev/test/system/test-default-config.yml
  packages/stan/data_stream/log/agent/stream/log.yml.hbs
  packages/stan/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/stan/data_stream/log/fields/base-fields.yml
  packages/stan/data_stream/log/fields/ecs.yml
  packages/stan/data_stream/log/fields/fields.yml
  packages/stan/data_stream/log/manifest.yml
  packages/stan/data_stream/log/sample_event.json
  packages/stan/data_stream/stats/_dev/test/system/test-default-config.yml
  packages/stan/data_stream/stats/agent/stream/stream.yml.hbs
  packages/stan/data_stream/stats/fields/base-fields.yml
  packages/stan/data_stream/stats/fields/ecs.yml
  packages/stan/data_stream/stats/fields/fields.yml
  packages/stan/data_stream/stats/fields/package-fields.yml
  packages/stan/data_stream/stats/manifest.yml
  packages/stan/data_stream/stats/sample_event.json
  packages/stan/data_stream/subscriptions/_dev/test/system/test-default-config.yml
  packages/stan/data_stream/subscriptions/agent/stream/stream.yml.hbs
  packages/stan/data_stream/subscriptions/fields/base-fields.yml
  packages/stan/data_stream/subscriptions/fields/ecs.yml
  packages/stan/data_stream/subscriptions/fields/fields.yml
  packages/stan/data_stream/subscriptions/fields/package-fields.yml
  packages/stan/data_stream/subscriptions/manifest.yml
  packages/stan/data_stream/subscriptions/sample_event.json
  packages/stan/docs/README.md
  packages/stan/img/logs-stan-overview.png
  packages/stan/img/metrics-stan-overview.png
  packages/stan/img/stan.svg
  packages/stan/kibana/dashboard/stan-Logs-stan-overview.json
  packages/stan/kibana/dashboard/stan-b6a60340-4371-11ea-b0c6-cb14c0977bd1.json
  packages/stan/kibana/visualization/stan-04083600-41af-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-0b2061d0-41ad-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-0e412fe0-4371-11ea-b0c6-cb14c0977bd1.json
  packages/stan/kibana/visualization/stan-3f6cca40-41ae-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-46a07ac0-436d-11ea-b0c6-cb14c0977bd1.json
  packages/stan/kibana/visualization/stan-4a6d9ec0-41a8-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-6987a800-41a8-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-7716c780-41ad-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-7ed62870-41ae-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-c3d1ab80-41a8-11e9-a4da-b1df688edbcd.json
  packages/stan/kibana/visualization/stan-c669ae20-41ed-11e9-ac5c-71ffa38a62e3.json
  packages/stan/manifest.yml
Labels: Integration:Stan, enhancement

#538 Fix issue template, remove empty folders to avoid confusion
  .github/ISSUE_TEMPLATE/integration-checklist.md
  doc/development/README.md
  doc/development/guidelines/README.md
Labels: documentation

#539 Add missing datastream filters
  packages/stan/kibana/visualization/stan-0e412fe0-4371-11ea-b0c6-cb14c0977bd1.json
  packages/stan/kibana/visualization/stan-46a07ac0-436d-11ea-b0c6-cb14c0977bd1.json
  packages/stan/manifest.yml
Labels: [zube]: In Review

#544 Fleet Server package
  packages/fleet_server/data_stream/fleet_server/agent/stream/stream.yml.hbs
  packages/fleet_server/data_stream/fleet_server/fields/base-fields.yml
  packages/fleet_server/data_stream/fleet_server/fields/package-fields.yml
  packages/fleet_server/data_stream/fleet_server/manifest.yml
  packages/fleet_server/docs/README.md
  packages/fleet_server/elasticsearch/ilm_policy/.fleet-actions-results.json
  packages/fleet_server/elasticsearch/index_template/.fleet-actions-results.json
  packages/fleet_server/elasticsearch/index_template/.fleet-actions.json
  packages/fleet_server/elasticsearch/index_template/.fleet-agents.json
  packages/fleet_server/elasticsearch/index_template/.fleet-enrollment-api-keys.json
  packages/fleet_server/elasticsearch/index_template/.fleet-policies-leader.json
  packages/fleet_server/elasticsearch/index_template/.fleet-policies.json
  packages/fleet_server/elasticsearch/index_template/.fleet-servers.json
  packages/fleet_server/manifest.yml
Labels: Team:Agent

#534 Migrate IIS package
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-72.log
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-72.log-config.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-72.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-75.log
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-75.log-config.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-75.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log-config.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-ipv6zone.log
  packages/iis/data_stream/access/_dev/test/pipeline/test-ipv6zone.log-config.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-ipv6zone.log-expected.json
  packages/iis/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/iis/data_stream/access/fields/ecs.yml
  packages/iis/data_stream/application_pool/agent/stream/stream.yml.hbs
  packages/iis/data_stream/application_pool/fields/fields.yml
  packages/iis/data_stream/application_pool/manifest.yml
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error-72.log
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error-72.log-config.json
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error-72.log-expected.json
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error.log
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error.log-config.json
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error.log-expected.json
  packages/iis/data_stream/error/_dev/test/pipeline/test-ipv6-zone-id.log
  packages/iis/data_stream/error/_dev/test/pipeline/test-ipv6-zone-id.log-config.json
  packages/iis/data_stream/error/_dev/test/pipeline/test-ipv6-zone-id.log-expected.json
  packages/iis/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/iis/data_stream/error/fields/ecs.yml
  packages/iis/data_stream/webserver/fields/fields.yml
  packages/iis/data_stream/website/fields/fields.yml
  packages/iis/docs/README.md
  packages/iis/kibana/dashboard/iis-2c171500-858b-11ea-91bc-ab084c7ec0e7.json
  packages/iis/kibana/dashboard/iis-4278ad30-fe16-11e7-a3b0-d13028918f9f.json
  packages/iis/kibana/dashboard/iis-4b975820-85a1-11ea-91bc-ab084c7ec0e7.json
  packages/iis/kibana/dashboard/iis-b4108810-861c-11ea-91bc-ab084c7ec0e7.json
  packages/iis/kibana/dashboard/iis-ebc23240-8572-11ea-91bc-ab084c7ec0e7.json
  packages/iis/manifest.yml
Labels: Team:Integrations

#550 Add event fields into ecs.yml for apache
  packages/apache/data_stream/access/fields/ecs.yml
  packages/apache/data_stream/error/fields/ecs.yml
  packages/apache/docs/README.md
  packages/apache/manifest.yml
Labels: Integration:Apache, Team:Integrations

#555 [checkpoint] Remove client/server field sets
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-expected.json
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
  packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/checkpoint/data_stream/firewall/fields/ecs.yml
  packages/checkpoint/docs/README.md
  packages/checkpoint/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#560 Set IIS package to beta
  packages/iis/data_stream/access/manifest.yml
  packages/iis/data_stream/application_pool/manifest.yml
  packages/iis/data_stream/error/manifest.yml
  packages/iis/data_stream/webserver/manifest.yml
  packages/iis/data_stream/website/manifest.yml
  packages/iis/manifest.yml
Labels: Team:Integrations, [zube]: In Review

#562 Improve STAN description and category
  packages/stan/manifest.yml
Labels: Team:Integrations

#542 Update suricata integration with wildcard fields
  packages/suricata/data_stream/eve/fields/agent.yml
  packages/suricata/data_stream/eve/fields/fields-epr.yml
  packages/suricata/docs/README.md
  packages/suricata/manifest.yml
Labels: Team:Security-External Integrations

#554 Fix linux documentation and config names
  packages/linux/_dev/build/docs/README.md
  packages/linux/data_stream/entropy/manifest.yml
  packages/linux/data_stream/network_summary/manifest.yml
  packages/linux/data_stream/raid/manifest.yml
  packages/linux/data_stream/service/manifest.yml
  packages/linux/data_stream/socket/manifest.yml
  packages/linux/data_stream/users/manifest.yml
  packages/linux/docs/README.md
  packages/linux/manifest.yml
Labels: bug, documentation

#553 Add UDP and TCP Syslog tests for CheckPoint Firewall
  go.mod
  go.sum
  packages/checkpoint/_dev/deploy/docker/docker-compose.yml
  packages/checkpoint/_dev/deploy/docker/test-checkpoint.log
  packages/checkpoint/data_stream/firewall/_dev/test/system/test-tcp-config.yml
  packages/checkpoint/data_stream/firewall/_dev/test/system/test-udp-config.yml
  packages/checkpoint/data_stream/firewall/agent/stream/tcp.yml.hbs
  packages/checkpoint/data_stream/firewall/fields/beats.yml
  packages/checkpoint/data_stream/firewall/manifest.yml
  packages/checkpoint/docs/README.md
  packages/checkpoint/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#563 Update to the latest elastic-package to pick up the package spec with optional datastream
  go.mod
  go.sum
Labels: Team:Agent, Team:Integrations

#565 Remove Fleet Server fake data_stream folder, since now it is optional
  packages/fleet_server/data_stream/fleet_server/agent/stream/stream.yml.hbs
  packages/fleet_server/data_stream/fleet_server/fields/base-fields.yml
  packages/fleet_server/data_stream/fleet_server/fields/package-fields.yml
  packages/fleet_server/data_stream/fleet_server/manifest.yml
  packages/fleet_server/manifest.yml
Labels: enhancement

#567 Fix nats package docs
  packages/nats/_dev/build/docs/README.md
  packages/nats/docs/README.md
Labels: Team:Integrations

#273 OSQuery Elastic Managed package
  packages/osquery_elastic_managed/data_stream/osquery/agent/stream/stream.yml.hbs
  packages/osquery_elastic_managed/data_stream/osquery/fields/base-fields.yml
  packages/osquery_elastic_managed/data_stream/osquery/fields/package-fields.yml
  packages/osquery_elastic_managed/data_stream/osquery/manifest.yml
  packages/osquery_elastic_managed/docs/README.md
  packages/osquery_elastic_managed/img/logo_osquery.svg
  packages/osquery_elastic_managed/manifest.yml
Labels: Team:Integrations, Team:SIEM, enhancement

#573 Rename action input_id to input_type
  packages/fleet_server/elasticsearch/index_template/.fleet-actions.json
  packages/fleet_server/manifest.yml
Labels: breaking change

#572 Add missing field definitions into AWS data streams
  packages/aws/data_stream/billing/fields/ecs.yml
  packages/aws/data_stream/cloudwatch_metrics/fields/ecs.yml
  packages/aws/data_stream/dynamodb/fields/ecs.yml
  packages/aws/data_stream/ebs/fields/ecs.yml
  packages/aws/data_stream/ec2_metrics/fields/ecs.yml
  packages/aws/data_stream/ec2_metrics/fields/fields.yml
  packages/aws/data_stream/elb_metrics/fields/ecs.yml
  packages/aws/data_stream/lambda/fields/ecs.yml
  packages/aws/data_stream/natgateway/fields/ecs.yml
  packages/aws/data_stream/rds/fields/ecs.yml
  packages/aws/data_stream/s3_daily_storage/fields/ecs.yml
  packages/aws/data_stream/s3_request/fields/ecs.yml
  packages/aws/data_stream/sns/fields/ecs.yml
  packages/aws/data_stream/sqs/fields/ecs.yml
  packages/aws/data_stream/transitgateway/fields/ecs.yml
  packages/aws/data_stream/usage/fields/ecs.yml
  packages/aws/data_stream/vpn/fields/ecs.yml
  packages/aws/docs/README.md
Labels: Team:Integrations

#564 Move aws package to beta
  packages/aws/_dev/build/docs/README.md
  packages/aws/data_stream/billing/agent/stream/stream.yml.hbs
  packages/aws/data_stream/billing/fields/fields.yml
  packages/aws/data_stream/billing/manifest.yml
  packages/aws/data_stream/cloudtrail/agent/stream/s3.yml.hbs
  packages/aws/data_stream/cloudtrail/manifest.yml
  packages/aws/data_stream/cloudwatch_logs/agent/stream/s3.yml.hbs
  packages/aws/data_stream/cloudwatch_logs/manifest.yml
  packages/aws/data_stream/cloudwatch_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/cloudwatch_metrics/manifest.yml
  packages/aws/data_stream/dynamodb/agent/stream/stream.yml.hbs
  packages/aws/data_stream/dynamodb/manifest.yml
  packages/aws/data_stream/ebs/agent/stream/stream.yml.hbs
  packages/aws/data_stream/ebs/manifest.yml
  packages/aws/data_stream/ec2_logs/agent/stream/s3.yml.hbs
  packages/aws/data_stream/ec2_logs/manifest.yml
  packages/aws/data_stream/ec2_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/ec2_metrics/manifest.yml
  packages/aws/data_stream/elb_logs/agent/stream/s3.yml.hbs
  packages/aws/data_stream/elb_logs/manifest.yml
  packages/aws/data_stream/elb_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/elb_metrics/manifest.yml
  packages/aws/data_stream/lambda/agent/stream/stream.yml.hbs
  packages/aws/data_stream/lambda/manifest.yml
  packages/aws/data_stream/natgateway/agent/stream/stream.yml.hbs
  packages/aws/data_stream/natgateway/manifest.yml
  packages/aws/data_stream/rds/agent/stream/stream.yml.hbs
  packages/aws/data_stream/rds/manifest.yml
  packages/aws/data_stream/s3_daily_storage/agent/stream/stream.yml.hbs
  packages/aws/data_stream/s3_daily_storage/manifest.yml
  packages/aws/data_stream/s3_request/agent/stream/stream.yml.hbs
  packages/aws/data_stream/s3_request/manifest.yml
  packages/aws/data_stream/s3access/agent/stream/s3.yml.hbs
  packages/aws/data_stream/s3access/manifest.yml
  packages/aws/data_stream/sns/agent/stream/stream.yml.hbs
  packages/aws/data_stream/sns/manifest.yml
  packages/aws/data_stream/sqs/agent/stream/stream.yml.hbs
  packages/aws/data_stream/sqs/manifest.yml
  packages/aws/data_stream/transitgateway/agent/stream/stream.yml.hbs
  packages/aws/data_stream/transitgateway/manifest.yml
  packages/aws/data_stream/usage/agent/stream/stream.yml.hbs
  packages/aws/data_stream/usage/manifest.yml
  packages/aws/data_stream/vpcflow/agent/stream/s3.yml.hbs
  packages/aws/data_stream/vpcflow/manifest.yml
  packages/aws/data_stream/vpn/agent/stream/stream.yml.hbs
  packages/aws/data_stream/vpn/manifest.yml
  packages/aws/docs/README.md
  packages/aws/manifest.yml
Labels: Team:Integrations

#571 Update project docs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/definitions.md
  docs/developer_workflow_design_build_test_integration.md
  docs/developer_workflow_promote_release_integration.md
  docs/fine_tune_integration.md
  docs/import_from_beats.md
  docs/testing_and_validation.md
  docs/tips_for_building_integrations.md
Labels: Team:Integrations

#574 Add logfile system test to CheckPoint Firewall
  packages/checkpoint/_dev/deploy/docker/docker-compose.yml
  packages/checkpoint/_dev/deploy/docker/sample_logs/test-checkpoint.log
  packages/checkpoint/data_stream/firewall/_dev/test/system/test-logfile-config.yml
Labels: Team:Security-External Integrations

#575 Add system tests for CEF
  packages/cef/_dev/deploy/docker/Dockerfile
  packages/cef/_dev/deploy/docker/cef.log
  packages/cef/_dev/deploy/docker/docker-compose.yml
  packages/cef/_dev/deploy/docker/sample_logs/cef.log
  packages/cef/_dev/deploy/docker/sample_logs/checkpoint.log
  packages/cef/_dev/deploy/docker/sample_logs/forcepoint-ngfw-smc.log
  packages/cef/data_stream/log/_dev/test/pipeline/test-cef-event.json-expected.json
  packages/cef/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cef/data_stream/log/_dev/test/system/test-syslog-config.yml
  packages/cef/data_stream/log/elasticsearch/ingest_pipeline/cp-pipeline.yml
  packages/cef/data_stream/log/fields/agent.yml
  packages/cef/data_stream/log/fields/ecs.yml
  packages/cef/data_stream/log/fields/fields.yml
  packages/cef/docs/README.md
  packages/cef/manifest.yml
Labels: Team:Security-External Integrations

#576 Remove unneeded Dockerfile form auditd package
  packages/auditd/_dev/deploy/docker/Dockerfile
  packages/auditd/_dev/deploy/docker/docker-compose.yml
  packages/auditd/_dev/deploy/docker/sample_logs/audit.log
  packages/auditd/data_stream/log/_dev/test/system/test-default-config.yml
Labels: Team:Security-External Integrations

#578 Add tests to Cisco package
  packages/cisco/_dev/deploy/docker/Dockerfile
  packages/cisco/_dev/deploy/docker/docker-compose.yml
  packages/cisco/_dev/deploy/docker/sample_logs/cisco-ios.log
  packages/cisco/_dev/deploy/docker/sample_logs/cisco-meraki.log
  packages/cisco/_dev/deploy/docker/sample_logs/test-asa.log
  packages/cisco/_dev/deploy/docker/sample_logs/test-ftd.log
  packages/cisco/_dev/deploy/docker/sample_logs/test-nexus.log
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/system/test-logfile-config.yml
  packages/cisco/data_stream/asa/_dev/test/system/test-udp-config.yml
  packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/asa/fields/agent.yml
  packages/cisco/data_stream/asa/fields/ecs.yml
  packages/cisco/data_stream/ftd/_dev/test/system/test-logfile-config.yml
  packages/cisco/data_stream/ftd/_dev/test/system/test-udp-config.yml
  packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ftd/fields/agent.yml
  packages/cisco/data_stream/ftd/fields/ecs.yml
  packages/cisco/data_stream/ftd/fields/fields.yml
  packages/cisco/data_stream/ios/_dev/test/system/test-logfile-config.yml
  packages/cisco/data_stream/ios/_dev/test/system/test-udp-config.yml
  packages/cisco/data_stream/ios/fields/agent.yml
  packages/cisco/data_stream/meraki/_dev/test/system/test-logfile-config.yml
  packages/cisco/data_stream/meraki/_dev/test/system/test-tcp-config.yml
  packages/cisco/data_stream/meraki/_dev/test/system/test-udp-config.yml
  packages/cisco/data_stream/nexus/_dev/test/system/test-logfile-config.yml
  packages/cisco/data_stream/nexus/_dev/test/system/test-tcp-config.yml
  packages/cisco/data_stream/nexus/_dev/test/system/test-udp-config.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations

#581 Updating package registry version
  go.mod
  go.sum
Labels: Team:Integrations
