Repository elastic/integrations, pull requests merged in 2021-02, with the labels that each got.

#582 Add pipeline tests to Cisco FTD
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-config.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
Labels: Team:Security-External Integrations

#583 Add system test to CrowdStrike Falcon
  packages/crowdstrike/_dev/deploy/docker/Dockerfile
  packages/crowdstrike/_dev/deploy/docker/docker-compose.yml
  packages/crowdstrike/_dev/deploy/docker/sample_logs/falcon-audit-events.log
  packages/crowdstrike/_dev/deploy/docker/sample_logs/falcon-events.log
  packages/crowdstrike/_dev/deploy/docker/sample_logs/falcon-sample.log
  packages/crowdstrike/data_stream/falcon/_dev/test/system/test-logfile-config.yml
  packages/crowdstrike/data_stream/falcon/test/pipeline/falcon-audit-events.log
  packages/crowdstrike/data_stream/falcon/test/pipeline/falcon-audit-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/test/pipeline/falcon-events.log
  packages/crowdstrike/data_stream/falcon/test/pipeline/falcon-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/test/pipeline/falcon-sample.log
  packages/crowdstrike/data_stream/falcon/test/pipeline/falcon-sample.log-expected.json
Labels: Team:Security-External Integrations

#585 Add system tests for Fortinet Firewall udp/tcp inputs
  packages/fortinet/_dev/deploy/docker/Dockerfile
  packages/fortinet/_dev/deploy/docker/docker-compose.yml
  packages/fortinet/_dev/deploy/docker/sample_logs/fortinet-clientendpoint.log
  packages/fortinet/_dev/deploy/docker/sample_logs/fortinet-firewall.log
  packages/fortinet/_dev/deploy/docker/sample_logs/fortinet-fortimail.log
  packages/fortinet/_dev/deploy/docker/sample_logs/fortinet-fortimanager.log
  packages/fortinet/data_stream/clientendpoint/_dev/test/system/test-logfile-config.yml
  packages/fortinet/data_stream/clientendpoint/_dev/test/system/test-tcp-config.yml
  packages/fortinet/data_stream/clientendpoint/_dev/test/system/test-udp-config.yml
  packages/fortinet/data_stream/firewall/_dev/test/system/test-logfile-config.yml
  packages/fortinet/data_stream/firewall/_dev/test/system/test-tcp-config.yml
  packages/fortinet/data_stream/firewall/_dev/test/system/test-udp-config.yml
  packages/fortinet/data_stream/firewall/fields/agent.yml
  packages/fortinet/data_stream/firewall/fields/ecs.yml
  packages/fortinet/data_stream/fortimail/_dev/test/system/test-logfile-config.yml
  packages/fortinet/data_stream/fortimail/_dev/test/system/test-tcp-config.yml
  packages/fortinet/data_stream/fortimail/_dev/test/system/test-udp-config.yml
  packages/fortinet/data_stream/fortimanager/_dev/test/system/test-logfile-config.yml
  packages/fortinet/data_stream/fortimanager/_dev/test/system/test-tcp-config.yml
  packages/fortinet/data_stream/fortimanager/_dev/test/system/test-udp-config.yml
  packages/fortinet/docs/README.md
Labels: Team:Security-External Integrations

#586 Remove unneeded Dockerfile for Google Workspace
  packages/google_workspace/_dev/deploy/docker/Dockerfile
  packages/google_workspace/_dev/deploy/docker/docker-compose.yml
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-application-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-calendar-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-chat-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-chromeos-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-contacts-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-delegatedadmin-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-docs-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-domain-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-gmail-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-groups-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-licenses-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-mobile-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-org-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-security-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-sites-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/admin-user-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/drive-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/groups-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/login-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/saml-test.json.log
  packages/google_workspace/_dev/deploy/docker/sample_logs/user_accounts-test.json.log
Labels: Team:Security-External Integrations

#587 Add system test for iptables syslog input
  packages/cisco/_dev/deploy/docker/cisco-ios.log
  packages/cisco/_dev/deploy/docker/cisco-meraki.log
  packages/iptables/_dev/deploy/docker/Dockerfile
  packages/iptables/_dev/deploy/docker/docker-compose.yml
  packages/iptables/_dev/deploy/docker/sample_logs/iptables.log
  packages/iptables/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/iptables/data_stream/log/_dev/test/system/test-syslog-config.yml
  packages/iptables/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/iptables/data_stream/log/fields/agent.yml
  packages/iptables/docs/README.md
  packages/iptables/manifest.yml
Labels: Team:Security-External Integrations

#588 Add system tests to Juniper
  packages/juniper/_dev/deploy/docker/Dockerfile
  packages/juniper/_dev/deploy/docker/docker-compose.yml
  packages/juniper/_dev/deploy/docker/sample_logs/juniper-junos.log
  packages/juniper/_dev/deploy/docker/sample_logs/juniper-netscreen.log
  packages/juniper/_dev/deploy/docker/sample_logs/juniper-srx.log
  packages/juniper/data_stream/junos/_dev/test/system/test-logfile-config.yml
  packages/juniper/data_stream/junos/_dev/test/system/test-tcp-config.yml
  packages/juniper/data_stream/junos/_dev/test/system/test-udp-config.yml
  packages/juniper/data_stream/junos/manifest.yml
  packages/juniper/data_stream/netscreen/_dev/test/system/test-logfile-config.yml
  packages/juniper/data_stream/netscreen/_dev/test/system/test-tcp-config.yml
  packages/juniper/data_stream/netscreen/_dev/test/system/test-udp-config.yml
  packages/juniper/data_stream/netscreen/agent/stream/logfile.yml.hbs
  packages/juniper/data_stream/netscreen/manifest.yml
  packages/juniper/data_stream/srx/_dev/test/system/test-logfile-config.yml
  packages/juniper/data_stream/srx/_dev/test/system/test-tcp-config.yml
  packages/juniper/data_stream/srx/_dev/test/system/test-udp-config.yml
  packages/juniper/data_stream/srx/agent/stream/logfile.yml.hbs
  packages/juniper/data_stream/srx/fields/agent.yml
  packages/juniper/data_stream/srx/manifest.yml
  packages/juniper/docs/README.md
  packages/juniper/manifest.yml
Labels: Team:Security-External Integrations

#589 Add system test for Microsoft DHCP udp/tcp inputs
  packages/microsoft/_dev/deploy/docker/Dockerfile
  packages/microsoft/_dev/deploy/docker/docker-compose.yml
  packages/microsoft/_dev/deploy/docker/sample_logs/microsoft-dhcp.log
  packages/microsoft/data_stream/dhcp/_dev/test/system/test-logfile-config.yml
  packages/microsoft/data_stream/dhcp/_dev/test/system/test-tcp-config.yml
  packages/microsoft/data_stream/dhcp/_dev/test/system/test-udp-config.yml
Labels: Team:Security-External Integrations

#591 Remove unneeded Dockerfile from o365
  packages/o365/_dev/deploy/docker/Dockerfile
  packages/o365/_dev/deploy/docker/docker-compose.yml
  packages/o365/_dev/deploy/docker/sample_logs/01-exchange-admin.log
  packages/o365/_dev/deploy/docker/sample_logs/02-exchange-item.log
  packages/o365/_dev/deploy/docker/sample_logs/04-sharepoint.log
  packages/o365/_dev/deploy/docker/sample_logs/06-sharepointfileop.log
  packages/o365/_dev/deploy/docker/sample_logs/08-azuread.log
  packages/o365/_dev/deploy/docker/sample_logs/11-dlp-sharepoint.log
  packages/o365/_dev/deploy/docker/sample_logs/13-dlp-exchange.log
  packages/o365/_dev/deploy/docker/sample_logs/14-sp-sharing-op.log
  packages/o365/_dev/deploy/docker/sample_logs/15-azuread-sts-logon.log
  packages/o365/_dev/deploy/docker/sample_logs/22-yammer.log
  packages/o365/_dev/deploy/docker/sample_logs/25-ms-teams.log
  packages/o365/_dev/deploy/docker/sample_logs/40-sec-comp-alerts.log
  packages/o365/_dev/deploy/docker/sample_logs/52-data-insights-api.log
  packages/o365/_dev/deploy/docker/sample_logs/ip-formats.log
Labels: Team:Security-External Integrations

#592 Remove unneeded Dockerfile from Okta
  packages/okta/_dev/deploy/docker/Dockerfile
  packages/okta/_dev/deploy/docker/docker-compose.yml
  packages/okta/_dev/deploy/docker/sample_logs/okta-system.json.log
Labels: Team:Security-External Integrations

#594 Add system test for panw pan-os (syslog input)
  packages/panw/_dev/deploy/docker/Dockerfile
  packages/panw/_dev/deploy/docker/docker-compose.yml
  packages/panw/_dev/deploy/docker/sample_logs/panw-panos-inc-other.log
  packages/panw/_dev/deploy/docker/sample_logs/panw-panos-inc-threat.log
  packages/panw/_dev/deploy/docker/sample_logs/panw-panos-inc-traffic.log
  packages/panw/_dev/deploy/docker/sample_logs/panw-panos-threat.log
  packages/panw/_dev/deploy/docker/sample_logs/panw-panos-traffic.log
  packages/panw/data_stream/panos/_dev/test/system/test-logfile-config.yml
  packages/panw/data_stream/panos/_dev/test/system/test-syslog-config.yml
  packages/panw/data_stream/panos/agent/stream/logfile.yml.hbs
  packages/panw/data_stream/panos/manifest.yml
Labels: Team:Security-External Integrations

#595 Remove unneeded Dockerfile from Santa
  packages/santa/_dev/deploy/docker/Dockerfile
  packages/santa/_dev/deploy/docker/docker-compose.yml
  packages/santa/_dev/deploy/docker/sample_logs/santa.log
Labels: Team:Security-External Integrations

#596 Remove unneeded Dockerfile from Suricata
  packages/suricata/_dev/deploy/docker/Dockerfile
  packages/suricata/_dev/deploy/docker/docker-compose.yml
  packages/suricata/_dev/deploy/docker/sample_logs/eve-alerts.ndjson
  packages/suricata/_dev/deploy/docker/sample_logs/eve-dns-4.1.4.ndjson
  packages/suricata/_dev/deploy/docker/sample_logs/eve-small.ndjson
Labels: Team:Security-External Integrations

#597 Remove unneeded Dockerfile from Zeek
  packages/zeek/_dev/deploy/docker/Dockerfile
  packages/zeek/_dev/deploy/docker/docker-compose.yml
  packages/zeek/_dev/deploy/docker/sample_logs/capture_loss.log
  packages/zeek/_dev/deploy/docker/sample_logs/conn.log
  packages/zeek/_dev/deploy/docker/sample_logs/dce_rpc.log
  packages/zeek/_dev/deploy/docker/sample_logs/dhcp.log
  packages/zeek/_dev/deploy/docker/sample_logs/dnp3.log
  packages/zeek/_dev/deploy/docker/sample_logs/dns.log
  packages/zeek/_dev/deploy/docker/sample_logs/dpd.log
  packages/zeek/_dev/deploy/docker/sample_logs/files.log
  packages/zeek/_dev/deploy/docker/sample_logs/http.log
  packages/zeek/_dev/deploy/docker/sample_logs/intel.log
  packages/zeek/_dev/deploy/docker/sample_logs/irc.log
  packages/zeek/_dev/deploy/docker/sample_logs/kerberos.log
  packages/zeek/_dev/deploy/docker/sample_logs/modbus.log
  packages/zeek/_dev/deploy/docker/sample_logs/mysql.log
  packages/zeek/_dev/deploy/docker/sample_logs/notice.log
  packages/zeek/_dev/deploy/docker/sample_logs/ntlm.log
  packages/zeek/_dev/deploy/docker/sample_logs/pe.log
  packages/zeek/_dev/deploy/docker/sample_logs/radius.log
  packages/zeek/_dev/deploy/docker/sample_logs/rdp.log
  packages/zeek/_dev/deploy/docker/sample_logs/rfb.log
  packages/zeek/_dev/deploy/docker/sample_logs/sip.log
  packages/zeek/_dev/deploy/docker/sample_logs/smb_cmd.log
  packages/zeek/_dev/deploy/docker/sample_logs/smb_files.log
  packages/zeek/_dev/deploy/docker/sample_logs/smb_mapping.log
  packages/zeek/_dev/deploy/docker/sample_logs/smtp.log
  packages/zeek/_dev/deploy/docker/sample_logs/snmp.log
  packages/zeek/_dev/deploy/docker/sample_logs/socks.log
  packages/zeek/_dev/deploy/docker/sample_logs/ssh.log
  packages/zeek/_dev/deploy/docker/sample_logs/ssl.log
  packages/zeek/_dev/deploy/docker/sample_logs/stats.log
  packages/zeek/_dev/deploy/docker/sample_logs/traceroute.log
  packages/zeek/_dev/deploy/docker/sample_logs/tunnel.log
  packages/zeek/_dev/deploy/docker/sample_logs/weird.log
  packages/zeek/_dev/deploy/docker/sample_logs/x509.log
Labels: Team:Security-External Integrations

#593 Remove unneeded Dockerfile from osquery (self-managed)
  packages/osquery/_dev/deploy/docker/Dockerfile
  packages/osquery/_dev/deploy/docker/docker-compose.yml
  packages/osquery/_dev/deploy/docker/sample_logs/osquery.log
Labels: Team:Security-External Integrations

#590 Add system test for Netflow Log (udp)
  packages/netflow/_dev/deploy/docker/docker-compose.yml
  packages/netflow/_dev/deploy/docker/sample_logs/ipfix_cisco.pcap
  packages/netflow/data_stream/log/_dev/test/system/test-netflow-config.yml
  packages/netflow/data_stream/log/fields/package-fields.yml
  packages/netflow/docs/README.md
Labels: Team:Security-External Integrations

#600 Fix Osquery naming, to make consistent with the official product naming
  packages/osquery_elastic_managed/data_stream/osquery/manifest.yml
  packages/osquery_elastic_managed/docs/README.md
  packages/osquery_elastic_managed/manifest.yml
Labels: enhancement

#598 Add system and pipeline tests for Zoom
  packages/zoom/_dev/build/docs/README.md
  packages/zoom/_dev/deploy/docker/docker-compose.yml
  packages/zoom/_dev/deploy/docker/sample_logs/account-ndjson.log
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-account.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-account.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-account.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-channel.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-channel.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-channel.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-message.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-message.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-message.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-meeting.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-meeting.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-meeting.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-phone.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-phone.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-phone.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-recording.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-recording.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-recording.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-user.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-user.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-user.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-webinar.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-webinar.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-webinar.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-zoomroom.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-zoomroom.json-config.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-zoomroom.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/system/test-webhook-http-config.yml
  packages/zoom/data_stream/webhook/_dev/test/system/test-webhook-https-config.yml
  packages/zoom/data_stream/webhook/agent/stream/http_endpoint.yml.hbs
  packages/zoom/data_stream/webhook/agent/stream/log.yml.hbs
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/chat_channel.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/chat_message.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/phone.yml
  packages/zoom/data_stream/webhook/fields/agent.yml
  packages/zoom/data_stream/webhook/manifest.yml
  packages/zoom/docs/README.md
  packages/zoom/manifest.yml
Labels: Team:Security-External Integrations

#633 Clean up linux config value names
  packages/linux/data_stream/conntrack/manifest.yml
  packages/linux/data_stream/entropy/manifest.yml
  packages/linux/data_stream/ksm/manifest.yml
  packages/linux/data_stream/network_summary/manifest.yml
  packages/linux/data_stream/pageinfo/manifest.yml
  packages/linux/data_stream/raid/manifest.yml
  packages/linux/data_stream/service/manifest.yml
  packages/linux/data_stream/socket/manifest.yml
  packages/linux/data_stream/users/manifest.yml
  packages/linux/manifest.yml
Labels: bug, documentation

#602 Remove leftover Dockerfile for k8s package
  packages/kubernetes/_dev/deploy/docker/Dockerfile
Labels: Team:Integrations

#667 Update .fleet-agents mapping, add "local_metadata" mapping
  packages/fleet_server/elasticsearch/index_template/.fleet-agents.json
  packages/fleet_server/manifest.yml
Labels: Team:Agent, enhancement

#672 Update .fleet-actions-results mapping
  packages/fleet_server/elasticsearch/index_template/.fleet-actions-results.json
  packages/fleet_server/manifest.yml
Labels: Team:Agent, Team:Fleet, enhancement

#673 Add system.hostfs setting
  packages/linux/_dev/build/docs/README.md
  packages/linux/data_stream/entropy/agent/stream/stream.yml.hbs
  packages/linux/data_stream/raid/agent/stream/stream.yml.hbs
  packages/linux/data_stream/socket/agent/stream/stream.yml.hbs
  packages/linux/docs/README.md
  packages/linux/manifest.yml
  packages/system/_dev/build/docs/README.md
  packages/system/data_stream/process/agent/stream/stream.yml.hbs
  packages/system/data_stream/process_summary/agent/stream/stream.yml.hbs
  packages/system/data_stream/socket_summary/agent/stream/stream.yml.hbs
  packages/system/docs/README.md
  packages/system/manifest.yml
Labels: Team:Integrations

#680 Enable only default datastreams of k8s package
  packages/kubernetes/_dev/build/docs/README.md
  packages/kubernetes/data_stream/apiserver/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/controllermanager/manifest.yml
  packages/kubernetes/data_stream/scheduler/manifest.yml
  packages/kubernetes/data_stream/state_container/manifest.yml
  packages/kubernetes/data_stream/state_cronjob/manifest.yml
  packages/kubernetes/data_stream/state_daemonset/manifest.yml
  packages/kubernetes/data_stream/state_deployment/manifest.yml
  packages/kubernetes/data_stream/state_node/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
  packages/kubernetes/data_stream/state_pod/manifest.yml
  packages/kubernetes/data_stream/state_replicaset/manifest.yml
  packages/kubernetes/data_stream/state_resourcequota/manifest.yml
  packages/kubernetes/data_stream/state_service/manifest.yml
  packages/kubernetes/data_stream/state_statefulset/manifest.yml
  packages/kubernetes/data_stream/state_storageclass/manifest.yml
  packages/kubernetes/docs/README.md
  packages/kubernetes/manifest.yml
Labels: Team:Integrations, integration:Kubernetes

#676 Add system test for Zeek FTP, OCSP
  packages/zeek/_dev/deploy/docker/sample_logs/ftp.log
  packages/zeek/_dev/deploy/docker/sample_logs/ocsp.log
  packages/zeek/data_stream/ftp/_dev/test/system/test-default-config.yml
  packages/zeek/data_stream/ftp/fields/ecs.yml
  packages/zeek/data_stream/ocsp/_dev/test/system/test-default-config.yml
  packages/zeek/data_stream/ocsp/fields/fields.yml
  packages/zeek/docs/README.md
  packages/zeek/manifest.yml
Labels: Team:Security-External Integrations

#677 Remove unreferenced log.yml.hbs from AWS vpcflow
  packages/aws/data_stream/vpcflow/agent/stream/log.yml.hbs
Labels: Team:Security-External Integrations

#684 Add guards to OS-specific data streams
  packages/linux/data_stream/conntrack/agent/stream/stream.yml.hbs
  packages/linux/data_stream/iostat/agent/stream/stream.yml.hbs
  packages/linux/data_stream/ksm/agent/stream/stream.yml.hbs
  packages/linux/data_stream/memory/agent/stream/stream.yml.hbs
  packages/linux/data_stream/pageinfo/agent/stream/stream.yml.hbs
  packages/linux/manifest.yml
  packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/perfmon/agent/stream/stream.yml.hbs
  packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/service/agent/stream/stream.yml.hbs
  packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
  packages/windows/manifest.yml
Labels: Team:Integrations, bug

#686 [cisco] Sync ftd and asa data streams with beats
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/asa/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/asa/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco/data_stream/ftd/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/ftd/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#687 [cef] Sync cef data streams with beats
  packages/cef/data_stream/log/_dev/test/pipeline/test-cef-event.json-expected.json
  packages/cef/data_stream/log/agent/stream/log.yml.hbs
  packages/cef/data_stream/log/agent/stream/syslog.yml.hbs
  packages/cef/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cef/data_stream/log/fields/ecs.yml
  packages/cef/docs/README.md
  packages/cef/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#688 [crowdstrike] Sync crowdstrike data streams with beats
  packages/crowdstrike/data_stream/falcon/agent/stream/log.yml.hbs
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/auth_activity_audit.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/detection_summary.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/firewall_match.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/incident_summary.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/remote_response_session_end.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/remote_response_session_start.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/user_activity_audit.yml
  packages/crowdstrike/data_stream/falcon/fields/ecs.yml
  packages/crowdstrike/docs/README.md
  packages/crowdstrike/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#690 [google_workspace] Sync google_workspace data streams with beats
  packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/admin/agent/stream/log.yml.hbs
  packages/google_workspace/data_stream/admin/fields/ecs.yml
  packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/drive/agent/stream/log.yml.hbs
  packages/google_workspace/data_stream/drive/fields/ecs.yml
  packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/groups/agent/stream/log.yml.hbs
  packages/google_workspace/data_stream/groups/fields/ecs.yml
  packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/login/agent/stream/log.yml.hbs
  packages/google_workspace/data_stream/login/fields/ecs.yml
  packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/saml/agent/stream/log.yml.hbs
  packages/google_workspace/data_stream/saml/fields/ecs.yml
  packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/user_accounts/agent/stream/log.yml.hbs
  packages/google_workspace/data_stream/user_accounts/fields/ecs.yml
  packages/google_workspace/docs/README.md
  packages/google_workspace/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#694 [panw] Sync panw package with beats
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
  packages/panw/data_stream/panos/agent/stream/logfile.yml.hbs
  packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#692 [juniper] Sync juniper src data stream with beats
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper/data_stream/srx/agent/stream/logfile.yml.hbs
  packages/juniper/data_stream/srx/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/srx/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#695 [system] Sync system auth data stream with beats
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth-ubuntu1204.log-expected.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-auth.log-expected.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-secure-rhel7.log-expected.json
  packages/system/data_stream/auth/_dev/test/pipeline/test-timestamp.log-expected.json
  packages/system/data_stream/auth/agent/stream/log.yml.hbs
  packages/system/data_stream/auth/elasticsearch/ingest_pipeline/default.json
  packages/system/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/auth/fields/ecs.yml
  packages/system/docs/README.md
  packages/system/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#689 [fortinet] Sync fortinet firewall data stream with beats
  packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log-expected.json
  packages/fortinet/data_stream/firewall/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/event.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/traffic.yml
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/utm.yml
  packages/fortinet/data_stream/firewall/fields/ecs.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#696 [zeel] Sync zeek package with beats
  packages/zeek/_dev/deploy/docker/sample_logs/http.log
  packages/zeek/data_stream/capture_loss/agent/stream/log.yml.hbs
  packages/zeek/data_stream/connection/agent/stream/log.yml.hbs
  packages/zeek/data_stream/dce_rpc/agent/stream/log.yml.hbs
  packages/zeek/data_stream/dhcp/agent/stream/log.yml.hbs
  packages/zeek/data_stream/dnp3/agent/stream/log.yml.hbs
  packages/zeek/data_stream/dns/agent/stream/log.yml.hbs
  packages/zeek/data_stream/dpd/agent/stream/log.yml.hbs
  packages/zeek/data_stream/files/agent/stream/log.yml.hbs
  packages/zeek/data_stream/ftp/agent/stream/log.yml.hbs
  packages/zeek/data_stream/http/agent/stream/log.yml.hbs
  packages/zeek/data_stream/http/fields/ecs.yml
  packages/zeek/data_stream/intel/agent/stream/log.yml.hbs
  packages/zeek/data_stream/irc/agent/stream/log.yml.hbs
  packages/zeek/data_stream/kerberos/agent/stream/log.yml.hbs
  packages/zeek/data_stream/modbus/agent/stream/log.yml.hbs
  packages/zeek/data_stream/mysql/agent/stream/log.yml.hbs
  packages/zeek/data_stream/mysql/elasticsearch/ingest_pipeline/default.yml
  packages/zeek/data_stream/notice/agent/stream/log.yml.hbs
  packages/zeek/data_stream/ntlm/agent/stream/log.yml.hbs
  packages/zeek/data_stream/ocsp/agent/stream/log.yml.hbs
  packages/zeek/data_stream/pe/agent/stream/log.yml.hbs
  packages/zeek/data_stream/radius/agent/stream/log.yml.hbs
  packages/zeek/data_stream/rdp/agent/stream/log.yml.hbs
  packages/zeek/data_stream/rfb/agent/stream/log.yml.hbs
  packages/zeek/data_stream/sip/agent/stream/log.yml.hbs
  packages/zeek/data_stream/smb_cmd/agent/stream/log.yml.hbs
  packages/zeek/data_stream/smb_files/agent/stream/log.yml.hbs
  packages/zeek/data_stream/smb_mapping/agent/stream/log.yml.hbs
  packages/zeek/data_stream/smtp/agent/stream/log.yml.hbs
  packages/zeek/data_stream/snmp/agent/stream/log.yml.hbs
  packages/zeek/data_stream/socks/agent/stream/log.yml.hbs
  packages/zeek/data_stream/ssh/agent/stream/log.yml.hbs
  packages/zeek/data_stream/ssl/agent/stream/log.yml.hbs
  packages/zeek/data_stream/stats/agent/stream/log.yml.hbs
  packages/zeek/data_stream/syslog/agent/stream/log.yml.hbs
  packages/zeek/data_stream/traceroute/agent/stream/log.yml.hbs
  packages/zeek/data_stream/tunnel/agent/stream/log.yml.hbs
  packages/zeek/data_stream/weird/agent/stream/log.yml.hbs
  packages/zeek/data_stream/x509/agent/stream/log.yml.hbs
  packages/zeek/docs/README.md
Labels: Team:Security-External Integrations, enhancement

#691 [okta] Sync okta package with beats
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-config.json
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
  packages/okta/data_stream/system/_dev/test/system/test-default-config.yml
  packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/okta/data_stream/system/agent/stream/log.yml.hbs
  packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/okta/data_stream/system/fields/ecs.yml
  packages/okta/docs/README.md
  packages/okta/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#699 [Fleet Server] Change default bind port from 8000 to 8220
  packages/fleet_server/manifest.yml
Labels: Team:Agent, enhancement

#718 ci: increase timeout
  .ci/Jenkinsfile
Labels: Team:Automation, automation, ci

#724 Add additional guards for Linux/Windows
  packages/linux/changelog.yml
  packages/linux/data_stream/entropy/agent/stream/stream.yml.hbs
  packages/linux/data_stream/network_summary/agent/stream/stream.yml.hbs
  packages/linux/data_stream/raid/agent/stream/stream.yml.hbs
  packages/linux/data_stream/service/agent/stream/stream.yml.hbs
  packages/linux/data_stream/socket/agent/stream/stream.yml.hbs
  packages/linux/data_stream/users/agent/stream/stream.yml.hbs
  packages/linux/manifest.yml
  packages/windows/changelog.yml
  packages/windows/data_stream/security/agent/stream/winlog.yml.hbs
  packages/windows/manifest.yml
Labels: bug

#716 Sync o365 package with beats
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/agent/stream/log.yml.hbs
  packages/o365/data_stream/audit/agent/stream/o365audit.yml.hbs
  packages/o365/data_stream/audit/fields/ecs.yml
  packages/o365/docs/README.md
  packages/o365/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#715 Sync auditd package with beats
  packages/auditd/_dev/deploy/docker/sample_logs/auditd-useradd.log
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-config.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
  packages/auditd/data_stream/log/agent/stream/log.yml.hbs
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/data_stream/log/fields/ecs.yml
  packages/auditd/data_stream/log/fields/fields.yml
  packages/auditd/docs/README.md
  packages/auditd/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#722 Sync azure package with beats
  packages/azure/changelog.yml
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
  packages/azure/data_stream/activitylogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/activitylogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/activitylogs/fields/ecs.yml
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-expected.json
  packages/azure/data_stream/auditlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/auditlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-remote-raw.log-expected.json
  packages/azure/data_stream/platformlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/platformlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
  packages/azure/data_stream/signinlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/signinlogs/agent/stream/log.yml.hbs
  packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/signinlogs/fields/ecs.yml
  packages/azure/docs/README.md
  packages/azure/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#721 Sync aws cloudtrail and s3access with beats
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-add-user-to-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-assume-role-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-change-password-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-cloudtrail-digest-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-console-login-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-key-pair-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-virtual-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-deactivate-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-bucket-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-virtual-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-enable-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-insight-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-remove-user-from-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-start-logging-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-stop-logging-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-accout-password-policy-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-login-profile-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-upload-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/agent/stream/s3.yml.hbs
  packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/cloudtrail/fields/ecs.yml
  packages/aws/data_stream/cloudtrail/fields/fields.yml
  packages/aws/data_stream/s3access/_dev/test/pipeline/test-s3-server-access.log
  packages/aws/data_stream/s3access/_dev/test/pipeline/test-s3-server-access.log-config.json
  packages/aws/data_stream/s3access/_dev/test/pipeline/test-s3-server-access.log-expected.json
  packages/aws/data_stream/s3access/agent/stream/log.yml.hbs
  packages/aws/data_stream/s3access/agent/stream/s3.yml.hbs
  packages/aws/data_stream/s3access/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/s3access/fields/ecs.yml
  packages/aws/data_stream/s3access/fields/fields.yml
  packages/aws/docs/README.md
  packages/aws/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#719 Sync zoom package with beats
  packages/zoom/changelog.yml
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-account.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-channel.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-message.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-meeting.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-phone.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-recording.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-user.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-webinar.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-zoomroom.json-expected.json
  packages/zoom/data_stream/webhook/agent/stream/http_endpoint.yml.hbs
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/account.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/default.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/meeting.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/phone.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/recording.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/user.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/webinar.yml
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/zoomroom.yml
  packages/zoom/data_stream/webhook/fields/ecs.yml
  packages/zoom/docs/README.md
  packages/zoom/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#468 Add Microsoft Defender ATP
  packages/microsoft/_dev/build/docs/README.md
  packages/microsoft/_dev/deploy/docker/sample_logs/defender_atp-test.json.log
  packages/microsoft/changelog.yml
  packages/microsoft/data_stream/defender_atp/_dev/test/pipeline/test-defenderatp.log
  packages/microsoft/data_stream/defender_atp/_dev/test/pipeline/test-defenderatp.log-config.json
  packages/microsoft/data_stream/defender_atp/_dev/test/pipeline/test-defenderatp.log-expected.json
  packages/microsoft/data_stream/defender_atp/_dev/test/system/test-logfile-config.yml
  packages/microsoft/data_stream/defender_atp/agent/stream/httpjson.yml.hbs
  packages/microsoft/data_stream/defender_atp/agent/stream/log.yml.hbs
  packages/microsoft/data_stream/defender_atp/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft/data_stream/defender_atp/fields/agent.yml
  packages/microsoft/data_stream/defender_atp/fields/base-fields.yml
  packages/microsoft/data_stream/defender_atp/fields/ecs.yml
  packages/microsoft/data_stream/defender_atp/fields/fields.yml
  packages/microsoft/data_stream/defender_atp/manifest.yml
  packages/microsoft/data_stream/defender_atp/sample_event.json
  packages/microsoft/docs/README.md
  packages/microsoft/img/filebeat-defender-atp-overview.png
  packages/microsoft/img/siem-alerts-cs.jpg
  packages/microsoft/img/siem-events-cs.jpg
  packages/microsoft/kibana/dashboard/microsoft-65402c30-ca6a-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/kibana/lens/microsoft-14d367f0-ca68-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/kibana/lens/microsoft-e415af10-ca67-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/kibana/visualization/microsoft-00e8fca0-ca68-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/kibana/visualization/microsoft-3c64f400-ca68-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/kibana/visualization/microsoft-62f081c0-ca68-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/kibana/visualization/microsoft-9e902dc0-ca68-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/kibana/visualization/microsoft-b9fcbf60-ca68-11ea-9d4d-9737a63aaa55.json
  packages/microsoft/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#732 Drop cloud field in Defender ATP to set it with provided values
  packages/microsoft/changelog.yml
  packages/microsoft/data_stream/defender_atp/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft/manifest.yml
Labels: Team:Security-External Integrations, bug

#725 Removing duplicate system/syslog ingest pipeline
  packages/system/changelog.yml
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog-sample.log
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog-sample.log-config.json
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog-sample.log-expected.json
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog.log
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog.log-config.json
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog.log-expected.json
  packages/system/data_stream/syslog/_dev/test/pipeline/test-suse-syslog.log
  packages/system/data_stream/syslog/_dev/test/pipeline/test-suse-syslog.log-config.json
  packages/system/data_stream/syslog/_dev/test/pipeline/test-suse-syslog.log-expected.json
  packages/system/data_stream/syslog/_dev/test/pipeline/test-tz-offset.log
  packages/system/data_stream/syslog/_dev/test/pipeline/test-tz-offset.log-config.json
  packages/system/data_stream/syslog/_dev/test/pipeline/test-tz-offset.log-expected.json
  packages/system/data_stream/syslog/elasticsearch/ingest_pipeline/default.json
  packages/system/data_stream/syslog/elasticsearch/ingest_pipeline/default.yml
Labels: Team:Integrations

#728 Move windows/security data stream back to system
  packages/system/changelog.yml
  packages/system/data_stream/security/agent/stream/winlog.yml.hbs
  packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/security/fields/ecs.yml
  packages/system/data_stream/security/fields/fields.yml
  packages/system/data_stream/security/fields/winlog.yml
  packages/system/data_stream/security/manifest.yml
  packages/system/docs/README.md
  packages/system/manifest.yml
  packages/windows/_dev/build/docs/README.md
  packages/windows/changelog.yml
  packages/windows/data_stream/security/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/security/elasticsearch/ingest_pipeline/default.yml
  packages/windows/data_stream/security/fields/agent.yml
  packages/windows/data_stream/security/fields/base-fields.yml
  packages/windows/data_stream/security/fields/ecs.yml
  packages/windows/data_stream/security/fields/fields.yml
  packages/windows/data_stream/security/fields/winlog.yml
  packages/windows/data_stream/security/manifest.yml
  packages/windows/docs/README.md
  packages/windows/manifest.yml
Labels: Team:Integrations, Team:Security-External Integrations, bug, enhancement

#737 Use correct types for source.port and source.ip
  packages/apache/changelog.yml
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-basic.log-expected.json
  packages/apache/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/apache/data_stream/error/fields/ecs.yml
  packages/apache/docs/README.md
  packages/apache/manifest.yml
Labels: Integration:Apache, Team:Integrations
