Repository elastic/integrations, pull requests merged in 2021-07, with the labels that each got.

#1247 [traefik] set event.module and event.dataset
  packages/traefik/changelog.yml
  packages/traefik/data_stream/access/fields/base-fields.yml
  packages/traefik/data_stream/health/fields/base-fields.yml
  packages/traefik/docs/README.md
  packages/traefik/manifest.yml
Labels: Team:Integrations

#1258 [crowdstrike] Set event.module and event.dataset
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/auth_activity_audit.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/detection_summary.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/firewall_match.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/incident_summary.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/remote_response_session_end.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/remote_response_session_start.yml
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/user_activity_audit.yml
  packages/crowdstrike/data_stream/falcon/fields/base-fields.yml
  packages/crowdstrike/data_stream/falcon/fields/ecs.yml
  packages/crowdstrike/docs/README.md
  packages/crowdstrike/manifest.yml
Labels: Integration:Crowdstrike, Team:Security-External Integrations, enhancement

#1282 ga system module
  packages/system/changelog.yml
  packages/system/manifest.yml
Labels: Team:Integrations

#1289 Add _meta information to Kubernetes fields
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/apiserver/fields/fields.yml
  packages/kubernetes/data_stream/container/fields/fields.yml
  packages/kubernetes/data_stream/controllermanager/fields/fields.yml
  packages/kubernetes/data_stream/event/fields/fields.yml
  packages/kubernetes/data_stream/node/fields/fields.yml
  packages/kubernetes/data_stream/pod/fields/fields.yml
  packages/kubernetes/data_stream/proxy/fields/fields.yml
  packages/kubernetes/data_stream/scheduler/fields/fields.yml
  packages/kubernetes/data_stream/state_container/fields/fields.yml
  packages/kubernetes/data_stream/state_cronjob/fields/fields.yml
  packages/kubernetes/data_stream/state_daemonset/fields/fields.yml
  packages/kubernetes/data_stream/state_deployment/fields/fields.yml
  packages/kubernetes/data_stream/state_node/fields/fields.yml
  packages/kubernetes/data_stream/state_persistentvolume/fields/fields.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/fields/fields.yml
  packages/kubernetes/data_stream/state_replicaset/fields/fields.yml
  packages/kubernetes/data_stream/state_resourcequota/fields/fields.yml
  packages/kubernetes/data_stream/state_statefulset/fields/fields.yml
  packages/kubernetes/data_stream/system/fields/fields.yml
  packages/kubernetes/data_stream/volume/fields/fields.yml
  packages/kubernetes/docs/events.md
  packages/kubernetes/docs/kube-apiserver.md
  packages/kubernetes/docs/kube-controller-manager.md
  packages/kubernetes/docs/kube-proxy.md
  packages/kubernetes/docs/kube-scheduler.md
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/docs/kubelet.md
  packages/kubernetes/manifest.yml
Labels: enhancement

#1299 [okta] Add missing initial_interval option to the manifest
  packages/okta/changelog.yml
  packages/okta/manifest.yml
Labels: Integration:Okta, Team:Security-External Integrations, bug

#1297 [Security Rules] Update rules package to 0.13.2
  packages/security_detection_engine/changelog.yml
  packages/security_detection_engine/kibana/security_rule/053a0387-f3b5-4ba5-8245-8002cca2bd08.json
  packages/security_detection_engine/kibana/security_rule/119c8877-8613-416d-a98a-96b6664ee73a5.json
  packages/security_detection_engine/kibana/security_rule/12051077-0124-4394-9522-8f4f4db1d674.json
  packages/security_detection_engine/kibana/security_rule/2045567e-b0af-444a-8c0b-0b6e2dae9e13.json
  packages/security_detection_engine/kibana/security_rule/26f68dba-ce29-497b-8e13-b4fde1db5a2d.json
  packages/security_detection_engine/kibana/security_rule/378f9024-8a0c-46a5-aa08-ce147ac73a4e.json
  packages/security_detection_engine/kibana/security_rule/3efee4f0-182a-40a8-a835-102c68a4175d.json
  packages/security_detection_engine/kibana/security_rule/5e87f165-45c2-4b80-bfa5-52822552c997.json
  packages/security_detection_engine/kibana/security_rule/6506c9fd-229e-4722-8f0f-69be759afd2a.json
  packages/security_detection_engine/kibana/security_rule/863cdf31-7fd3-41cf-a185-681237ea277b.json
  packages/security_detection_engine/kibana/security_rule/8b4f0816-6a65-4630-86a6-c21c179c0d09.json
  packages/security_detection_engine/kibana/security_rule/c1812764-0788-470f-8e74-eb4a14d47573.json
  packages/security_detection_engine/kibana/security_rule/c292fa52-4115-408a-b897-e14f684b3cb7.json
  packages/security_detection_engine/kibana/security_rule/c4818812-d44f-47be-aaef-4cfb2f9cc799.json
  packages/security_detection_engine/kibana/security_rule/c82b2bd8-d701-420c-ba43-f11a155b681a.json
  packages/security_detection_engine/kibana/security_rule/c8cccb06-faf2-4cd5-886e-2c9636cfcb87.json
  packages/security_detection_engine/kibana/security_rule/d461fac0-43e8-49e2-85ea-3a58fe120b4f.json
  packages/security_detection_engine/kibana/security_rule/e919611d-6b6f-493b-8314-7ed6ac2e413b.json
  packages/security_detection_engine/kibana/security_rule/ee5300a7-7e31-4a72-a258-250abb8b3aa1.json
  packages/security_detection_engine/kibana/security_rule/f30f3443-4fbb-4c27-ab89-c3ad49d62315.json
  packages/security_detection_engine/kibana/security_rule/f766ffaf-9568-4909-b734-75d19b35cbf4.json
  packages/security_detection_engine/manifest.yml
Labels: Integration:SecurityRules

#1316 Fix MySQL logs overview dashboard
  packages/mysql/changelog.yml
  packages/mysql/data_stream/error/manifest.yml
  packages/mysql/data_stream/galera_status/fields/fields.yml
  packages/mysql/data_stream/galera_status/manifest.yml
  packages/mysql/data_stream/performance/manifest.yml
  packages/mysql/data_stream/slowlog/manifest.yml
  packages/mysql/data_stream/status/fields/fields.yml
  packages/mysql/data_stream/status/manifest.yml
  packages/mysql/kibana/search/mysql-Logs-MySQL-Slow-log.json
  packages/mysql/kibana/search/mysql-Logs-MySQL-error-log.json
  packages/mysql/manifest.yml
Labels: Team:Integrations

#1051 Rename Azure package to Azure logs package and create input groups
  packages/azure/_dev/build/docs/README.md
  packages/azure/_dev/build/docs/activitylogs.md
  packages/azure/_dev/build/docs/adlogs.md
  packages/azure/_dev/build/docs/platformlogs.md
  packages/azure/changelog.yml
  packages/azure/data_stream/activitylogs/manifest.yml
  packages/azure/data_stream/auditlogs/manifest.yml
  packages/azure/data_stream/signinlogs/manifest.yml
  packages/azure/docs/README.md
  packages/azure/docs/active-directory.md
  packages/azure/docs/activity.md
  packages/azure/docs/activitylogs.md
  packages/azure/docs/adlogs.md
  packages/azure/docs/platform.md
  packages/azure/docs/platformlogs.md
  packages/azure/img/active_directory_logo.png
  packages/azure/img/azure_logs_logo.png
  packages/azure/img/platformlogs_logo.png
  packages/azure/manifest.yml
Labels: 7.14 Candidate, Integration:Azure, Team:Platforms

#1314 [dependabot][mergify] automate merge and add reviewers
  .github/dependabot.yml
  .mergify.yml
Labels: automation

#1317 Add Processors to linux package
  packages/linux/changelog.yml
  packages/linux/data_stream/entropy/agent/stream/stream.yml.hbs
  packages/linux/data_stream/network_summary/agent/stream/stream.yml.hbs
  packages/linux/data_stream/raid/agent/stream/stream.yml.hbs
  packages/linux/data_stream/service/agent/stream/stream.yml.hbs
  packages/linux/data_stream/socket/agent/stream/stream.yml.hbs
  packages/linux/data_stream/users/agent/stream/stream.yml.hbs
  packages/linux/manifest.yml
Labels: bug

#1321 Add leader election variable in kube state metrics integration
  packages/kubernetes/_dev/build/docs/events.md
  packages/kubernetes/_dev/build/docs/kube-apiserver.md
  packages/kubernetes/_dev/build/docs/kube-state-metrics.md
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/apiserver/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/apiserver/manifest.yml
  packages/kubernetes/data_stream/event/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/event/manifest.yml
  packages/kubernetes/data_stream/state_container/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_container/manifest.yml
  packages/kubernetes/data_stream/state_cronjob/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_cronjob/manifest.yml
  packages/kubernetes/data_stream/state_daemonset/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_daemonset/manifest.yml
  packages/kubernetes/data_stream/state_deployment/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_deployment/manifest.yml
  packages/kubernetes/data_stream/state_node/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_node/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolume/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
  packages/kubernetes/data_stream/state_pod/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_pod/manifest.yml
  packages/kubernetes/data_stream/state_replicaset/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_replicaset/manifest.yml
  packages/kubernetes/data_stream/state_resourcequota/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_resourcequota/manifest.yml
  packages/kubernetes/data_stream/state_service/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_service/manifest.yml
  packages/kubernetes/data_stream/state_statefulset/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_statefulset/manifest.yml
  packages/kubernetes/data_stream/state_storageclass/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_storageclass/manifest.yml
  packages/kubernetes/docs/events.md
  packages/kubernetes/docs/kube-apiserver.md
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/manifest.yml
Labels: Team:Integrations, enhancement

#1320 Change AWS default credential option to access keys
  packages/aws/changelog.yml
  packages/aws/manifest.yml
Labels: Team:Integrations

#1323 Fix: replace dollar-yml tags with yml
  packages/prometheus/_dev/build/docs/README.md
  packages/prometheus/changelog.yml
  packages/prometheus/docs/README.md
  packages/prometheus/manifest.yml
Labels: Team:Integrations

#1290 Add state_job data_stream in kubernetes package
  packages/kubernetes/_dev/build/docs/kube-state-metrics.md
  packages/kubernetes/_dev/deploy/k8s/job.yaml
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/controllermanager/_dev/test/system/test-default-config.yml
  packages/kubernetes/data_stream/controllermanager/manifest.yml
  packages/kubernetes/data_stream/scheduler/_dev/test/system/test-default-config.yml
  packages/kubernetes/data_stream/scheduler/manifest.yml
  packages/kubernetes/data_stream/state_job/_dev/test/system/test-default-config.yml
  packages/kubernetes/data_stream/state_job/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_job/fields/agent.yml
  packages/kubernetes/data_stream/state_job/fields/base-fields.yml
  packages/kubernetes/data_stream/state_job/fields/ecs.yml
  packages/kubernetes/data_stream/state_job/fields/fields.yml
  packages/kubernetes/data_stream/state_job/manifest.yml
  packages/kubernetes/data_stream/state_job/sample_event.json
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/manifest.yml
Labels: 7.15-candidate, Team:Integrations, enhancement

#1326 Fix reversed ingress and egress interfaces in cisco asa and ftd
  packages/cisco/changelog.yml
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/asa/sample_event.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ftd/sample_event.json
  packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco/data_stream/ios/sample_event.json
  packages/cisco/data_stream/meraki/_dev/test/pipeline/test-generated.log-expected.json
  packages/cisco/data_stream/meraki/sample_event.json
  packages/cisco/data_stream/nexus/sample_event.json
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Integration:Cisco, Team:Security-External Integrations, bug

#1335 Add missing daemonset.name field
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/state_container/fields/base-fields.yml
  packages/kubernetes/data_stream/state_pod/fields/base-fields.yml
  packages/kubernetes/docs/apiserver.md
  packages/kubernetes/docs/container.md
  packages/kubernetes/docs/controllermanager.md
  packages/kubernetes/docs/event.md
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/docs/node.md
  packages/kubernetes/docs/pod.md
  packages/kubernetes/docs/proxy.md
  packages/kubernetes/docs/scheduler.md
  packages/kubernetes/docs/state_container.md
  packages/kubernetes/docs/state_cronjob.md
  packages/kubernetes/docs/state_daemonset.md
  packages/kubernetes/docs/state_deployment.md
  packages/kubernetes/docs/state_node.md
  packages/kubernetes/docs/state_persistentvolume.md
  packages/kubernetes/docs/state_persistentvolumeclaim.md
  packages/kubernetes/docs/state_pod.md
  packages/kubernetes/docs/state_replicaset.md
  packages/kubernetes/docs/state_resourcequota.md
  packages/kubernetes/docs/state_service.md
  packages/kubernetes/docs/state_statefulset.md
  packages/kubernetes/docs/state_storageclass.md
  packages/kubernetes/docs/system.md
  packages/kubernetes/docs/volume.md
  packages/kubernetes/manifest.yml
Labels: Team:Integrations

#1353 Re-adding pipeline changes removed by mistake
  packages/azure/changelog.yml
  packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/manifest.yml
Labels: Integration:Azure

#1340 Init commit of linux system tests
  packages/linux/_dev/build/build.yml
  packages/linux/_dev/deploy/docker/Dockerfile
  packages/linux/_dev/deploy/docker/docker-compose.yml
  packages/linux/changelog.yml
  packages/linux/data_stream/conntrack/_dev/test/system/test-default-config.yml
  packages/linux/data_stream/conntrack/fields/ecs.yml
  packages/linux/data_stream/entropy/_dev/test/system/test-default-config.yml
  packages/linux/data_stream/entropy/fields/ecs.yml
  packages/linux/data_stream/iostat/_dev/test/system/test-default-config.yml
  packages/linux/data_stream/iostat/fields/ecs.yml
  packages/linux/data_stream/ksm/_dev/test/system/test-default-config.yml
  packages/linux/data_stream/ksm/fields/ecs.yml
  packages/linux/data_stream/memory/_dev/test/system/test-default-config.yml
  packages/linux/data_stream/memory/fields/ecs.yml
  packages/linux/data_stream/network_summary/_dev/test/system/test-default-config.yml
  packages/linux/data_stream/network_summary/fields/ecs.yml
  packages/linux/data_stream/pageinfo/fields/ecs.yml
  packages/linux/data_stream/raid/fields/ecs.yml
  packages/linux/data_stream/service/fields/ecs.yml
  packages/linux/data_stream/socket/fields/ecs.yml
  packages/linux/data_stream/users/fields/ecs.yml
  packages/linux/docs/README.md
  packages/linux/manifest.yml
Labels: Team:Integrations

#971 adding zerofox integration
  packages/zerofox/_dev/build/build.yml
  packages/zerofox/_dev/build/docs/README.md
  packages/zerofox/changelog.yml
  packages/zerofox/data_stream/alerts/_dev/test/pipeline/test-alert.json
  packages/zerofox/data_stream/alerts/_dev/test/pipeline/test-alert.json-config.yml
  packages/zerofox/data_stream/alerts/_dev/test/pipeline/test-alert.json-expected.json
  packages/zerofox/data_stream/alerts/agent/stream/httpjson.yml.hbs
  packages/zerofox/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
  packages/zerofox/data_stream/alerts/fields/agent.yml
  packages/zerofox/data_stream/alerts/fields/base-fields.yml
  packages/zerofox/data_stream/alerts/fields/ecs.yml
  packages/zerofox/data_stream/alerts/fields/fields.yml
  packages/zerofox/data_stream/alerts/manifest.yml
  packages/zerofox/docs/README.md
  packages/zerofox/img/logo.svg
  packages/zerofox/manifest.yml
Labels: Team:Security-External Integrations

#1358 Move system dashboards to cpu.*.norm.pct
  packages/system/changelog.yml
  packages/system/kibana/visualization/system-7cdb1330-4d1a-11e7-a196-69b9a7a020a9.json
  packages/system/kibana/visualization/system-83e12df0-1b91-11e7-bec4-a5e9ec5cab8b.json
  packages/system/kibana/visualization/system-855899e0-1b1c-11e7-b09e-037021c4f8df.json
  packages/system/kibana/visualization/system-ab2d1e90-1b1a-11e7-b09e-037021c4f8df.json
  packages/system/manifest.yml
Labels: Team:Integrations

#1401 Update documentation to fit mdx spec
  packages/cef/_dev/build/docs/README.md
  packages/cef/changelog.yml
  packages/cef/docs/README.md
  packages/cef/manifest.yml
  packages/docker/_dev/build/docs/README.md
  packages/docker/changelog.yml
  packages/docker/docs/README.md
  packages/docker/manifest.yml
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/state_job/fields/fields.yml
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/manifest.yml
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/memcached/fields/protocol.yml
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
  packages/postgresql/_dev/build/docs/README.md
  packages/postgresql/changelog.yml
  packages/postgresql/data_stream/log/fields/fields.yml
  packages/postgresql/docs/README.md
  packages/postgresql/manifest.yml
  packages/rabbitmq/changelog.yml
  packages/rabbitmq/data_stream/queue/fields/fields.yml
  packages/rabbitmq/docs/README.md
  packages/rabbitmq/manifest.yml
  packages/redis/_dev/build/docs/README.md
  packages/redis/changelog.yml
  packages/redis/data_stream/key/fields/fields.yml
  packages/redis/docs/README.md
  packages/redis/manifest.yml
  packages/zeek/_dev/build/docs/README.md
  packages/zeek/changelog.yml
  packages/zeek/docs/README.md
  packages/zeek/manifest.yml
Labels: enhancement
