Repository elastic/integrations, pull requests merged in 2021-03, with the labels that each got.

#746 ci: spread the agent provision to avoid conflicts
  .ci/Jenkinsfile
Labels: Team:Automation, automation, bug, ci

#741 Add check for empty fields in azure integration
  packages/azure/changelog.yml
  packages/azure/data_stream/activitylogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/auditlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/platformlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/data_stream/signinlogs/agent/stream/azure-eventhub.yml.hbs
  packages/azure/manifest.yml
Labels: Integration:Azure, Team:Integrations

#760 Temporary switch to stable image of Elastic Agent
  .ci/Jenkinsfile
  go.mod
  go.sum
Labels: Team:Integrations

#697 Update fields for Netflow module
  packages/netflow/changelog.yml
  packages/netflow/data_stream/log/fields/package-fields.yml
  packages/netflow/docs/README.md
  packages/netflow/manifest.yml
Labels: Team:Security-External Integrations

#759 [Okta] Removes edge processing
  packages/okta/changelog.yml
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-config.yml
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
  packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/okta/data_stream/system/agent/stream/log.yml.hbs
  packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/okta/manifest.yml
Labels: Integration:Okta, Team:Security-External Integrations

#459 Add GCP package
  packages/gcp/_dev/build/docs/README.md
  packages/gcp/_dev/deploy/docker/docker-compose.yml
  packages/gcp/_dev/deploy/docker/sample_logs/audit.log
  packages/gcp/_dev/deploy/docker/sample_logs/firewall.log
  packages/gcp/_dev/deploy/docker/sample_logs/vpcflow.log
  packages/gcp/changelog.yml
  packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log
  packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-config.json
  packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/gcp/data_stream/audit/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/audit/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/audit/fields/agent.yml
  packages/gcp/data_stream/audit/fields/base-fields.yml
  packages/gcp/data_stream/audit/fields/ecs.yml
  packages/gcp/data_stream/audit/fields/fields.yml
  packages/gcp/data_stream/audit/fields/package-fields.yml
  packages/gcp/data_stream/audit/manifest.yml
  packages/gcp/data_stream/audit/sample_event.json
  packages/gcp/data_stream/firewall/_dev/test/pipeline/test-firewall.log
  packages/gcp/data_stream/firewall/_dev/test/pipeline/test-firewall.log-config.json
  packages/gcp/data_stream/firewall/_dev/test/pipeline/test-firewall.log-expected.json
  packages/gcp/data_stream/firewall/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/firewall/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/firewall/fields/agent.yml
  packages/gcp/data_stream/firewall/fields/base-fields.yml
  packages/gcp/data_stream/firewall/fields/ecs.yml
  packages/gcp/data_stream/firewall/fields/fields.yml
  packages/gcp/data_stream/firewall/fields/package-fields.yml
  packages/gcp/data_stream/firewall/manifest.yml
  packages/gcp/data_stream/firewall/sample_event.json
  packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log
  packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-config.json
  packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-expected.json
  packages/gcp/data_stream/vpcflow/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/vpcflow/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/vpcflow/fields/agent.yml
  packages/gcp/data_stream/vpcflow/fields/base-fields.yml
  packages/gcp/data_stream/vpcflow/fields/ecs.yml
  packages/gcp/data_stream/vpcflow/fields/fields.yml
  packages/gcp/data_stream/vpcflow/fields/package-fields.yml
  packages/gcp/data_stream/vpcflow/manifest.yml
  packages/gcp/data_stream/vpcflow/sample_event.json
  packages/gcp/docs/README.md
  packages/gcp/img/filebeat-gcp-audit.png
  packages/gcp/img/logo_gcp.svg
  packages/gcp/kibana/dashboard/gcp-6576c480-73a2-11ea-a345-f985c61fe654.json
  packages/gcp/kibana/map/gcp-a97de660-73a5-11ea-a345-f985c61fe654.json
  packages/gcp/kibana/search/gcp-d88364c0-73a1-11ea-a345-f985c61fe654.json
  packages/gcp/kibana/visualization/gcp-33ee1320-73a5-11ea-a345-f985c61fe654.json
  packages/gcp/kibana/visualization/gcp-4627efa0-73a2-11ea-a345-f985c61fe654.json
  packages/gcp/kibana/visualization/gcp-6d90d320-73a4-11ea-a345-f985c61fe654.json
  packages/gcp/kibana/visualization/gcp-a8e40240-73a3-11ea-a345-f985c61fe654.json
  packages/gcp/kibana/visualization/gcp-eb5bf570-73a2-11ea-a345-f985c61fe654.json
  packages/gcp/manifest.yml
Labels: Integration:GCP, Team:Security-External Integrations, [zube]: In Review, enhancement

#766 Fix teams in integrations packages
  docs/tips_for_building_integrations.md
  packages/apache/changelog.yml
  packages/apache/manifest.yml
  packages/aws/changelog.yml
  packages/aws/manifest.yml
  packages/kafka/changelog.yml
  packages/kafka/manifest.yml
  packages/kubernetes/changelog.yml
  packages/kubernetes/manifest.yml
  packages/linux/changelog.yml
  packages/linux/manifest.yml
  packages/log/changelog.yml
  packages/log/manifest.yml
  packages/mongodb/changelog.yml
  packages/mongodb/manifest.yml
  packages/mysql/changelog.yml
  packages/mysql/manifest.yml
  packages/nats/changelog.yml
  packages/nats/manifest.yml
  packages/nginx/changelog.yml
  packages/nginx/manifest.yml
  packages/nginx_ingress_controller/changelog.yml
  packages/nginx_ingress_controller/manifest.yml
  packages/osquery_elastic_managed/changelog.yml
  packages/osquery_elastic_managed/manifest.yml
  packages/postgresql/changelog.yml
  packages/postgresql/manifest.yml
  packages/prometheus/changelog.yml
  packages/prometheus/manifest.yml
  packages/rabbitmq/changelog.yml
  packages/rabbitmq/manifest.yml
  packages/redis/changelog.yml
  packages/redis/manifest.yml
  packages/system/changelog.yml
  packages/system/manifest.yml
  packages/windows/changelog.yml
  packages/windows/manifest.yml
  packages/zookeeper/changelog.yml
  packages/zookeeper/manifest.yml
Labels: Team:Integrations, enhancement

#780 Updating dependency on elastic-package
  go.mod
  go.sum
Labels: Team:Integrations

#771 Update osquery elastic managed datastream naming convention
  packages/osquery_elastic_managed/changelog.yml
  packages/osquery_elastic_managed/data_stream/result/agent/stream/stream.yml.hbs
  packages/osquery_elastic_managed/data_stream/result/fields/base-fields.yml
  packages/osquery_elastic_managed/data_stream/result/fields/package-fields.yml
  packages/osquery_elastic_managed/data_stream/result/manifest.yml
  packages/osquery_elastic_managed/manifest.yml
Labels: breaking change

#776 Fix: git diff ignores "their" commits
  .ci/Jenkinsfile
Labels: Team:Integrations

#779 [CI] enable one shoot workers
  .ci/Jenkinsfile
Labels: Team:Automation

#763 Migrating traefik module
  packages/traefik/_dev/build/docs/README.md
  packages/traefik/_dev/deploy/docker/Dockerfile
  packages/traefik/_dev/deploy/docker/docker-compose.yml
  packages/traefik/_dev/deploy/docker/traefik.toml
  packages/traefik/_dev/deploy/variants.yml
  packages/traefik/changelog.yml
  packages/traefik/data_stream/access/_dev/test/pipeline/test-default.log
  packages/traefik/data_stream/access/_dev/test/pipeline/test-default.log-config.yml
  packages/traefik/data_stream/access/_dev/test/pipeline/test-default.log-expected.json
  packages/traefik/data_stream/access/_dev/test/system/test-default-config.yml
  packages/traefik/data_stream/access/agent/stream/log.yml.hbs
  packages/traefik/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/traefik/data_stream/access/fields/base-fields.yml
  packages/traefik/data_stream/access/fields/ecs.yml
  packages/traefik/data_stream/access/fields/fields.yml
  packages/traefik/data_stream/access/manifest.yml
  packages/traefik/data_stream/access/sample_event.json
  packages/traefik/data_stream/health/_dev/test/system/test-default-config.yml
  packages/traefik/data_stream/health/agent/stream/stream.yml.hbs
  packages/traefik/data_stream/health/fields/base-fields.yml
  packages/traefik/data_stream/health/fields/ecs.yml
  packages/traefik/data_stream/health/fields/fields.yml
  packages/traefik/data_stream/health/manifest.yml
  packages/traefik/data_stream/health/sample_event.json
  packages/traefik/docs/README.md
  packages/traefik/img/kibana-traefik.png
  packages/traefik/img/traefik.svg
  packages/traefik/kibana/dashboard/traefik-Logs-Traefik-Dashboard.json
  packages/traefik/kibana/search/traefik-Logs-Traefik-integration.json
  packages/traefik/kibana/visualization/traefik-Access-Browsers.json
  packages/traefik/kibana/visualization/traefik-Access-Map.json
  packages/traefik/kibana/visualization/traefik-Access-OSes.json
  packages/traefik/kibana/visualization/traefik-Access-Response-codes-by-top-URLs.json
  packages/traefik/kibana/visualization/traefik-New-Visualization.json
  packages/traefik/kibana/visualization/traefik-Sent-sizes.json
  packages/traefik/manifest.yml
Labels: Team:Integrations

#786 [jjbb] remove periodic-folder-trigger
  .ci/jobs/defaults.yml
Labels: Team:Automation

#774 [Crowdstrike] Removing edge processing and fixing some missing field definitions
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log-config.yml
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-config.yml
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-config.yml
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
  packages/crowdstrike/data_stream/falcon/agent/stream/log.yml.hbs
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/data_stream/falcon/fields/fields.yml
  packages/crowdstrike/docs/README.md
  packages/crowdstrike/manifest.yml
Labels: Integration:Crowdstrike, Team:Security-External Integrations, enhancement

#788 prevent 7.12 Fleet-Server package usage to avoid future / upgrade bugs
  packages/fleet_server/changelog.yml
  packages/fleet_server/manifest.yml
Labels: Team:Agent

#790 [CI] use the stash/unstash approach
  .ci/Jenkinsfile
Labels: Team:Automation

#791 Update dependency on elastic-package
  go.mod
  go.sum
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
  packages/aws/manifest.yml
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
  packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log
  packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
Labels: Team:Integrations

#795 Fix Google workspace pagination
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
  packages/google_workspace/manifest.yml
Labels: Team:Security-External Integrations, bug

#793 [Fleet] Fix Elastic Agent package README
  packages/elastic_agent/changelog.yml
  packages/elastic_agent/docs/README.md
  packages/elastic_agent/img/elastic_agent_metrics.png
  packages/elastic_agent/img/logo_elastic_agent.svg
  packages/elastic_agent/manifest.yml
Labels: 7.12 candidate, Team:Fleet, bug

#798 Update dependency on elastic-package
  go.mod
  go.sum
Labels: Team:Integrations

#775 [Cisco] Removing edge processing and updating field definitions
  packages/cisco/changelog.yml
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/asa/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/asa/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/asa/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/asa/fields/ecs.yml
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco/data_stream/ftd/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/ftd/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/ftd/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ftd/fields/ecs.yml
  packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log
  packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-config.yml
  packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco/data_stream/ios/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/ios/agent/stream/syslog.yml.hbs
  packages/cisco/data_stream/ios/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ios/fields/ecs.yml
  packages/cisco/data_stream/ios/manifest.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Integration:Cisco, Team:Security-External Integrations, enhancement

#772 [Panw] Removing edge processing and adding some new common fields
  packages/panw/changelog.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-config.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-config.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log-config.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-config.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-config.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/agent/stream/logfile.yml.hbs
  packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/data_stream/panos/fields/fields.yml
  packages/panw/docs/README.md
  packages/panw/manifest.yml
Labels: Integration:PANW, Team:Security-External Integrations, enhancement

#801 Mention the need of a fork of package-storage in the docs
  docs/developer_workflow_promote_release_integration.md
Labels: documentation

#809 [Google workspace] Fix saml NaN error
  packages/google_workspace/_dev/deploy/docker/sample_logs/saml-test.json.log
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/saml/agent/stream/log.yml.hbs
  packages/google_workspace/data_stream/saml/fields/fields.yml
  packages/google_workspace/docs/README.md
  packages/google_workspace/manifest.yml
Labels: Team:Security-External Integrations, bug

#810 Generate initial package changelog when importing from Beats modules
  dev/import-beats/changelog.go
  dev/import-beats/packages.go
Labels: enhancement

#806 [Fleet] Add agent input template for the fleet server package
  packages/fleet_server/agent/input/agent.yml.hbs
  packages/fleet_server/changelog.yml
  packages/fleet_server/manifest.yml
Labels: Team:Fleet
