Repository elastic/integrations, pull requests merged in 2021-05, with the labels that each got.

#962 Fix typo in elastic agent dashboard
  .ci/Jenkinsfile
  packages/elastic_agent/changelog.yml
  packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
  packages/elastic_agent/manifest.yml
Labels: bug

#972 Move sysmon edge processing to ingest pipeline
  packages/windows/changelog.yml
  packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json
  packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-config.yml
  packages/windows/data_stream/sysmon_operational/_dev/test/pipeline/test-events.json-expected.json
  packages/windows/data_stream/sysmon_operational/agent/stream/httpjson.yml.hbs
  packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/sysmon_operational/elasticsearch/ingest_pipeline/default.yml
  packages/windows/data_stream/sysmon_operational/fields/ecs.yml
  packages/windows/data_stream/sysmon_operational/fields/winlog.yml
  packages/windows/docs/README.md
  packages/windows/manifest.yml
Labels: Integration:Windows, Team:Security-External Integrations, enhancement

#981 [Synthetics] fix add fields formatting
  packages/synthetics/changelog.yml
  packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
  packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
  packages/synthetics/manifest.yml
Labels: 7.13 candidate, Team:Uptime, bug

#974 [Synthetics] update README
  packages/synthetics/changelog.yml
  packages/synthetics/docs/README.md
  packages/synthetics/manifest.yml
Labels: 7.13 candidate, Team:Uptime, documentation, enhancement, v7.13.0

#979 Update documentation for using role_arn
  packages/aws/_dev/build/docs/README.md
  packages/aws/changelog.yml
  packages/aws/docs/README.md
  packages/aws/manifest.yml
Labels: Team:Integrations

#896 [Cisco] Parse additional IOS log types
  packages/cisco/changelog.yml
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco/data_stream/ftd/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log
  packages/cisco/data_stream/ios/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco/data_stream/ios/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/ios/fields/ecs.yml
  packages/cisco/data_stream/ios/fields/fields.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Integration:Cisco, Team:Security-External Integrations, enhancement

#989 [auditd] Move edge to ingest pipeline and make event.original optional
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
  packages/auditd/data_stream/log/agent/stream/log.yml.hbs
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/data_stream/log/fields/base-fields.yml
  packages/auditd/data_stream/log/manifest.yml
  packages/auditd/docs/README.md
  packages/auditd/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#991 [suricata] Make event.original optional
  packages/suricata/changelog.yml
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-6-0.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-dns-4-1-4.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
  packages/suricata/data_stream/eve/agent/stream/log.yml.hbs
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#990 [system] Make event.original optional for application, security, and system ata streams
  packages/system/changelog.yml
  packages/system/data_stream/application/agent/stream/httpjson.yml.hbs
  packages/system/data_stream/application/agent/stream/winlog.yml.hbs
  packages/system/data_stream/application/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/security/agent/stream/httpjson.yml.hbs
  packages/system/data_stream/security/agent/stream/winlog.yml.hbs
  packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/system/data_stream/system/agent/stream/winlog.yml.hbs
  packages/system/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/system/manifest.yml
Labels: Team:Integrations, Team:Security-External Integrations, enhancement

#778 Attempt to fix process summary name
  packages/system/changelog.yml
  packages/system/data_stream/process_summary/manifest.yml
  packages/system/manifest.yml
Labels: Team:Integrations, bug

#995 [fleet_server] Push to beta release
  packages/fleet_server/changelog.yml
  packages/fleet_server/manifest.yml
Labels: Team:Agent

#1005 Update k8s package version
  packages/kubernetes/manifest.yml
Labels: Team:Integrations

#1008 Update README.md for Fleet Server
  packages/fleet_server/changelog.yml
  packages/fleet_server/docs/README.md
  packages/fleet_server/manifest.yml
Labels: Team:Agent, enhancement

#1011 Fix broken Cisco package
  packages/cisco/changelog.yml
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations, bug

#1016 [Synthetics] bump version to 0.1.0 for 7.13.0 release
  packages/synthetics/changelog.yml
  packages/synthetics/manifest.yml
Labels: 7.13 candidate, Team:Uptime, v7.13.0

#1006 [netflow] Add pipeline tests and move ecs.version to ingest pipeline
  packages/netflow/changelog.yml
  packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json
  packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-config.yml
  packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
  packages/netflow/data_stream/log/agent/stream/netflow.yml.hbs
  packages/netflow/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/netflow/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#1019 [google_workspace] Use fingerprint of id object as document id
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/manifest.yml
Labels: Team:Security-External Integrations, enhancement

#1007 [panw] Make event.original optional
  packages/panw/changelog.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-config.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
  packages/panw/data_stream/panos/agent/stream/logfile.yml.hbs
  packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/manifest.yml
Labels: Integration:PANW, Team:Security-External Integrations, enhancement

#1025 [apache] Move ecs.version to the ingest pipeline and make event.original optional
  packages/apache/changelog.yml
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-config.yml
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-darwin.log-config.yml
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-darwin.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ssl-request.log-config.yml
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ssl-request.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ubuntu.log-config.yml
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ubuntu.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-vhost.log-config.yml
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-vhost.log-expected.json
  packages/apache/data_stream/access/agent/stream/httpjson.yml.hbs
  packages/apache/data_stream/access/agent/stream/log.yml.hbs
  packages/apache/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/apache/data_stream/access/manifest.yml
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-basic.log-config.yml
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-basic.log-expected.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-darwin.log-config.yml
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-darwin.log-expected.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-ubuntu.log-config.yml
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-ubuntu.log-expected.json
  packages/apache/data_stream/error/agent/stream/httpjson.yml.hbs
  packages/apache/data_stream/error/agent/stream/log.yml.hbs
  packages/apache/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/apache/data_stream/error/fields/base-fields.yml
  packages/apache/data_stream/error/manifest.yml
  packages/apache/docs/README.md
  packages/apache/manifest.yml
Labels: Integration:Apache, Team:Security-External Integrations, enhancement

#1009 [okta] Make event.original optional
  packages/okta/_dev/build/docs/README.md
  packages/okta/changelog.yml
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-config.yml
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
  packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/okta/data_stream/system/agent/stream/log.yml.hbs
  packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/okta/data_stream/system/manifest.yml
  packages/okta/data_stream/system/sample_event.json
  packages/okta/docs/README.md
  packages/okta/manifest.yml
Labels: Integration:Okta, Team:Security-External Integrations, enhancement

#1027 Clean up fixture files
  packages/crowdstrike/_dev/deploy/docker/sample_logs/falcon-sample.log
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
Labels: Team:Security-External Integrations

#1030 Update elastic-package dependency
  go.mod
  go.sum
Labels: Team:Integrations, enhancement
