Repository elastic/integrations, pull requests merged in 2021-09, with the labels that each got.

#1569 [Fleet] Publish a new version of elastic agent package
  packages/elastic_agent/changelog.yml
  packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json
  packages/elastic_agent/manifest.yml
Labels: Team:Fleet, v7.15.0

#1327 [New Package] Palo Alto Cortex XDR
  packages/panw_cortex_xdr/_dev/build/build.yml
  packages/panw_cortex_xdr/_dev/build/docs/README.md
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-common-config.yml
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr-bioc.log
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr-bioc.log-expected.json
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr.log
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr.log-expected.json
  packages/panw_cortex_xdr/data_stream/alerts/agent/stream/httpjson.yml.hbs
  packages/panw_cortex_xdr/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
  packages/panw_cortex_xdr/data_stream/alerts/fields/agent.yml
  packages/panw_cortex_xdr/data_stream/alerts/fields/base-fields.yml
  packages/panw_cortex_xdr/data_stream/alerts/fields/beats.yml
  packages/panw_cortex_xdr/data_stream/alerts/fields/ecs.yml
  packages/panw_cortex_xdr/data_stream/alerts/fields/fields.yml
  packages/panw_cortex_xdr/data_stream/alerts/manifest.yml
  packages/panw_cortex_xdr/docs/README.md
  packages/panw_cortex_xdr/img/icon-cortex.svg
  packages/panw_cortex_xdr/manifest.yml
Labels: Team:Security-External Integrations, 7.15 candidate, Integration:PanwCortexXDR

#1574 Osquery_manager: Update host.ip field mapping from keyword to ip data type
  packages/osquery_manager/changelog.yml
  packages/osquery_manager/data_stream/result/fields/ecs.yml
  packages/osquery_manager/manifest.yml
Labels: enhancement, v7.16.0, v7.15.0, Team:Asset Mgt

#1577 Skip "latest" directory for dumped logs
  .ci/Jenkinsfile
Labels: bug

#1580 [Panw] Add time zone offset
  packages/panw/changelog.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-common-config.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/agent/stream/logfile.yml.hbs
  packages/panw/data_stream/panos/agent/stream/syslog.yml.hbs
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/data_stream/panos/manifest.yml
  packages/panw/manifest.yml
Labels: Team:Security-External Integrations

#1589 [Cisco] Deprecate Cisco package in favor of product specific packages
  packages/cisco/changelog.yml
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate

#1582 [Cisco_IOS] initial commit to split cisco IOS package
  packages/cisco_ios/_dev/build/build.yml
  packages/cisco_ios/_dev/build/docs/README.md
  packages/cisco_ios/_dev/deploy/docker/docker-compose.yml
  packages/cisco_ios/_dev/deploy/docker/sample_logs/cisco-ios.log
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/cisco_ios/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cisco_ios/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/cisco_ios/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ios/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/data_stream/log/fields/agent.yml
  packages/cisco_ios/data_stream/log/fields/base-fields.yml
  packages/cisco_ios/data_stream/log/fields/ecs.yml
  packages/cisco_ios/data_stream/log/fields/fields.yml
  packages/cisco_ios/data_stream/log/manifest.yml
  packages/cisco_ios/data_stream/log/sample_event.json
  packages/cisco_ios/docs/README.md
  packages/cisco_ios/img/cisco.svg
  packages/cisco_ios/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate

#1583 [Cisco] initial commit to split Cisco ASA out of cisco package
  packages/cisco_asa/_dev/build/build.yml
  packages/cisco_asa/_dev/build/docs/README.md
  packages/cisco_asa/_dev/deploy/docker/docker-compose.yml
  packages/cisco_asa/_dev/deploy/docker/sample_logs/cisco-asa.log
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-dap-records.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-filtered.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-hostnames.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cisco_asa/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/cisco_asa/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_asa/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_asa/data_stream/log/fields/agent.yml
  packages/cisco_asa/data_stream/log/fields/base-fields.yml
  packages/cisco_asa/data_stream/log/fields/ecs.yml
  packages/cisco_asa/data_stream/log/fields/fields.yml
  packages/cisco_asa/data_stream/log/manifest.yml
  packages/cisco_asa/data_stream/log/sample_event.json
  packages/cisco_asa/docs/README.md
  packages/cisco_asa/img/cisco.svg
  packages/cisco_asa/img/kibana-cisco-asa.png
  packages/cisco_asa/kibana/dashboard/cisco_asa-a555b160-4987-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/search/cisco_asa-14fce5e0-498f-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/search/cisco_asa-753406e0-4986-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/search/cisco_asa-96c6ff60-4986-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/visualization/cisco_asa-08ef4d90-499b-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/visualization/cisco_asa-118da960-4987-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/visualization/cisco_asa-5d0322d0-4987-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/visualization/cisco_asa-80d0c1b0-498a-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/visualization/cisco_asa-a3b5ab10-4989-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/visualization/cisco_asa-d05cdf60-498b-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/kibana/visualization/cisco_asa-fd89b1e0-49a2-11e9-b8ce-ed898b5ef295.json
  packages/cisco_asa/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate

#1586 [Cisco FTD] Splitting Cisco FTD out of original Cisco package
  packages/cisco_ftd/_dev/build/build.yml
  packages/cisco_ftd/_dev/build/docs/README.md
  packages/cisco_ftd/_dev/deploy/docker/docker-compose.yml
  packages/cisco_ftd/_dev/deploy/docker/sample_logs/cisco-ftd.log
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-dns.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-filtered.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-firepower-management.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-no-type-id.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-not-ip.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-sample.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-file-malware.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-malware-site.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cisco_ftd/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/cisco_ftd/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ftd/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ftd/data_stream/log/fields/agent.yml
  packages/cisco_ftd/data_stream/log/fields/base-fields.yml
  packages/cisco_ftd/data_stream/log/fields/ecs.yml
  packages/cisco_ftd/data_stream/log/fields/fields.yml
  packages/cisco_ftd/data_stream/log/manifest.yml
  packages/cisco_ftd/data_stream/log/sample_event.json
  packages/cisco_ftd/docs/README.md
  packages/cisco_ftd/img/cisco.svg
  packages/cisco_ftd/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate

#1588 [Cisco] initial commit splitting cisco nexus from cisco package
  packages/cisco_nexus/_dev/build/build.yml
  packages/cisco_nexus/_dev/build/docs/README.md
  packages/cisco_nexus/_dev/deploy/docker/docker-compose.yml
  packages/cisco_nexus/_dev/deploy/docker/sample_logs/test-nexus.log
  packages/cisco_nexus/changelog.yml
  packages/cisco_nexus/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/cisco_nexus/data_stream/log/_dev/test/pipeline/test-nexus.log
  packages/cisco_nexus/data_stream/log/_dev/test/pipeline/test-nexus.log-expected.json
  packages/cisco_nexus/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cisco_nexus/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/cisco_nexus/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/cisco_nexus/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_nexus/data_stream/log/agent/stream/tcp.yml.hbs
  packages/cisco_nexus/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_nexus/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_nexus/data_stream/log/fields/agent.yml
  packages/cisco_nexus/data_stream/log/fields/base-fields.yml
  packages/cisco_nexus/data_stream/log/fields/ecs.yml
  packages/cisco_nexus/data_stream/log/fields/fields.yml
  packages/cisco_nexus/data_stream/log/manifest.yml
  packages/cisco_nexus/data_stream/log/sample_event.json
  packages/cisco_nexus/docs/README.md
  packages/cisco_nexus/img/cisco.svg
  packages/cisco_nexus/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate

#1587 [Cisco Meraki] initial split of meraki and cisco package
  packages/cisco_meraki/_dev/build/build.yml
  packages/cisco_meraki/_dev/build/docs/README.md
  packages/cisco_meraki/_dev/deploy/docker/docker-compose.yml
  packages/cisco_meraki/_dev/deploy/docker/sample_logs/cisco-meraki.log
  packages/cisco_meraki/changelog.yml
  packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-generated.log
  packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-generated.log-config.yml
  packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/cisco_meraki/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cisco_meraki/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/cisco_meraki/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/cisco_meraki/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_meraki/data_stream/log/agent/stream/tcp.yml.hbs
  packages/cisco_meraki/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_meraki/data_stream/log/fields/agent.yml
  packages/cisco_meraki/data_stream/log/fields/base-fields.yml
  packages/cisco_meraki/data_stream/log/fields/ecs.yml
  packages/cisco_meraki/data_stream/log/fields/fields.yml
  packages/cisco_meraki/data_stream/log/manifest.yml
  packages/cisco_meraki/data_stream/log/sample_event.json
  packages/cisco_meraki/docs/README.md
  packages/cisco_meraki/img/cisco.svg
  packages/cisco_meraki/manifest.yml
Labels: Team:Security-External Integrations, 7.16 candidate

#1641 Add markdown with workflow for fleet ui development
  docs/developer_workflow_fleet_ui.md
Labels: enhancement, Team:Integrations

#1610 Make Kubernetes GA
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/apiserver/manifest.yml
  packages/kubernetes/data_stream/container/manifest.yml
  packages/kubernetes/data_stream/controllermanager/manifest.yml
  packages/kubernetes/data_stream/event/manifest.yml
  packages/kubernetes/data_stream/node/manifest.yml
  packages/kubernetes/data_stream/pod/manifest.yml
  packages/kubernetes/data_stream/proxy/manifest.yml
  packages/kubernetes/data_stream/scheduler/manifest.yml
  packages/kubernetes/data_stream/state_container/manifest.yml
  packages/kubernetes/data_stream/state_cronjob/manifest.yml
  packages/kubernetes/data_stream/state_daemonset/manifest.yml
  packages/kubernetes/data_stream/state_deployment/manifest.yml
  packages/kubernetes/data_stream/state_job/manifest.yml
  packages/kubernetes/data_stream/state_node/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
  packages/kubernetes/data_stream/state_pod/manifest.yml
  packages/kubernetes/data_stream/state_replicaset/manifest.yml
  packages/kubernetes/data_stream/state_resourcequota/manifest.yml
  packages/kubernetes/data_stream/state_service/manifest.yml
  packages/kubernetes/data_stream/state_statefulset/manifest.yml
  packages/kubernetes/data_stream/state_storageclass/manifest.yml
  packages/kubernetes/data_stream/system/manifest.yml
  packages/kubernetes/data_stream/volume/manifest.yml
  packages/kubernetes/manifest.yml
Labels: enhancement, Team:Integrations

#1622 Make Zookeeper GA
  packages/zookeeper/changelog.yml
  packages/zookeeper/data_stream/connection/manifest.yml
  packages/zookeeper/data_stream/mntr/manifest.yml
  packages/zookeeper/data_stream/server/manifest.yml
  packages/zookeeper/manifest.yml
Labels: enhancement, Team:Integrations

#1614 Make Nginx GA
  packages/nginx/changelog.yml
  packages/nginx/data_stream/access/manifest.yml
  packages/nginx/data_stream/error/manifest.yml
  packages/nginx/data_stream/stubstatus/manifest.yml
  packages/nginx/manifest.yml
Labels: enhancement, Team:Integrations

#1617 Make RabbitMQ GA
  packages/rabbitmq/changelog.yml
  packages/rabbitmq/data_stream/connection/manifest.yml
  packages/rabbitmq/data_stream/exchange/manifest.yml
  packages/rabbitmq/data_stream/log/manifest.yml
  packages/rabbitmq/data_stream/node/manifest.yml
  packages/rabbitmq/data_stream/queue/manifest.yml
  packages/rabbitmq/manifest.yml
Labels: enhancement, Team:Integrations

#1607 Make Apache integration GA
  packages/apache/changelog.yml
  packages/apache/data_stream/access/manifest.yml
  packages/apache/data_stream/error/manifest.yml
  packages/apache/data_stream/status/manifest.yml
  packages/apache/manifest.yml
Labels: enhancement, Team:Integrations

#1612 Make MySQL GA
  packages/mysql/changelog.yml
  packages/mysql/data_stream/error/manifest.yml
  packages/mysql/data_stream/galera_status/manifest.yml
  packages/mysql/data_stream/performance/manifest.yml
  packages/mysql/data_stream/slowlog/manifest.yml
  packages/mysql/data_stream/status/manifest.yml
  packages/mysql/manifest.yml
Labels: enhancement, Team:Integrations

#1618 Make Redis GA
  packages/redis/changelog.yml
  packages/redis/data_stream/info/manifest.yml
  packages/redis/data_stream/key/manifest.yml
  packages/redis/data_stream/keyspace/manifest.yml
  packages/redis/data_stream/log/manifest.yml
  packages/redis/data_stream/slowlog/manifest.yml
  packages/redis/manifest.yml
Labels: enhancement, Team:Integrations

#1616 Make Postresql GA
  packages/postgresql/changelog.yml
  packages/postgresql/data_stream/activity/manifest.yml
  packages/postgresql/data_stream/bgwriter/manifest.yml
  packages/postgresql/data_stream/database/manifest.yml
  packages/postgresql/data_stream/log/manifest.yml
  packages/postgresql/data_stream/statement/manifest.yml
  packages/postgresql/manifest.yml
Labels: enhancement, Team:Integrations

#1611 Make Mongodb GA
  packages/mongodb/changelog.yml
  packages/mongodb/data_stream/collstats/manifest.yml
  packages/mongodb/data_stream/dbstats/manifest.yml
  packages/mongodb/data_stream/log/manifest.yml
  packages/mongodb/data_stream/metrics/manifest.yml
  packages/mongodb/data_stream/replstatus/manifest.yml
  packages/mongodb/data_stream/status/manifest.yml
  packages/mongodb/manifest.yml
Labels: enhancement, Team:Integrations

#1620 Make Tomcat GA
  packages/tomcat/changelog.yml
  packages/tomcat/data_stream/log/manifest.yml
  packages/tomcat/manifest.yml
Labels: enhancement, Team:Integrations

#1621 Make Traefik GA
  packages/traefik/changelog.yml
  packages/traefik/data_stream/access/manifest.yml
  packages/traefik/data_stream/health/manifest.yml
  packages/traefik/manifest.yml
Labels: enhancement, Team:Integrations

#1613 Make NATS GA
  packages/nats/changelog.yml
  packages/nats/data_stream/connection/manifest.yml
  packages/nats/data_stream/connections/manifest.yml
  packages/nats/data_stream/log/manifest.yml
  packages/nats/data_stream/route/manifest.yml
  packages/nats/data_stream/routes/manifest.yml
  packages/nats/data_stream/stats/manifest.yml
  packages/nats/data_stream/subscriptions/manifest.yml
  packages/nats/manifest.yml
Labels: enhancement, Team:Integrations

#1615 Make Nginx Ingress Controller GA
  packages/nginx_ingress_controller/changelog.yml
  packages/nginx_ingress_controller/data_stream/access/manifest.yml
  packages/nginx_ingress_controller/data_stream/error/manifest.yml
  packages/nginx_ingress_controller/manifest.yml
Labels: enhancement, Team:Integrations

#1619 Make Stan GA
  packages/stan/changelog.yml
  packages/stan/data_stream/channels/manifest.yml
  packages/stan/data_stream/log/manifest.yml
  packages/stan/data_stream/stats/manifest.yml
  packages/stan/data_stream/subscriptions/manifest.yml
  packages/stan/manifest.yml
Labels: enhancement, Team:Integrations

#1571 Release Docker as GA
  packages/docker/changelog.yml
  packages/docker/data_stream/container/manifest.yml
  packages/docker/data_stream/cpu/manifest.yml
  packages/docker/data_stream/diskio/manifest.yml
  packages/docker/data_stream/event/manifest.yml
  packages/docker/data_stream/healthcheck/manifest.yml
  packages/docker/data_stream/image/manifest.yml
  packages/docker/data_stream/info/manifest.yml
  packages/docker/data_stream/memory/manifest.yml
  packages/docker/data_stream/network/manifest.yml
  packages/docker/manifest.yml
Labels: enhancement, Team:Integrations

#1644 [Azure] Add `client.ip` mappingto `azure.platformlogs`
  packages/azure/changelog.yml
  packages/azure/data_stream/platformlogs/fields/ecs.yml
  packages/azure/docs/README.md
  packages/azure/docs/platformlogs.md
  packages/azure/manifest.yml
Labels: bug, Integration:Azure

#1515 [Zeek] Add NTP and Signature data streams
  packages/zeek/_dev/build/docs/README.md
  packages/zeek/_dev/deploy/docker/http-mock-config.yml
  packages/zeek/_dev/deploy/docker/sample_logs/ntp.log
  packages/zeek/_dev/deploy/docker/sample_logs/signature.log
  packages/zeek/changelog.yml
  packages/zeek/data_stream/connection/_dev/test/pipeline/test-conn.log-expected.json
  packages/zeek/data_stream/connection/elasticsearch/ingest_pipeline/default.yml
  packages/zeek/data_stream/ntp/_dev/test/pipeline/test-ntp.log
  packages/zeek/data_stream/ntp/_dev/test/pipeline/test-ntp.log-config.yml
  packages/zeek/data_stream/ntp/_dev/test/pipeline/test-ntp.log-expected.json
  packages/zeek/data_stream/ntp/_dev/test/system/test-logs-config.yml
  packages/zeek/data_stream/ntp/_dev/test/system/test-splunk-config.yml
  packages/zeek/data_stream/ntp/agent/stream/httpjson.yml.hbs
  packages/zeek/data_stream/ntp/agent/stream/log.yml.hbs
  packages/zeek/data_stream/ntp/elasticsearch/ingest_pipeline/default.yml
  packages/zeek/data_stream/ntp/elasticsearch/ingest_pipeline/third-party.yml
  packages/zeek/data_stream/ntp/fields/agent.yml
  packages/zeek/data_stream/ntp/fields/base-fields.yml
  packages/zeek/data_stream/ntp/fields/beats.yml
  packages/zeek/data_stream/ntp/fields/ecs.yml
  packages/zeek/data_stream/ntp/fields/fields.yml
  packages/zeek/data_stream/ntp/fields/package-fields.yml
  packages/zeek/data_stream/ntp/manifest.yml
  packages/zeek/data_stream/signature/_dev/test/pipeline/test-signature.log
  packages/zeek/data_stream/signature/_dev/test/pipeline/test-signature.log-config.yml
  packages/zeek/data_stream/signature/_dev/test/pipeline/test-signature.log-expected.json
  packages/zeek/data_stream/signature/_dev/test/system/test-logs-config.yml
  packages/zeek/data_stream/signature/_dev/test/system/test-splunk-config.yml
  packages/zeek/data_stream/signature/agent/stream/httpjson.yml.hbs
  packages/zeek/data_stream/signature/agent/stream/log.yml.hbs
  packages/zeek/data_stream/signature/elasticsearch/ingest_pipeline/default.yml
  packages/zeek/data_stream/signature/elasticsearch/ingest_pipeline/third-party.yml
  packages/zeek/data_stream/signature/fields/agent.yml
  packages/zeek/data_stream/signature/fields/base-fields.yml
  packages/zeek/data_stream/signature/fields/beats.yml
  packages/zeek/data_stream/signature/fields/ecs.yml
  packages/zeek/data_stream/signature/fields/fields.yml
  packages/zeek/data_stream/signature/fields/package-fields.yml
  packages/zeek/data_stream/signature/manifest.yml
  packages/zeek/docs/README.md
  packages/zeek/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1646 [Cisco Umbrella] Add Cisco Umbrella package
  packages/cisco_umbrella/_dev/build/build.yml
  packages/cisco_umbrella/_dev/build/docs/README.md
  packages/cisco_umbrella/changelog.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-cloudfirewalllogs.log
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-cloudfirewalllogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-iplogs.log
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-iplogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-proxylogs.log
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-proxylogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
  packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_umbrella/data_stream/log/fields/agent.yml
  packages/cisco_umbrella/data_stream/log/fields/base-fields.yml
  packages/cisco_umbrella/data_stream/log/fields/ecs.yml
  packages/cisco_umbrella/data_stream/log/fields/fields.yml
  packages/cisco_umbrella/data_stream/log/manifest.yml
  packages/cisco_umbrella/data_stream/log/sample_event.json
  packages/cisco_umbrella/docs/README.md
  packages/cisco_umbrella/img/cisco.svg
  packages/cisco_umbrella/manifest.yml
  packages/cloudflare/changelog.yml
Labels: Team:Security-External Integrations, Integration:Cisco

#1648 Add Proxy configs for httpjson, aws-s3 inputs and AWS metric sets
  packages/aws/changelog.yml
  packages/aws/data_stream/billing/agent/stream/stream.yml.hbs
  packages/aws/data_stream/cloudtrail/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/cloudwatch_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/cloudwatch_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/dynamodb/agent/stream/stream.yml.hbs
  packages/aws/data_stream/ebs/agent/stream/stream.yml.hbs
  packages/aws/data_stream/ec2_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/ec2_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/elb_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/elb_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/lambda/agent/stream/stream.yml.hbs
  packages/aws/data_stream/natgateway/agent/stream/stream.yml.hbs
  packages/aws/data_stream/rds/agent/stream/stream.yml.hbs
  packages/aws/data_stream/s3_daily_storage/agent/stream/stream.yml.hbs
  packages/aws/data_stream/s3_request/agent/stream/stream.yml.hbs
  packages/aws/data_stream/s3access/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/sns/agent/stream/stream.yml.hbs
  packages/aws/data_stream/sqs/agent/stream/stream.yml.hbs
  packages/aws/data_stream/transitgateway/agent/stream/stream.yml.hbs
  packages/aws/data_stream/usage/agent/stream/stream.yml.hbs
  packages/aws/data_stream/vpcflow/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/vpn/agent/stream/stream.yml.hbs
  packages/aws/manifest.yml
  packages/cloudflare/changelog.yml
  packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs
  packages/cloudflare/data_stream/logpull/manifest.yml
  packages/cloudflare/manifest.yml
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
  packages/crowdstrike/data_stream/fdr/manifest.yml
  packages/crowdstrike/manifest.yml
  packages/microsoft/changelog.yml
  packages/microsoft/data_stream/defender_atp/agent/stream/httpjson.yml.hbs
  packages/microsoft/data_stream/defender_atp/manifest.yml
  packages/microsoft/manifest.yml
  packages/okta/changelog.yml
  packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs
  packages/okta/manifest.yml
Labels: Team:Integrations, Team:Security-External Integrations, Integration:System, Integration:AWS, Integration:Microsoft, Integration:Crowdstrike, Integration:Okta, Integration:Cloudflare

#1579 [vSphere] Add vSphere package
  packages/vsphere/_dev/build/build.yml
  packages/vsphere/_dev/build/docs/README.md
  packages/vsphere/_dev/deploy/docker/docker-compose.yml
  packages/vsphere/_dev/deploy/docker/sample_logs/syslog.log
  packages/vsphere/changelog.yml
  packages/vsphere/data_stream/datastore/agent/stream/stream.yml.hbs
  packages/vsphere/data_stream/datastore/fields/agent.yml
  packages/vsphere/data_stream/datastore/fields/base-fields.yml
  packages/vsphere/data_stream/datastore/fields/ecs.yml
  packages/vsphere/data_stream/datastore/fields/fields.yml
  packages/vsphere/data_stream/datastore/manifest.yml
  packages/vsphere/data_stream/datastore/sample_event.json
  packages/vsphere/data_stream/host/agent/stream/stream.yml.hbs
  packages/vsphere/data_stream/host/fields/agent.yml
  packages/vsphere/data_stream/host/fields/base-fields.yml
  packages/vsphere/data_stream/host/fields/ecs.yml
  packages/vsphere/data_stream/host/fields/fields.yml
  packages/vsphere/data_stream/host/manifest.yml
  packages/vsphere/data_stream/host/sample_event.json
  packages/vsphere/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/vsphere/data_stream/log/_dev/test/pipeline/test-format-common.log
  packages/vsphere/data_stream/log/_dev/test/pipeline/test-format-common.log-expected.json
  packages/vsphere/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/vsphere/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/vsphere/data_stream/log/agent/stream/tcpudp.yml.hbs
  packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/vsphere/data_stream/log/fields/agent.yml
  packages/vsphere/data_stream/log/fields/base-fields.yml
  packages/vsphere/data_stream/log/fields/ecs.yml
  packages/vsphere/data_stream/log/fields/fields.yml
  packages/vsphere/data_stream/log/manifest.yml
  packages/vsphere/data_stream/virtualmachine/agent/stream/stream.yml.hbs
  packages/vsphere/data_stream/virtualmachine/fields/agent.yml
  packages/vsphere/data_stream/virtualmachine/fields/base-fields.yml
  packages/vsphere/data_stream/virtualmachine/fields/ecs.yml
  packages/vsphere/data_stream/virtualmachine/fields/fields.yml
  packages/vsphere/data_stream/virtualmachine/manifest.yml
  packages/vsphere/data_stream/virtualmachine/sample_event.json
  packages/vsphere/docs/README.md
  packages/vsphere/img/vmware.svg
  packages/vsphere/img/vsphere_dashboard.png
  packages/vsphere/img/vsphere_vm_dashboard.png
  packages/vsphere/kibana/dashboard/vsphere-0ebd0be0-f049-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/dashboard/vsphere-8a2d1540-f049-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/search/vsphere-1411b690-f017-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-47125df0-f040-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-5c6a93a0-f04c-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-5f74c330-f048-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-783f2c50-f040-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-79dcd290-f047-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-867e0c70-f048-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-9afddd20-f04c-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-a6026680-f017-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-ab07c5d0-f03f-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-d6370680-f049-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-dae93d90-f041-11e9-aaf3-15199b632da7.json
  packages/vsphere/kibana/visualization/vsphere-e3a3e080-f018-11e9-aaf3-15199b632da7.json
  packages/vsphere/manifest.yml
Labels: Team:Integrations

#1731 [Cisco_ftd] adding missing ECS fields
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/data_stream/log/fields/ecs.yml
  packages/cisco_ftd/docs/README.md
  packages/cisco_ftd/manifest.yml
Labels: Team:Security-External Integrations

#1732 [Cisco_asa] Update ECS fields
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/fields/ecs.yml
  packages/cisco_asa/docs/README.md
  packages/cisco_asa/manifest.yml
Labels: Team:Security-External Integrations

#1730 [Cisco package] adding missing ECS fields
  packages/cisco/changelog.yml
  packages/cisco/data_stream/asa/fields/ecs.yml
  packages/cisco/data_stream/ftd/fields/ecs.yml
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: Team:Security-External Integrations

#1568 [Enhancement] Move GCP integration from experimental to GA
  packages/gcp/changelog.yml
  packages/gcp/manifest.yml
Labels: Team:Security-External Integrations, Integration:GCP

#1734 update osquery manager readme
  packages/osquery_manager/changelog.yml
  packages/osquery_manager/docs/README.md
  packages/osquery_manager/manifest.yml
Labels: enhancement

#1605 GA checkpoint integration
  packages/checkpoint/changelog.yml
  packages/checkpoint/data_stream/firewall/manifest.yml
  packages/checkpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1631 GA cyperarkpas integration
  packages/cyberarkpas/changelog.yml
  packages/cyberarkpas/data_stream/audit/manifest.yml
  packages/cyberarkpas/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1642 0365 Add type assertions to painless scripts
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/o365/manifest.yml
Labels: bug, Team:Security-External Integrations

#1604 GA CEF integration
  packages/cef/changelog.yml
  packages/cef/data_stream/log/manifest.yml
  packages/cef/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1716 GA winlog integration
  packages/winlog/_dev/build/build.yml
  packages/winlog/_dev/deploy/docker/docker-compose.yml
  packages/winlog/_dev/deploy/docker/http-mock-config.yml
  packages/winlog/changelog.yml
  packages/winlog/data_stream/winlog/_dev/test/system/test-splunk-config.yml
  packages/winlog/data_stream/winlog/fields/beats.yml
  packages/winlog/data_stream/winlog/fields/ecs.yml
  packages/winlog/data_stream/winlog/fields/winlog.yml
  packages/winlog/data_stream/winlog/manifest.yml
  packages/winlog/docs/README.md
  packages/winlog/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1719 [google_workspace] ga google_workspace integration
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/manifest.yml
  packages/google_workspace/data_stream/drive/manifest.yml
  packages/google_workspace/data_stream/groups/manifest.yml
  packages/google_workspace/data_stream/login/manifest.yml
  packages/google_workspace/data_stream/saml/manifest.yml
  packages/google_workspace/data_stream/user_accounts/manifest.yml
  packages/google_workspace/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1735 ga hashicorp vault integration
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1636 [zerofox] Update ECS to 1.12
  packages/zerofox/_dev/build/build.yml
  packages/zerofox/changelog.yml
  packages/zerofox/data_stream/alerts/_dev/test/pipeline/test-alert.json-expected.json
  packages/zerofox/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
  packages/zerofox/docs/README.md
  packages/zerofox/manifest.yml
Labels: enhancement, [zube]: In Review, Team:Security-External Integrations

#1637 [auditd] Update ECS to 1.12
  packages/auditd/_dev/build/build.yml
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/docs/README.md
  packages/auditd/manifest.yml
Labels: enhancement, [zube]: In Review, Team:Security-External Integrations

#1650 [bluecoat] Update ECS to 1.12
  packages/bluecoat/_dev/build/build.yml
  packages/bluecoat/changelog.yml
  packages/bluecoat/data_stream/director/_dev/test/pipeline/test-generated.log-expected.json
  packages/bluecoat/data_stream/director/elasticsearch/ingest_pipeline/default.yml
  packages/bluecoat/manifest.yml
Labels: enhancement, [zube]: In Review, Team:Security-External Integrations

#1649 [barracuda] Update ECS to 1.12
  packages/barracuda/_dev/build/build.yml
  packages/barracuda/changelog.yml
  packages/barracuda/data_stream/spamfirewall/_dev/test/pipeline/test-generated.log-expected.json
  packages/barracuda/data_stream/spamfirewall/elasticsearch/ingest_pipeline/default.yml
  packages/barracuda/data_stream/waf/_dev/test/pipeline/test-generated.log-expected.json
  packages/barracuda/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
  packages/barracuda/manifest.yml
Labels: enhancement, [zube]: In Review, Team:Security-External Integrations

#1651 [carbonblack_edr] Update ECS to 1.12
  packages/carbonblack_edr/_dev/build/build.yml
  packages/carbonblack_edr/changelog.yml
  packages/carbonblack_edr/data_stream/log/_dev/test/pipeline/test-events.json
  packages/carbonblack_edr/data_stream/log/_dev/test/pipeline/test-events.json-expected.json
  packages/carbonblack_edr/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/carbonblack_edr/data_stream/log/sample_event.json
  packages/carbonblack_edr/docs/README.md
  packages/carbonblack_edr/manifest.yml
Labels: enhancement, [zube]: In Review, Team:Security-External Integrations

#1656 [cyberark] Update ECS to 1.12
  packages/cyberark/_dev/build/build.yml
  packages/cyberark/changelog.yml
  packages/cyberark/data_stream/corepas/_dev/test/pipeline/test-generated.log-expected.json
  packages/cyberark/data_stream/corepas/elasticsearch/ingest_pipeline/default.yml
  packages/cyberark/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1658 [cylance] Update ECS to 1.12
  packages/cylance/_dev/build/build.yml
  packages/cylance/changelog.yml
  packages/cylance/data_stream/protect/_dev/test/pipeline/test-generated.log-expected.json
  packages/cylance/data_stream/protect/elasticsearch/ingest_pipeline/default.yml
  packages/cylance/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1659 [f5] Update ECS to 1.12
  packages/f5/_dev/build/build.yml
  packages/f5/changelog.yml
  packages/f5/data_stream/bigipafm/_dev/test/pipeline/test-generated.log-expected.json
  packages/f5/data_stream/bigipafm/elasticsearch/ingest_pipeline/default.yml
  packages/f5/data_stream/bigipapm/_dev/test/pipeline/test-generated.log-expected.json
  packages/f5/data_stream/bigipapm/elasticsearch/ingest_pipeline/default.yml
  packages/f5/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1638 [okta] Update ECS to 1.12
  packages/okta/_dev/build/build.yml
  packages/okta/changelog.yml
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
  packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/okta/docs/README.md
  packages/okta/manifest.yml
Labels: enhancement, [zube]: In Review, Team:Security-External Integrations

#1664 [infoblox] Update ECS to 1.12
  packages/infoblox/_dev/build/build.yml
  packages/infoblox/changelog.yml
  packages/infoblox/data_stream/nios/_dev/test/pipeline/test-generated.log-expected.json
  packages/infoblox/data_stream/nios/elasticsearch/ingest_pipeline/default.yml
  packages/infoblox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1665 [iptables] Update ECS to 1.12
  packages/iptables/_dev/build/build.yml
  packages/iptables/changelog.yml
  packages/iptables/data_stream/log/_dev/test/pipeline/test-iptables-raw.log-expected.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-ubiquiti.log-expected.json
  packages/iptables/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/iptables/docs/README.md
  packages/iptables/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1666 [juniper] Update ECS to 1.12
  packages/juniper/_dev/build/build.yml
  packages/juniper/changelog.yml
  packages/juniper/data_stream/junos/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper/data_stream/junos/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/netscreen/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper/data_stream/netscreen/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/srx/fields/ecs.yml
  packages/juniper/docs/README.md
  packages/juniper/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1667 [netflow] Update ECS to 1.12
  packages/netflow/_dev/build/build.yml
  packages/netflow/changelog.yml
  packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
  packages/netflow/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/netflow/data_stream/log/fields/ecs.yml
  packages/netflow/docs/README.md
  packages/netflow/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1668 [netscout] Update ECS to 1.12
  packages/netscout/_dev/build/build.yml
  packages/netscout/changelog.yml
  packages/netscout/data_stream/sightline/_dev/test/pipeline/test-generated.log-expected.json
  packages/netscout/data_stream/sightline/elasticsearch/ingest_pipeline/default.yml
  packages/netscout/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1673 [panw_cortex_xdr] Update ECS to 1.12
  packages/panw_cortex_xdr/_dev/build/build.yml
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/docs/README.md
  packages/panw_cortex_xdr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1674 [proofpoint] Update ECS to 1.12
  packages/proofpoint/_dev/build/build.yml
  packages/proofpoint/changelog.yml
  packages/proofpoint/data_stream/emailsecurity/_dev/test/pipeline/test-generated.log-expected.json
  packages/proofpoint/data_stream/emailsecurity/elasticsearch/ingest_pipeline/default.yml
  packages/proofpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1675 [radware] Update ECS to 1.12
  packages/radware/_dev/build/build.yml
  packages/radware/changelog.yml
  packages/radware/data_stream/defensepro/elasticsearch/ingest_pipeline/default.yml
  packages/radware/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1676 [santa] Update ECS to 1.12
  packages/santa/_dev/build/build.yml
  packages/santa/changelog.yml
  packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
  packages/santa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/santa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1677 [sonicwall] Update ECS to 1.12
  packages/sonicwall/_dev/build/build.yml
  packages/sonicwall/changelog.yml
  packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-general.log-expected.json
  packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-generated.log-expected.json
  packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/sonicwall/docs/README.md
  packages/sonicwall/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1679 [squid] Update ECS to 1.12
  packages/squid/_dev/build/build.yml
  packages/squid/changelog.yml
  packages/squid/data_stream/log/_dev/test/pipeline/test-access1.log-expected.json
  packages/squid/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/squid/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/squid/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1680 [suricata] Update ECS to 1.12
  packages/suricata/_dev/build/build.yml
  packages/suricata/changelog.yml
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-6-0.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-dns-4-1-4.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-metadata.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/docs/README.md
  packages/suricata/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1683 [zoom] Update ECS to 1.12
  packages/zoom/_dev/build/build.yml
  packages/zoom/changelog.yml
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-account.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-channel.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-message.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-meeting.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-phone.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-recording.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-user.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-webinar.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-zoomroom.json-expected.json
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/default.yml
  packages/zoom/docs/README.md
  packages/zoom/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1684 [zscaler] Update ECS to 1.12
  packages/zscaler/_dev/build/build.yml
  packages/zscaler/changelog.yml
  packages/zscaler/data_stream/zia/_dev/test/pipeline/test-generated.log-expected.json
  packages/zscaler/data_stream/zia/_dev/test/pipeline/test-zscaler.log-expected.json
  packages/zscaler/data_stream/zia/elasticsearch/ingest_pipeline/default.yml
  packages/zscaler/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1661 [gcp] Update ECS to 1.12
  packages/gcp/_dev/build/build.yml
  packages/gcp/changelog.yml
  packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/firewall/_dev/test/pipeline/test-firewall.log-expected.json
  packages/gcp/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-expected.json
  packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/docs/README.md
  packages/gcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1660 [fortinet] Update ECS to 1.12
  packages/fortinet/_dev/build/build.yml
  packages/fortinet/changelog.yml
  packages/fortinet/data_stream/clientendpoint/_dev/test/pipeline/test-generated.log-expected.json
  packages/fortinet/data_stream/clientendpoint/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/firewall/_dev/test/pipeline/test-fortinet.log-expected.json
  packages/fortinet/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimail/_dev/test/pipeline/test-generated.log-expected.json
  packages/fortinet/data_stream/fortimail/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimanager/_dev/test/pipeline/test-generated.log-expected.json
  packages/fortinet/data_stream/fortimanager/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1694 [iis] Update ECS to 1.12
  packages/iis/_dev/build/build.yml
  packages/iis/changelog.yml
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-72.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access-75.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-ipv6zone.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-x-forward-for-extended.log-expected.json
  packages/iis/data_stream/access/_dev/test/pipeline/test-x-forward-for.log-expected.json
  packages/iis/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/iis/data_stream/application_pool/fields/ecs.yml
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error-72.log-expected.json
  packages/iis/data_stream/error/_dev/test/pipeline/test-iis-error.log-expected.json
  packages/iis/data_stream/error/_dev/test/pipeline/test-ipv6-zone-id.log-expected.json
  packages/iis/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/iis/data_stream/webserver/fields/ecs.yml
  packages/iis/data_stream/website/fields/ecs.yml
  packages/iis/docs/README.md
  packages/iis/manifest.yml
Labels: enhancement, Team:Integrations

#1695 [kafka] Update ECS to 1.12
  packages/kafka/_dev/build/build.yml
  packages/kafka/changelog.yml
  packages/kafka/data_stream/broker/fields/ecs.yml
  packages/kafka/data_stream/consumergroup/fields/ecs.yml
  packages/kafka/data_stream/log/_dev/test/pipeline/test-controller-2-0-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-controller.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-server-2-0-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-server.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-1-1-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-2-0-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-2-2-2.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change.log-expected.json
  packages/kafka/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/kafka/data_stream/partition/fields/ecs.yml
  packages/kafka/docs/README.md
  packages/kafka/manifest.yml
Labels: enhancement, Team:Integrations

#1697 [linux] Update ECS to 1.12
  packages/linux/_dev/build/build.yml
  packages/linux/changelog.yml
  packages/linux/data_stream/conntrack/fields/ecs.yml
  packages/linux/data_stream/entropy/fields/ecs.yml
  packages/linux/data_stream/iostat/fields/ecs.yml
  packages/linux/data_stream/ksm/fields/ecs.yml
  packages/linux/data_stream/memory/fields/ecs.yml
  packages/linux/data_stream/network_summary/fields/ecs.yml
  packages/linux/data_stream/pageinfo/fields/ecs.yml
  packages/linux/data_stream/raid/fields/ecs.yml
  packages/linux/data_stream/service/fields/ecs.yml
  packages/linux/data_stream/socket/fields/ecs.yml
  packages/linux/data_stream/users/fields/ecs.yml
  packages/linux/docs/README.md
  packages/linux/manifest.yml
Labels: enhancement, Team:Integrations

#1717 GA gcp integrations
  packages/gcp/changelog.yml
  packages/gcp/data_stream/audit/manifest.yml
  packages/gcp/data_stream/firewall/manifest.yml
  packages/gcp/data_stream/vpcflow/manifest.yml
  packages/gcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1746 [CI] use obltGitHubComments
  .ci/Jenkinsfile
Labels: automation

#1715 Osquery_manager: Update integration manifest to allow free-form osquery configuration, limit to one integration
  packages/osquery_manager/changelog.yml
  packages/osquery_manager/manifest.yml
Labels: enhancement, v7.16.0, Team:Asset Mgt, 7.16 candidate, 7.16-candidate

#1634 [google_workspace] Update ECS to 1.12
  packages/google_workspace/_dev/build/build.yml
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-application.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-calendar.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chat.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chromeos.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-contacts.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-delegatedadmin.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-docs.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-domain.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-gmail.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-groups.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-licenses.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-mobile.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-org.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-security.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-sites.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-user.log-expected.json
  packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/admin/fields/ecs.yml
  packages/google_workspace/data_stream/drive/_dev/test/pipeline/test-drive.log-expected.json
  packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/drive/fields/ecs.yml
  packages/google_workspace/data_stream/groups/_dev/test/pipeline/test-groups.log-expected.json
  packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/login/_dev/test/pipeline/test-login.log-expected.json
  packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/saml/_dev/test/pipeline/test-saml.log-expected.json
  packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/user_accounts/_dev/test/pipeline/test-user-accounts.log-expected.json
  packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/docs/README.md
  packages/google_workspace/manifest.yml
Labels: enhancement, [zube]: In Review, Team:Security-External Integrations

#1698 [mongodb] Update ECS to 1.12
  packages/mongodb/_dev/build/build.yml
  packages/mongodb/changelog.yml
  packages/mongodb/data_stream/collstats/fields/ecs.yml
  packages/mongodb/data_stream/dbstats/fields/ecs.yml
  packages/mongodb/data_stream/log/fields/ecs.yml
  packages/mongodb/data_stream/metrics/fields/ecs.yml
  packages/mongodb/data_stream/replstatus/fields/ecs.yml
  packages/mongodb/data_stream/status/fields/ecs.yml
  packages/mongodb/docs/README.md
  packages/mongodb/manifest.yml
Labels: enhancement, Team:Integrations

#1696 [kubernetes] Update ECS to 1.12
  packages/kubernetes/_dev/build/build.yml
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/apiserver/fields/ecs.yml
  packages/kubernetes/data_stream/container/fields/ecs.yml
  packages/kubernetes/data_stream/controllermanager/fields/ecs.yml
  packages/kubernetes/data_stream/event/fields/ecs.yml
  packages/kubernetes/data_stream/node/fields/ecs.yml
  packages/kubernetes/data_stream/pod/fields/ecs.yml
  packages/kubernetes/data_stream/proxy/fields/ecs.yml
  packages/kubernetes/data_stream/scheduler/fields/ecs.yml
  packages/kubernetes/data_stream/state_container/fields/ecs.yml
  packages/kubernetes/data_stream/state_cronjob/fields/ecs.yml
  packages/kubernetes/data_stream/state_daemonset/fields/ecs.yml
  packages/kubernetes/data_stream/state_deployment/fields/ecs.yml
  packages/kubernetes/data_stream/state_job/fields/ecs.yml
  packages/kubernetes/data_stream/state_node/fields/ecs.yml
  packages/kubernetes/data_stream/state_persistentvolume/fields/ecs.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/fields/ecs.yml
  packages/kubernetes/data_stream/state_pod/fields/ecs.yml
  packages/kubernetes/data_stream/state_replicaset/fields/ecs.yml
  packages/kubernetes/data_stream/state_resourcequota/fields/ecs.yml
  packages/kubernetes/data_stream/state_service/fields/ecs.yml
  packages/kubernetes/data_stream/state_statefulset/fields/ecs.yml
  packages/kubernetes/data_stream/state_storageclass/fields/ecs.yml
  packages/kubernetes/data_stream/system/fields/ecs.yml
  packages/kubernetes/data_stream/volume/fields/ecs.yml
  packages/kubernetes/docs/events.md
  packages/kubernetes/docs/kube-apiserver.md
  packages/kubernetes/docs/kube-controller-manager.md
  packages/kubernetes/docs/kube-proxy.md
  packages/kubernetes/docs/kube-scheduler.md
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/docs/kubelet.md
  packages/kubernetes/manifest.yml
Labels: enhancement, Team:Integrations

#1701 [nginx] Update ECS to 1.12
  packages/nginx/_dev/build/build.yml
  packages/nginx/changelog.yml
  packages/nginx/data_stream/access/_dev/test/pipeline/test-access.log-expected.json
  packages/nginx/data_stream/access/_dev/test/pipeline/test-nginx.log-expected.json
  packages/nginx/data_stream/access/_dev/test/pipeline/test-test-with-host.log-expected.json
  packages/nginx/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/nginx/data_stream/error/_dev/test/pipeline/test-error-raw.log-expected.json
  packages/nginx/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/nginx/data_stream/stubstatus/fields/ecs.yml
  packages/nginx/docs/README.md
  packages/nginx/manifest.yml
Labels: enhancement, Team:Integrations

#1670 [o365] Update ECS to 1.12
  packages/o365/_dev/build/build.yml
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/_dev/test/pipeline/test-azuread-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-azuread-sts-logon-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-data-insights-api-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-dlp-exchange-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-dlp-sharepoint-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-admin-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-item-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-ip-formats-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-ms-teams-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-parameter-string.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sec-comp-alerts-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepoint-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepointfileop-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sp-sharing-op-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-yammer-events.json-expected.json
  packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/o365/docs/README.md
  packages/o365/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1681 [tomcat] Update ECS to 1.12
  packages/tomcat/_dev/build/build.yml
  packages/tomcat/changelog.yml
  packages/tomcat/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/tomcat/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/tomcat/data_stream/log/sample_event.json
  packages/tomcat/docs/README.md
  packages/tomcat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1672 [panw] Update ECS to 1.12
  packages/panw/_dev/build/build.yml
  packages/panw/changelog.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/docs/README.md
  packages/panw/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1662 [hashicorp_vault] Update ECS to 1.12
  packages/hashicorp_vault/_dev/build/build.yml
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-faked-all-fields.log-expected.json
  packages/hashicorp_vault/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/data_stream/audit/sample_event.json
  packages/hashicorp_vault/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/hashicorp_vault/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/data_stream/log/sample_event.json
  packages/hashicorp_vault/data_stream/metrics/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/docs/README.md
  packages/hashicorp_vault/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1655 [crowdstrike] Update ECS to 1.12
  packages/crowdstrike/_dev/build/build.yml
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/data_stream/falcon/sample_event.json
  packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log-expected.json
  packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/data_stream/fdr/fields/ecs.yml
  packages/crowdstrike/data_stream/fdr/fields/fields.yml
  packages/crowdstrike/data_stream/fdr/sample_event.json
  packages/crowdstrike/docs/README.md
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1654 [cloudflare] Update ECS to 1.12
  packages/cloudflare/_dev/build/build.yml
  packages/cloudflare/changelog.yml
  packages/cloudflare/docs/README.md
  packages/cloudflare/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1652 [cef] Update ECS to 1.12
  packages/cef/_dev/build/build.yml
  packages/cef/changelog.yml
  packages/cef/data_stream/log/_dev/test/pipeline/test-cef.log-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-checkpoint.log-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-fp-ngfw-smc.log-expected.json
  packages/cef/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cef/docs/README.md
  packages/cef/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1653 [checkpoint] Update ECS to 1.12
  packages/checkpoint/_dev/build/build.yml
  packages/checkpoint/changelog.yml
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-expected.json
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
  packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/checkpoint/docs/README.md
  packages/checkpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1700 [nats] Update ECS to 1.12
  packages/nats/_dev/build/build.yml
  packages/nats/changelog.yml
  packages/nats/data_stream/connection/fields/ecs.yml
  packages/nats/data_stream/connections/fields/ecs.yml
  packages/nats/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
  packages/nats/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/nats/data_stream/route/fields/ecs.yml
  packages/nats/data_stream/routes/fields/ecs.yml
  packages/nats/data_stream/stats/fields/ecs.yml
  packages/nats/data_stream/subscriptions/fields/ecs.yml
  packages/nats/docs/README.md
  packages/nats/manifest.yml
Labels: enhancement, Team:Integrations

#1699 [mysql] Update ECS to 1.12
  packages/mysql/_dev/build/build.yml
  packages/mysql/changelog.yml
  packages/mysql/data_stream/error/fields/ecs.yml
  packages/mysql/data_stream/galera_status/fields/ecs.yml
  packages/mysql/data_stream/slowlog/fields/ecs.yml
  packages/mysql/data_stream/status/fields/ecs.yml
  packages/mysql/docs/README.md
  packages/mysql/manifest.yml
Labels: enhancement, Team:Integrations

#1686 [apache] Update ECS to 1.12
  packages/apache/_dev/build/build.yml
  packages/apache/changelog.yml
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-basic.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-darwin.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ssl-request.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-ubuntu.log-expected.json
  packages/apache/data_stream/access/_dev/test/pipeline/test-access-vhost.log-expected.json
  packages/apache/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-basic.log-expected.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-darwin.log-expected.json
  packages/apache/data_stream/error/_dev/test/pipeline/test-error-ubuntu.log-expected.json
  packages/apache/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/apache/data_stream/status/fields/ecs.yml
  packages/apache/docs/README.md
  packages/apache/manifest.yml
Labels: enhancement, Team:Integrations

#1678 [sophos] Update ECS to 1.12
  packages/sophos/_dev/build/build.yml
  packages/sophos/changelog.yml
  packages/sophos/data_stream/utm/_dev/test/pipeline/test-generated.log-expected.json
  packages/sophos/data_stream/utm/elasticsearch/ingest_pipeline/default.yml
  packages/sophos/data_stream/utm/fields/ecs.yml
  packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-xg.log-expected.json
  packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
  packages/sophos/data_stream/xg/fields/ecs.yml
  packages/sophos/docs/README.md
  packages/sophos/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1623 Make AWS ga
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/manifest.yml
  packages/aws/data_stream/cloudwatch_logs/manifest.yml
  packages/aws/data_stream/cloudwatch_metrics/manifest.yml
  packages/aws/data_stream/dynamodb/manifest.yml
  packages/aws/data_stream/ebs/manifest.yml
  packages/aws/data_stream/ec2_logs/manifest.yml
  packages/aws/data_stream/ec2_metrics/manifest.yml
  packages/aws/data_stream/elb_logs/manifest.yml
  packages/aws/data_stream/elb_metrics/manifest.yml
  packages/aws/data_stream/lambda/manifest.yml
  packages/aws/data_stream/natgateway/manifest.yml
  packages/aws/data_stream/rds/manifest.yml
  packages/aws/data_stream/s3_daily_storage/manifest.yml
  packages/aws/data_stream/s3_request/manifest.yml
  packages/aws/data_stream/s3access/manifest.yml
  packages/aws/data_stream/sns/manifest.yml
  packages/aws/data_stream/sqs/manifest.yml
  packages/aws/data_stream/transitgateway/manifest.yml
  packages/aws/data_stream/usage/manifest.yml
  packages/aws/data_stream/vpcflow/manifest.yml
  packages/aws/data_stream/vpn/manifest.yml
  packages/aws/manifest.yml
Labels: enhancement, Team:Integrations

#1555 Logstash package
  packages/elasticsearch/data_stream/node_stats/manifest.yml
  packages/logstash/_dev/build/build.yml
  packages/logstash/_dev/build/docs/README.md
  packages/logstash/changelog.yml
  packages/logstash/data_stream/log/agent/stream/log.yml.hbs
  packages/logstash/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/logstash/data_stream/log/elasticsearch/ingest_pipeline/pipeline-json.yml
  packages/logstash/data_stream/log/elasticsearch/ingest_pipeline/pipeline-plaintext.yml
  packages/logstash/data_stream/log/fields/base-fields.yml
  packages/logstash/data_stream/log/fields/ecs.yml
  packages/logstash/data_stream/log/fields/fields.yml
  packages/logstash/data_stream/log/manifest.yml
  packages/logstash/data_stream/node/agent/stream/stream.yml.hbs
  packages/logstash/data_stream/node/fields/base-fields.yml
  packages/logstash/data_stream/node/fields/ecs.yml
  packages/logstash/data_stream/node/fields/fields.yml
  packages/logstash/data_stream/node/fields/package-fields.yml
  packages/logstash/data_stream/node/manifest.yml
  packages/logstash/data_stream/node/sample_event.json
  packages/logstash/data_stream/node_stats/agent/stream/stream.yml.hbs
  packages/logstash/data_stream/node_stats/fields/base-fields.yml
  packages/logstash/data_stream/node_stats/fields/ecs.yml
  packages/logstash/data_stream/node_stats/fields/fields.yml
  packages/logstash/data_stream/node_stats/fields/package-fields.yml
  packages/logstash/data_stream/node_stats/manifest.yml
  packages/logstash/data_stream/node_stats/sample_event.json
  packages/logstash/data_stream/slowlog/agent/stream/log.yml.hbs
  packages/logstash/data_stream/slowlog/elasticsearch/ingest_pipeline/default.yml
  packages/logstash/data_stream/slowlog/elasticsearch/ingest_pipeline/pipeline-json.yml
  packages/logstash/data_stream/slowlog/elasticsearch/ingest_pipeline/pipeline-plaintext.yml
  packages/logstash/data_stream/slowlog/fields/base-fields.yml
  packages/logstash/data_stream/slowlog/fields/ecs.yml
  packages/logstash/data_stream/slowlog/fields/fields.yml
  packages/logstash/data_stream/slowlog/manifest.yml
  packages/logstash/docs/README.md
  packages/logstash/img/kibana-logstash-log.png
  packages/logstash/img/kibana-logstash-slowlog.png
  packages/logstash/img/logo_logstash.svg
  packages/logstash/kibana/dashboard/logstash-Logs-Logstash-Log-Dashboard.json
  packages/logstash/kibana/dashboard/logstash-Logs-Logstash-Slowlog-Dashboard.json
  packages/logstash/kibana/search/logstash-742e45d0-cbdd-11e7-9852-73e0a9df1bb6.json
  packages/logstash/kibana/search/logstash-cfaba090-cbda-11e7-9852-73e0a9df1bb6.json
  packages/logstash/kibana/visualization/logstash-0b1dace0-cbdb-11e7-9852-73e0a9df1bb6.json
  packages/logstash/kibana/visualization/logstash-b3315630-cbdf-11e7-9852-73e0a9df1bb6.json
  packages/logstash/kibana/visualization/logstash-e90b7240-cbda-11e7-9852-73e0a9df1bb6.json
  packages/logstash/manifest.yml
Labels: enhancement, Team:Integrations, Team:Services

#1755 [winlog] Fix example processors config
  packages/winlog/changelog.yml
  packages/winlog/data_stream/winlog/manifest.yml
  packages/winlog/manifest.yml
Labels: bug, Team:Security-External Integrations

#1753 Zoom: Release version 1.0.0 as GA
  packages/zoom/changelog.yml
  packages/zoom/data_stream/webhook/manifest.yml
  packages/zoom/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1519 Kibana Package
  packages/kibana/_dev/build/build.yml
  packages/kibana/_dev/build/docs/README.md
  packages/kibana/changelog.yml
  packages/kibana/data_stream/audit/agent/stream/log.yml.hbs
  packages/kibana/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/kibana/data_stream/audit/elasticsearch/ingest_pipeline/pipeline-json.yml
  packages/kibana/data_stream/audit/fields/base-fields.yml
  packages/kibana/data_stream/audit/fields/ecs.yml
  packages/kibana/data_stream/audit/fields/package-fields.yml
  packages/kibana/data_stream/audit/manifest.yml
  packages/kibana/data_stream/log/agent/stream/log.yml.hbs
  packages/kibana/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/kibana/data_stream/log/fields/base-fields.yml
  packages/kibana/data_stream/log/fields/ecs.yml
  packages/kibana/data_stream/log/fields/fields.yml
  packages/kibana/data_stream/log/fields/package-fields.yml
  packages/kibana/data_stream/log/manifest.yml
  packages/kibana/data_stream/stats/agent/stream/stream.yml.hbs
  packages/kibana/data_stream/stats/fields/base-fields.yml
  packages/kibana/data_stream/stats/fields/ecs.yml
  packages/kibana/data_stream/stats/fields/fields.yml
  packages/kibana/data_stream/stats/fields/package-fields.yml
  packages/kibana/data_stream/stats/manifest.yml
  packages/kibana/data_stream/stats/sample_event.json
  packages/kibana/data_stream/status/agent/stream/stream.yml.hbs
  packages/kibana/data_stream/status/fields/base-fields.yml
  packages/kibana/data_stream/status/fields/ecs.yml
  packages/kibana/data_stream/status/fields/fields.yml
  packages/kibana/data_stream/status/fields/package-fields.yml
  packages/kibana/data_stream/status/manifest.yml
  packages/kibana/data_stream/status/sample_event.json
  packages/kibana/docs/README.md
  packages/kibana/img/logo_kibana.svg
  packages/kibana/manifest.yml
Labels: enhancement, Team:Integrations, Team:Services

#1764 [network_traffic] Set title to Network Packet Capture
  packages/network_traffic/_dev/build/docs/README.md
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/flow/agent/stream/flow.yml.hbs
  packages/network_traffic/data_stream/flow/manifest.yml
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1723 [cef] Add time zone config option
  packages/cef/changelog.yml
  packages/cef/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cef/data_stream/log/agent/stream/log.yml.hbs
  packages/cef/data_stream/log/agent/stream/udp.yml.hbs
  packages/cef/data_stream/log/manifest.yml
  packages/cef/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:CEF

#1630 GA crowdstrike integration
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/falcon/manifest.yml
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1628 GA Cloudflare integration
  packages/cloudflare/changelog.yml
  packages/cloudflare/data_stream/logpull/manifest.yml
  packages/cloudflare/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1756 Osquery_manager: Upgrade schema and readme to match osquery 5.0.1
  packages/osquery_manager/changelog.yml
  packages/osquery_manager/data_stream/result/fields/osquery.yml
  packages/osquery_manager/docs/README.md
  packages/osquery_manager/manifest.yml
Labels: enhancement, v7.16.0, Team:Asset Mgt, 7.16 candidate, 7.16-candidate

#1706 [rabbitmq] Update ECS to 1.12
  packages/rabbitmq/_dev/build/build.yml
  packages/rabbitmq/changelog.yml
  packages/rabbitmq/data_stream/connection/fields/ecs.yml
  packages/rabbitmq/data_stream/exchange/fields/ecs.yml
  packages/rabbitmq/data_stream/log/_dev/test/pipeline/test-rabbitmq.log-expected.json
  packages/rabbitmq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/rabbitmq/data_stream/node/fields/ecs.yml
  packages/rabbitmq/data_stream/queue/fields/ecs.yml
  packages/rabbitmq/docs/README.md
  packages/rabbitmq/manifest.yml
Labels: enhancement, Team:Integrations

#1705 [prometheus] Update ECS to 1.12
  packages/prometheus/_dev/build/build.yml
  packages/prometheus/changelog.yml
  packages/prometheus/data_stream/collector/fields/ecs.yml
  packages/prometheus/data_stream/query/fields/ecs.yml
  packages/prometheus/data_stream/remote_write/fields/ecs.yml
  packages/prometheus/docs/README.md
  packages/prometheus/manifest.yml
Labels: enhancement, Team:Integrations

#1704 [postgresql] Update ECS to 1.12
  packages/postgresql/_dev/build/build.yml
  packages/postgresql/changelog.yml
  packages/postgresql/data_stream/activity/fields/ecs.yml
  packages/postgresql/data_stream/bgwriter/fields/ecs.yml
  packages/postgresql/data_stream/database/fields/ecs.yml
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-10-default.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-10-min-duration-statement.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-4.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-autovacuum-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-connection-disconnection-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-duration-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-ipv6-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-multi-line-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-parse-bind-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-start-stop-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-tempfile-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-12-default.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-12-min-duration-statement.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-13-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-13-error-code-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-debian-with-slowlog.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-multi-core.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-new-timestamp.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-query-steps-slowlog.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-ubuntu-9-5.log-expected.json
  packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/postgresql/data_stream/statement/fields/ecs.yml
  packages/postgresql/docs/README.md
  packages/postgresql/manifest.yml
Labels: enhancement, Team:Integrations

#1702 [nginx_ingress_controller] Update ECS to 1.12
  packages/nginx_ingress_controller/_dev/build/build.yml
  packages/nginx_ingress_controller/changelog.yml
  packages/nginx_ingress_controller/data_stream/access/_dev/test/pipeline/test-ingest-raw.log-expected.json
  packages/nginx_ingress_controller/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/nginx_ingress_controller/data_stream/access/fields/ecs.yml
  packages/nginx_ingress_controller/data_stream/error/_dev/test/pipeline/test-error-raw.log-expected.json
  packages/nginx_ingress_controller/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/nginx_ingress_controller/docs/README.md
  packages/nginx_ingress_controller/manifest.yml
Labels: enhancement, Team:Integrations

#1693 [haproxy] Update ECS to 1.12
  packages/haproxy/_dev/build/build.yml
  packages/haproxy/changelog.yml
  packages/haproxy/data_stream/info/fields/ecs.yml
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-default.log-expected.json
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-haproxy.log-expected.json
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-httplog-no-headers.log-expected.json
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-tcplog.log-expected.json
  packages/haproxy/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/haproxy/data_stream/stat/fields/ecs.yml
  packages/haproxy/docs/README.md
  packages/haproxy/manifest.yml
Labels: enhancement, Team:Integrations

#1692 [elasticsearch] Update ECS to 1.12
  packages/elasticsearch/_dev/build/build.yml
  packages/elasticsearch/changelog.yml
  packages/elasticsearch/data_stream/audit/fields/ecs.yml
  packages/elasticsearch/data_stream/ccr/fields/ecs.yml
  packages/elasticsearch/docs/README.md
  packages/elasticsearch/manifest.yml
Labels: enhancement, Team:Integrations

#1691 [docker] Update ECS to 1.12
  packages/docker/_dev/build/build.yml
  packages/docker/changelog.yml
  packages/docker/data_stream/container/fields/ecs.yml
  packages/docker/data_stream/cpu/fields/ecs.yml
  packages/docker/data_stream/diskio/fields/ecs.yml
  packages/docker/data_stream/event/fields/ecs.yml
  packages/docker/data_stream/healthcheck/fields/ecs.yml
  packages/docker/data_stream/image/fields/ecs.yml
  packages/docker/data_stream/info/fields/ecs.yml
  packages/docker/data_stream/memory/fields/ecs.yml
  packages/docker/data_stream/network/fields/ecs.yml
  packages/docker/docs/README.md
  packages/docker/manifest.yml
Labels: enhancement, Team:Integrations

#1712 [zookeeper] Update ECS to 1.12
  packages/zookeeper/_dev/build/build.yml
  packages/zookeeper/changelog.yml
  packages/zookeeper/data_stream/connection/fields/ecs.yml
  packages/zookeeper/data_stream/mntr/fields/ecs.yml
  packages/zookeeper/data_stream/server/fields/ecs.yml
  packages/zookeeper/docs/README.md
  packages/zookeeper/manifest.yml
Labels: enhancement, Team:Integrations

#1710 [traefik] Update ECS to 1.12
  packages/traefik/_dev/build/build.yml
  packages/traefik/changelog.yml
  packages/traefik/data_stream/access/_dev/test/pipeline/test-format-common.log-expected.json
  packages/traefik/data_stream/access/_dev/test/pipeline/test-format-json.log-expected.json
  packages/traefik/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/traefik/data_stream/health/fields/ecs.yml
  packages/traefik/docs/README.md
  packages/traefik/manifest.yml
Labels: enhancement, Team:Integrations

#1690 [azure_metrics] Update ECS to 1.12
  packages/azure_metrics/_dev/build/build.yml
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/manifest.yml
Labels: enhancement, Team:Integrations

#1689 [azure_application_insights] Update ECS to 1.12
  packages/azure_application_insights/_dev/build/build.yml
  packages/azure_application_insights/changelog.yml
  packages/azure_application_insights/data_stream/app_insights/sample_event.json
  packages/azure_application_insights/data_stream/app_state/sample_event.json
  packages/azure_application_insights/docs/README.md
  packages/azure_application_insights/docs/app_insights.md
  packages/azure_application_insights/manifest.yml
Labels: enhancement, Team:Integrations

#1688 [azure] Update ECS to 1.12
  packages/azure/_dev/build/build.yml
  packages/azure/changelog.yml
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-edgecases.log-expected.json
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
  packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-expected.json
  packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-kube.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-remote-raw.log-expected.json
  packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
  packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/docs/README.md
  packages/azure/docs/activitylogs.md
  packages/azure/docs/adlogs.md
  packages/azure/docs/platformlogs.md
  packages/azure/docs/springcloudlogs.md
  packages/azure/manifest.yml
Labels: enhancement, Team:Integrations

#1765 GA Microsoft Defender integration
  packages/microsoft/_dev/deploy/docker/docker-compose.yml
  packages/microsoft/_dev/deploy/docker/http-mock-config.yml
  packages/microsoft/changelog.yml
  packages/microsoft/data_stream/defender_atp/_dev/test/system/test-httpjson-config.yml
  packages/microsoft/data_stream/defender_atp/agent/stream/httpjson.yml.hbs
  packages/microsoft/data_stream/defender_atp/fields/fields.yml
  packages/microsoft/data_stream/defender_atp/manifest.yml
  packages/microsoft/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1772 sync aws vpcflow data_set with filebeat fileset
  packages/aws/changelog.yml
  packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-extra-samples.log-expected.json
  packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-tcp-flag-sequence.log-expected.json
  packages/aws/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/vpcflow/fields/ecs.yml
  packages/aws/data_stream/vpcflow/fields/fields.yml
  packages/aws/docs/vpcflow.md
  packages/aws/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1758 osquery: GA package as version 1.0.0
  packages/osquery/changelog.yml
  packages/osquery/data_stream/result/manifest.yml
  packages/osquery/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1757 Zerofox: Release version 1.0.0 as GA
  packages/zerofox/_dev/deploy/docker/docker-compose.yml
  packages/zerofox/_dev/deploy/docker/files/config.yml
  packages/zerofox/changelog.yml
  packages/zerofox/data_stream/alerts/_dev/test/system/test-default-config.yml
  packages/zerofox/data_stream/alerts/fields/beats.yml
  packages/zerofox/data_stream/alerts/manifest.yml
  packages/zerofox/docs/README.md
  packages/zerofox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1775 ga sophos xg
  packages/sophos/changelog.yml
  packages/sophos/data_stream/xg/fields/fields.yml
  packages/sophos/data_stream/xg/manifest.yml
  packages/sophos/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1774 ga juniper integration
  packages/juniper/changelog.yml
  packages/juniper/data_stream/srx/fields/fields.yml
  packages/juniper/data_stream/srx/manifest.yml
  packages/juniper/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#1718 [santa] ga santa integration
  packages/santa/changelog.yml
  packages/santa/data_stream/log/manifest.yml
  packages/santa/manifest.yml
Labels: enhancement, Team:Security-External Integrations
