Repository elastic/integrations, pull requests merged in 2021-12, with the labels that each got.

#2226 [osquery] Add 8.0.0 constraint
  packages/osquery/changelog.yml
  packages/osquery/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2228 [cylance] Add 8.0.0 constraint
  packages/cylance/changelog.yml
  packages/cylance/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2216 [cef] Add 8.0.0 constraint
  packages/cef/_dev/deploy/docker/sample_logs/cef.log
  packages/cef/_dev/deploy/docker/sample_logs/checkpoint.log
  packages/cef/_dev/deploy/docker/sample_logs/forcepoint-ngfw-smc.log
  packages/cef/changelog.yml
  packages/cef/data_stream/log/_dev/test/pipeline/test-cef.log
  packages/cef/data_stream/log/_dev/test/pipeline/test-cef.log-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-checkpoint.log
  packages/cef/data_stream/log/_dev/test/pipeline/test-checkpoint.log-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-fp-ngfw-smc.log
  packages/cef/data_stream/log/_dev/test/pipeline/test-fp-ngfw-smc.log-expected.json
  packages/cef/data_stream/log/sample_event.json
  packages/cef/docs/README.md
  packages/cef/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2225 [fireeye] Add 8.0.0 constraint
  packages/fireeye/changelog.yml
  packages/fireeye/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2230 [zerofox] Add 8.0.0 constraint
  packages/zerofox/changelog.yml
  packages/zerofox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2231 [checkpoint] Add 8.0.0 constraint
  packages/checkpoint/changelog.yml
  packages/checkpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2232 [carbonblack_edr] Add 8.0.0 constraint
  packages/carbonblack_edr/changelog.yml
  packages/carbonblack_edr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2234 [microsoft_defender_endpoint] Add 8.0.0 constraint
  packages/microsoft_defender_endpoint/changelog.yml
  packages/microsoft_defender_endpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2235 [tomcat] Add 8.0.0 constraint
  packages/tomcat/changelog.yml
  packages/tomcat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2236 [cisco_asa] Add 8.0.0 constraint
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2238 [hashicorp_vault] Add 8.0.0 constraint
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2239 [squid] Add 8.0.0 constraint
  packages/squid/changelog.yml
  packages/squid/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2240 [f5] Add 8.0.0 constraint
  packages/f5/changelog.yml
  packages/f5/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2241 [proofpoint] Add 8.0.0 constraint
  packages/proofpoint/changelog.yml
  packages/proofpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2243 [cloudflare] Add 8.0.0 constraint
  packages/cloudflare/changelog.yml
  packages/cloudflare/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2244 [suricata] Add 8.0.0 constraint
  packages/suricata/changelog.yml
  packages/suricata/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2246 [netscout] Add 8.0.0 constraint
  packages/netscout/changelog.yml
  packages/netscout/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2247 [bluecoat] Add 8.0.0 constraint
  packages/bluecoat/changelog.yml
  packages/bluecoat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2291 [mergify] use merge queue
  .mergify.yml
Labels: Team:Automation, automation

#2248 [sonicwall] Add 8.0.0 constraint
  packages/sonicwall/changelog.yml
  packages/sonicwall/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2249 [cisco_duo] Add 8.0.0 constraint
  packages/cisco_duo/changelog.yml
  packages/cisco_duo/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2250 [cisco_nexus] Add 8.0.0 constraint
  packages/cisco_nexus/changelog.yml
  packages/cisco_nexus/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2251 [gcp] Add 8.0.0 constraint
  packages/gcp/changelog.yml
  packages/gcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2252 [o365] Add 8.0.0 constraint
  packages/o365/changelog.yml
  packages/o365/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2253 [cisco_secure_endpoint] Add 8.0.0 constraint
  packages/cisco_secure_endpoint/changelog.yml
  packages/cisco_secure_endpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2254 [radware] Add 8.0.0 constraint
  packages/radware/changelog.yml
  packages/radware/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2256 [google_workspace] Add 8.0.0 constraint
  packages/google_workspace/changelog.yml
  packages/google_workspace/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2257 [pfsense] Add 8.0.0 constraint
  packages/pfsense/changelog.yml
  packages/pfsense/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2258 [cisco_ftd] Add 8.0.0 constraint
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2260 [santa] Add 8.0.0 constraint
  packages/santa/changelog.yml
  packages/santa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2261 [snort] Add 8.0.0 constraint
  packages/snort/changelog.yml
  packages/snort/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2262 [infoblox] Add 8.0.0 constraint
  packages/infoblox/changelog.yml
  packages/infoblox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2263 [zeek] Add 8.0.0 constraint
  packages/zeek/changelog.yml
  packages/zeek/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2264 [okta] Add 8.0.0 constraint
  packages/okta/changelog.yml
  packages/okta/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2266 [zoom] Add 8.0.0 constraint
  packages/zoom/changelog.yml
  packages/zoom/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2268 [winlog] Add 8.0.0 constraint
  packages/winlog/changelog.yml
  packages/winlog/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2269 [cisco_umbrella] Add 8.0.0 constraint
  packages/cisco_umbrella/changelog.yml
  packages/cisco_umbrella/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2270 [cisco_meraki] Add 8.0.0 constraint
  packages/cisco_meraki/changelog.yml
  packages/cisco_meraki/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2271 [sophos] Add 8.0.0 constraint
  packages/sophos/changelog.yml
  packages/sophos/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2272 [iptables] Add 8.0.0 constraint
  packages/iptables/changelog.yml
  packages/iptables/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2273 [keycloak] Add 8.0.0 constraint
  packages/keycloak/changelog.yml
  packages/keycloak/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2274 [imperva] Add 8.0.0 constraint
  packages/imperva/changelog.yml
  packages/imperva/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2276 [microsoft_dhcp] Add 8.0.0 constraint
  packages/microsoft_dhcp/changelog.yml
  packages/microsoft_dhcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2277 [fortinet] Add 8.0.0 constraint
  packages/fortinet/changelog.yml
  packages/fortinet/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2279 [cisco_ios] Add 8.0.0 constraint
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2161 [Uptime] Add fields for browser throttling
  packages/synthetics/changelog.yml
  packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
  packages/synthetics/data_stream/browser/manifest.yml
  packages/synthetics/manifest.yml
Labels: enhancement, Team:Uptime

#2215 [auditd] Add 8.0.0 constraint
  packages/auditd/_dev/deploy/docker/sample_logs/audit.log
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
  packages/auditd/data_stream/log/sample_event.json
  packages/auditd/docs/README.md
  packages/auditd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2229 [crowdstrike] Add 8.0.0 constraint
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2290 [Synthetics] add synthetics enabled key
  packages/synthetics/changelog.yml
  packages/synthetics/data_stream/browser/agent/stream/browser.yml.hbs
  packages/synthetics/data_stream/browser/manifest.yml
  packages/synthetics/data_stream/http/agent/stream/http.yml.hbs
  packages/synthetics/data_stream/http/manifest.yml
  packages/synthetics/data_stream/icmp/agent/stream/icmp.yml.hbs
  packages/synthetics/data_stream/icmp/manifest.yml
  packages/synthetics/data_stream/tcp/agent/stream/tcp.yml.hbs
  packages/synthetics/data_stream/tcp/manifest.yml
  packages/synthetics/manifest.yml
Labels: enhancement, Team:Uptime, v8.0.0

#2210 [Juniper] Deprecate package in favor of more specific packages
  packages/juniper/changelog.yml
  packages/juniper/data_stream/junos/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper/data_stream/junos/sample_event.json
  packages/juniper/data_stream/netscreen/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper/data_stream/netscreen/sample_event.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper/data_stream/srx/sample_event.json
  packages/juniper/manifest.yml
  packages/juniper_srx/_dev/deploy/docker/sample_logs/juniper-srx.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-atp.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-flow.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-idp.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-ids.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-secintel.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-utm.log
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper_srx/data_stream/log/sample_event.json
Labels: Team:Security-External Integrations

#2167 Add etcd package
  packages/etcd/_dev/build/build.yml
  packages/etcd/_dev/build/docs/README.md
  packages/etcd/_dev/deploy/docker/Dockerfile
  packages/etcd/_dev/deploy/docker/docker-compose.yml
  packages/etcd/_dev/deploy/variants.yml
  packages/etcd/changelog.yml
  packages/etcd/data_stream/leader/agent/stream/stream.yml.hbs
  packages/etcd/data_stream/leader/fields/base-fields.yml
  packages/etcd/data_stream/leader/fields/ecs.yml
  packages/etcd/data_stream/leader/fields/fields.yml
  packages/etcd/data_stream/leader/fields/package-fields.yml
  packages/etcd/data_stream/leader/manifest.yml
  packages/etcd/data_stream/leader/sample_event.json
  packages/etcd/data_stream/metrics/_dev/test/system/test-default-config.yml
  packages/etcd/data_stream/metrics/agent/stream/stream.yml.hbs
  packages/etcd/data_stream/metrics/fields/base-fields.yml
  packages/etcd/data_stream/metrics/fields/ecs.yml
  packages/etcd/data_stream/metrics/fields/fields.yml
  packages/etcd/data_stream/metrics/fields/package-fields.yml
  packages/etcd/data_stream/metrics/manifest.yml
  packages/etcd/data_stream/metrics/sample_event.json
  packages/etcd/data_stream/self/agent/stream/stream.yml.hbs
  packages/etcd/data_stream/self/elasticsearch/ingest_pipeline/default.yml
  packages/etcd/data_stream/self/fields/base-fields.yml
  packages/etcd/data_stream/self/fields/ecs.yml
  packages/etcd/data_stream/self/fields/fields.yml
  packages/etcd/data_stream/self/fields/package-fields.yml
  packages/etcd/data_stream/self/manifest.yml
  packages/etcd/data_stream/self/sample_event.json
  packages/etcd/data_stream/store/agent/stream/stream.yml.hbs
  packages/etcd/data_stream/store/elasticsearch/ingest_pipeline/default.yml
  packages/etcd/data_stream/store/fields/base-fields.yml
  packages/etcd/data_stream/store/fields/ecs.yml
  packages/etcd/data_stream/store/fields/fields.yml
  packages/etcd/data_stream/store/fields/package-fields.yml
  packages/etcd/data_stream/store/manifest.yml
  packages/etcd/data_stream/store/sample_event.json
  packages/etcd/docs/README.md
  packages/etcd/img/etcd.svg
  packages/etcd/manifest.yml
Labels: Integration:Etcd

#2299 [aws] Add max_number_of_messages to AWS integration config
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/cloudtrail/manifest.yml
  packages/aws/data_stream/cloudwatch_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/cloudwatch_logs/manifest.yml
  packages/aws/data_stream/ec2_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/ec2_logs/manifest.yml
  packages/aws/data_stream/elb_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/elb_logs/manifest.yml
  packages/aws/data_stream/s3access/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/s3access/manifest.yml
  packages/aws/data_stream/vpcflow/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/vpcflow/manifest.yml
  packages/aws/data_stream/waf/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/waf/manifest.yml
  packages/aws/manifest.yml
Labels: enhancement, Team:Integrations, Team:Security-External Integrations, Integration:AWS

#2293 [AbuseCH] Adds new ECS fields
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malware/fields/base-fields.yml
  packages/ti_abusech/data_stream/malware/sample_event.json
  packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malwarebazaar/fields/base-fields.yml
  packages/ti_abusech/data_stream/malwarebazaar/sample_event.json
  packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
  packages/ti_abusech/data_stream/url/fields/base-fields.yml
  packages/ti_abusech/data_stream/url/sample_event.json
  packages/ti_abusech/docs/README.md
  packages/ti_abusech/manifest.yml
Labels: Team:Security-External Integrations

#2292 [Anomali] Add dashboard and pipeline changes
  packages/ti_anomali/_dev/deploy/docker/sample_logs/test-threatstream-ndjson.log
  packages/ti_anomali/changelog.yml
  packages/ti_anomali/data_stream/limo/_dev/test/pipeline/test-anomali-limo-ndjson.log-expected.json
  packages/ti_anomali/data_stream/limo/elasticsearch/ingest_pipeline/default.yml
  packages/ti_anomali/data_stream/limo/fields/base-fields.yml
  packages/ti_anomali/data_stream/limo/sample_event.json
  packages/ti_anomali/data_stream/threatstream/_dev/test/pipeline/test-anomali-threatstream.json
  packages/ti_anomali/data_stream/threatstream/_dev/test/pipeline/test-anomali-threatstream.json-expected.json
  packages/ti_anomali/data_stream/threatstream/fields/base-fields.yml
  packages/ti_anomali/data_stream/threatstream/sample_event.json
  packages/ti_anomali/docs/README.md
  packages/ti_anomali/kibana/dashboard/ti_anomali-207f3c40-45fb-11ec-ab0c-d7f52dcaa020.json
  packages/ti_anomali/kibana/dashboard/ti_anomali-39699a60-45fc-11ec-ab0c-d7f52dcaa020.json
  packages/ti_anomali/kibana/dashboard/ti_anomali-78e08d20-45fc-11ec-ab0c-d7f52dcaa020.json
  packages/ti_anomali/kibana/dashboard/ti_anomali-96fe1e60-4261-11ec-b7be-d3026acdf1cf.json
  packages/ti_anomali/kibana/tag/ti_anomali-94419670-4261-11ec-b7be-d3026acdf1cf.json
  packages/ti_anomali/kibana/tag/ti_anomali-ti_abusech-320c5c80-3b0c-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_anomali/manifest.yml
Labels: Team:Security-External Integrations

#1998 Add Pulse Connect Secure
  packages/pulse_connect_secure/_dev/build/build.yml
  packages/pulse_connect_secure/_dev/build/docs/README.md
  packages/pulse_connect_secure/_dev/deploy/docker/docker-compose.yml
  packages/pulse_connect_secure/_dev/deploy/docker/sample_logs/test-syslog.log
  packages/pulse_connect_secure/changelog.yml
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-admin.log
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-admin.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-system.log
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-system.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-vpn.log
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-vpn.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/pulse_connect_secure/data_stream/log/_dev/test/system/test-tls-config.yml
  packages/pulse_connect_secure/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/pulse_connect_secure/data_stream/log/agent/stream/tcp.yml.hbs
  packages/pulse_connect_secure/data_stream/log/agent/stream/udp.yml.hbs
  packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/pulse_connect_secure/data_stream/log/fields/agent.yml
  packages/pulse_connect_secure/data_stream/log/fields/base-fields.yml
  packages/pulse_connect_secure/data_stream/log/fields/ecs.yml
  packages/pulse_connect_secure/data_stream/log/fields/fields.yml
  packages/pulse_connect_secure/data_stream/log/manifest.yml
  packages/pulse_connect_secure/data_stream/log/sample_event.json
  packages/pulse_connect_secure/docs/README.md
  packages/pulse_connect_secure/img/pulse_connect_secure.svg
  packages/pulse_connect_secure/manifest.yml
Labels: Team:Security-External Integrations

#2289 Mimecast | Changing dashboards, adding logo, renaming integration and release
  packages/mimecast/_dev/build/docs/README.md
  packages/mimecast/changelog.yml
  packages/mimecast/data_stream/siem_logs/_dev/test/pipeline/test-siem-logs.log
  packages/mimecast/data_stream/siem_logs/_dev/test/pipeline/test-siem-logs.log-expected.json
  packages/mimecast/data_stream/siem_logs/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/siem_logs/fields/field.yml
  packages/mimecast/docs/README.md
  packages/mimecast/img/mimecast.png
  packages/mimecast/img/mimecast.svg
  packages/mimecast/kibana/dashboard/mimecast-042d5620-5411-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-061eb320-3e4a-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/dashboard/mimecast-0ebd21e0-5422-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-13366440-3e45-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/dashboard/mimecast-1a4e8460-3fd5-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/dashboard/mimecast-1d771e30-3f1d-11ec-9edf-13c963822dec.json
  packages/mimecast/kibana/dashboard/mimecast-222caa50-3e49-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/dashboard/mimecast-2c81bc30-3e48-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/dashboard/mimecast-44778db0-3e34-11ec-a4d8-6b18148fbf3a.json
  packages/mimecast/kibana/dashboard/mimecast-4f4f23d0-3fe5-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/dashboard/mimecast-50bfa050-4080-11ec-b8da-95c3fba730d0.json
  packages/mimecast/kibana/dashboard/mimecast-53cd8660-3fed-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/dashboard/mimecast-57b10a70-3e32-11ec-a4d8-6b18148fbf3a.json
  packages/mimecast/kibana/dashboard/mimecast-68b50ce0-3f1d-11ec-9edf-13c963822dec.json
  packages/mimecast/kibana/dashboard/mimecast-68d3cfa0-3e45-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/dashboard/mimecast-6c61f080-541f-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-7790e470-541a-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-87fba310-5413-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-88cbbc00-3fd5-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/dashboard/mimecast-a2f56a50-3e49-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/dashboard/mimecast-a36ff3a0-3f1c-11ec-9edf-13c963822dec.json
  packages/mimecast/kibana/dashboard/mimecast-adefc320-3fd8-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/dashboard/mimecast-b4585cb0-541c-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-b8e38930-3fdb-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/dashboard/mimecast-bca36430-540f-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-be142f50-3fe4-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/dashboard/mimecast-c06de870-4081-11ec-b8da-95c3fba730d0.json
  packages/mimecast/kibana/dashboard/mimecast-c9649870-3e33-11ec-a4d8-6b18148fbf3a.json
  packages/mimecast/kibana/dashboard/mimecast-cd32b740-407f-11ec-b8da-95c3fba730d0.json
  packages/mimecast/kibana/dashboard/mimecast-ced41610-3f1d-11ec-9edf-13c963822dec.json
  packages/mimecast/kibana/dashboard/mimecast-f22e62f0-5417-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/dashboard/mimecast-f5a92540-3e33-11ec-a4d8-6b18148fbf3a.json
  packages/mimecast/kibana/dashboard/mimecast-f7faa440-4081-11ec-b8da-95c3fba730d0.json
  packages/mimecast/kibana/dashboard/mimecast-f8933590-541b-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/lens/mimecast-09cd47c0-3e40-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/lens/mimecast-47017670-3e40-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/lens/mimecast-86374180-3e40-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/lens/mimecast-8f37e6f0-3e3f-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/lens/mimecast-b06b3340-3e3f-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/search/mimecast-0d8b0660-3fdd-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/kibana/search/mimecast-96ac7780-541e-11ec-bd43-b5e1f9a9c8d5.json
  packages/mimecast/kibana/search/mimecast-9749a210-3e4a-11ec-80fa-4dfb04910642.json
  packages/mimecast/kibana/search/mimecast-bfb8e8f0-4084-11ec-b8da-95c3fba730d0.json
  packages/mimecast/kibana/search/mimecast-df42cb00-4084-11ec-b8da-95c3fba730d0.json
  packages/mimecast/kibana/search/mimecast-eb3179f0-51ed-11ec-a4ca-b3a74c021655.json
  packages/mimecast/kibana/search/mimecast-fa36c5f0-3fef-11ec-8ace-9fcc35bfe253.json
  packages/mimecast/manifest.yml
Labels: Team:Security-External Integrations

#2325 [aws] Fix event.created in CloudTrail data stream
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-add-user-to-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-assume-role-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-change-password-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-cloudtrail-digest-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-common-config.yml
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-console-login-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-key-pair-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-virtual-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-deactivate-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-bucket-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-virtual-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-enable-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-insight-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-remove-user-from-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-start-logging-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-stop-logging-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-accout-password-policy-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-login-profile-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-user-json.log
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-upload-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
  packages/aws/manifest.yml
Labels: bug, Team:Integrations, Team:Security-External Integrations, Integration:AWS

#2326 [journald] Update package description
  packages/journald/changelog.yml
  packages/journald/manifest.yml
Labels: Team:Security-External Integrations, Integration:journald

#2330 [Anomali] Fixing typos in base-fields.yml
  packages/ti_anomali/changelog.yml
  packages/ti_anomali/data_stream/limo/_dev/test/pipeline/test-anomali-limo-ndjson.log-expected.json
  packages/ti_anomali/data_stream/limo/fields/base-fields.yml
  packages/ti_anomali/data_stream/limo/sample_event.json
  packages/ti_anomali/data_stream/threatstream/_dev/test/pipeline/test-anomali-threatstream.json-expected.json
  packages/ti_anomali/data_stream/threatstream/fields/base-fields.yml
  packages/ti_anomali/data_stream/threatstream/sample_event.json
  packages/ti_anomali/docs/README.md
  packages/ti_anomali/manifest.yml
Labels: Team:Security-External Integrations

#2331 [AbuseCH] Update typo on base-fields.yml
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malware/fields/base-fields.yml
  packages/ti_abusech/data_stream/malware/sample_event.json
  packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malwarebazaar/fields/base-fields.yml
  packages/ti_abusech/data_stream/malwarebazaar/sample_event.json
  packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
  packages/ti_abusech/data_stream/url/fields/base-fields.yml
  packages/ti_abusech/data_stream/url/sample_event.json
  packages/ti_abusech/docs/README.md
  packages/ti_abusech/manifest.yml
Labels: Team:Security-External Integrations

#2199 AWS Network Firewall integration
  packages/aws/_dev/build/docs/firewall.md
  packages/aws/changelog.yml
  packages/aws/data_stream/firewall_logs/_dev/test/pipeline/test-common-config.yml
  packages/aws/data_stream/firewall_logs/_dev/test/pipeline/test-firewall.log
  packages/aws/data_stream/firewall_logs/_dev/test/pipeline/test-firewall.log-expected.json
  packages/aws/data_stream/firewall_logs/agent/stream/aws-s3.yml.hbs
  packages/aws/data_stream/firewall_logs/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/firewall_logs/fields/agent.yml
  packages/aws/data_stream/firewall_logs/fields/base-fields.yml
  packages/aws/data_stream/firewall_logs/fields/ecs.yml
  packages/aws/data_stream/firewall_logs/fields/fields.yml
  packages/aws/data_stream/firewall_logs/manifest.yml
  packages/aws/data_stream/firewall_logs/sample_event.json
  packages/aws/data_stream/firewall_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/firewall_metrics/fields/agent.yml
  packages/aws/data_stream/firewall_metrics/fields/base-fields.yml
  packages/aws/data_stream/firewall_metrics/fields/ecs.yml
  packages/aws/data_stream/firewall_metrics/fields/fields.yml
  packages/aws/data_stream/firewall_metrics/fields/package-fields.yml
  packages/aws/data_stream/firewall_metrics/manifest.yml
  packages/aws/data_stream/firewall_metrics/sample_event.json
  packages/aws/docs/firewall.md
  packages/aws/docs/networkfirewall.md
  packages/aws/img/filebeat-aws-firewall-alerts.png
  packages/aws/img/filebeat-aws-firewall-flows.png
  packages/aws/img/filebeat-aws-firewall-overview.png
  packages/aws/img/logo_firewall.svg
  packages/aws/img/metricbeat-aws-firewall-overview.png
  packages/aws/kibana/dashboard/aws-2ba11b50-4b9d-11ec-8282-5342b8988acc.json
  packages/aws/kibana/dashboard/aws-3abffe60-4ba9-11ec-8282-5342b8988acc.json
  packages/aws/kibana/dashboard/aws-562bdea0-4ba7-11ec-8282-5342b8988acc.json
  packages/aws/kibana/dashboard/aws-dfa76470-4ba1-11ec-8282-5342b8988acc.json
  packages/aws/kibana/search/aws-f4856850-4d32-11ec-a678-057fce71e8cd.json
  packages/aws/kibana/visualization/aws-fefd6ff0-4c8b-11ec-953a-17b90af0b790.json
  packages/aws/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:AWS, New Integration

#2009 Integration of Microsoft SQL Server - Audit Events
  packages/microsoft_sqlserver/_dev/build/build.yml
  packages/microsoft_sqlserver/_dev/build/docs/README.md
  packages/microsoft_sqlserver/changelog.yml
  packages/microsoft_sqlserver/data_stream/audit/_dev/test/pipeline/test-events.json
  packages/microsoft_sqlserver/data_stream/audit/_dev/test/pipeline/test-events.json-config.yml
  packages/microsoft_sqlserver/data_stream/audit/_dev/test/pipeline/test-events.json-expected.json
  packages/microsoft_sqlserver/data_stream/audit/agent/stream/winlog.yml.hbs
  packages/microsoft_sqlserver/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_sqlserver/data_stream/audit/fields/base-fields.yml
  packages/microsoft_sqlserver/data_stream/audit/fields/ecs.yml
  packages/microsoft_sqlserver/data_stream/audit/fields/fields.yml
  packages/microsoft_sqlserver/data_stream/audit/fields/winlog.yml
  packages/microsoft_sqlserver/data_stream/audit/manifest.yml
  packages/microsoft_sqlserver/docs/README.md
  packages/microsoft_sqlserver/img/microsoft-sql-server-logo.svg
  packages/microsoft_sqlserver/img/sqlserver-dashboard.png
  packages/microsoft_sqlserver/kibana/dashboard/microsoft_sqlserver-361588b0-389b-11ec-9973-85eff9a74fdb.json
  packages/microsoft_sqlserver/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.1 candidate

#2203 [Jira] Add Jira Package
  packages/atlassian_jira/_dev/build/build.yml
  packages/atlassian_jira/_dev/build/docs/README.md
  packages/atlassian_jira/_dev/deploy/docker/docker-compose.yml
  packages/atlassian_jira/_dev/deploy/docker/files/config.yml
  packages/atlassian_jira/_dev/deploy/docker/files/test-audit.log
  packages/atlassian_jira/changelog.yml
  packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-api.log
  packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-api.log-expected.json
  packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-files.log
  packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-files.log-expected.json
  packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-common-config.yml
  packages/atlassian_jira/data_stream/audit/_dev/test/system/test-api-config.yml
  packages/atlassian_jira/data_stream/audit/_dev/test/system/test-files-config.yml
  packages/atlassian_jira/data_stream/audit/agent/stream/httpjson.yml.hbs
  packages/atlassian_jira/data_stream/audit/agent/stream/stream.yml.hbs
  packages/atlassian_jira/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/atlassian_jira/data_stream/audit/fields/agent.yml
  packages/atlassian_jira/data_stream/audit/fields/base-fields.yml
  packages/atlassian_jira/data_stream/audit/fields/ecs.yml
  packages/atlassian_jira/data_stream/audit/fields/fields.yml
  packages/atlassian_jira/data_stream/audit/manifest.yml
  packages/atlassian_jira/data_stream/audit/sample_event.json
  packages/atlassian_jira/docs/README.md
  packages/atlassian_jira/img/jira-software-logo.svg
  packages/atlassian_jira/manifest.yml
Labels: Team:Security-External Integrations

#2208 [Confluence] Add Confluence package
  packages/atlassian_confluence/_dev/build/build.yml
  packages/atlassian_confluence/_dev/build/docs/README.md
  packages/atlassian_confluence/_dev/deploy/docker/docker-compose.yml
  packages/atlassian_confluence/_dev/deploy/docker/files/config.yml
  packages/atlassian_confluence/_dev/deploy/docker/files/test-audit.log
  packages/atlassian_confluence/changelog.yml
  packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-api.log
  packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-api.log-expected.json
  packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-files.log
  packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-files.log-expected.json
  packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-common-config.yml
  packages/atlassian_confluence/data_stream/audit/_dev/test/system/test-api-config.yml
  packages/atlassian_confluence/data_stream/audit/_dev/test/system/test-files-config.yml
  packages/atlassian_confluence/data_stream/audit/agent/stream/httpjson.yml.hbs
  packages/atlassian_confluence/data_stream/audit/agent/stream/stream.yml.hbs
  packages/atlassian_confluence/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/atlassian_confluence/data_stream/audit/fields/agent.yml
  packages/atlassian_confluence/data_stream/audit/fields/base-fields.yml
  packages/atlassian_confluence/data_stream/audit/fields/ecs.yml
  packages/atlassian_confluence/data_stream/audit/fields/fields.yml
  packages/atlassian_confluence/data_stream/audit/manifest.yml
  packages/atlassian_confluence/data_stream/audit/sample_event.json
  packages/atlassian_confluence/docs/README.md
  packages/atlassian_confluence/img/confluence-logo.svg
  packages/atlassian_confluence/manifest.yml
Labels: Team:Security-External Integrations

#2202 [QNAP NAS] Add QNAP NAS Logs package
  packages/qnap_nas/_dev/build/build.yml
  packages/qnap_nas/_dev/build/docs/README.md
  packages/qnap_nas/_dev/deploy/docker/docker-compose.yml
  packages/qnap_nas/_dev/deploy/docker/sample_logs/access.log
  packages/qnap_nas/_dev/deploy/docker/sample_logs/event.log
  packages/qnap_nas/changelog.yml
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-access.log
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-access.log-expected.json
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-event.log
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-event.log-expected.json
  packages/qnap_nas/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/qnap_nas/data_stream/log/_dev/test/system/test-tls-config.yml
  packages/qnap_nas/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/qnap_nas/data_stream/log/agent/stream/tcp.yml.hbs
  packages/qnap_nas/data_stream/log/agent/stream/udp.yml.hbs
  packages/qnap_nas/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/qnap_nas/data_stream/log/fields/base-fields.yml
  packages/qnap_nas/data_stream/log/fields/beats.yml
  packages/qnap_nas/data_stream/log/fields/ecs.yml
  packages/qnap_nas/data_stream/log/fields/fields.yml
  packages/qnap_nas/data_stream/log/manifest.yml
  packages/qnap_nas/data_stream/log/sample_event.json
  packages/qnap_nas/docs/README.md
  packages/qnap_nas/img/logo.svg
  packages/qnap_nas/kibana/dashboard/qnap_nas-32e28700-4b0c-11ec-b2cc-b9a3cc301b75.json
  packages/qnap_nas/kibana/search/qnap_nas-50acdec0-4b0c-11ec-b2cc-b9a3cc301b75.json
  packages/qnap_nas/kibana/visualization/qnap_nas-05c7ac80-4b0e-11ec-b2cc-b9a3cc301b75.json
  packages/qnap_nas/kibana/visualization/qnap_nas-47e207a0-4b13-11ec-b2cc-b9a3cc301b75.json
  packages/qnap_nas/kibana/visualization/qnap_nas-6cc17ac0-4b0d-11ec-b2cc-b9a3cc301b75.json
  packages/qnap_nas/kibana/visualization/qnap_nas-ae17aa40-4b0c-11ec-b2cc-b9a3cc301b75.json
  packages/qnap_nas/kibana/visualization/qnap_nas-d315c4c0-4b0d-11ec-b2cc-b9a3cc301b75.json
  packages/qnap_nas/manifest.yml
Labels: Team:Security-External Integrations

#2332 [Cybersixgill] Add dashboard and update Icon
  packages/ti_cybersixgill/changelog.yml
  packages/ti_cybersixgill/data_stream/threat/fields/base-fields.yml
  packages/ti_cybersixgill/data_stream/threat/sample_event.json
  packages/ti_cybersixgill/docs/README.md
  packages/ti_cybersixgill/img/cybersixgill.svg
  packages/ti_cybersixgill/kibana/dashboard/ti_cybersixgill-63c9fee0-5bea-11ec-9302-152fd766c738.json
  packages/ti_cybersixgill/kibana/dashboard/ti_cybersixgill-717013b0-5bed-11ec-9302-152fd766c738.json
  packages/ti_cybersixgill/kibana/dashboard/ti_cybersixgill-c75353f0-5be8-11ec-9302-152fd766c738.json
  packages/ti_cybersixgill/kibana/tag/ti_cybersixgill-7186bf10-5be4-11ec-9302-152fd766c738.json
  packages/ti_cybersixgill/manifest.yml
Labels: Team:Security-External Integrations

#2162 [Snyk] Add Snyk pacakge
  packages/snyk/_dev/build/build.yml
  packages/snyk/_dev/build/docs/README.md
  packages/snyk/_dev/deploy/docker/docker-compose.yml
  packages/snyk/_dev/deploy/docker/files/config.yml
  packages/snyk/changelog.yml
  packages/snyk/data_stream/audit/_dev/test/pipeline/test-common-config.yml
  packages/snyk/data_stream/audit/_dev/test/pipeline/test-snyk-audit.log
  packages/snyk/data_stream/audit/_dev/test/pipeline/test-snyk-audit.log-expected.json
  packages/snyk/data_stream/audit/_dev/test/system/test-default-config.yml
  packages/snyk/data_stream/audit/agent/stream/httpjson.yml.hbs
  packages/snyk/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/snyk/data_stream/audit/fields/agent.yml
  packages/snyk/data_stream/audit/fields/base-fields.yml
  packages/snyk/data_stream/audit/fields/beats.yml
  packages/snyk/data_stream/audit/fields/ecs.yml
  packages/snyk/data_stream/audit/fields/fields.yml
  packages/snyk/data_stream/audit/fields/package-fields.yml
  packages/snyk/data_stream/audit/manifest.yml
  packages/snyk/data_stream/audit/sample_event.json
  packages/snyk/data_stream/vulnerabilities/_dev/test/pipeline/test-common-config.yml
  packages/snyk/data_stream/vulnerabilities/_dev/test/pipeline/test-snyk-vulnerabilities.log
  packages/snyk/data_stream/vulnerabilities/_dev/test/pipeline/test-snyk-vulnerabilities.log-expected.json
  packages/snyk/data_stream/vulnerabilities/_dev/test/system/test-default-config.yml
  packages/snyk/data_stream/vulnerabilities/agent/stream/httpjson.yml.hbs
  packages/snyk/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
  packages/snyk/data_stream/vulnerabilities/fields/agent.yml
  packages/snyk/data_stream/vulnerabilities/fields/base-fields.yml
  packages/snyk/data_stream/vulnerabilities/fields/beats.yml
  packages/snyk/data_stream/vulnerabilities/fields/ecs.yml
  packages/snyk/data_stream/vulnerabilities/fields/fields.yml
  packages/snyk/data_stream/vulnerabilities/fields/package-fields.yml
  packages/snyk/data_stream/vulnerabilities/manifest.yml
  packages/snyk/data_stream/vulnerabilities/sample_event.json
  packages/snyk/docs/README.md
  packages/snyk/img/snyk-logo.svg
  packages/snyk/manifest.yml
Labels: Team:Security-External Integrations

#1643 [Akamai] Add Akamai package
  packages/akamai/_dev/build/build.yml
  packages/akamai/_dev/build/docs/README.md
  packages/akamai/_dev/deploy/docker/docker-compose.yml
  packages/akamai/_dev/deploy/docker/files/config.yml
  packages/akamai/changelog.yml
  packages/akamai/data_stream/siem/_dev/test/pipeline/test-http-json.log
  packages/akamai/data_stream/siem/_dev/test/pipeline/test-http-json.log-config.yml
  packages/akamai/data_stream/siem/_dev/test/pipeline/test-http-json.log-expected.json
  packages/akamai/data_stream/siem/_dev/test/system/test-default-config.yml
  packages/akamai/data_stream/siem/agent/stream/httpjson.yml.hbs
  packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
  packages/akamai/data_stream/siem/fields/agent.yml
  packages/akamai/data_stream/siem/fields/base-fields.yml
  packages/akamai/data_stream/siem/fields/beats.yml
  packages/akamai/data_stream/siem/fields/ecs.yml
  packages/akamai/data_stream/siem/fields/fields.yml
  packages/akamai/data_stream/siem/manifest.yml
  packages/akamai/data_stream/siem/sample_event.json
  packages/akamai/docs/README.md
  packages/akamai/img/akamai_logo.svg
  packages/akamai/manifest.yml
Labels: Team:Security-External Integrations

#2154 [New Package] httpjson custom input
  packages/httpjson/_dev/build/build.yml
  packages/httpjson/_dev/build/docs/README.md
  packages/httpjson/_dev/deploy/docker/docker-compose.yml
  packages/httpjson/_dev/deploy/docker/files/config.yml
  packages/httpjson/changelog.yml
  packages/httpjson/data_stream/generic/_dev/test/system/test-basicauth-config.yml
  packages/httpjson/data_stream/generic/_dev/test/system/test-oauth-config.yml
  packages/httpjson/data_stream/generic/_dev/test/system/test-pagination-config.yml
  packages/httpjson/data_stream/generic/_dev/test/system/test-transforms-config.yml
  packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
  packages/httpjson/data_stream/generic/fields/base-fields.yml
  packages/httpjson/data_stream/generic/fields/beats.yml
  packages/httpjson/data_stream/generic/fields/ecs.yml
  packages/httpjson/data_stream/generic/manifest.yml
  packages/httpjson/data_stream/generic/sample_event.json
  packages/httpjson/docs/README.md
  packages/httpjson/manifest.yml
Labels: Team:Integrations, Team:Security-External Integrations

#2275 [panw_cortex_xdr] Add 8.0.0 constraint
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2344 Expose event_id, and language options to all winlog inputs
  packages/microsoft_sqlserver/changelog.yml
  packages/microsoft_sqlserver/data_stream/audit/agent/stream/winlog.yml.hbs
  packages/microsoft_sqlserver/data_stream/audit/manifest.yml
  packages/microsoft_sqlserver/manifest.yml
  packages/system/changelog.yml
  packages/system/data_stream/application/agent/stream/winlog.yml.hbs
  packages/system/data_stream/application/manifest.yml
  packages/system/data_stream/security/agent/stream/winlog.yml.hbs
  packages/system/data_stream/security/manifest.yml
  packages/system/data_stream/system/agent/stream/winlog.yml.hbs
  packages/system/data_stream/system/manifest.yml
  packages/system/manifest.yml
  packages/windows/changelog.yml
  packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/forwarded/manifest.yml
  packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell/manifest.yml
  packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell_operational/manifest.yml
  packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/sysmon_operational/manifest.yml
  packages/windows/manifest.yml
  packages/winlog/changelog.yml
  packages/winlog/data_stream/winlog/agent/stream/winlog.yml.hbs
  packages/winlog/data_stream/winlog/manifest.yml
  packages/winlog/manifest.yml
Labels: enhancement, Team:Integrations, Team:Security-External Integrations

#2345 Support additional parser configuration: ndjson and multiline in container logs data-stream
  packages/kubernetes/_dev/build/docs/container-logs.md
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
  packages/kubernetes/data_stream/container_logs/fields/ecs.yml
  packages/kubernetes/data_stream/container_logs/manifest.yml
  packages/kubernetes/data_stream/container_logs/sample_event.json
  packages/kubernetes/docs/container-logs.md
  packages/kubernetes/manifest.yml
Labels: enhancement

#2288 Fix kubernetes.volume.fs.used.pct type
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/volume/fields/fields.yml
  packages/kubernetes/docs/kubelet.md
  packages/kubernetes/manifest.yml
Labels: bug, Team:Integrations

#2364 Workaround: skip ppid deprecation notice
  packages/auditd/_dev/build/build.yml
  packages/cisco/_dev/build/build.yml
  packages/cisco_meraki/_dev/build/build.yml
  packages/cisco_nexus/_dev/build/build.yml
  packages/fortinet/_dev/build/build.yml
  packages/juniper/_dev/build/build.yml
  packages/juniper_junos/_dev/build/build.yml
  packages/juniper_netscreen/_dev/build/build.yml
  packages/juniper_srx/_dev/build/build.yml
  packages/linux/_dev/build/build.yml
  packages/microsoft/_dev/build/build.yml
  packages/netflow/_dev/build/build.yml
  packages/santa/_dev/build/build.yml
  packages/sonicwall/_dev/build/build.yml
  packages/sophos/_dev/build/build.yml
  packages/system/_dev/build/build.yml
  packages/tomcat/_dev/build/build.yml
Labels: Team:Integrations

#2336 [etcd] Add metrics dashboard
  packages/etcd/changelog.yml
  packages/etcd/img/metrics-overview.png
  packages/etcd/kibana/dashboard/etcd-a2f2c8fd-f016-42c8-9dc1-4e5a36038e35.json
  packages/etcd/kibana/visualization/etcd-212dc4bd-bf51-4bed-88b5-74bb4441574f.json
  packages/etcd/kibana/visualization/etcd-55c39055-3c9c-491a-b45f-15a2b0f684a0.json
  packages/etcd/kibana/visualization/etcd-744a430c-e117-495b-bbca-42b9102aec8b.json
  packages/etcd/kibana/visualization/etcd-ce03dbe8-a869-40a0-b5dd-115b7821730f.json
  packages/etcd/kibana/visualization/etcd-d1292452-aff5-4d66-ae4f-276a8a497e88.json
  packages/etcd/kibana/visualization/etcd-d444c52e-f204-4719-88de-f3b930beeeb0.json
  packages/etcd/kibana/visualization/etcd-d8f81d62-ddd3-4b78-a1c2-17c9765296ff.json
  packages/etcd/kibana/visualization/etcd-ef66b2be-da4e-4030-a49a-f3f91ccaf655.json
  packages/etcd/manifest.yml
Labels: Team:Integrations

#2360 GA security integrations for 8.1
  packages/1password/changelog.yml
  packages/1password/manifest.yml
  packages/carbonblack_edr/changelog.yml
  packages/carbonblack_edr/data_stream/log/manifest.yml
  packages/carbonblack_edr/img/carbon-black-logo.svg
  packages/carbonblack_edr/manifest.yml
  packages/cisco_duo/changelog.yml
  packages/cisco_duo/data_stream/admin/manifest.yml
  packages/cisco_duo/data_stream/auth/manifest.yml
  packages/cisco_duo/data_stream/offline_enrollment/manifest.yml
  packages/cisco_duo/data_stream/summary/manifest.yml
  packages/cisco_duo/data_stream/telephony/manifest.yml
  packages/cisco_duo/manifest.yml
  packages/cisco_secure_endpoint/changelog.yml
  packages/cisco_secure_endpoint/data_stream/event/manifest.yml
  packages/cisco_secure_endpoint/manifest.yml
  packages/microsoft_dhcp/changelog.yml
  packages/microsoft_dhcp/manifest.yml
  packages/panw_cortex_xdr/_dev/deploy/docker/docker-compose.yml
  packages/panw_cortex_xdr/_dev/deploy/docker/http-mock-config.yml
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/system/test-http-config.yml
  packages/panw_cortex_xdr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2372 Upgrade k8s version to v1.23.0
  .ci/Jenkinsfile
Labels: Team:Integrations
