Repository elastic/integrations, pull requests merged in 2022-02, with the labels that each got.

#2625 Add job.name field in state_container
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/state_container/fields/base-fields.yml
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/manifest.yml
Labels: Team:Cloudnative-Monitoring

#2623 Disable system tests exercising journald input
  packages/iptables/data_stream/log/_dev/test/system/test-journald-config.yml
  packages/journald/data_stream/log/_dev/test/system/test-journald-config.yml
Labels: Team:Integrations

#2380 [auditd] Upgrade ECS to 8.0.0
  packages/auditd/_dev/build/build.yml
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/data_stream/log/fields/ecs.yml
  packages/auditd/data_stream/log/sample_event.json
  packages/auditd/docs/README.md
  packages/auditd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2437 [santa] Upgrade ECS to 8.0.0
  packages/santa/_dev/build/build.yml
  packages/santa/changelog.yml
  packages/santa/data_stream/log/_dev/test/pipeline/test-santa-raw.log-expected.json
  packages/santa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/santa/data_stream/log/fields/ecs.yml
  packages/santa/data_stream/log/sample_event.json
  packages/santa/docs/README.md
  packages/santa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2629 [osquery] [panw] Fix package versions
  packages/osquery/changelog.yml
  packages/osquery/manifest.yml
  packages/panw/changelog.yml
  packages/panw/manifest.yml
Labels: bug, 8.0 candidate

#2395 [cisco_secure_endpoint] Upgrade ECS to 8.0.0
  packages/cisco_secure_endpoint/_dev/build/build.yml
  packages/cisco_secure_endpoint/changelog.yml
  packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp1.log-expected.json
  packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp2.log-expected.json
  packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp3.log-expected.json
  packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp4.log-expected.json
  packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp5.log-expected.json
  packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp6.log-expected.json
  packages/cisco_secure_endpoint/data_stream/event/_dev/test/pipeline/test-cisco-amp7.log-expected.json
  packages/cisco_secure_endpoint/data_stream/event/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_secure_endpoint/data_stream/event/fields/ecs.yml
  packages/cisco_secure_endpoint/data_stream/event/sample_event.json
  packages/cisco_secure_endpoint/docs/README.md
  packages/cisco_secure_endpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2630 CI fix: use full semver for Elastic stacks
  .ci/schedule-daily.groovy
Labels: Team:Integrations

#2636 cisco_ios: add missing event.original mapping
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/data_stream/log/fields/ecs.yml
  packages/cisco_ios/docs/README.md
  packages/cisco_ios/manifest.yml
Labels: bug, Team:Security-External Integrations, 8.1-candidate

#2424 [netflow] Upgrade ECS to 8.0.0
  packages/netflow/_dev/build/build.yml
  packages/netflow/changelog.yml
  packages/netflow/data_stream/log/_dev/test/pipeline/test-netflow-log-events.json-expected.json
  packages/netflow/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/netflow/data_stream/log/fields/ecs.yml
  packages/netflow/data_stream/log/sample_event.json
  packages/netflow/docs/README.md
  packages/netflow/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2632 Add standard HTTP options to Prometheus package
  packages/prometheus/changelog.yml
  packages/prometheus/data_stream/collector/agent/stream/stream.yml.hbs
  packages/prometheus/data_stream/collector/manifest.yml
  packages/prometheus/manifest.yml
Labels: Team:Cloudnative-Monitoring

#2493 [microsoft_sqlserver] Upgrade ECS to 8.0.0
  packages/microsoft_sqlserver/_dev/build/build.yml
  packages/microsoft_sqlserver/changelog.yml
  packages/microsoft_sqlserver/data_stream/audit/_dev/test/pipeline/test-events.json-expected.json
  packages/microsoft_sqlserver/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_sqlserver/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2438 [snort] Upgrade ECS to 8.0.0
  packages/snort/_dev/build/build.yml
  packages/snort/changelog.yml
  packages/snort/data_stream/log/_dev/test/pipeline/test-log-csv.log-expected.json
  packages/snort/data_stream/log/_dev/test/pipeline/test-log-fast.log-expected.json
  packages/snort/data_stream/log/_dev/test/pipeline/test-log-full.log-expected.json
  packages/snort/data_stream/log/_dev/test/pipeline/test-log-pfsense.log-expected.json
  packages/snort/data_stream/log/_dev/test/pipeline/test-log-syslog.log-expected.json
  packages/snort/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/snort/data_stream/log/sample_event.json
  packages/snort/docs/README.md
  packages/snort/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2432 [pfsense] Upgrade ECS to 8.0.0
  packages/pfsense/_dev/build/build.yml
  packages/pfsense/changelog.yml
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-bsd.log-expected.json
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-dhcp.log-expected.json
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-haproxy.log-expected.json
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-ipsec.log-expected.json
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-openvpn.log-expected.json
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-syslog.log-expected.json
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-pfsense-unbound.log-expected.json
  packages/pfsense/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/pfsense/data_stream/log/sample_event.json
  packages/pfsense/docs/README.md
  packages/pfsense/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2426 [network_traffic] Upgrade ECS to 8.0.0
  packages/network_traffic/_dev/build/build.yml
  packages/network_traffic/_dev/build/docs/README.md
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/amqp/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/amqp/sample_event.json
  packages/network_traffic/data_stream/cassandra/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/cassandra/sample_event.json
  packages/network_traffic/data_stream/dhcpv4/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/dhcpv4/sample_event.json
  packages/network_traffic/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/dns/sample_event.json
  packages/network_traffic/data_stream/flow/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/http/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/http/sample_event.json
  packages/network_traffic/data_stream/icmp/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/icmp/sample_event.json
  packages/network_traffic/data_stream/memcached/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/memcached/sample_event.json
  packages/network_traffic/data_stream/mongodb/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/mongodb/sample_event.json
  packages/network_traffic/data_stream/mysql/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/mysql/sample_event.json
  packages/network_traffic/data_stream/nfs/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/nfs/sample_event.json
  packages/network_traffic/data_stream/pgsql/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/pgsql/sample_event.json
  packages/network_traffic/data_stream/redis/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/redis/sample_event.json
  packages/network_traffic/data_stream/sip/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/sip/sample_event.json
  packages/network_traffic/data_stream/thrift/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/thrift/sample_event.json
  packages/network_traffic/data_stream/tls/elasticsearch/ingest_pipeline/default.yml
  packages/network_traffic/data_stream/tls/sample_event.json
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2408 [google_workspace] Upgrade ECS to 8.0.0
  packages/google_workspace/_dev/build/build.yml
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-application.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-calendar.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chat.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chromeos.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-contacts.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-delegatedadmin.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-docs.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-domain.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-gmail.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-groups.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-licenses.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-mobile.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-org.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-security.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-sites.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-user.log-expected.json
  packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/admin/sample_event.json
  packages/google_workspace/data_stream/drive/_dev/test/pipeline/test-drive.log-expected.json
  packages/google_workspace/data_stream/drive/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/drive/sample_event.json
  packages/google_workspace/data_stream/groups/_dev/test/pipeline/test-groups.log-expected.json
  packages/google_workspace/data_stream/groups/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/groups/sample_event.json
  packages/google_workspace/data_stream/login/_dev/test/pipeline/test-login.log-expected.json
  packages/google_workspace/data_stream/login/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/login/sample_event.json
  packages/google_workspace/data_stream/saml/_dev/test/pipeline/test-saml.log-expected.json
  packages/google_workspace/data_stream/saml/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/saml/sample_event.json
  packages/google_workspace/data_stream/user_accounts/_dev/test/pipeline/test-user-accounts.log-expected.json
  packages/google_workspace/data_stream/user_accounts/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/data_stream/user_accounts/sample_event.json
  packages/google_workspace/docs/README.md
  packages/google_workspace/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2434 [pulse_connect_secure] Upgrade ECS to 8.0.0
  packages/pulse_connect_secure/_dev/build/build.yml
  packages/pulse_connect_secure/changelog.yml
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-admin.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-system.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-vpn.log-expected.json
  packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/pulse_connect_secure/data_stream/log/sample_event.json
  packages/pulse_connect_secure/docs/README.md
  packages/pulse_connect_secure/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2407 [github] Upgrade ECS to 8.0.0
  packages/github/_dev/build/build.yml
  packages/github/_dev/deploy/docker/docker-compose.yml
  packages/github/changelog.yml
  packages/github/data_stream/audit/_dev/test/pipeline/test-audit-json.log-expected.json
  packages/github/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/github/data_stream/audit/sample_event.json
  packages/github/docs/README.md
  packages/github/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2396 [cisco_umbrella] Upgrade ECS to 8.0.0
  packages/cisco_umbrella/_dev/build/build.yml
  packages/cisco_umbrella/changelog.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-cloudfirewalllogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-iplogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-proxylogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_umbrella/docs/README.md
  packages/cisco_umbrella/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2423 [microsoft_dhcp] Upgrade ECS to 8.0.0
  packages/microsoft_dhcp/_dev/build/build.yml
  packages/microsoft_dhcp/changelog.yml
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-logv6.log-expected.json
  packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_dhcp/data_stream/log/sample_event.json
  packages/microsoft_dhcp/docs/README.md
  packages/microsoft_dhcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2552 pulse_connect_secure: add syslog priority format parsing support
  packages/pulse_connect_secure/changelog.yml
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-admin.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-syslog.log
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-syslog.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-system.log-expected.json
  packages/pulse_connect_secure/data_stream/log/_dev/test/pipeline/test-log-vpn.log-expected.json
  packages/pulse_connect_secure/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/pulse_connect_secure/data_stream/log/fields/ecs.yml
  packages/pulse_connect_secure/docs/README.md
  packages/pulse_connect_secure/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.1-candidate

#2414 [iptables] Upgrade ECS to 8.0.0
  packages/iptables/_dev/build/build.yml
  packages/iptables/changelog.yml
  packages/iptables/data_stream/log/_dev/test/pipeline/test-iptables-raw.log-expected.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-journald.json-expected.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-ubiquiti.log-expected.json
  packages/iptables/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/iptables/data_stream/log/fields/ecs.yml
  packages/iptables/data_stream/log/sample_event.json
  packages/iptables/docs/README.md
  packages/iptables/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2641 Fix templates to include username and password in Mongodb
  packages/mongodb/changelog.yml
  packages/mongodb/data_stream/collstats/agent/stream/stream.yml.hbs
  packages/mongodb/data_stream/dbstats/agent/stream/stream.yml.hbs
  packages/mongodb/data_stream/replstatus/agent/stream/stream.yml.hbs
  packages/mongodb/data_stream/status/agent/stream/stream.yml.hbs
  packages/mongodb/manifest.yml
Labels: bug, Team:Integrations, Integration:MongoDB

#2649 cisco_asa: clarify config option
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/manifest.yml
  packages/cisco_asa/manifest.yml
Labels: bug, Team:Security-External Integrations, 8.2-candidate

#2650 [microsoft_sqlserver] fix owner
  packages/microsoft_sqlserver/changelog.yml
  packages/microsoft_sqlserver/manifest.yml
Labels: bug

#2648 network_traffic: fix typo
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/amqp/fields/agent.yml
  packages/network_traffic/data_stream/cassandra/fields/agent.yml
  packages/network_traffic/data_stream/dhcpv4/fields/agent.yml
  packages/network_traffic/data_stream/dns/fields/agent.yml
  packages/network_traffic/data_stream/flow/fields/agent.yml
  packages/network_traffic/data_stream/http/fields/agent.yml
  packages/network_traffic/data_stream/icmp/fields/agent.yml
  packages/network_traffic/data_stream/memcached/fields/agent.yml
  packages/network_traffic/data_stream/mongodb/fields/agent.yml
  packages/network_traffic/data_stream/mysql/fields/agent.yml
  packages/network_traffic/data_stream/nfs/fields/agent.yml
  packages/network_traffic/data_stream/pgsql/fields/agent.yml
  packages/network_traffic/data_stream/redis/fields/agent.yml
  packages/network_traffic/data_stream/sip/fields/agent.yml
  packages/network_traffic/data_stream/thrift/fields/agent.yml
  packages/network_traffic/data_stream/tls/fields/agent.yml
  packages/network_traffic/data_stream/tls/fields/protocol.yml
  packages/network_traffic/manifest.yml
Labels: bug, Team:Security-External Integrations, 8.1-candidate

#2655 Fix hashicorp documentation
  packages/hashicorp_vault/_dev/build/docs/README.md
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/docs/README.md
  packages/hashicorp_vault/manifest.yml
Labels: Team:Docs

#2654 Fix hid_bravura documentation
  packages/hid_bravura_monitor/_dev/build/docs/README.md
  packages/hid_bravura_monitor/changelog.yml
  packages/hid_bravura_monitor/docs/README.md
  packages/hid_bravura_monitor/manifest.yml
Labels: Team:Docs

#2653 [crowdstrike] Fix issue with 'Is FDR Queue' option not taking effect
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
  packages/crowdstrike/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Crowdstrike

#2560 Add data_stream.dataset option for custom aws-cloudwatch log input
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudwatch_logs/_dev/test/pipeline/test-cloudwatch-ec2.log-expected.json
  packages/aws/data_stream/cloudwatch_logs/agent/stream/aws-cloudwatch.yml.hbs
  packages/aws/data_stream/cloudwatch_logs/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/cloudwatch_logs/fields/ecs.yml
  packages/aws/data_stream/cloudwatch_logs/manifest.yml
  packages/aws/docs/cloudwatch.md
  packages/aws/manifest.yml
Labels: Team:Integrations

#2664 [github] Fix Github query operator error
  packages/github/_dev/build/docs/README.md
  packages/github/_dev/deploy/docker/files/config.yml
  packages/github/changelog.yml
  packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
  packages/github/docs/README.md
  packages/github/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Github

#2671 [UDP] Fixing typo in listen_address for package
  packages/udp/changelog.yml
  packages/udp/data_stream/generic/manifest.yml
  packages/udp/manifest.yml
Labels: Team:Security-External Integrations

#2677 [Anomali] adding initial interval to manifest
  packages/ti_anomali/changelog.yml
  packages/ti_anomali/data_stream/limo/manifest.yml
  packages/ti_anomali/manifest.yml
Labels: Team:Security-External Integrations

#2678 Release docker package for 8.0
  packages/docker/changelog.yml
  packages/docker/manifest.yml
Labels: Team:Integrations

#2656 Fix azure_metrics docs
  packages/azure_metrics/_dev/build/docs/compute_vm.md
  packages/azure_metrics/_dev/build/docs/compute_vm_scaleset.md
  packages/azure_metrics/_dev/build/docs/container_instance.md
  packages/azure_metrics/_dev/build/docs/container_registry.md
  packages/azure_metrics/_dev/build/docs/container_service.md
  packages/azure_metrics/_dev/build/docs/database_account.md
  packages/azure_metrics/_dev/build/docs/storage_account.md
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/docs/compute_vm.md
  packages/azure_metrics/docs/compute_vm_scaleset.md
  packages/azure_metrics/docs/container_instance.md
  packages/azure_metrics/docs/container_registry.md
  packages/azure_metrics/docs/container_service.md
  packages/azure_metrics/docs/database_account.md
  packages/azure_metrics/docs/storage_account.md
  packages/azure_metrics/manifest.yml
Labels: Team:Docs

#2624 [gcp] Add gcp.dns integration
  packages/gcp/_dev/build/docs/README.md
  packages/gcp/changelog.yml
  packages/gcp/data_stream/dns/_dev/test/pipeline/test-common-config.yml
  packages/gcp/data_stream/dns/_dev/test/pipeline/test-dns.log
  packages/gcp/data_stream/dns/_dev/test/pipeline/test-dns.log-expected.json
  packages/gcp/data_stream/dns/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/dns/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/dns/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/dns/fields/agent.yml
  packages/gcp/data_stream/dns/fields/base-fields.yml
  packages/gcp/data_stream/dns/fields/ecs.yml
  packages/gcp/data_stream/dns/fields/fields.yml
  packages/gcp/data_stream/dns/manifest.yml
  packages/gcp/data_stream/dns/sample_event.json
  packages/gcp/docs/README.md
  packages/gcp/manifest.yml
Labels: enhancement, Team:Integrations, Team:Security-External Integrations, Integration:GCP

#2644 mimecast/auditevents: fix typo
  packages/mimecast/changelog.yml
  packages/mimecast/data_stream/audit_events/fields/ecs.yml
  packages/mimecast/docs/README.md
  packages/mimecast/manifest.yml
Labels: bug, Team:Security-External Integrations, 8.1-candidate, Integration:Mimecast

#2685 [fortinet] Clarify description of listen address/port
  packages/fortinet/changelog.yml
  packages/fortinet/data_stream/clientendpoint/manifest.yml
  packages/fortinet/data_stream/firewall/manifest.yml
  packages/fortinet/data_stream/fortimail/manifest.yml
  packages/fortinet/data_stream/fortimanager/manifest.yml
  packages/fortinet/manifest.yml
Labels: Team:Security-External Integrations, Integration:Fortinet

#2681 Fix url in docker changelog
  packages/docker/changelog.yml
Labels: Integration:Docker

#2702 Add missing metadata fields
  packages/kubernetes/_dev/deploy/k8s/cluster-role-binding.yaml
  packages/kubernetes/_dev/deploy/k8s/cluster-role.yaml
  packages/kubernetes/_dev/deploy/k8s/cronjob.yaml
  packages/kubernetes/_dev/deploy/k8s/deployment.yaml
  packages/kubernetes/_dev/deploy/k8s/service-account.yaml
  packages/kubernetes/_dev/deploy/k8s/service.yaml
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/container/fields/ecs.yml
  packages/kubernetes/data_stream/state_job/fields/base-fields.yml
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/docs/kubelet.md
  packages/kubernetes/manifest.yml
Labels: Team:Cloudnative-Monitoring

#2703 network_traffic/tls: capture tls random data and ocsp status
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/tls/fields/protocol.yml
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.1-candidate

#2701 [crowdstrike] Fix multi-line string handling for config variable
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
  packages/crowdstrike/data_stream/fdr/manifest.yml
  packages/crowdstrike/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Crowdstrike

#2708 [zscaler] Mark package as deprecated
  packages/zscaler/changelog.yml
  packages/zscaler/docs/README.md
  packages/zscaler/manifest.yml
Labels: Team:Security-External Integrations, Integration:Zscaler

#2669 [o365] Better handling of address formats
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/_dev/test/pipeline/test-azuread-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-azuread-sts-logon-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-bad-ips.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-bad-ips.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-common-config.yml
  packages/o365/data_stream/audit/_dev/test/pipeline/test-data-insights-api-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-dlp-exchange-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-dlp-sharepoint-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-admin-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-item-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-ip-formats-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-ms-teams-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-parameter-string.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sec-comp-alerts-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepoint-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepointfileop-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sp-sharing-op-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-yammer-events.json-expected.json
  packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/o365/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:o365

#2682 Support new Azure audit logs and signin logs
  packages/azure/changelog.yml
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-audit-logs-sample.log
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-audit-logs-sample.log-expected.json
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-common-config.yml
  packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/auditlogs/fields/ecs.yml
  packages/azure/data_stream/auditlogs/fields/fields.yml
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-managed-identity-sample.log
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-managed-identity-sample.log-expected.json
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-non-interactive-user-sample.log
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-non-interactive-user-sample.log-expected.json
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-service-principal-signinlogs-sample.log
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-service-principal-signinlogs-sample.log-expected.json
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-sample.log
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-sample.log-expected.json
  packages/azure/data_stream/signinlogs/fields/fields.yml
  packages/azure/docs/README.md
  packages/azure/docs/adlogs.md
  packages/azure/manifest.yml
Labels: Integration:Azure

#2680 Fix missing ignore in filesystem config
  packages/system/changelog.yml
  packages/system/data_stream/filesystem/agent/stream/stream.yml.hbs
  packages/system/data_stream/filesystem/manifest.yml
  packages/system/manifest.yml
Labels: bug, Integration:System, Team:Elastic-Agent-Data-Plane

#2712 Add single quotes around the credentials_json var
  packages/gcp/changelog.yml
  packages/gcp/data_stream/audit/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/audit/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/dns/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/dns/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/firewall/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/firewall/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/data_stream/vpcflow/_dev/test/system/test-pubsub-config.yml
  packages/gcp/data_stream/vpcflow/agent/stream/gcp-pubsub.yml.hbs
  packages/gcp/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:GCP

#2724 [HTTP_endpoint] New input package
  packages/http_endpoint/_dev/build/build.yml
  packages/http_endpoint/_dev/build/docs/README.md
  packages/http_endpoint/_dev/deploy/docker/docker-compose.yml
  packages/http_endpoint/_dev/deploy/docker/sample_logs/test-webhook.log
  packages/http_endpoint/changelog.yml
  packages/http_endpoint/data_stream/generic/_dev/test/system/test-http-config.yml
  packages/http_endpoint/data_stream/generic/agent/stream/http.yml.hbs
  packages/http_endpoint/data_stream/generic/fields/base-fields.yml
  packages/http_endpoint/data_stream/generic/fields/beats.yml
  packages/http_endpoint/data_stream/generic/fields/ecs.yml
  packages/http_endpoint/data_stream/generic/manifest.yml
  packages/http_endpoint/data_stream/generic/sample_event.json
  packages/http_endpoint/docs/README.md
  packages/http_endpoint/img/icon.svg
  packages/http_endpoint/manifest.yml
Labels: Team:Security-External Integrations

#2725 synthetics - add apm service name mapping
  packages/synthetics/changelog.yml
  packages/synthetics/data_stream/browser/fields/common.yml
  packages/synthetics/data_stream/browser_network/fields/common.yml
  packages/synthetics/data_stream/browser_screenshot/fields/common.yml
  packages/synthetics/data_stream/http/fields/common.yml
  packages/synthetics/data_stream/icmp/fields/common.yml
  packages/synthetics/data_stream/tcp/fields/common.yml
  packages/synthetics/manifest.yml
Labels: v8.1.0

#2732 [github] Fix date format used in queries
  packages/github/_dev/deploy/docker/files/config.yml
  packages/github/changelog.yml
  packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
  packages/github/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Github

#2535 [Cisco ASA] Add event codes 113029-113040
  packages/cisco_asa/_dev/deploy/docker/docker-compose.yml
  packages/cisco_asa/_dev/deploy/docker/sample_logs/cisco-asa.log
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-anyconnect-messages.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-missing-groups.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sip.log-expected.json
  packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_asa/manifest.yml
Labels: Team:Security-External Integrations, Integration:Cisco

#2690 [mimecast] Add use cases, docs, and update sample events
  packages/mimecast/_dev/build/build.yml
  packages/mimecast/changelog.yml
  packages/mimecast/data_stream/audit_events/_dev/test/pipeline/test-audit-events.log
  packages/mimecast/data_stream/audit_events/_dev/test/pipeline/test-audit-events.log-expected.json
  packages/mimecast/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/audit_events/fields/field.yml
  packages/mimecast/data_stream/audit_events/sample_event.json
  packages/mimecast/data_stream/dlp_logs/_dev/test/pipeline/test-dlp-logs.log-expected.json
  packages/mimecast/data_stream/dlp_logs/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/dlp_logs/sample_event.json
  packages/mimecast/data_stream/siem_logs/_dev/test/pipeline/test-siem-logs.log-expected.json
  packages/mimecast/data_stream/siem_logs/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/siem_logs/sample_event.json
  packages/mimecast/data_stream/threat_intel_malware_customer/_dev/test/pipeline/test-threat-intel-malware-customer.log-expected.json
  packages/mimecast/data_stream/threat_intel_malware_customer/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/threat_intel_malware_customer/sample_event.json
  packages/mimecast/data_stream/threat_intel_malware_grid/_dev/test/pipeline/test-threat-intel-malware-grid.log-expected.json
  packages/mimecast/data_stream/threat_intel_malware_grid/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/threat_intel_malware_grid/sample_event.json
  packages/mimecast/data_stream/ttp_ap_logs/_dev/test/pipeline/test-ttp-ap-logs.log-expected.json
  packages/mimecast/data_stream/ttp_ap_logs/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/ttp_ap_logs/sample_event.json
  packages/mimecast/data_stream/ttp_ip_logs/_dev/test/pipeline/test-ttp-ip-logs.log-expected.json
  packages/mimecast/data_stream/ttp_ip_logs/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/ttp_ip_logs/sample_event.json
  packages/mimecast/data_stream/ttp_url_logs/_dev/test/pipeline/test-ttp-url-logs.log-expected.json
  packages/mimecast/data_stream/ttp_url_logs/elasticsearch/ingest_pipeline/default.yml
  packages/mimecast/data_stream/ttp_url_logs/sample_event.json
  packages/mimecast/docs/README.md
  packages/mimecast/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Mimecast

#2733 Tune docker package according to Beat's fields deprecation
  packages/docker/changelog.yml
  packages/docker/data_stream/diskio/fields/fields.yml
  packages/docker/data_stream/diskio/sample_event.json
  packages/docker/data_stream/network/fields/fields.yml
  packages/docker/data_stream/network/sample_event.json
  packages/docker/docs/README.md
  packages/docker/kibana/visualization/docker-Network-IO.json
  packages/docker/kibana/visualization/docker-containers.json
  packages/docker/manifest.yml
Labels: Team:Cloudnative-Monitoring

#2730 [Auditd] Populate process.args array with process arguments
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-useradd.log-expected.json
  packages/auditd/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-truncated-execve.log
  packages/auditd/data_stream/log/_dev/test/pipeline/test-truncated-execve.log-expected.json
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Auditd

#2727 [HTTP Endpoint] update README
  packages/http_endpoint/_dev/build/docs/README.md
  packages/http_endpoint/changelog.yml
  packages/http_endpoint/docs/README.md
  packages/http_endpoint/manifest.yml
Labels: Team:Security-External Integrations

#2721 [Oracle] New Package
  packages/oracle/_dev/build/build.yml
  packages/oracle/_dev/build/docs/README.md
  packages/oracle/_dev/deploy/docker/docker-compose.yml
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_j002_28264_20201007122838056263426565.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_m000_25412_20201007115808319837620840.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_m002_28369_20201007123022392204603031.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_m003_24705_20201007113805036530435635.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_m004_29815_20201007130106080227473114.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_m004_29815_20201007130106085635422771.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_m005_24958_20201007115707242540239811.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_10651_20201007131744782913507561.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13448_20201007105245091084628324.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13448_20201007105751018661587803.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13765_20201007105751904399925443.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13779_20201007105801980871631378.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13788_20201007105802970031936241.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13790_20201007105803021897922657.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13791_20201007105803053277493103.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13792_20201007105804019827529526.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_13794_20201007105804045603856206.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_9667_20201007130533504494345257.aud.log
  packages/oracle/_dev/deploy/docker/sample_logs/ORCLCDB_ora_9680_20201007130542916949215077.aud.log
  packages/oracle/changelog.yml
  packages/oracle/data_stream/database_audit/_dev/test/pipeline/test-common-config.yml
  packages/oracle/data_stream/database_audit/_dev/test/pipeline/test-oracle-database-audit.log
  packages/oracle/data_stream/database_audit/_dev/test/pipeline/test-oracle-database-audit.log-expected.json
  packages/oracle/data_stream/database_audit/_dev/test/system/test-logfile-config.yml
  packages/oracle/data_stream/database_audit/agent/stream/stream.yml.hbs
  packages/oracle/data_stream/database_audit/elasticsearch/ingest_pipeline/default.yml
  packages/oracle/data_stream/database_audit/fields/agent.yml
  packages/oracle/data_stream/database_audit/fields/base-fields.yml
  packages/oracle/data_stream/database_audit/fields/ecs.yml
  packages/oracle/data_stream/database_audit/fields/fields.yml
  packages/oracle/data_stream/database_audit/manifest.yml
  packages/oracle/data_stream/database_audit/sample_event.json
  packages/oracle/docs/README.md
  packages/oracle/img/oracle_logo.svg
  packages/oracle/manifest.yml
Labels: Team:Security-External Integrations

#2719 [MySQL Enterprise] New package
  packages/mysql_enterprise/_dev/build/build.yml
  packages/mysql_enterprise/_dev/build/docs/README.md
  packages/mysql_enterprise/_dev/deploy/docker/docker-compose.yml
  packages/mysql_enterprise/_dev/deploy/docker/sample_logs/mysql_audit.log
  packages/mysql_enterprise/changelog.yml
  packages/mysql_enterprise/data_stream/audit/_dev/test/pipeline/test-common-config.yml
  packages/mysql_enterprise/data_stream/audit/_dev/test/pipeline/test-mysql-audit.log
  packages/mysql_enterprise/data_stream/audit/_dev/test/pipeline/test-mysql-audit.log-expected.json
  packages/mysql_enterprise/data_stream/audit/_dev/test/system/test-logfile-config.yml
  packages/mysql_enterprise/data_stream/audit/agent/stream/stream.yml.hbs
  packages/mysql_enterprise/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/mysql_enterprise/data_stream/audit/fields/agent.yml
  packages/mysql_enterprise/data_stream/audit/fields/base-fields.yml
  packages/mysql_enterprise/data_stream/audit/fields/ecs.yml
  packages/mysql_enterprise/data_stream/audit/fields/fields.yml
  packages/mysql_enterprise/data_stream/audit/manifest.yml
  packages/mysql_enterprise/data_stream/audit/sample_event.json
  packages/mysql_enterprise/docs/README.md
  packages/mysql_enterprise/img/logo_mysql.svg
  packages/mysql_enterprise/manifest.yml
Labels: Team:Security-External Integrations

#2739 [mimecast] Add content-disposition to test logs
  packages/mimecast/_dev/deploy/docker/files/config.yml
  packages/mimecast/changelog.yml
  packages/mimecast/data_stream/siem_logs/sample_event.json
  packages/mimecast/docs/README.md
  packages/mimecast/manifest.yml
Labels: Team:Security-External Integrations, Integration:Mimecast

#2718 [tenable_sc] Add User-Agent and batch_size config
  packages/tenable_sc/_dev/build/docs/README.md
  packages/tenable_sc/_dev/deploy/docker/files/config.yml
  packages/tenable_sc/changelog.yml
  packages/tenable_sc/data_stream/asset/_dev/test/pipeline/test-asset.log-expected.json
  packages/tenable_sc/data_stream/asset/_dev/test/system/test-default-config.yml
  packages/tenable_sc/data_stream/asset/agent/stream/httpjson.yml.hbs
  packages/tenable_sc/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
  packages/tenable_sc/data_stream/asset/fields/fields.yml
  packages/tenable_sc/data_stream/asset/sample_event.json
  packages/tenable_sc/data_stream/plugin/_dev/test/pipeline/test-plugin.log-expected.json
  packages/tenable_sc/data_stream/plugin/_dev/test/system/test-default-config.yml
  packages/tenable_sc/data_stream/plugin/agent/stream/httpjson.yml.hbs
  packages/tenable_sc/data_stream/plugin/sample_event.json
  packages/tenable_sc/data_stream/vulnerability/_dev/test/pipeline/test-vulnerability.log-expected.json
  packages/tenable_sc/data_stream/vulnerability/_dev/test/system/test-default-config.yml
  packages/tenable_sc/data_stream/vulnerability/agent/stream/httpjson.yml.hbs
  packages/tenable_sc/data_stream/vulnerability/sample_event.json
  packages/tenable_sc/docs/README.md
  packages/tenable_sc/kibana/dashboard/tenable_sc-b9b277f0-2c11-11ec-b3e0-f3fd7c471f4b.json
  packages/tenable_sc/kibana/search/tenable_sc-e23be000-8970-11ec-a56b-9fd8deec1ba2.json
  packages/tenable_sc/kibana/visualization/tenable_sc-2b883920-88c7-11ec-a56b-9fd8deec1ba2.json
  packages/tenable_sc/kibana/visualization/tenable_sc-5de3dfd0-30bd-11ec-b7d2-eba3454d2335.json
  packages/tenable_sc/kibana/visualization/tenable_sc-773a1570-323a-11ec-b7d2-eba3454d2335.json
  packages/tenable_sc/kibana/visualization/tenable_sc-8b4a4cd0-30bc-11ec-b7d2-eba3454d2335.json
  packages/tenable_sc/kibana/visualization/tenable_sc-b1c8bb30-30bc-11ec-b7d2-eba3454d2335.json
  packages/tenable_sc/kibana/visualization/tenable_sc-c16a8ae0-30bd-11ec-b7d2-eba3454d2335.json
  packages/tenable_sc/kibana/visualization/tenable_sc-d27cc590-88c5-11ec-a56b-9fd8deec1ba2.json
  packages/tenable_sc/manifest.yml
Labels: Team:Security-External Integrations, Integration:TenableSC
