Repository elastic/integrations, pull requests merged in 2022-01, with the labels that each got.

#2296 [microsoft_dhcp] Add more event.action and event.outcome values
  packages/microsoft_dhcp/changelog.yml
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_dhcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Microsoft_dhcp

#2320 packages/sophos/xg: fix kv split and handle syslog headers
  packages/sophos/changelog.yml
  packages/sophos/data_stream/utm/_dev/test/pipeline/test-generated.log-expected.json
  packages/sophos/data_stream/utm/sample_event.json
  packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-xg.log
  packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-xg.log-expected.json
  packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
  packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/waf.yml
  packages/sophos/data_stream/xg/fields/ecs.yml
  packages/sophos/data_stream/xg/fields/fields.yml
  packages/sophos/data_stream/xg/sample_event.json
  packages/sophos/docs/README.md
  packages/sophos/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Sophos, 8.1-candidate

#2462 [Cisco Umbrella] adding support for Cisco Managed S3 buckets and non SQS
  packages/cisco_umbrella/_dev/build/docs/README.md
  packages/cisco_umbrella/changelog.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-cloudfirewalllogs.log-config.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-cloudfirewalllogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-config.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-dnslogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-iplogs.log-config.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-iplogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-proxylogs.log-config.yml
  packages/cisco_umbrella/data_stream/log/_dev/test/pipeline/test-umbrella-proxylogs.log-expected.json
  packages/cisco_umbrella/data_stream/log/agent/stream/aws-s3.yml.hbs
  packages/cisco_umbrella/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_umbrella/data_stream/log/fields/ecs.yml
  packages/cisco_umbrella/data_stream/log/fields/fields.yml
  packages/cisco_umbrella/data_stream/log/manifest.yml
  packages/cisco_umbrella/docs/README.md
  packages/cisco_umbrella/manifest.yml
Labels: Team:Security-External Integrations

#2471 [hashicorp_vault] Make hashicorp_vault.audit.request.id optional in pipeline
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-audit.log
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-common-config.yml
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-faked-all-fields.log-expected.json
  packages/hashicorp_vault/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/hashicorp_vault/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/hashicorp_vault/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/manifest.yml
Labels: bug, Team:Security-External Integrations

#2469 Add memory.workingset.limit.pct field in container and pod data stream
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/container/fields/fields.yml
  packages/kubernetes/data_stream/container/sample_event.json
  packages/kubernetes/data_stream/pod/fields/fields.yml
  packages/kubernetes/data_stream/pod/sample_event.json
  packages/kubernetes/docs/kubelet.md
  packages/kubernetes/manifest.yml
Labels: enhancement, Team:Integrations

#2487 Fix timestamp issues in pipeline tests
  packages/cisco/data_stream/asa/_dev/test/pipeline/test-common-config.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/cyberarkpas/data_stream/audit/_dev/test/pipeline/test-common-config.yml
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/pfsense/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/snort/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/snort/data_stream/log/_dev/test/pipeline/test-log-full.log-config.yml
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog-sample.log-config.yml
  packages/system/data_stream/syslog/_dev/test/pipeline/test-darwin-syslog.log-config.yml
Labels: Team:Integrations

#2475 [cisco_ios] Add syslog header and timestamp parsing
  packages/cisco_ios/_dev/deploy/docker/sample_logs/cisco-ios.log
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-config.yml
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-expected.json
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format.log
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format.log-expected.json
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
  packages/cisco_ios/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_ios/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/data_stream/log/fields/ecs.yml
  packages/cisco_ios/data_stream/log/fields/fields.yml
  packages/cisco_ios/data_stream/log/manifest.yml
  packages/cisco_ios/docs/README.md
  packages/cisco_ios/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Cisco

#2187 [symantec_endpoint] New package for Symantec Endpoint Protection logs
  packages/symantec_endpoint/_dev/build/build.yml
  packages/symantec_endpoint/_dev/build/docs/README.md
  packages/symantec_endpoint/_dev/deploy/docker/docker-compose.yml
  packages/symantec_endpoint/_dev/deploy/docker/sample_logs/symantec_endpoint.log
  packages/symantec_endpoint/changelog.yml
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-administrative.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-administrative.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-activity.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-activity.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-behavior.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-behavior.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-packet.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-packet.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-proactive-detection-sonar.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-proactive-detection-sonar.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-risk.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-risk.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-scan.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-scan.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-security.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-security.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-system.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-system.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-traffic.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-agent-traffic.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-policy.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-policy.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-remove-mapped-fields.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-remove-mapped-fields.log-config.yml
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-remove-mapped-fields.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc3164.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc3164.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc5424.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-rfc5424.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-system.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-system.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-text-log-dump.log
  packages/symantec_endpoint/data_stream/log/_dev/test/pipeline/test-text-log-dump.log-expected.json
  packages/symantec_endpoint/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/symantec_endpoint/data_stream/log/_dev/test/system/test-tcp-config.yml
  packages/symantec_endpoint/data_stream/log/_dev/test/system/test-udp-config.yml
  packages/symantec_endpoint/data_stream/log/agent/stream/logfile.yml.hbs
  packages/symantec_endpoint/data_stream/log/agent/stream/tcp.yml.hbs
  packages/symantec_endpoint/data_stream/log/agent/stream/udp.yml.hbs
  packages/symantec_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/symantec_endpoint/data_stream/log/fields/agent.yml
  packages/symantec_endpoint/data_stream/log/fields/base-fields.yml
  packages/symantec_endpoint/data_stream/log/fields/ecs.yml
  packages/symantec_endpoint/data_stream/log/fields/fields.yml
  packages/symantec_endpoint/data_stream/log/manifest.yml
  packages/symantec_endpoint/data_stream/log/sample_event.json
  packages/symantec_endpoint/docs/README.md
  packages/symantec_endpoint/img/logo.svg
  packages/symantec_endpoint/img/symantec-endpoint-logs-overview.png
  packages/symantec_endpoint/kibana/dashboard/symantec_endpoint-3ac0a690-5f71-11ec-85e4-338fc80d8393.json
  packages/symantec_endpoint/manifest.yml
Labels: Team:Security-External Integrations, Integration:Symantec-Endpoint, New Integration

#2501 Ignore uri_parts failures in zeek.http
  packages/zeek/changelog.yml
  packages/zeek/data_stream/http/_dev/test/pipeline/test-http.log
  packages/zeek/data_stream/http/_dev/test/pipeline/test-http.log-expected.json
  packages/zeek/data_stream/http/elasticsearch/ingest_pipeline/default.yml
  packages/zeek/manifest.yml
Labels: Team:Security-External Integrations, Integration:Zeek

#2524 Osquery_manager: Add back the explicit mapping for the known osquery text/keyword fields text/keyword fields
  packages/osquery_manager/changelog.yml
  packages/osquery_manager/data_stream/result/fields/osquery.yml
  packages/osquery_manager/manifest.yml
Labels: bug

#2486 [etcd] Upgrade ECS to 8.0.0
  packages/etcd/_dev/build/build.yml
  packages/etcd/changelog.yml
  packages/etcd/data_stream/metrics/sample_event.json
  packages/etcd/docs/README.md
  packages/etcd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2484 [cockroachdb] Upgrade ECS to 8.0.0
  packages/cockroachdb/_dev/build/build.yml
  packages/cockroachdb/changelog.yml
  packages/cockroachdb/data_stream/status/elasticsearch/ingest_pipeline/default.yml
  packages/cockroachdb/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2483 [cassandra] Upgrade ECS to 8.0.0
  packages/cassandra/_dev/build/build.yml
  packages/cassandra/changelog.yml
  packages/cassandra/data_stream/log/_dev/test/pipeline/test-cassandra.log-expected.json
  packages/cassandra/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cassandra/data_stream/log/sample_event.json
  packages/cassandra/data_stream/metrics/elasticsearch/ingest_pipeline/default.yml
  packages/cassandra/data_stream/metrics/sample_event.json
  packages/cassandra/docs/README.md
  packages/cassandra/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2482 [azure_metrics] Upgrade ECS to 8.0.0
  packages/azure_metrics/_dev/build/build.yml
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/data_stream/compute_vm/elasticsearch/ingest_pipeline/default.yml
  packages/azure_metrics/data_stream/compute_vm_scaleset/elasticsearch/ingest_pipeline/default.yml
  packages/azure_metrics/data_stream/storage_account/elasticsearch/ingest_pipeline/default.yml
  packages/azure_metrics/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2481 [azure_billing] Upgrade ECS to 8.0.0
  packages/azure_billing/_dev/build/build.yml
  packages/azure_billing/changelog.yml
  packages/azure_billing/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2480 [azure_application_insights] Upgrade ECS to 8.0.0
  packages/azure_application_insights/_dev/build/build.yml
  packages/azure_application_insights/changelog.yml
  packages/azure_application_insights/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2479 [azure] Upgrade ECS to 8.0.0
  packages/azure/_dev/build/build.yml
  packages/azure/changelog.yml
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-edgecases.log-expected.json
  packages/azure/data_stream/activitylogs/_dev/test/pipeline/test-activitylogs-raw.log-expected.json
  packages/azure/data_stream/activitylogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/auditlogs/_dev/test/pipeline/test-auditlogs-raw.log-expected.json
  packages/azure/data_stream/auditlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/eventhub/_dev/test/pipeline/test-eventhub-raw.log-expected.json
  packages/azure/data_stream/eventhub/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-invalid-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-kube.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-raw.log-expected.json
  packages/azure/data_stream/platformlogs/_dev/test/pipeline/test-platformlogs-remote-raw.log-expected.json
  packages/azure/data_stream/platformlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-managed-identity.log-expected.json
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-non-interactive-user.log-expected.json
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-service-principal.log-expected.json
  packages/azure/data_stream/signinlogs/_dev/test/pipeline/test-signinlogs-raw.log-expected.json
  packages/azure/data_stream/signinlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/data_stream/springcloudlogs/_dev/test/pipeline/test-springcloudlogs-raw.log-expected.json
  packages/azure/data_stream/springcloudlogs/elasticsearch/ingest_pipeline/default.yml
  packages/azure/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2368 [1password] Upgrade ECS to 8.0.0
  packages/1password/_dev/build/build.yml
  packages/1password/_dev/build/docs/README.md
  packages/1password/changelog.yml
  packages/1password/data_stream/item_usages/_dev/test/pipeline/test-itemusages.json-expected.json
  packages/1password/data_stream/item_usages/elasticsearch/ingest_pipeline/default.yml
  packages/1password/data_stream/item_usages/fields/ecs.yml
  packages/1password/data_stream/item_usages/sample_event.json
  packages/1password/data_stream/signin_attempts/_dev/test/pipeline/test-signinattempts.json-expected.json
  packages/1password/data_stream/signin_attempts/elasticsearch/ingest_pipeline/default.yml
  packages/1password/data_stream/signin_attempts/fields/ecs.yml
  packages/1password/data_stream/signin_attempts/sample_event.json
  packages/1password/docs/README.md
  packages/1password/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2473 [microsoft_dhcp] Add DHCPv6 support
  packages/microsoft_dhcp/_dev/build/docs/README.md
  packages/microsoft_dhcp/_dev/deploy/docker/sample_logs/test-dhcp.log
  packages/microsoft_dhcp/_dev/deploy/docker/sample_logs/test-dhcpV6.log
  packages/microsoft_dhcp/changelog.yml
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-log.log-config.yml
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-logv6.log
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-logv6.log-config.yml
  packages/microsoft_dhcp/data_stream/log/_dev/test/pipeline/test-logv6.log-expected.json
  packages/microsoft_dhcp/data_stream/log/agent/stream/logfile.yml.hbs
  packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcp.yml
  packages/microsoft_dhcp/data_stream/log/elasticsearch/ingest_pipeline/dhcpv6.yml
  packages/microsoft_dhcp/data_stream/log/fields/ecs.yml
  packages/microsoft_dhcp/data_stream/log/fields/fields.yml
  packages/microsoft_dhcp/docs/README.md
  packages/microsoft_dhcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2529 [system] Fix incorrect PR number in changelog
  packages/system/changelog.yml
Labels: bug, Team:Security-External Integrations

#2537 Fix admin parameter processing by removing early return from script
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-application.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-calendar.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chat.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-chromeos.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-contacts.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-delegatedadmin.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-docs.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-domain.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-gmail.log
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-gmail.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-groups.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-licenses.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-mobile.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-org.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-security.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-sites.log-expected.json
  packages/google_workspace/data_stream/admin/_dev/test/pipeline/test-admin-user.log-expected.json
  packages/google_workspace/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
  packages/google_workspace/manifest.yml
Labels: bug, Team:Security-External Integrations

#2525 [iptables] Add journald input support iptables
  packages/iptables/_dev/build/docs/README.md
  packages/iptables/_dev/deploy/docker/Dockerfile
  packages/iptables/_dev/deploy/docker/docker-compose.yml
  packages/iptables/_dev/deploy/docker/sample_logs/iptables.journal.export
  packages/iptables/changelog.yml
  packages/iptables/data_stream/log/_dev/test/pipeline/test-common-config.yml
  packages/iptables/data_stream/log/_dev/test/pipeline/test-iptables-raw.log-expected.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-journald.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-journald.json-expected.json
  packages/iptables/data_stream/log/_dev/test/pipeline/test-ubiquiti.log-config.yml
  packages/iptables/data_stream/log/_dev/test/pipeline/test-ubiquiti.log-expected.json
  packages/iptables/data_stream/log/_dev/test/system/test-journald-config.yml
  packages/iptables/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/iptables/data_stream/log/agent/stream/journald.yml.hbs
  packages/iptables/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/iptables/data_stream/log/fields/ecs.yml
  packages/iptables/data_stream/log/fields/journald-input.yml
  packages/iptables/data_stream/log/manifest.yml
  packages/iptables/docs/README.md
  packages/iptables/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:iptables

#2530 [AWS/vpcflow] add description of supported vpcflow formats
  packages/aws/_dev/build/docs/vpcflow.md
  packages/aws/changelog.yml
  packages/aws/docs/vpcflow.md
  packages/aws/manifest.yml
Labels: documentation, Team:Security-External Integrations

#2485 [MISP] Adding dashboards
  packages/ti_misp/changelog.yml
  packages/ti_misp/data_stream/threat/_dev/test/pipeline/test-misp-attributes-ndjson.log-expected.json
  packages/ti_misp/data_stream/threat/_dev/test/pipeline/test-misp-sample-ndjson.log-expected.json
  packages/ti_misp/data_stream/threat/fields/base-fields.yml
  packages/ti_misp/data_stream/threat/sample_event.json
  packages/ti_misp/docs/README.md
  packages/ti_misp/kibana/dashboard/ti_misp-32d9c020-71ea-11ec-8197-5d53a5437877.json
  packages/ti_misp/kibana/dashboard/ti_misp-399bb8d0-71ec-11ec-8197-5d53a5437877.json
  packages/ti_misp/kibana/dashboard/ti_misp-56ed8040-6c7d-11ec-9bce-f7a4dc94c294.json
  packages/ti_misp/kibana/tag/ti_misp-550ba0e0-6c7d-11ec-9bce-f7a4dc94c294.json
  packages/ti_misp/manifest.yml
Labels: Team:Security-External Integrations, Integration:MISP

#2543 [ThreatQ] Adding threat.feed ECS fields and dashboards
  packages/ti_threatq/changelog.yml
  packages/ti_threatq/data_stream/threat/fields/base-fields.yml
  packages/ti_threatq/data_stream/threat/sample_event.json
  packages/ti_threatq/docs/README.md
  packages/ti_threatq/kibana/dashboard/ti_threatq-a05fd810-78f1-11ec-a97c-7db1518ab848.json
  packages/ti_threatq/kibana/dashboard/ti_threatq-ab289de0-78f1-11ec-a97c-7db1518ab848.json
  packages/ti_threatq/kibana/dashboard/ti_threatq-b45b0c40-78f1-11ec-a97c-7db1518ab848.json
  packages/ti_threatq/kibana/tag/ti_threatq-c0cca010-78f1-11ec-a97c-7db1518ab848.json
  packages/ti_threatq/manifest.yml
Labels: Team:Security-External Integrations

#2544 [AbuseCH] removing tag from dashboard
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/kibana/dashboard/ti_abusech-2457fb50-3bc3-11ec-ae8c-7d00429ad420.json
  packages/ti_abusech/kibana/dashboard/ti_abusech-6a90c980-3b32-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_abusech/kibana/dashboard/ti_abusech-c0d8d1f0-3b20-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_abusech/kibana/tag/ti_abusech-320c5c80-3b0c-11ec-ae50-2fdf1e96c6a6.json
  packages/ti_abusech/manifest.yml
Labels: Team:Security-External Integrations

#2540 [OTX] Updating threat.feed fields and adding dashboards
  packages/ti_otx/changelog.yml
  packages/ti_otx/data_stream/threat/fields/base-fields.yml
  packages/ti_otx/docs/README.md
  packages/ti_otx/kibana/dashboard/ti_otx-7da241a0-71f3-11ec-9910-d1ceb8a1734b.json
  packages/ti_otx/kibana/dashboard/ti_otx-83b01770-71f3-11ec-9910-d1ceb8a1734b.json
  packages/ti_otx/kibana/dashboard/ti_otx-8957ff80-71f3-11ec-9910-d1ceb8a1734b.json
  packages/ti_otx/kibana/tag/ti_otx-6bc35230-71fd-11ec-9910-d1ceb8a1734b.json
  packages/ti_otx/manifest.yml
Labels: Team:Security-External Integrations

#2527 [windows] Add provider name check to forwarded/security conditional
  packages/windows/changelog.yml
  packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/default.yml
  packages/windows/manifest.yml
Labels: bug, Team:Security-External Integrations

#2536 Change cloudwatch metrics and logs default to false
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudwatch_logs/manifest.yml
  packages/aws/data_stream/cloudwatch_metrics/manifest.yml
  packages/aws/manifest.yml
Labels: Team:Integrations

#2319 [Synthetics] add index optimizations
  packages/synthetics/changelog.yml
  packages/synthetics/data_stream/browser/fields/ecs.yml
  packages/synthetics/data_stream/browser/manifest.yml
  packages/synthetics/data_stream/browser_network/fields/ecs.yml
  packages/synthetics/data_stream/browser_network/fields/http.yml
  packages/synthetics/data_stream/browser_network/manifest.yml
  packages/synthetics/data_stream/browser_screenshot/manifest.yml
  packages/synthetics/data_stream/http/fields/ecs.yml
  packages/synthetics/data_stream/http/manifest.yml
  packages/synthetics/data_stream/icmp/fields/ecs.yml
  packages/synthetics/data_stream/icmp/manifest.yml
  packages/synthetics/data_stream/tcp/fields/ecs.yml
  packages/synthetics/data_stream/tcp/manifest.yml
  packages/synthetics/manifest.yml
Labels: enhancement, Team:Uptime, v8.0.0

#2516 [zookeeper] Upgrade ECS to 8.0.0
  packages/zookeeper/_dev/build/build.yml
  packages/zookeeper/changelog.yml
  packages/zookeeper/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2513 [traefik] Upgrade ECS to 8.0.0
  packages/traefik/_dev/build/build.yml
  packages/traefik/changelog.yml
  packages/traefik/data_stream/access/_dev/test/pipeline/test-format-common.log-expected.json
  packages/traefik/data_stream/access/_dev/test/pipeline/test-format-json.log-expected.json
  packages/traefik/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/traefik/data_stream/access/sample_event.json
  packages/traefik/data_stream/health/sample_event.json
  packages/traefik/docs/README.md
  packages/traefik/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2511 [stan] Upgrade ECS to 8.0.0
  packages/stan/_dev/build/build.yml
  packages/stan/changelog.yml
  packages/stan/data_stream/channels/sample_event.json
  packages/stan/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
  packages/stan/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/stan/data_stream/log/sample_event.json
  packages/stan/data_stream/stats/sample_event.json
  packages/stan/data_stream/subscriptions/sample_event.json
  packages/stan/docs/README.md
  packages/stan/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2510 [redis] Upgrade ECS to 8.0.0
  packages/redis/_dev/build/build.yml
  packages/redis/changelog.yml
  packages/redis/data_stream/log/_dev/test/pipeline/test-redis-5-0-3.log-expected.json
  packages/redis/data_stream/log/_dev/test/pipeline/test-redis-darwin-3-0-2.log-expected.json
  packages/redis/data_stream/log/_dev/test/pipeline/test-redis-debian-1-2-6.log-expected.json
  packages/redis/data_stream/log/_dev/test/pipeline/test-redis-windows-2-4-6.log-expected.json
  packages/redis/data_stream/log/_dev/test/pipeline/test-redis.log-expected.json
  packages/redis/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/redis/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2509 [rabbitmq] Upgrade ECS to 8.0.0
  packages/rabbitmq/_dev/build/build.yml
  packages/rabbitmq/changelog.yml
  packages/rabbitmq/data_stream/log/_dev/test/pipeline/test-rabbitmq.log-expected.json
  packages/rabbitmq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/rabbitmq/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2507 [postgresql] Upgrade ECS to 8.0.0
  packages/postgresql/_dev/build/build.yml
  packages/postgresql/changelog.yml
  packages/postgresql/data_stream/activity/sample_event.json
  packages/postgresql/data_stream/bgwriter/sample_event.json
  packages/postgresql/data_stream/database/sample_event.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-10-default.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-10-min-duration-statement.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-4.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-autovacuum-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-connection-disconnection-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-duration-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-ipv6-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-multi-line-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-parse-bind-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-start-stop-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-11-tempfile-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-12-default.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-12-min-duration-statement.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-13-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-13-error-code-csv.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-debian-with-slowlog.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-multi-core.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-9-6-new-timestamp.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-query-steps-slowlog.log-expected.json
  packages/postgresql/data_stream/log/_dev/test/pipeline/test-postgresql-ubuntu-9-5.log-expected.json
  packages/postgresql/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/postgresql/data_stream/statement/sample_event.json
  packages/postgresql/docs/README.md
  packages/postgresql/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2506 [nginx_ingress_controller] Upgrade ECS to 8.0.0
  packages/nginx_ingress_controller/_dev/build/build.yml
  packages/nginx_ingress_controller/changelog.yml
  packages/nginx_ingress_controller/data_stream/access/_dev/test/pipeline/test-ingest-raw.log-expected.json
  packages/nginx_ingress_controller/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/nginx_ingress_controller/data_stream/access/sample_event.json
  packages/nginx_ingress_controller/data_stream/error/_dev/test/pipeline/test-error-raw.log-expected.json
  packages/nginx_ingress_controller/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/nginx_ingress_controller/data_stream/error/sample_event.json
  packages/nginx_ingress_controller/docs/README.md
  packages/nginx_ingress_controller/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2505 [nginx] Upgrade ECS to 8.0.0
  packages/nginx/_dev/build/build.yml
  packages/nginx/changelog.yml
  packages/nginx/data_stream/access/_dev/test/pipeline/test-access.log-expected.json
  packages/nginx/data_stream/access/_dev/test/pipeline/test-nginx.log-expected.json
  packages/nginx/data_stream/access/_dev/test/pipeline/test-test-with-host.log-expected.json
  packages/nginx/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/nginx/data_stream/access/sample_event.json
  packages/nginx/data_stream/error/_dev/test/pipeline/test-error-raw.log-expected.json
  packages/nginx/data_stream/error/elasticsearch/ingest_pipeline/default.yml
  packages/nginx/data_stream/error/sample_event.json
  packages/nginx/data_stream/stubstatus/sample_event.json
  packages/nginx/docs/README.md
  packages/nginx/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2504 [nats] Upgrade ECS to 8.0.0
  packages/nats/_dev/build/build.yml
  packages/nats/changelog.yml
  packages/nats/data_stream/connection/sample_event.json
  packages/nats/data_stream/connections/sample_event.json
  packages/nats/data_stream/log/_dev/test/pipeline/test-log-sample.log-expected.json
  packages/nats/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/nats/data_stream/route/sample_event.json
  packages/nats/data_stream/routes/sample_event.json
  packages/nats/data_stream/stats/sample_event.json
  packages/nats/data_stream/subscriptions/sample_event.json
  packages/nats/docs/README.md
  packages/nats/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2496 [mysql] Upgrade ECS to 8.0.0
  packages/mysql/_dev/build/build.yml
  packages/mysql/changelog.yml
  packages/mysql/data_stream/error/_dev/test/pipeline/test-error.log-expected.json
  packages/mysql/data_stream/error/_dev/test/pipeline/test-mariadb-10-4-8.log-expected.json
  packages/mysql/data_stream/error/_dev/test/pipeline/test-mysql-darwin-brew-5-7-10.log-expected.json
  packages/mysql/data_stream/error/_dev/test/pipeline/test-mysql-ubuntu-5-5-53.log-expected.json
  packages/mysql/data_stream/error/_dev/test/pipeline/test-mysql-ubuntu-8-0-15.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-10-1-21.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-10-2-12.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-10-3-13.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mariadb-explain.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-5-7-22.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-darwin-brew-5-7-10.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-debian-5-7-17.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-debian-5-7-19.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-ubuntu-5-5-53.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-mysql-ubuntu-8-0-15.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-percona-ubuntu-5-7-19-innodb.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-percona-ubuntu-5-7-19.log-expected.json
  packages/mysql/data_stream/slowlog/_dev/test/pipeline/test-percona-ubuntu-8-0-15.log-expected.json
  packages/mysql/docs/README.md
  packages/mysql/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2494 [mongodb] Upgrade ECS to 8.0.0
  packages/mongodb/_dev/build/build.yml
  packages/mongodb/changelog.yml
  packages/mongodb/data_stream/log/_dev/test/pipeline/test-mongodb-debian.log-expected.json
  packages/mongodb/data_stream/log/_dev/test/pipeline/test-mongodb-ubuntu-4-4-4.log-expected.json
  packages/mongodb/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2490 [kafka] Upgrade ECS to 8.0.0
  packages/kafka/_dev/build/build.yml
  packages/kafka/changelog.yml
  packages/kafka/data_stream/log/_dev/test/pipeline/test-controller-2-0-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-controller.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-server-2-0-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-server.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-1-1-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-2-0-0.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change-2-2-2.log-expected.json
  packages/kafka/data_stream/log/_dev/test/pipeline/test-state-change.log-expected.json
  packages/kafka/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/kafka/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2488 [haproxy] Upgrade ECS to 8.0.0
  packages/haproxy/_dev/build/build.yml
  packages/haproxy/_dev/build/docs/README.md
  packages/haproxy/changelog.yml
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-default.log-expected.json
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-haproxy.log-expected.json
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-httplog-no-headers.log-expected.json
  packages/haproxy/data_stream/log/_dev/test/pipeline/test-tcplog.log-expected.json
  packages/haproxy/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/haproxy/data_stream/log/sample_event.json
  packages/haproxy/docs/README.md
  packages/haproxy/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2454 [zoom] Upgrade ECS to 8.0.0
  packages/zoom/_dev/build/build.yml
  packages/zoom/changelog.yml
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-account.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-channel.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-chat-message.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-meeting.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-phone.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-recording.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-user.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-webinar.json-expected.json
  packages/zoom/data_stream/webhook/_dev/test/pipeline/test-zoomroom.json-expected.json
  packages/zoom/data_stream/webhook/elasticsearch/ingest_pipeline/default.yml
  packages/zoom/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2491 [kubernetes] Upgrade ECS to 8.0.0
  packages/kubernetes/_dev/build/build.yml
  packages/kubernetes/changelog.yml
  packages/kubernetes/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.0-candidate

#2478 [aws] Upgrade ECS to 8.0.0
  packages/aws/_dev/build/build.yml
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-add-user-to-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-assume-role-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-change-password-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-cloudtrail-digest-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-console-login-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-key-pair-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-create-virtual-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-deactivate-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-bucket-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-delete-virtual-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-enable-mfa-device-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-insight-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-remove-user-from-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-start-logging-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-stop-logging-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-access-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-accout-password-policy-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-group-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-login-profile-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-trail-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-update-user-json.log-expected.json
  packages/aws/data_stream/cloudtrail/_dev/test/pipeline/test-upload-ssh-public-key-json.log-expected.json
  packages/aws/data_stream/cloudtrail/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/cloudwatch_logs/_dev/test/pipeline/test-cloudwatch-ec2.log-expected.json
  packages/aws/data_stream/cloudwatch_logs/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/ec2_logs/_dev/test/pipeline/test-ec2.log-expected.json
  packages/aws/data_stream/ec2_logs/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/ec2_metrics/sample_event.json
  packages/aws/data_stream/elb_logs/_dev/test/pipeline/test-alb.log-expected.json
  packages/aws/data_stream/elb_logs/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/firewall_logs/_dev/test/pipeline/test-firewall.log-expected.json
  packages/aws/data_stream/firewall_logs/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/s3access/_dev/test/pipeline/test-s3-server-access.log-expected.json
  packages/aws/data_stream/s3access/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-extra-samples.log-expected.json
  packages/aws/data_stream/vpcflow/_dev/test/pipeline/test-tcp-flag-sequence.log-expected.json
  packages/aws/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/waf/_dev/test/pipeline/test-waf.log-expected.json
  packages/aws/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
  packages/aws/docs/ec2.md
  packages/aws/docs/firewall.md
  packages/aws/docs/route53.md
  packages/aws/docs/s3.md
  packages/aws/docs/vpcflow.md
  packages/aws/docs/waf.md
  packages/aws/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2369 [akamai] Upgrade ECS to 8.0.0
  packages/akamai/_dev/build/build.yml
  packages/akamai/changelog.yml
  packages/akamai/data_stream/siem/_dev/test/pipeline/test-http-json.log-expected.json
  packages/akamai/data_stream/siem/elasticsearch/ingest_pipeline/default.yml
  packages/akamai/data_stream/siem/fields/ecs.yml
  packages/akamai/data_stream/siem/sample_event.json
  packages/akamai/docs/README.md
  packages/akamai/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2554 [Github] Remove saved search for testing and update dashboard
  packages/github/changelog.yml
  packages/github/kibana/dashboard/github-8bfd8310-205c-11ec-8b10-11a4c5e322a0.json
  packages/github/kibana/search/github-c5657210-205d-11ec-8b10-11a4c5e322a0.json
  packages/github/manifest.yml
Labels: Team:Security-External Integrations

#2450 [ti_threatq] Upgrade ECS to 8.0.0
  packages/ti_threatq/_dev/build/build.yml
  packages/ti_threatq/changelog.yml
  packages/ti_threatq/data_stream/threat/_dev/test/pipeline/test-threatq-sample-ndjson.log-expected.json
  packages/ti_threatq/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
  packages/ti_threatq/data_stream/threat/sample_event.json
  packages/ti_threatq/docs/README.md
  packages/ti_threatq/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2453 [zerofox] Upgrade ECS to 8.0.0
  packages/zerofox/_dev/build/build.yml
  packages/zerofox/changelog.yml
  packages/zerofox/data_stream/alerts/_dev/test/pipeline/test-alert.json-expected.json
  packages/zerofox/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
  packages/zerofox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2447 [ti_cybersixgill] Upgrade ECS to 8.0.0
  packages/ti_cybersixgill/_dev/build/build.yml
  packages/ti_cybersixgill/changelog.yml
  packages/ti_cybersixgill/data_stream/threat/_dev/test/pipeline/test-cybersixgill.json-expected.json
  packages/ti_cybersixgill/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
  packages/ti_cybersixgill/data_stream/threat/sample_event.json
  packages/ti_cybersixgill/docs/README.md
  packages/ti_cybersixgill/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2448 [ti_misp] Upgrade ECS to 8.0.0
  packages/ti_misp/_dev/build/build.yml
  packages/ti_misp/changelog.yml
  packages/ti_misp/data_stream/threat/_dev/test/pipeline/test-misp-attributes-ndjson.log-expected.json
  packages/ti_misp/data_stream/threat/_dev/test/pipeline/test-misp-sample-ndjson.log-expected.json
  packages/ti_misp/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
  packages/ti_misp/data_stream/threat/sample_event.json
  packages/ti_misp/docs/README.md
  packages/ti_misp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2444 [tenable_sc] Upgrade ECS to 8.0.0
  packages/tenable_sc/_dev/build/build.yml
  packages/tenable_sc/changelog.yml
  packages/tenable_sc/data_stream/asset/_dev/test/pipeline/test-asset.log-expected.json
  packages/tenable_sc/data_stream/asset/elasticsearch/ingest_pipeline/default.yml
  packages/tenable_sc/data_stream/asset/sample_event.json
  packages/tenable_sc/data_stream/plugin/_dev/test/pipeline/test-plugin.log-expected.json
  packages/tenable_sc/data_stream/plugin/elasticsearch/ingest_pipeline/default.yml
  packages/tenable_sc/data_stream/plugin/sample_event.json
  packages/tenable_sc/data_stream/vulnerability/_dev/test/pipeline/test-vulnerability.log-expected.json
  packages/tenable_sc/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
  packages/tenable_sc/data_stream/vulnerability/sample_event.json
  packages/tenable_sc/docs/README.md
  packages/tenable_sc/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2443 [suricata] Upgrade ECS to 8.0.0
  packages/suricata/_dev/build/build.yml
  packages/suricata/_dev/build/docs/README.md
  packages/suricata/changelog.yml
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-6-0.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-dns-4-1-4.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-metadata.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/data_stream/eve/sample_event.json
  packages/suricata/docs/README.md
  packages/suricata/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2439 [snyk] Upgrade ECS to 8.0.0
  packages/snyk/_dev/build/build.yml
  packages/snyk/changelog.yml
  packages/snyk/data_stream/audit/_dev/test/pipeline/test-snyk-audit.log-expected.json
  packages/snyk/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/snyk/data_stream/audit/sample_event.json
  packages/snyk/data_stream/vulnerabilities/_dev/test/pipeline/test-snyk-vulnerabilities.log-expected.json
  packages/snyk/data_stream/vulnerabilities/elasticsearch/ingest_pipeline/default.yml
  packages/snyk/data_stream/vulnerabilities/sample_event.json
  packages/snyk/docs/README.md
  packages/snyk/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2435 [qnap_nas] Upgrade ECS to 8.0.0
  packages/qnap_nas/_dev/build/build.yml
  packages/qnap_nas/changelog.yml
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-access.log-expected.json
  packages/qnap_nas/data_stream/log/_dev/test/pipeline/test-event.log-expected.json
  packages/qnap_nas/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/qnap_nas/data_stream/log/sample_event.json
  packages/qnap_nas/docs/README.md
  packages/qnap_nas/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2431 [panw_cortex_xdr] Upgrade ECS to 8.0.0
  packages/panw_cortex_xdr/_dev/build/build.yml
  packages/panw_cortex_xdr/_dev/build/docs/README.md
  packages/panw_cortex_xdr/changelog.yml
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr-bioc.log-expected.json
  packages/panw_cortex_xdr/data_stream/alerts/_dev/test/pipeline/test-panw-xdr.log-expected.json
  packages/panw_cortex_xdr/data_stream/alerts/elasticsearch/ingest_pipeline/default.yml
  packages/panw_cortex_xdr/data_stream/alerts/sample_event.json
  packages/panw_cortex_xdr/docs/README.md
  packages/panw_cortex_xdr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2430 [panw] Upgrade ECS to 8.0.0
  packages/panw/_dev/build/build.yml
  packages/panw/changelog.yml
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-other-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-inc-traffic.json-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-threat-sample.log-expected.json
  packages/panw/data_stream/panos/_dev/test/pipeline/test-panw-panos-traffic-sample.log-expected.json
  packages/panw/data_stream/panos/elasticsearch/ingest_pipeline/default.yml
  packages/panw/data_stream/panos/fields/ecs.yml
  packages/panw/data_stream/panos/sample_event.json
  packages/panw/docs/README.md
  packages/panw/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2449 [ti_otx] Upgrade ECS to 8.0.0
  packages/ti_otx/_dev/build/build.yml
  packages/ti_otx/changelog.yml
  packages/ti_otx/data_stream/threat/_dev/test/pipeline/test-otx-sample-ndjson.log-expected.json
  packages/ti_otx/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
  packages/ti_otx/data_stream/threat/sample_event.json
  packages/ti_otx/docs/README.md
  packages/ti_otx/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2428 [okta] Upgrade ECS to 8.0.0
  packages/okta/_dev/build/build.yml
  packages/okta/changelog.yml
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
  packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/okta/data_stream/system/sample_event.json
  packages/okta/docs/README.md
  packages/okta/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2427 [o365] Upgrade ECS to 8.0.0
  packages/o365/_dev/build/build.yml
  packages/o365/_dev/build/docs/README.md
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/_dev/test/pipeline/test-azuread-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-azuread-sts-logon-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-data-insights-api-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-dlp-exchange-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-dlp-sharepoint-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-admin-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-exchange-item-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-ip-formats-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-ms-teams-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-parameter-string.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sec-comp-alerts-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepoint-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sharepointfileop-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-sp-sharing-op-events.json-expected.json
  packages/o365/data_stream/audit/_dev/test/pipeline/test-yammer-events.json-expected.json
  packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/o365/data_stream/audit/sample_event.json
  packages/o365/docs/README.md
  packages/o365/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2422 [microsoft_defender_endpoint] Upgrade ECS to 8.0.0
  packages/microsoft_defender_endpoint/_dev/build/build.yml
  packages/microsoft_defender_endpoint/_dev/build/docs/README.md
  packages/microsoft_defender_endpoint/changelog.yml
  packages/microsoft_defender_endpoint/data_stream/log/_dev/test/pipeline/test-defenderatp.log-expected.json
  packages/microsoft_defender_endpoint/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_defender_endpoint/data_stream/log/sample_event.json
  packages/microsoft_defender_endpoint/docs/README.md
  packages/microsoft_defender_endpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2420 [mattermost] Upgrade ECS to 8.0.0
  packages/mattermost/_dev/build/build.yml
  packages/mattermost/changelog.yml
  packages/mattermost/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/mattermost/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/mattermost/data_stream/audit/sample_event.json
  packages/mattermost/docs/README.md
  packages/mattermost/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2419 [keycloak] Upgrade ECS to 8.0.0
  packages/keycloak/_dev/build/build.yml
  packages/keycloak/changelog.yml
  packages/keycloak/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/keycloak/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/keycloak/data_stream/log/sample_event.json
  packages/keycloak/docs/README.md
  packages/keycloak/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2418 [juniper_srx] Upgrade ECS to 8.0.0
  packages/juniper_srx/_dev/build/build.yml
  packages/juniper_srx/changelog.yml
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper_srx/data_stream/log/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper_srx/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/juniper_srx/data_stream/log/fields/ecs.yml
  packages/juniper_srx/data_stream/log/sample_event.json
  packages/juniper_srx/docs/README.md
  packages/juniper_srx/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2409 [hashicorp_vault] Upgrade ECS to 8.0.0
  packages/hashicorp_vault/_dev/build/build.yml
  packages/hashicorp_vault/changelog.yml
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/hashicorp_vault/data_stream/audit/_dev/test/pipeline/test-faked-all-fields.log-expected.json
  packages/hashicorp_vault/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/data_stream/audit/sample_event.json
  packages/hashicorp_vault/data_stream/log/_dev/test/pipeline/test-log.log-expected.json
  packages/hashicorp_vault/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/data_stream/log/sample_event.json
  packages/hashicorp_vault/data_stream/metrics/elasticsearch/ingest_pipeline/default.yml
  packages/hashicorp_vault/data_stream/metrics/sample_event.json
  packages/hashicorp_vault/docs/README.md
  packages/hashicorp_vault/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2406 [gcp] Upgrade ECS to 8.0.0
  packages/gcp/_dev/build/build.yml
  packages/gcp/changelog.yml
  packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/audit/sample_event.json
  packages/gcp/data_stream/firewall/_dev/test/pipeline/test-firewall.log-expected.json
  packages/gcp/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/firewall/sample_event.json
  packages/gcp/data_stream/vpcflow/_dev/test/pipeline/test-vpcflow.log-expected.json
  packages/gcp/data_stream/vpcflow/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/vpcflow/sample_event.json
  packages/gcp/docs/README.md
  packages/gcp/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2404 [fireeye] Upgrade ECS to 8.0.0
  packages/fireeye/_dev/build/build.yml
  packages/fireeye/changelog.yml
  packages/fireeye/data_stream/nx/_dev/test/pipeline/test-nx.log-expected.json
  packages/fireeye/data_stream/nx/elasticsearch/ingest_pipeline/default.yml
  packages/fireeye/data_stream/nx/sample_event.json
  packages/fireeye/docs/README.md
  packages/fireeye/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2398 [crowdstrike] Upgrade ECS to 8.0.0
  packages/crowdstrike/_dev/build/build.yml
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-audit-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-events.log-expected.json
  packages/crowdstrike/data_stream/falcon/_dev/test/pipeline/test-falcon-sample.log-expected.json
  packages/crowdstrike/data_stream/falcon/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/data_stream/falcon/sample_event.json
  packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log-expected.json
  packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/data_stream/fdr/sample_event.json
  packages/crowdstrike/docs/README.md
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2397 [cloudflare] Upgrade ECS to 8.0.0
  packages/cloudflare/_dev/build/build.yml
  packages/cloudflare/changelog.yml
  packages/cloudflare/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/cloudflare/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/cloudflare/data_stream/audit/sample_event.json
  packages/cloudflare/data_stream/logpull/_dev/test/pipeline/test-http-json.log-expected.json
  packages/cloudflare/data_stream/logpull/elasticsearch/ingest_pipeline/default.yml
  packages/cloudflare/data_stream/logpull/sample_event.json
  packages/cloudflare/docs/README.md
  packages/cloudflare/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2392 [cisco_ios] Upgrade ECS to 8.0.0
  packages/cisco_ios/_dev/build/build.yml
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-cisco-ios.log-expected.json
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format-tzoffset.log-expected.json
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-date-format.log-expected.json
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-syslog.log-expected.json
  packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/data_stream/log/sample_event.json
  packages/cisco_ios/docs/README.md
  packages/cisco_ios/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2391 [cisco_ftd] Upgrade ECS to 8.0.0
  packages/cisco_ftd/_dev/build/build.yml
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-intrusion.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-no-type-id.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-connection.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-malware-site.log-expected.json
  packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ftd/data_stream/log/fields/ecs.yml
  packages/cisco_ftd/data_stream/log/sample_event.json
  packages/cisco_ftd/docs/README.md
  packages/cisco_ftd/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2390 [cisco_duo] Upgrade ECS to 8.0.0
  packages/cisco_duo/_dev/build/build.yml
  packages/cisco_duo/changelog.yml
  packages/cisco_duo/data_stream/admin/_dev/test/pipeline/test-admin.log-expected.json
  packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_duo/data_stream/admin/sample_event.json
  packages/cisco_duo/data_stream/auth/_dev/test/pipeline/test-auth.log-expected.json
  packages/cisco_duo/data_stream/auth/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_duo/data_stream/auth/sample_event.json
  packages/cisco_duo/data_stream/offline_enrollment/_dev/test/pipeline/test-offline-enrollment.log-expected.json
  packages/cisco_duo/data_stream/offline_enrollment/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_duo/data_stream/offline_enrollment/sample_event.json
  packages/cisco_duo/data_stream/summary/_dev/test/pipeline/test-summary.log-expected.json
  packages/cisco_duo/data_stream/summary/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_duo/data_stream/summary/sample_event.json
  packages/cisco_duo/data_stream/telephony/_dev/test/pipeline/test-telephony.log-expected.json
  packages/cisco_duo/data_stream/telephony/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_duo/data_stream/telephony/sample_event.json
  packages/cisco_duo/docs/README.md
  packages/cisco_duo/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2389 [cisco_asa] Upgrade ECS to 8.0.0
  packages/cisco_asa/_dev/build/build.yml
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-additional-messages.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-fix.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa-missing-groups.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-asa.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-dap-records.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-filtered.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-hostnames.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sip.log-expected.json
  packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_asa/data_stream/log/fields/ecs.yml
  packages/cisco_asa/data_stream/log/sample_event.json
  packages/cisco_asa/docs/README.md
  packages/cisco_asa/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2387 [checkpoint] Upgrade ECS to 8.0.0
  packages/checkpoint/_dev/build/build.yml
  packages/checkpoint/_dev/build/docs/README.md
  packages/checkpoint/changelog.yml
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint-with-time.log-expected.json
  packages/checkpoint/data_stream/firewall/_dev/test/pipeline/test-checkpoint.log-expected.json
  packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/checkpoint/data_stream/firewall/sample_event.json
  packages/checkpoint/docs/README.md
  packages/checkpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2386 [cef] Upgrade ECS to 8.0.0
  packages/cef/_dev/build/build.yml
  packages/cef/changelog.yml
  packages/cef/data_stream/log/_dev/test/pipeline/test-cef.log-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-checkpoint.log-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-fp-ngfw-smc.log-expected.json
  packages/cef/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cef/data_stream/log/sample_event.json
  packages/cef/docs/README.md
  packages/cef/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2378 [atlassian_confluence] Upgrade ECS to 8.0.0
  packages/atlassian_confluence/_dev/build/build.yml
  packages/atlassian_confluence/changelog.yml
  packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-api.log-expected.json
  packages/atlassian_confluence/data_stream/audit/_dev/test/pipeline/test-audit-files.log-expected.json
  packages/atlassian_confluence/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/atlassian_confluence/data_stream/audit/sample_event.json
  packages/atlassian_confluence/docs/README.md
  packages/atlassian_confluence/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2376 [atlassian_bitbucket] Upgrade ECS to 8.0.0
  packages/atlassian_bitbucket/_dev/build/build.yml
  packages/atlassian_bitbucket/changelog.yml
  packages/atlassian_bitbucket/data_stream/audit/_dev/test/pipeline/test-audit-api.log-expected.json
  packages/atlassian_bitbucket/data_stream/audit/_dev/test/pipeline/test-audit-files.log-expected.json
  packages/atlassian_bitbucket/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/atlassian_bitbucket/data_stream/audit/sample_event.json
  packages/atlassian_bitbucket/docs/README.md
  packages/atlassian_bitbucket/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2152 Integration for Auth0
  packages/auth0/_dev/build/build.yml
  packages/auth0/_dev/build/docs/README.md
  packages/auth0/_dev/deploy/docker/docker-compose.yml
  packages/auth0/_dev/deploy/docker/sample_logs/auth0-ndjson.log
  packages/auth0/changelog.yml
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-common-config.yml
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-login-failure.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-login-failure.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-login-success.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-login-success.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-logout-success.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-logout-success.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-mgmt-api-success.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-mgmt-api-success.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-signup-failure.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-signup-failure.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-signup-success.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-signup-success.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-token-xchg-success.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-token-xchg-success.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-user-behaviour-fail.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-user-behaviour-fail.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-user-behaviour-success.json
  packages/auth0/data_stream/logs/_dev/test/pipeline/test-user-behaviour-success.json-expected.json
  packages/auth0/data_stream/logs/_dev/test/system/test-auth0-http-config.yml
  packages/auth0/data_stream/logs/_dev/test/system/test-auth0-https-config.yml
  packages/auth0/data_stream/logs/agent/stream/http_endpoint.yml.hbs
  packages/auth0/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
  packages/auth0/data_stream/logs/fields/agent.yml
  packages/auth0/data_stream/logs/fields/base-fields.yml
  packages/auth0/data_stream/logs/fields/ecs.yml
  packages/auth0/data_stream/logs/fields/fields.yml
  packages/auth0/data_stream/logs/manifest.yml
  packages/auth0/data_stream/logs/sample_event.json
  packages/auth0/docs/README.md
  packages/auth0/img/auth0-logo.svg
  packages/auth0/img/auth0-screenshot.png
  packages/auth0/kibana/dashboard/auth0-29fb7200-4062-11ec-b18d-ef6bf98b26bf.json
  packages/auth0/kibana/search/auth0-629b19e0-4061-11ec-b18d-ef6bf98b26bf.json
  packages/auth0/kibana/visualization/auth0-187e7650-42a9-11ec-b9a2-edbe9edd14c9.json
  packages/auth0/manifest.yml
Labels: enhancement, Team:Security-External Integrations, 8.1-candidate

#2522 Add containerd package and cpu,memory,blkio data streams
  packages/containerd/_dev/build/build.yml
  packages/containerd/_dev/build/docs/README.md
  packages/containerd/_dev/deploy/docker/containerdv1.5.2.txt
  packages/containerd/_dev/deploy/docker/docker-compose.yml
  packages/containerd/_dev/deploy/docker/nginx.conf
  packages/containerd/changelog.yml
  packages/containerd/data_stream/blkio/_dev/test/system/test-default-config.yml
  packages/containerd/data_stream/blkio/agent/stream/stream.yml.hbs
  packages/containerd/data_stream/blkio/fields/base-fields.yml
  packages/containerd/data_stream/blkio/fields/ecs.yml
  packages/containerd/data_stream/blkio/fields/fields.yml
  packages/containerd/data_stream/blkio/manifest.yml
  packages/containerd/data_stream/blkio/sample_event.json
  packages/containerd/data_stream/cpu/_dev/test/system/test-default-config.yml
  packages/containerd/data_stream/cpu/agent/stream/stream.yml.hbs
  packages/containerd/data_stream/cpu/fields/base-fields.yml
  packages/containerd/data_stream/cpu/fields/ecs.yml
  packages/containerd/data_stream/cpu/fields/fields.yml
  packages/containerd/data_stream/cpu/manifest.yml
  packages/containerd/data_stream/cpu/sample_event.json
  packages/containerd/data_stream/memory/_dev/test/system/test-default-config.yml
  packages/containerd/data_stream/memory/agent/stream/stream.yml.hbs
  packages/containerd/data_stream/memory/fields/base-fields.yml
  packages/containerd/data_stream/memory/fields/ecs.yml
  packages/containerd/data_stream/memory/fields/fields.yml
  packages/containerd/data_stream/memory/manifest.yml
  packages/containerd/data_stream/memory/sample_event.json
  packages/containerd/docs/README.md
  packages/containerd/img/containerd-logo.svg
  packages/containerd/img/containerd-screenshot.png
  packages/containerd/kibana/dashboard/containerd-53ba62e0-79dd-11ec-af32-5f2c93bb0f7e.json
  packages/containerd/manifest.yml
Labels: Team:Integrations

#2379 [atlassian_jira] Upgrade ECS to 8.0.0
  packages/atlassian_jira/_dev/build/build.yml
  packages/atlassian_jira/changelog.yml
  packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-api.log-expected.json
  packages/atlassian_jira/data_stream/audit/_dev/test/pipeline/test-audit-files.log-expected.json
  packages/atlassian_jira/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/atlassian_jira/data_stream/audit/sample_event.json
  packages/atlassian_jira/docs/README.md
  packages/atlassian_jira/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2385 [carbonblack_edr] Upgrade ECS to 8.0.0
  packages/carbonblack_edr/_dev/build/build.yml
  packages/carbonblack_edr/changelog.yml
  packages/carbonblack_edr/data_stream/log/_dev/test/pipeline/test-events.json-expected.json
  packages/carbonblack_edr/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/carbonblack_edr/data_stream/log/fields/ecs.yml
  packages/carbonblack_edr/data_stream/log/fields/fields.yml
  packages/carbonblack_edr/data_stream/log/sample_event.json
  packages/carbonblack_edr/docs/README.md
  packages/carbonblack_edr/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2542 Update and Sync winlog input integrations
  packages/microsoft_sqlserver/changelog.yml
  packages/microsoft_sqlserver/data_stream/audit/_dev/test/pipeline/test-events.json-expected.json
  packages/microsoft_sqlserver/data_stream/audit/agent/stream/winlog.yml.hbs
  packages/microsoft_sqlserver/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_sqlserver/data_stream/audit/manifest.yml
  packages/microsoft_sqlserver/manifest.yml
  packages/system/changelog.yml
  packages/system/data_stream/application/agent/stream/winlog.yml.hbs
  packages/system/data_stream/application/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/application/manifest.yml
  packages/system/data_stream/security/agent/stream/winlog.yml.hbs
  packages/system/data_stream/security/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/security/manifest.yml
  packages/system/data_stream/system/agent/stream/winlog.yml.hbs
  packages/system/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/system/data_stream/system/manifest.yml
  packages/system/manifest.yml
  packages/windows/changelog.yml
  packages/windows/data_stream/forwarded/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/forwarded/elasticsearch/ingest_pipeline/security.yml
  packages/windows/data_stream/forwarded/manifest.yml
  packages/windows/data_stream/powershell/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell/manifest.yml
  packages/windows/data_stream/powershell_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/powershell_operational/manifest.yml
  packages/windows/data_stream/sysmon_operational/agent/stream/winlog.yml.hbs
  packages/windows/data_stream/sysmon_operational/manifest.yml
  packages/windows/manifest.yml
  packages/winlog/changelog.yml
  packages/winlog/data_stream/winlog/agent/stream/winlog.yml.hbs
  packages/winlog/data_stream/winlog/manifest.yml
  packages/winlog/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2567 Tune k8s package settings
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/state_container/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_container/manifest.yml
  packages/kubernetes/data_stream/state_cronjob/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_cronjob/manifest.yml
  packages/kubernetes/data_stream/state_daemonset/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_daemonset/manifest.yml
  packages/kubernetes/data_stream/state_deployment/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_deployment/manifest.yml
  packages/kubernetes/data_stream/state_job/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_job/manifest.yml
  packages/kubernetes/data_stream/state_node/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_node/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolume/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_persistentvolume/manifest.yml
  packages/kubernetes/data_stream/state_persistentvolumeclaim/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_persistentvolumeclaim/manifest.yml
  packages/kubernetes/data_stream/state_pod/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_pod/manifest.yml
  packages/kubernetes/data_stream/state_replicaset/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_replicaset/manifest.yml
  packages/kubernetes/data_stream/state_resourcequota/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_resourcequota/manifest.yml
  packages/kubernetes/data_stream/state_service/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_service/manifest.yml
  packages/kubernetes/data_stream/state_statefulset/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_statefulset/manifest.yml
  packages/kubernetes/data_stream/state_storageclass/agent/stream/stream.yml.hbs
  packages/kubernetes/data_stream/state_storageclass/manifest.yml
  packages/kubernetes/manifest.yml
Labels: Team:Integrations

#2599 [rsa2elk/zscaler] Upgrade to ECS 8.0.0
  packages/zscaler/_dev/build/build.yml
  packages/zscaler/changelog.yml
  packages/zscaler/data_stream/zia/_dev/test/pipeline/test-generated.log-expected.json
  packages/zscaler/data_stream/zia/_dev/test/pipeline/test-zscaler.log-expected.json
  packages/zscaler/data_stream/zia/agent/stream/stream.yml.hbs
  packages/zscaler/data_stream/zia/agent/stream/tcp.yml.hbs
  packages/zscaler/data_stream/zia/agent/stream/udp.yml.hbs
  packages/zscaler/data_stream/zia/elasticsearch/ingest_pipeline/default.yml
  packages/zscaler/data_stream/zia/fields/ecs.yml
  packages/zscaler/data_stream/zia/sample_event.json
  packages/zscaler/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2598 [rsa2elk/tomcat] Upgrade to ECS 8.0.0
  packages/tomcat/_dev/build/build.yml
  packages/tomcat/changelog.yml
  packages/tomcat/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/tomcat/data_stream/log/agent/stream/stream.yml.hbs
  packages/tomcat/data_stream/log/agent/stream/tcp.yml.hbs
  packages/tomcat/data_stream/log/agent/stream/udp.yml.hbs
  packages/tomcat/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/tomcat/data_stream/log/fields/ecs.yml
  packages/tomcat/data_stream/log/sample_event.json
  packages/tomcat/docs/README.md
  packages/tomcat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2597 [rsa2elk/squid] Upgrade to ECS 8.0.0
  packages/squid/_dev/build/build.yml
  packages/squid/changelog.yml
  packages/squid/data_stream/log/_dev/test/pipeline/test-access1.log-expected.json
  packages/squid/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/squid/data_stream/log/agent/stream/stream.yml.hbs
  packages/squid/data_stream/log/agent/stream/tcp.yml.hbs
  packages/squid/data_stream/log/agent/stream/udp.yml.hbs
  packages/squid/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/squid/data_stream/log/fields/ecs.yml
  packages/squid/data_stream/log/sample_event.json
  packages/squid/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2595 [rsa2elk/sonicwall] Upgrade to ECS 8.0.0
  packages/sonicwall/_dev/build/build.yml
  packages/sonicwall/changelog.yml
  packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-general.log-expected.json
  packages/sonicwall/data_stream/firewall/_dev/test/pipeline/test-generated.log-expected.json
  packages/sonicwall/data_stream/firewall/agent/stream/stream.yml.hbs
  packages/sonicwall/data_stream/firewall/agent/stream/tcp.yml.hbs
  packages/sonicwall/data_stream/firewall/agent/stream/udp.yml.hbs
  packages/sonicwall/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml
  packages/sonicwall/data_stream/firewall/fields/ecs.yml
  packages/sonicwall/docs/README.md
  packages/sonicwall/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2594 [rsa2elk/radware] Upgrade to ECS 8.0.0
  packages/radware/_dev/build/build.yml
  packages/radware/changelog.yml
  packages/radware/data_stream/defensepro/agent/stream/stream.yml.hbs
  packages/radware/data_stream/defensepro/agent/stream/tcp.yml.hbs
  packages/radware/data_stream/defensepro/agent/stream/udp.yml.hbs
  packages/radware/data_stream/defensepro/elasticsearch/ingest_pipeline/default.yml
  packages/radware/data_stream/defensepro/fields/ecs.yml
  packages/radware/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2593 [rsa2elk/proofpoint] Upgrade to ECS 8.0.0
  packages/proofpoint/_dev/build/build.yml
  packages/proofpoint/changelog.yml
  packages/proofpoint/data_stream/emailsecurity/_dev/test/pipeline/test-generated.log-expected.json
  packages/proofpoint/data_stream/emailsecurity/agent/stream/stream.yml.hbs
  packages/proofpoint/data_stream/emailsecurity/agent/stream/tcp.yml.hbs
  packages/proofpoint/data_stream/emailsecurity/agent/stream/udp.yml.hbs
  packages/proofpoint/data_stream/emailsecurity/elasticsearch/ingest_pipeline/default.yml
  packages/proofpoint/data_stream/emailsecurity/fields/ecs.yml
  packages/proofpoint/data_stream/emailsecurity/sample_event.json
  packages/proofpoint/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2591 [rsa2elk/microsoft] Upgrade to ECS 8.0.0
  packages/microsoft/_dev/build/build.yml
  packages/microsoft/changelog.yml
  packages/microsoft/data_stream/dhcp/_dev/test/pipeline/test-generated.log-expected.json
  packages/microsoft/data_stream/dhcp/agent/stream/log.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/tcp.yml.hbs
  packages/microsoft/data_stream/dhcp/agent/stream/udp.yml.hbs
  packages/microsoft/data_stream/dhcp/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft/data_stream/dhcp/fields/ecs.yml
  packages/microsoft/data_stream/dhcp/sample_event.json
  packages/microsoft/docs/README.md
  packages/microsoft/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2590 [rsa2elk/juniper_netscreen] Upgrade to ECS 8.0.0
  packages/juniper_netscreen/_dev/build/build.yml
  packages/juniper_netscreen/changelog.yml
  packages/juniper_netscreen/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper_netscreen/data_stream/log/agent/stream/logfile.yml.hbs
  packages/juniper_netscreen/data_stream/log/agent/stream/tcp.yml.hbs
  packages/juniper_netscreen/data_stream/log/agent/stream/udp.yml.hbs
  packages/juniper_netscreen/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/juniper_netscreen/data_stream/log/fields/ecs.yml
  packages/juniper_netscreen/data_stream/log/sample_event.json
  packages/juniper_netscreen/docs/README.md
  packages/juniper_netscreen/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2589 [rsa2elk/juniper_junos] Upgrade to ECS 8.0.0
  packages/juniper_junos/_dev/build/build.yml
  packages/juniper_junos/changelog.yml
  packages/juniper_junos/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper_junos/data_stream/log/agent/stream/stream.yml.hbs
  packages/juniper_junos/data_stream/log/agent/stream/tcp.yml.hbs
  packages/juniper_junos/data_stream/log/agent/stream/udp.yml.hbs
  packages/juniper_junos/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/juniper_junos/data_stream/log/fields/ecs.yml
  packages/juniper_junos/data_stream/log/sample_event.json
  packages/juniper_junos/docs/README.md
  packages/juniper_junos/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2588 [rsa2elk/juniper] Upgrade to ECS 8.0.0
  packages/juniper/_dev/build/build.yml
  packages/juniper/changelog.yml
  packages/juniper/data_stream/junos/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper/data_stream/junos/agent/stream/stream.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/junos/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/junos/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/junos/fields/ecs.yml
  packages/juniper/data_stream/junos/sample_event.json
  packages/juniper/data_stream/netscreen/_dev/test/pipeline/test-generated.log-expected.json
  packages/juniper/data_stream/netscreen/agent/stream/logfile.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/tcp.yml.hbs
  packages/juniper/data_stream/netscreen/agent/stream/udp.yml.hbs
  packages/juniper/data_stream/netscreen/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/netscreen/fields/ecs.yml
  packages/juniper/data_stream/netscreen/sample_event.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-atp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-flow.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-idp.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-ids.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-secintel.log-expected.json
  packages/juniper/data_stream/srx/_dev/test/pipeline/test-utm.log-expected.json
  packages/juniper/data_stream/srx/elasticsearch/ingest_pipeline/default.yml
  packages/juniper/data_stream/srx/fields/ecs.yml
  packages/juniper/docs/README.md
  packages/juniper/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2587 [rsa2elk/infoblox] Upgrade to ECS 8.0.0
  packages/infoblox/_dev/build/build.yml
  packages/infoblox/changelog.yml
  packages/infoblox/data_stream/nios/_dev/test/pipeline/test-generated.log-expected.json
  packages/infoblox/data_stream/nios/agent/stream/stream.yml.hbs
  packages/infoblox/data_stream/nios/agent/stream/tcp.yml.hbs
  packages/infoblox/data_stream/nios/agent/stream/udp.yml.hbs
  packages/infoblox/data_stream/nios/elasticsearch/ingest_pipeline/default.yml
  packages/infoblox/data_stream/nios/fields/ecs.yml
  packages/infoblox/data_stream/nios/sample_event.json
  packages/infoblox/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2586 [rsa2elk/imperva] Upgrade to ECS 8.0.0
  packages/imperva/_dev/build/build.yml
  packages/imperva/changelog.yml
  packages/imperva/data_stream/securesphere/_dev/test/pipeline/test-generated.log-expected.json
  packages/imperva/data_stream/securesphere/agent/stream/stream.yml.hbs
  packages/imperva/data_stream/securesphere/agent/stream/tcp.yml.hbs
  packages/imperva/data_stream/securesphere/agent/stream/udp.yml.hbs
  packages/imperva/data_stream/securesphere/elasticsearch/ingest_pipeline/default.yml
  packages/imperva/data_stream/securesphere/fields/ecs.yml
  packages/imperva/data_stream/securesphere/sample_event.json
  packages/imperva/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2585 [rsa2elk/fortinet] Upgrade to ECS 8.0.0
  packages/fortinet/_dev/build/build.yml
  packages/fortinet/changelog.yml
  packages/fortinet/data_stream/clientendpoint/_dev/test/pipeline/test-generated.log-expected.json
  packages/fortinet/data_stream/clientendpoint/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/clientendpoint/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/clientendpoint/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/clientendpoint/fields/ecs.yml
  packages/fortinet/data_stream/clientendpoint/sample_event.json
  packages/fortinet/data_stream/fortimail/_dev/test/pipeline/test-generated.log-expected.json
  packages/fortinet/data_stream/fortimail/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimail/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimail/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimail/fields/ecs.yml
  packages/fortinet/data_stream/fortimail/sample_event.json
  packages/fortinet/data_stream/fortimanager/_dev/test/pipeline/test-generated.log-expected.json
  packages/fortinet/data_stream/fortimanager/agent/stream/log.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/tcp.yml.hbs
  packages/fortinet/data_stream/fortimanager/agent/stream/udp.yml.hbs
  packages/fortinet/data_stream/fortimanager/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet/data_stream/fortimanager/fields/ecs.yml
  packages/fortinet/data_stream/fortimanager/sample_event.json
  packages/fortinet/docs/README.md
  packages/fortinet/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2584 [rsa2elk/f5] Upgrade to ECS 8.0.0
  packages/f5/_dev/build/build.yml
  packages/f5/changelog.yml
  packages/f5/data_stream/bigipafm/_dev/test/pipeline/test-generated.log-expected.json
  packages/f5/data_stream/bigipafm/agent/stream/stream.yml.hbs
  packages/f5/data_stream/bigipafm/agent/stream/tcp.yml.hbs
  packages/f5/data_stream/bigipafm/agent/stream/udp.yml.hbs
  packages/f5/data_stream/bigipafm/elasticsearch/ingest_pipeline/default.yml
  packages/f5/data_stream/bigipafm/fields/ecs.yml
  packages/f5/data_stream/bigipafm/sample_event.json
  packages/f5/data_stream/bigipapm/_dev/test/pipeline/test-generated.log-expected.json
  packages/f5/data_stream/bigipapm/agent/stream/stream.yml.hbs
  packages/f5/data_stream/bigipapm/agent/stream/tcp.yml.hbs
  packages/f5/data_stream/bigipapm/agent/stream/udp.yml.hbs
  packages/f5/data_stream/bigipapm/elasticsearch/ingest_pipeline/default.yml
  packages/f5/data_stream/bigipapm/fields/ecs.yml
  packages/f5/data_stream/bigipapm/sample_event.json
  packages/f5/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2583 [rsa2elk/cylance] Upgrade to ECS 8.0.0
  packages/cylance/_dev/build/build.yml
  packages/cylance/changelog.yml
  packages/cylance/data_stream/protect/_dev/test/pipeline/test-generated.log-expected.json
  packages/cylance/data_stream/protect/agent/stream/stream.yml.hbs
  packages/cylance/data_stream/protect/agent/stream/tcp.yml.hbs
  packages/cylance/data_stream/protect/agent/stream/udp.yml.hbs
  packages/cylance/data_stream/protect/elasticsearch/ingest_pipeline/default.yml
  packages/cylance/data_stream/protect/fields/ecs.yml
  packages/cylance/data_stream/protect/sample_event.json
  packages/cylance/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2582 [rsa2elk/cyberark] Upgrade to ECS 8.0.0
  packages/cyberark/_dev/build/build.yml
  packages/cyberark/changelog.yml
  packages/cyberark/data_stream/corepas/_dev/test/pipeline/test-generated.log-expected.json
  packages/cyberark/data_stream/corepas/agent/stream/stream.yml.hbs
  packages/cyberark/data_stream/corepas/agent/stream/tcp.yml.hbs
  packages/cyberark/data_stream/corepas/agent/stream/udp.yml.hbs
  packages/cyberark/data_stream/corepas/elasticsearch/ingest_pipeline/default.yml
  packages/cyberark/data_stream/corepas/fields/ecs.yml
  packages/cyberark/data_stream/corepas/sample_event.json
  packages/cyberark/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2581 [rsa2elk/cisco_nexus] Upgrade to ECS 8.0.0
  packages/cisco_nexus/_dev/build/build.yml
  packages/cisco_nexus/changelog.yml
  packages/cisco_nexus/data_stream/log/_dev/test/pipeline/test-nexus.log-expected.json
  packages/cisco_nexus/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_nexus/data_stream/log/agent/stream/tcp.yml.hbs
  packages/cisco_nexus/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_nexus/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_nexus/data_stream/log/fields/ecs.yml
  packages/cisco_nexus/data_stream/log/sample_event.json
  packages/cisco_nexus/docs/README.md
  packages/cisco_nexus/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2580 [rsa2elk/cisco_meraki] Upgrade to ECS 8.0.0
  packages/cisco_meraki/_dev/build/build.yml
  packages/cisco_meraki/changelog.yml
  packages/cisco_meraki/data_stream/log/_dev/test/pipeline/test-generated.log-expected.json
  packages/cisco_meraki/data_stream/log/agent/stream/stream.yml.hbs
  packages/cisco_meraki/data_stream/log/agent/stream/tcp.yml.hbs
  packages/cisco_meraki/data_stream/log/agent/stream/udp.yml.hbs
  packages/cisco_meraki/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_meraki/data_stream/log/fields/ecs.yml
  packages/cisco_meraki/data_stream/log/sample_event.json
  packages/cisco_meraki/docs/README.md
  packages/cisco_meraki/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2577 [rsa2elk/cisco] Upgrade to ECS 8.0.0
  packages/cisco/_dev/build/build.yml
  packages/cisco/changelog.yml
  packages/cisco/data_stream/asa/fields/ecs.yml
  packages/cisco/data_stream/ftd/fields/ecs.yml
  packages/cisco/data_stream/meraki/_dev/test/pipeline/test-generated.log-expected.json
  packages/cisco/data_stream/meraki/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/meraki/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/meraki/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/meraki/fields/ecs.yml
  packages/cisco/data_stream/meraki/sample_event.json
  packages/cisco/data_stream/nexus/agent/stream/stream.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/tcp.yml.hbs
  packages/cisco/data_stream/nexus/agent/stream/udp.yml.hbs
  packages/cisco/data_stream/nexus/elasticsearch/ingest_pipeline/default.yml
  packages/cisco/data_stream/nexus/fields/ecs.yml
  packages/cisco/data_stream/nexus/sample_event.json
  packages/cisco/docs/README.md
  packages/cisco/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2576 [rsa2elk/bluecoat] Upgrade to ECS 8.0.0
  packages/bluecoat/_dev/build/build.yml
  packages/bluecoat/changelog.yml
  packages/bluecoat/data_stream/director/_dev/test/pipeline/test-generated.log-expected.json
  packages/bluecoat/data_stream/director/agent/stream/stream.yml.hbs
  packages/bluecoat/data_stream/director/agent/stream/tcp.yml.hbs
  packages/bluecoat/data_stream/director/agent/stream/udp.yml.hbs
  packages/bluecoat/data_stream/director/elasticsearch/ingest_pipeline/default.yml
  packages/bluecoat/data_stream/director/fields/ecs.yml
  packages/bluecoat/data_stream/director/sample_event.json
  packages/bluecoat/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2574 [rsa2elk/barracuda] Upgrade to ECS 8.0.0
  packages/barracuda/_dev/build/build.yml
  packages/barracuda/changelog.yml
  packages/barracuda/data_stream/spamfirewall/_dev/test/pipeline/test-generated.log-expected.json
  packages/barracuda/data_stream/spamfirewall/agent/stream/stream.yml.hbs
  packages/barracuda/data_stream/spamfirewall/agent/stream/tcp.yml.hbs
  packages/barracuda/data_stream/spamfirewall/agent/stream/udp.yml.hbs
  packages/barracuda/data_stream/spamfirewall/elasticsearch/ingest_pipeline/default.yml
  packages/barracuda/data_stream/spamfirewall/fields/ecs.yml
  packages/barracuda/data_stream/spamfirewall/sample_event.json
  packages/barracuda/data_stream/waf/_dev/test/pipeline/test-generated.log-expected.json
  packages/barracuda/data_stream/waf/agent/stream/stream.yml.hbs
  packages/barracuda/data_stream/waf/agent/stream/tcp.yml.hbs
  packages/barracuda/data_stream/waf/agent/stream/udp.yml.hbs
  packages/barracuda/data_stream/waf/elasticsearch/ingest_pipeline/default.yml
  packages/barracuda/data_stream/waf/fields/ecs.yml
  packages/barracuda/data_stream/waf/sample_event.json
  packages/barracuda/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2592 [rsa2elk/netscout] Upgrade to ECS 8.0.0
  packages/netscout/_dev/build/build.yml
  packages/netscout/changelog.yml
  packages/netscout/data_stream/sightline/_dev/test/pipeline/test-generated.log-expected.json
  packages/netscout/data_stream/sightline/agent/stream/stream.yml.hbs
  packages/netscout/data_stream/sightline/agent/stream/tcp.yml.hbs
  packages/netscout/data_stream/sightline/agent/stream/udp.yml.hbs
  packages/netscout/data_stream/sightline/elasticsearch/ingest_pipeline/default.yml
  packages/netscout/data_stream/sightline/fields/ecs.yml
  packages/netscout/data_stream/sightline/sample_event.json
  packages/netscout/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2596 [rsa2elk/sophos] Upgrade to ECS 8.0.0
  packages/sophos/_dev/build/build.yml
  packages/sophos/changelog.yml
  packages/sophos/data_stream/utm/_dev/test/pipeline/test-generated.log-expected.json
  packages/sophos/data_stream/utm/agent/stream/stream.yml.hbs
  packages/sophos/data_stream/utm/agent/stream/tcp.yml.hbs
  packages/sophos/data_stream/utm/agent/stream/udp.yml.hbs
  packages/sophos/data_stream/utm/elasticsearch/ingest_pipeline/default.yml
  packages/sophos/data_stream/utm/fields/ecs.yml
  packages/sophos/data_stream/utm/sample_event.json
  packages/sophos/data_stream/xg/_dev/test/pipeline/test-sophos-xg.log-expected.json
  packages/sophos/data_stream/xg/elasticsearch/ingest_pipeline/default.yml
  packages/sophos/data_stream/xg/fields/ecs.yml
  packages/sophos/data_stream/xg/sample_event.json
  packages/sophos/docs/README.md
  packages/sophos/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2565 [tenable_sc] Promote to GA
  packages/tenable_sc/changelog.yml
  packages/tenable_sc/data_stream/asset/manifest.yml
  packages/tenable_sc/data_stream/plugin/manifest.yml
  packages/tenable_sc/data_stream/vulnerability/manifest.yml
  packages/tenable_sc/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:TenableSC

#2564 [suricata] Fix missing destination.ip
  packages/suricata/changelog.yml
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-6-0.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-alerts.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-dns-4-1-4.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-metadata.log-expected.json
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log
  packages/suricata/data_stream/eve/_dev/test/pipeline/test-eve-small.log-expected.json
  packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml
  packages/suricata/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Suricata

#2517 package/network_traffic/tls: fix mapping for tls.detailed.server_certificate_chain
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/tls/fields/protocol.yml
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
Labels: bug, Team:Security-External Integrations, 8.1-candidate

#2608 Add missing job.name and cronjob.name meta fields
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/pod/fields/base-fields.yml
  packages/kubernetes/data_stream/state_pod/fields/base-fields.yml
  packages/kubernetes/docs/kube-state-metrics.md
  packages/kubernetes/docs/kubelet.md
  packages/kubernetes/manifest.yml
Labels: Team:Integrations

#2446 [ti_anomali] Upgrade ECS to 8.0.0
  packages/ti_anomali/_dev/build/build.yml
  packages/ti_anomali/changelog.yml
  packages/ti_anomali/data_stream/limo/_dev/test/pipeline/test-anomali-limo-ndjson.log-expected.json
  packages/ti_anomali/data_stream/limo/elasticsearch/ingest_pipeline/default.yml
  packages/ti_anomali/data_stream/limo/sample_event.json
  packages/ti_anomali/data_stream/threatstream/_dev/test/pipeline/test-anomali-threatstream.json-expected.json
  packages/ti_anomali/data_stream/threatstream/elasticsearch/ingest_pipeline/default.yml
  packages/ti_anomali/data_stream/threatstream/sample_event.json
  packages/ti_anomali/docs/README.md
  packages/ti_anomali/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2445 [ti_abusech] Upgrade ECS to 8.0.0
  packages/ti_abusech/_dev/build/build.yml
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/data_stream/malware/_dev/test/pipeline/test-malware-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malware/elasticsearch/ingest_pipeline/default.yml
  packages/ti_abusech/data_stream/malware/sample_event.json
  packages/ti_abusech/data_stream/malwarebazaar/_dev/test/pipeline/test-malwarebazaar-ndjson.log-expected.json
  packages/ti_abusech/data_stream/malwarebazaar/elasticsearch/ingest_pipeline/default.yml
  packages/ti_abusech/data_stream/malwarebazaar/sample_event.json
  packages/ti_abusech/data_stream/url/_dev/test/pipeline/test-abusechurl-ndjson.log-expected.json
  packages/ti_abusech/data_stream/url/elasticsearch/ingest_pipeline/default.yml
  packages/ti_abusech/data_stream/url/sample_event.json
  packages/ti_abusech/manifest.yml
Labels: enhancement, Team:Security-External Integrations

#2612 Add missing job and cronjob fields in container related metricsets
  packages/kubernetes/changelog.yml
  packages/kubernetes/data_stream/container/fields/base-fields.yml
  packages/kubernetes/data_stream/container_logs/fields/base-fields.yml
  packages/kubernetes/docs/kubelet.md
  packages/kubernetes/manifest.yml
Labels: Team:Integrations

#2619 Improve Prometheus default datastream enablement
  packages/prometheus/changelog.yml
  packages/prometheus/data_stream/collector/manifest.yml
  packages/prometheus/data_stream/query/manifest.yml
  packages/prometheus/data_stream/remote_write/manifest.yml
  packages/prometheus/manifest.yml
Labels: Team:Cloudnative-Monitoring
