Repository elastic/integrations, pull requests merged in 2022-06, with the labels that each got.

#3456 network_traffic: add config option to monitor processes
  packages/network_traffic/_dev/build/docs/README.md
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/amqp/agent/stream/amqp.yml.hbs
  packages/network_traffic/data_stream/amqp/manifest.yml
  packages/network_traffic/data_stream/cassandra/agent/stream/cassandra.yml.hbs
  packages/network_traffic/data_stream/cassandra/manifest.yml
  packages/network_traffic/data_stream/dhcpv4/agent/stream/dhcpv4.yml.hbs
  packages/network_traffic/data_stream/dhcpv4/manifest.yml
  packages/network_traffic/data_stream/dns/agent/stream/dns.yml.hbs
  packages/network_traffic/data_stream/dns/manifest.yml
  packages/network_traffic/data_stream/flow/agent/stream/flow.yml.hbs
  packages/network_traffic/data_stream/flow/manifest.yml
  packages/network_traffic/data_stream/http/agent/stream/http.yml.hbs
  packages/network_traffic/data_stream/http/manifest.yml
  packages/network_traffic/data_stream/icmp/agent/stream/icmp.yml.hbs
  packages/network_traffic/data_stream/icmp/manifest.yml
  packages/network_traffic/data_stream/memcached/agent/stream/memcached.yml.hbs
  packages/network_traffic/data_stream/memcached/manifest.yml
  packages/network_traffic/data_stream/mongodb/agent/stream/mongodb.yml.hbs
  packages/network_traffic/data_stream/mongodb/manifest.yml
  packages/network_traffic/data_stream/mysql/agent/stream/mysql.yml.hbs
  packages/network_traffic/data_stream/mysql/manifest.yml
  packages/network_traffic/data_stream/nfs/agent/stream/nfs.yml.hbs
  packages/network_traffic/data_stream/nfs/manifest.yml
  packages/network_traffic/data_stream/pgsql/agent/stream/pgsql.yml.hbs
  packages/network_traffic/data_stream/pgsql/manifest.yml
  packages/network_traffic/data_stream/redis/agent/stream/redis.yml.hbs
  packages/network_traffic/data_stream/redis/manifest.yml
  packages/network_traffic/data_stream/sip/agent/stream/sip.yml.hbs
  packages/network_traffic/data_stream/sip/manifest.yml
  packages/network_traffic/data_stream/thrift/agent/stream/thrift.yml.hbs
  packages/network_traffic/data_stream/thrift/manifest.yml
  packages/network_traffic/data_stream/tls/agent/stream/tls.yml.hbs
  packages/network_traffic/data_stream/tls/manifest.yml
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
Labels: bug, enhancement, Team:Security-External Integrations, Integration:Network Packet Capture

#3189 [oracle_weblogic] Add Integration Package with ThreadPool Data Stream
  packages/oracle_weblogic/_dev/build/docs/README.md
  packages/oracle_weblogic/changelog.yml
  packages/oracle_weblogic/data_stream/threadpool/_dev/test/system/test-default-config.yml
  packages/oracle_weblogic/data_stream/threadpool/agent/stream/stream.yml.hbs
  packages/oracle_weblogic/data_stream/threadpool/elasticsearch/ingest_pipeline/default.yml
  packages/oracle_weblogic/data_stream/threadpool/fields/base-fields.yml
  packages/oracle_weblogic/data_stream/threadpool/fields/ecs.yml
  packages/oracle_weblogic/data_stream/threadpool/fields/fields.yml
  packages/oracle_weblogic/data_stream/threadpool/manifest.yml
  packages/oracle_weblogic/data_stream/threadpool/sample_event.json
  packages/oracle_weblogic/docs/README.md
  packages/oracle_weblogic/img/oracle_weblogic-threadpool.png
  packages/oracle_weblogic/kibana/dashboard/oracle_weblogic-08549310-bef8-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-1d8fc050-bf03-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-2673e7a0-bf03-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-ae12cbf0-bf02-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-b25075a0-bf02-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-b6d401f0-bf02-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-c31dabf0-c132-11ec-aaae-35e5cf8554e6.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-cd92c2f0-bf02-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-d11ea8d0-bf02-11ec-b09e-d5f6721c5e40.json
  packages/oracle_weblogic/kibana/visualization/oracle_weblogic-6feffac0-bbd1-11ec-89c6-4d6d87ffa28e.json
  packages/oracle_weblogic/manifest.yml
Labels: enhancement, New Integration, Team:Service-Integrations, Integration:oracle_weblogic

#3467 Move RDS lightweight module config into integration
  packages/aws/changelog.yml
  packages/aws/data_stream/rds/agent/stream/stream.yml.hbs
  packages/aws/data_stream/rds/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/rds/fields/fields.yml
  packages/aws/data_stream/rds/sample_event.json
  packages/aws/docs/rds.md
  packages/aws/manifest.yml
Labels: Team:Cloud-Monitoring

#3471 [carbon_black_cloud] Fixed CBC Dashboard issue.
  packages/carbon_black_cloud/changelog.yml
  packages/carbon_black_cloud/kibana/dashboard/carbon_black_cloud-7e095a40-e325-11ec-8642-e7f3d8b25a9b.json
  packages/carbon_black_cloud/kibana/dashboard/carbon_black_cloud-af030950-8d73-11ec-ac12-4bc77fa14e95.json
  packages/carbon_black_cloud/kibana/visualization/carbon_black_cloud-71058370-e323-11ec-8642-e7f3d8b25a9b.json
  packages/carbon_black_cloud/manifest.yml
Labels: bug, Team:Security-External Integrations, dashboard, Integration:CarbonBlackCloud

#3121 [oracle_weblogic] Add Integration Package with Deployed Application Data Stream
  packages/oracle_weblogic/_dev/build/docs/README.md
  packages/oracle_weblogic/_dev/deploy/docker/oracle_weblogic/container-scripts/adminServerLogs.sh
  packages/oracle_weblogic/_dev/deploy/docker/oracle_weblogic/container-scripts/managedServerLogs.sh
  packages/oracle_weblogic/changelog.yml
  packages/oracle_weblogic/data_stream/deployed_application/_dev/test/system/test-default-config.yml
  packages/oracle_weblogic/data_stream/deployed_application/agent/stream/stream.yml.hbs
  packages/oracle_weblogic/data_stream/deployed_application/elasticsearch/ingest_pipeline/default.yml
  packages/oracle_weblogic/data_stream/deployed_application/fields/base-fields.yml
  packages/oracle_weblogic/data_stream/deployed_application/fields/ecs.yml
  packages/oracle_weblogic/data_stream/deployed_application/fields/fields.yml
  packages/oracle_weblogic/data_stream/deployed_application/manifest.yml
  packages/oracle_weblogic/data_stream/deployed_application/sample_event.json
  packages/oracle_weblogic/docs/README.md
  packages/oracle_weblogic/img/oracle_weblogic-deployed-application.png
  packages/oracle_weblogic/kibana/dashboard/oracle_weblogic-ea8cae80-ba24-11ec-913e-9be55c877bed.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-0a14bf00-ba29-11ec-913e-9be55c877bed.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-0ddf0d70-ba29-11ec-913e-9be55c877bed.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-12f42b60-ba29-11ec-913e-9be55c877bed.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-15cc2a90-ba29-11ec-913e-9be55c877bed.json
  packages/oracle_weblogic/kibana/lens/oracle_weblogic-1df7e830-baf6-11ec-bb0c-dbfaa8a6536b.json
  packages/oracle_weblogic/kibana/visualization/oracle_weblogic-12f3e390-baf5-11ec-bb0c-dbfaa8a6536b.json
  packages/oracle_weblogic/kibana/visualization/oracle_weblogic-4769b080-baf7-11ec-bb0c-dbfaa8a6536b.json
  packages/oracle_weblogic/manifest.yml
Labels: enhancement, New Integration, Team:Service-Integrations, Integration:oracle_weblogic

#3430 [google_workspace] Allow to set credentials directly in the config.
  packages/google_workspace/changelog.yml
  packages/google_workspace/data_stream/admin/_dev/test/system/test-default-config.yml
  packages/google_workspace/data_stream/admin/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/drive/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/groups/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/login/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/saml/agent/stream/httpjson.yml.hbs
  packages/google_workspace/data_stream/user_accounts/agent/stream/httpjson.yml.hbs
  packages/google_workspace/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Google Workspace

#3495 windows/powershell: fix regexp constraints in event 800 parameter detail processing
  packages/windows/changelog.yml
  packages/windows/data_stream/powershell/_dev/test/pipeline/test-events.json
  packages/windows/data_stream/powershell/_dev/test/pipeline/test-events.json-expected.json
  packages/windows/data_stream/powershell/elasticsearch/ingest_pipeline/default.yml
  packages/windows/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Windows

#3287 [Cassandra] Fix dashboard issues.
  packages/cassandra/changelog.yml
  packages/cassandra/kibana/dashboard/cassandra-25b7d6d0-1c71-11ec-84f1-e1733c643874.json
  packages/cassandra/kibana/dashboard/cassandra-49e4e6e0-cc54-11ec-8c59-ed6efced90da.json
  packages/cassandra/kibana/dashboard/cassandra-dd325020-1f8b-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/search/cassandra-7ff6a1a0-1c6f-11ec-84f1-e1733c643874.json
  packages/cassandra/kibana/search/cassandra-a7a48e10-1f8a-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-01880100-1f5e-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-33068620-1f90-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-3437c610-1f83-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-49575c60-1f8b-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-49daddb0-1f5e-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-54c57b30-1f91-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-5ba3b360-2020-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-700c4f60-2020-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-86a4d8e0-1f5e-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-87490750-1f8e-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-88fb36d0-2020-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-8d84a7e0-1f62-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-90562c80-1f64-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-aa19ff10-1f83-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-ae0768e0-1f62-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-b5f8a180-1f5e-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-c0d1d7b0-1f82-11ec-ba68-fbf426daf104.json
  packages/cassandra/kibana/visualization/cassandra-c6465e10-1f5e-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-d83fced0-1f5e-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-e84ad280-1f5d-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/kibana/visualization/cassandra-f733d980-1f5e-11ec-a3a3-6bd3ff5963e5.json
  packages/cassandra/manifest.yml
Labels: bug, Team:Integrations, Integration:Cassandra, dashboard, Team:Service-Integrations

#3222 update Cyberasrkpas readme
  packages/cyberarkpas/_dev/build/docs/README.md
  packages/cyberarkpas/changelog.yml
  packages/cyberarkpas/docs/README.md
  packages/cyberarkpas/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3177 update winlog readme
  packages/winlog/_dev/build/docs/README.md
  packages/winlog/changelog.yml
  packages/winlog/docs/README.md
  packages/winlog/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3175 update UDP readme
  packages/udp/_dev/build/docs/README.md
  packages/udp/changelog.yml
  packages/udp/docs/README.md
  packages/udp/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3155 update QNAP NAS readme
  packages/qnap_nas/_dev/build/docs/README.md
  packages/qnap_nas/changelog.yml
  packages/qnap_nas/docs/README.md
  packages/qnap_nas/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3153 updated Prometheus readme
  packages/prometheus/_dev/build/docs/README.md
  packages/prometheus/changelog.yml
  packages/prometheus/docs/README.md
  packages/prometheus/manifest.yml
Labels: documentation, enhancement, Integration:Prometheus, Team:Cloudnative-Monitoring

#3275 [elasticsearch] Add `scope` configuration option for metricsets
  packages/elasticsearch/changelog.yml
  packages/elasticsearch/data_stream/ccr/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/cluster_stats/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/enrich/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/index/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/index_recovery/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/index_summary/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/ml_job/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/node/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/node_stats/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/pending_tasks/agent/stream/stream.yml.hbs
  packages/elasticsearch/data_stream/shard/agent/stream/stream.yml.hbs
  packages/elasticsearch/manifest.yml
Labels: Integration:Elasticsearch

#3136 update keycloak readme
  packages/keycloak/_dev/build/docs/README.md
  packages/keycloak/changelog.yml
  packages/keycloak/docs/README.md
  packages/keycloak/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3492 [crowdstrike.fdr] Use 'params' for data table in script processors
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Crowdstrike

#3497 cyberarkpas: Make paths a multi string var
  packages/cyberarkpas/changelog.yml
  packages/cyberarkpas/data_stream/audit/manifest.yml
  packages/cyberarkpas/manifest.yml
Labels: bug, Team:Security-External Integrations

#3133 Update Jupiter JUNOS readme
  packages/juniper_junos/_dev/build/docs/README.md
  packages/juniper_junos/changelog.yml
  packages/juniper_junos/docs/README.md
  packages/juniper_junos/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3071 update AWS-Logs readme
  packages/aws_logs/_dev/build/docs/README.md
  packages/aws_logs/changelog.yml
  packages/aws_logs/docs/README.md
  packages/aws_logs/manifest.yml
Labels: documentation, Team:Cloud-Monitoring

#3075 Update azure_application_insights Readme
  packages/azure_application_insights/_dev/build/docs/README.md
  packages/azure_application_insights/changelog.yml
  packages/azure_application_insights/docs/README.md
  packages/azure_application_insights/manifest.yml
Labels: documentation, Team:Cloud-Monitoring

#3076 Update Azure Billing Readme
  packages/azure_billing/_dev/build/docs/README.md
  packages/azure_billing/changelog.yml
  packages/azure_billing/docs/README.md
  packages/azure_billing/manifest.yml
Labels: documentation, Team:Cloud-Monitoring

#3077 Update Azure Metrics Readme
  packages/azure_metrics/_dev/build/docs/README.md
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/docs/README.md
  packages/azure_metrics/manifest.yml
Labels: documentation, Team:Cloud-Monitoring

#3108 update hid_bravura_monitor readme
  packages/hid_bravura_monitor/_dev/build/docs/README.md
  packages/hid_bravura_monitor/changelog.yml
  packages/hid_bravura_monitor/docs/README.md
  packages/hid_bravura_monitor/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3105 update github readme
  packages/github/_dev/build/docs/README.md
  packages/github/changelog.yml
  packages/github/docs/README.md
  packages/github/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3107 update Google workspace readme
  packages/google_workspace/_dev/build/docs/README.md
  packages/google_workspace/changelog.yml
  packages/google_workspace/docs/README.md
  packages/google_workspace/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3104 Update gcp_pubsub readme
  packages/gcp_pubsub/_dev/build/docs/README.md
  packages/gcp_pubsub/changelog.yml
  packages/gcp_pubsub/docs/README.md
  packages/gcp_pubsub/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3484 crowdstrike/fdr: Prevent ingesting documents without `@timestamp`
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log
  packages/crowdstrike/data_stream/fdr/_dev/test/pipeline/test-fdr.log-expected.json
  packages/crowdstrike/data_stream/fdr/elasticsearch/ingest_pipeline/default.yml
  packages/crowdstrike/manifest.yml
Labels: bug, Team:Security-External Integrations

#3395 [microsoft_sqlserver] Add transaction log DataStream
  .github/CODEOWNERS
  packages/microsoft_sqlserver/_dev/build/docs/README.md
  packages/microsoft_sqlserver/changelog.yml
  packages/microsoft_sqlserver/data_stream/transaction_log/_dev/test/system/test-transaction-config.yml
  packages/microsoft_sqlserver/data_stream/transaction_log/agent/stream/stream.yml.hbs
  packages/microsoft_sqlserver/data_stream/transaction_log/elasticsearch/ingest_pipeline/default.yml
  packages/microsoft_sqlserver/data_stream/transaction_log/fields/base-fields.yml
  packages/microsoft_sqlserver/data_stream/transaction_log/fields/ecs.yml
  packages/microsoft_sqlserver/data_stream/transaction_log/fields/fields.yml
  packages/microsoft_sqlserver/data_stream/transaction_log/manifest.yml
  packages/microsoft_sqlserver/data_stream/transaction_log/sample_event.json
  packages/microsoft_sqlserver/docs/README.md
  packages/microsoft_sqlserver/img/sqlserver-transaction-dashboard.png
  packages/microsoft_sqlserver/kibana/dashboard/microsoft_sqlserver-18d66970-1fb4-11e9-8a4d-eb34d2834f6b.json
  packages/microsoft_sqlserver/manifest.yml
Labels: enhancement, Team:Integrations, Team:Security-External Integrations, Integration:microsoft_sqlserver, Team:Service-Integrations

#3465 cef: improve documentation and testing
  packages/cef/_dev/deploy/docker/sample_logs/arcsight.log
  packages/cef/_dev/deploy/docker/sample_logs/cisco.log
  packages/cef/_dev/deploy/docker/sample_logs/netscaler.log
  packages/cef/_dev/deploy/docker/sample_logs/trend-micro.log
  packages/cef/changelog.yml
  packages/cef/data_stream/log/_dev/test/pipeline/test-arcsight.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-arcsight.json-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-checkpoint.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-checkpoint.json-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-cisco-asa.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-cisco-asa.json-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-netscaler.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-netscaler.json-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-syslog.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-syslog.json-expected.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-trend-micro.json
  packages/cef/data_stream/log/_dev/test/pipeline/test-trend-micro.json-expected.json
  packages/cef/data_stream/log/elasticsearch/ingest_pipeline/cp-pipeline.yml
  packages/cef/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cef/data_stream/log/fields/ecs.yml
  packages/cef/data_stream/log/fields/fields.yml
  packages/cef/data_stream/log/sample_event.json
  packages/cef/docs/README.md
  packages/cef/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations, Integration:CEF

#3362 okta: add extended okta.debug_context.debug_data handling
  packages/okta/changelog.yml
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json
  packages/okta/data_stream/system/_dev/test/pipeline/test-okta-system-events.json-expected.json
  packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml
  packages/okta/data_stream/system/fields/fields.yml
  packages/okta/data_stream/system/sample_event.json
  packages/okta/docs/README.md
  packages/okta/manifest.yml
Labels: bug, enhancement, Team:Security-External Integrations, Integration:Okta

#3122 Update IIS readme
  packages/iis/_dev/build/docs/README.md
  packages/iis/changelog.yml
  packages/iis/docs/README.md
  packages/iis/manifest.yml
Labels: documentation, enhancement, Team:Service-Integrations

#3220 Update Netskope Readme
  packages/netskope/_dev/build/docs/README.md
  packages/netskope/changelog.yml
  packages/netskope/docs/README.md
  packages/netskope/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations, docs

#3219 update Cisco umbrella readme
  packages/cisco_umbrella/_dev/build/docs/README.md
  packages/cisco_umbrella/changelog.yml
  packages/cisco_umbrella/docs/README.md
  packages/cisco_umbrella/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3139 update Kubernetes readme
  packages/kubernetes/_dev/build/docs/README.md
  packages/kubernetes/changelog.yml
  packages/kubernetes/docs/README.md
  packages/kubernetes/manifest.yml
Labels: documentation, enhancement, Team:Cloudnative-Monitoring

#3160 update Sophos readme
  packages/sophos/_dev/build/docs/README.md
  packages/sophos/changelog.yml
  packages/sophos/docs/README.md
  packages/sophos/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3172 update recorded futurereadme readme
  packages/ti_recordedfuture/_dev/build/docs/README.md
  packages/ti_recordedfuture/changelog.yml
  packages/ti_recordedfuture/docs/README.md
  packages/ti_recordedfuture/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3173 update ThreatQ readme
  packages/ti_threatq/_dev/build/docs/README.md
  packages/ti_threatq/changelog.yml
  packages/ti_threatq/docs/README.md
  packages/ti_threatq/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3171 Update Alienvault OTX Integration readme
  packages/ti_otx/_dev/build/docs/README.md
  packages/ti_otx/changelog.yml
  packages/ti_otx/docs/README.md
  packages/ti_otx/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3168 updated MISP readme
  packages/ti_misp/_dev/build/docs/README.md
  packages/ti_misp/changelog.yml
  packages/ti_misp/docs/README.md
  packages/ti_misp/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3166 update AbuseCH readme
  packages/ti_abusech/_dev/build/docs/README.md
  packages/ti_abusech/changelog.yml
  packages/ti_abusech/docs/README.md
  packages/ti_abusech/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3162 update Symantec endpoint readme
  packages/symantec_endpoint/_dev/build/docs/README.md
  packages/symantec_endpoint/changelog.yml
  packages/symantec_endpoint/docs/README.md
  packages/symantec_endpoint/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3135 update juniper SRX readme
  packages/juniper_srx/_dev/build/docs/README.md
  packages/juniper_srx/changelog.yml
  packages/juniper_srx/docs/README.md
  packages/juniper_srx/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3103 Update # Google Cloud Integration readme
  packages/gcp/_dev/build/docs/README.md
  packages/gcp/changelog.yml
  packages/gcp/docs/README.md
  packages/gcp/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3176 update windows readme
  packages/windows/_dev/build/docs/README.md
  packages/windows/changelog.yml
  packages/windows/docs/README.md
  packages/windows/manifest.yml
Labels: documentation, enhancement, Team:Service-Integrations

#3518 [httpjson] Remove conditional rendering based on oauth_id of auth options
  packages/httpjson/changelog.yml
  packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
  packages/httpjson/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:httpjson

#3522 Fix missing key in system/process yaml template
  packages/system/changelog.yml
  packages/system/data_stream/process/agent/stream/stream.yml.hbs
  packages/system/manifest.yml
Labels: bug, Team:Elastic-Agent-Data-Plane

#3529 Fix doc build (Cisco Meraki)
  packages/cisco_meraki/_dev/build/docs/README.md
  packages/cisco_meraki/changelog.yml
  packages/cisco_meraki/docs/README.md
  packages/cisco_meraki/manifest.yml
Labels: enhancement

#3528 Fix doc build (Azure Metrics)
  packages/azure_metrics/_dev/build/docs/monitor.md
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/docs/monitor.md
  packages/azure_metrics/manifest.yml
Labels: enhancement

#3145 update pfSense documentation
  packages/pfsense/_dev/build/docs/README.md
  packages/pfsense/changelog.yml
  packages/pfsense/docs/README.md
  packages/pfsense/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3167 update Anomoli readme
  packages/ti_anomali/_dev/build/docs/README.md
  packages/ti_anomali/changelog.yml
  packages/ti_anomali/docs/README.md
  packages/ti_anomali/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3224 update Cloudflare Readme
  packages/cloudflare/_dev/build/docs/README.md
  packages/cloudflare/changelog.yml
  packages/cloudflare/docs/README.md
  packages/cloudflare/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3516 IIS Integration - pipeline update for the log format
  packages/iis/changelog.yml
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log
  packages/iis/data_stream/access/_dev/test/pipeline/test-iis-access.log-expected.json
  packages/iis/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/iis/manifest.yml
Labels: enhancement, Team:Service-Integrations

#3544 pulse_connect_secure: add mapping for `event.create`
  packages/pulse_connect_secure/changelog.yml
  packages/pulse_connect_secure/data_stream/log/fields/ecs.yml
  packages/pulse_connect_secure/docs/README.md
  packages/pulse_connect_secure/manifest.yml
Labels: bug, Integration:PulseConnectSecure

#3474 Move ELB lightweight module config into integration
  packages/aws/changelog.yml
  packages/aws/data_stream/elb_metrics/agent/stream/stream.yml.hbs
  packages/aws/data_stream/elb_metrics/fields/package-fields.yml
  packages/aws/data_stream/elb_metrics/sample_event.json
  packages/aws/docs/elb.md
  packages/aws/manifest.yml
Labels: Team:Cloud-Monitoring

#3308 [docs] Add context to AWS integration documentation
  packages/aws/_dev/build/docs/README.md
  packages/aws/_dev/build/docs/cloudfront.md
  packages/aws/changelog.yml
  packages/aws/docs/README.md
  packages/aws/docs/cloudfront.md
  packages/aws/manifest.yml
Labels: documentation, enhancement, Team:Docs

#3352 [docs] Add context to Windows integration documentation
  packages/windows/_dev/build/docs/README.md
  packages/windows/changelog.yml
  packages/windows/docs/README.md
  packages/windows/manifest.yml
Labels: documentation, enhancement, Integration:Windows, Team:Docs

#3359 [docs] Add context to Linux Metrics integration documentation
  packages/linux/_dev/build/docs/README.md
  packages/linux/changelog.yml
  packages/linux/docs/README.md
  packages/linux/manifest.yml
Labels: documentation, enhancement, Team:Docs

#3532 update readme for Akamai
  packages/akamai/_dev/build/docs/README.md
  packages/akamai/changelog.yml
  packages/akamai/docs/README.md
  packages/akamai/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations, Integration:Akamai

#3537 update Cyberark Readme
  packages/cyberark/changelog.yml
  packages/cyberark/docs/README.md
  packages/cyberark/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations, Integration:CyberArk

#3549 cisco_{asa,ftd}: fix syslog priority handling
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_asa/data_stream/log/fields/ecs.yml
  packages/cisco_asa/data_stream/log/sample_event.json
  packages/cisco_asa/docs/README.md
  packages/cisco_asa/manifest.yml
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-firepower-management.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-not-ip.log-expected.json
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-security-file-malware.log-expected.json
  packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ftd/data_stream/log/fields/ecs.yml
  packages/cisco_ftd/data_stream/log/fields/fields.yml
  packages/cisco_ftd/data_stream/log/sample_event.json
  packages/cisco_ftd/docs/README.md
  packages/cisco_ftd/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:CiscoASA

#3072 Add context to Azure integration documentation
  packages/azure/_dev/build/docs/README.md
  packages/azure/changelog.yml
  packages/azure/docs/README.md
  packages/azure/manifest.yml
Labels: documentation, Team:Cloud-Monitoring

#3563 Add processors and tags to all system data streams
  packages/system/changelog.yml
  packages/system/data_stream/core/agent/stream/stream.yml.hbs
  packages/system/data_stream/core/manifest.yml
  packages/system/data_stream/cpu/agent/stream/stream.yml.hbs
  packages/system/data_stream/cpu/manifest.yml
  packages/system/data_stream/diskio/agent/stream/stream.yml.hbs
  packages/system/data_stream/diskio/manifest.yml
  packages/system/data_stream/filesystem/agent/stream/stream.yml.hbs
  packages/system/data_stream/filesystem/manifest.yml
  packages/system/data_stream/fsstat/agent/stream/stream.yml.hbs
  packages/system/data_stream/fsstat/manifest.yml
  packages/system/data_stream/load/agent/stream/stream.yml.hbs
  packages/system/data_stream/load/manifest.yml
  packages/system/data_stream/memory/agent/stream/stream.yml.hbs
  packages/system/data_stream/memory/manifest.yml
  packages/system/data_stream/network/agent/stream/stream.yml.hbs
  packages/system/data_stream/network/manifest.yml
  packages/system/data_stream/process/agent/stream/stream.yml.hbs
  packages/system/data_stream/process/manifest.yml
  packages/system/data_stream/process_summary/agent/stream/stream.yml.hbs
  packages/system/data_stream/process_summary/manifest.yml
  packages/system/data_stream/socket_summary/agent/stream/stream.yml.hbs
  packages/system/data_stream/socket_summary/manifest.yml
  packages/system/data_stream/syslog/agent/stream/log.yml.hbs
  packages/system/data_stream/syslog/manifest.yml
  packages/system/data_stream/uptime/agent/stream/stream.yml.hbs
  packages/system/data_stream/uptime/manifest.yml
  packages/system/manifest.yml
Labels: enhancement, Team:Elastic-Agent-Data-Plane

#3565 [Security Rules] Update security rules package to v8.1.1
  packages/security_detection_engine/changelog.yml
  packages/security_detection_engine/kibana/security_rule/0c9a14d9-d65d-486f-9b5b-91e4e6b22bd0.json
  packages/security_detection_engine/kibana/security_rule/68994a6c-c7ba-4e82-b476-26a26877adf6.json
  packages/security_detection_engine/kibana/security_rule/699e9fdb-b77c-4c01-995c-1c15019b9c43.json
  packages/security_detection_engine/kibana/security_rule/6f435062-b7fc-4af9-acea-5b1ead65c5a5.json
  packages/security_detection_engine/kibana/security_rule/785a404b-75aa-4ffd-8be5-3334a5a544dd.json
  packages/security_detection_engine/kibana/security_rule/93e63c3e-4154-4fc6-9f86-b411e0987bbf.json
  packages/security_detection_engine/kibana/security_rule/a99f82f5-8e77-4f8b-b3ce-10c0f6afbc73.json
  packages/security_detection_engine/kibana/security_rule/acbc8bb9-2486-49a8-8779-45fb5f9a93ee.json
  packages/security_detection_engine/kibana/security_rule/ad3f2807-2b3e-47d7-b282-f84acbbe14be.json
  packages/security_detection_engine/kibana/security_rule/cad4500a-abd7-4ef3-b5d3-95524de7cfe1.json
  packages/security_detection_engine/kibana/security_rule/cf549724-c577-4fd6-8f9b-d1b8ec519ec0.json
  packages/security_detection_engine/kibana/security_rule/e555105c-ba6d-481f-82bb-9b633e7b4827.json
  packages/security_detection_engine/manifest.yml
Labels: v8.3.0, trade-artifacts

#3568 tenable_sc: add mapping for event.created
  packages/tenable_sc/changelog.yml
  packages/tenable_sc/data_stream/asset/fields/ecs.yml
  packages/tenable_sc/data_stream/plugin/fields/ecs.yml
  packages/tenable_sc/data_stream/vulnerability/fields/ecs.yml
  packages/tenable_sc/docs/README.md
  packages/tenable_sc/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:TenableSC

#3579 Add correct mapping for event.created
  packages/apache/changelog.yml
  packages/apache/data_stream/error/fields/ecs.yml
  packages/apache/docs/README.md
  packages/apache/manifest.yml
  packages/atlassian_bitbucket/changelog.yml
  packages/atlassian_bitbucket/data_stream/audit/fields/ecs.yml
  packages/atlassian_bitbucket/docs/README.md
  packages/atlassian_bitbucket/manifest.yml
  packages/carbon_black_cloud/changelog.yml
  packages/carbon_black_cloud/data_stream/alert/fields/ecs.yml
  packages/carbon_black_cloud/data_stream/asset_vulnerability_summary/fields/ecs.yml
  packages/carbon_black_cloud/data_stream/audit/fields/ecs.yml
  packages/carbon_black_cloud/data_stream/endpoint_event/fields/ecs.yml
  packages/carbon_black_cloud/data_stream/watchlist_hit/fields/ecs.yml
  packages/carbon_black_cloud/docs/README.md
  packages/carbon_black_cloud/manifest.yml
  packages/github/changelog.yml
  packages/github/data_stream/audit/fields/ecs.yml
  packages/github/docs/README.md
  packages/github/manifest.yml
  packages/httpjson/changelog.yml
  packages/httpjson/data_stream/generic/fields/ecs.yml
  packages/httpjson/manifest.yml
  packages/snyk/changelog.yml
  packages/snyk/data_stream/audit/fields/ecs.yml
  packages/snyk/data_stream/vulnerabilities/fields/ecs.yml
  packages/snyk/docs/README.md
  packages/snyk/manifest.yml
  packages/winlog/changelog.yml
  packages/winlog/data_stream/winlog/fields/ecs.yml
  packages/winlog/docs/README.md
  packages/winlog/manifest.yml
Labels: bug, Team:Security-External Integrations

#3165 Update tenable.sc readme
  packages/tenable_sc/_dev/build/docs/README.md
  packages/tenable_sc/changelog.yml
  packages/tenable_sc/docs/README.md
  packages/tenable_sc/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations

#3588 o365: add record types beyond 66
  packages/o365/changelog.yml
  packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/o365/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:o365

#3583 Fix GCP auditlog parsing issue on response status
  packages/gcp/changelog.yml
  packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log
  packages/gcp/data_stream/audit/_dev/test/pipeline/test-audit.log-expected.json
  packages/gcp/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/manifest.yml
Labels: bug, Team:Security-External Integrations

#3569 [AWS] Add Redshift Integration
  packages/aws/_dev/build/docs/redshift.md
  packages/aws/changelog.yml
  packages/aws/data_stream/redshift/_dev/deploy/tf/.terraform.lock.hcl
  packages/aws/data_stream/redshift/_dev/deploy/tf/env.yml
  packages/aws/data_stream/redshift/_dev/deploy/tf/main.tf
  packages/aws/data_stream/redshift/_dev/deploy/tf/variables.tf
  packages/aws/data_stream/redshift/_dev/test/system/test-default-config.yml
  packages/aws/data_stream/redshift/agent/stream/stream.yml.hbs
  packages/aws/data_stream/redshift/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/redshift/fields/base-fields.yml
  packages/aws/data_stream/redshift/fields/ecs.yml
  packages/aws/data_stream/redshift/fields/fields.yml
  packages/aws/data_stream/redshift/fields/package-fields.yml
  packages/aws/data_stream/redshift/manifest.yml
  packages/aws/data_stream/redshift/sample_event.json
  packages/aws/docs/redshift.md
  packages/aws/img/logo_redshift.svg
  packages/aws/img/metricbeat-aws-redshift-overview.png
  packages/aws/kibana/dashboard/aws-81f2c980-e743-11ec-93f6-9b98f71110cd.json
  packages/aws/manifest.yml
Labels: enhancement, Integration:AWS, Team:Cloud-Monitoring

#3607 [Github] Fix pagination and missing fields
  packages/github/changelog.yml
  packages/github/data_stream/audit/_dev/test/pipeline/test-audit-json.log
  packages/github/data_stream/audit/_dev/test/pipeline/test-audit-json.log-expected.json
  packages/github/data_stream/audit/agent/stream/httpjson.yml.hbs
  packages/github/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/github/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Github

#3515 network_traffic: add mappings for process.* fields
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/amqp/fields/beats.yml
  packages/network_traffic/data_stream/amqp/fields/ecs.yml
  packages/network_traffic/data_stream/amqp/sample_event.json
  packages/network_traffic/data_stream/cassandra/fields/beats.yml
  packages/network_traffic/data_stream/cassandra/fields/ecs.yml
  packages/network_traffic/data_stream/cassandra/sample_event.json
  packages/network_traffic/data_stream/dhcpv4/fields/beats.yml
  packages/network_traffic/data_stream/dhcpv4/fields/ecs.yml
  packages/network_traffic/data_stream/dhcpv4/sample_event.json
  packages/network_traffic/data_stream/dns/fields/beats.yml
  packages/network_traffic/data_stream/dns/fields/ecs.yml
  packages/network_traffic/data_stream/dns/sample_event.json
  packages/network_traffic/data_stream/flow/fields/beats.yml
  packages/network_traffic/data_stream/flow/fields/ecs.yml
  packages/network_traffic/data_stream/http/fields/beats.yml
  packages/network_traffic/data_stream/http/fields/ecs.yml
  packages/network_traffic/data_stream/http/sample_event.json
  packages/network_traffic/data_stream/icmp/fields/beats.yml
  packages/network_traffic/data_stream/icmp/fields/ecs.yml
  packages/network_traffic/data_stream/icmp/sample_event.json
  packages/network_traffic/data_stream/memcached/fields/beats.yml
  packages/network_traffic/data_stream/memcached/fields/ecs.yml
  packages/network_traffic/data_stream/memcached/sample_event.json
  packages/network_traffic/data_stream/mongodb/fields/beats.yml
  packages/network_traffic/data_stream/mongodb/fields/ecs.yml
  packages/network_traffic/data_stream/mongodb/sample_event.json
  packages/network_traffic/data_stream/mysql/fields/beats.yml
  packages/network_traffic/data_stream/mysql/fields/ecs.yml
  packages/network_traffic/data_stream/mysql/sample_event.json
  packages/network_traffic/data_stream/nfs/fields/beats.yml
  packages/network_traffic/data_stream/nfs/fields/ecs.yml
  packages/network_traffic/data_stream/nfs/sample_event.json
  packages/network_traffic/data_stream/pgsql/fields/beats.yml
  packages/network_traffic/data_stream/pgsql/fields/ecs.yml
  packages/network_traffic/data_stream/pgsql/sample_event.json
  packages/network_traffic/data_stream/redis/fields/beats.yml
  packages/network_traffic/data_stream/redis/fields/ecs.yml
  packages/network_traffic/data_stream/redis/sample_event.json
  packages/network_traffic/data_stream/sip/fields/beats.yml
  packages/network_traffic/data_stream/sip/fields/ecs.yml
  packages/network_traffic/data_stream/sip/sample_event.json
  packages/network_traffic/data_stream/thrift/fields/beats.yml
  packages/network_traffic/data_stream/thrift/fields/ecs.yml
  packages/network_traffic/data_stream/thrift/sample_event.json
  packages/network_traffic/data_stream/tls/fields/beats.yml
  packages/network_traffic/data_stream/tls/fields/ecs.yml
  packages/network_traffic/data_stream/tls/sample_event.json
  packages/network_traffic/docs/README.md
  packages/network_traffic/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Network Packet Capture

#3593 [Azure] Move container instance metrics from beats to integrations
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/data_stream/container_instance/agent/stream/stream.yml.hbs
  packages/azure_metrics/data_stream/container_instance/elasticsearch/ingest_pipeline/default.yml
  packages/azure_metrics/manifest.yml
Labels: enhancement, Team:Cloud-Monitoring

#3545 [httpjson] Add option to the manifest
  packages/httpjson/changelog.yml
  packages/httpjson/data_stream/generic/agent/stream/httpjson.yml.hbs
  packages/httpjson/data_stream/generic/manifest.yml
  packages/httpjson/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:httpjson

#3627 Move container_service metrics from beats to integrations
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/data_stream/container_service/agent/stream/stream.yml.hbs
  packages/azure_metrics/data_stream/container_service/elasticsearch/ingest_pipeline/default.yml
  packages/azure_metrics/manifest.yml
Labels: enhancement, Team:Cloud-Monitoring

#3433 [docs] Add detailed documentation guidelines
  docs/documentation_guidelines.md
  docs/generic_guidelines.md
Labels: documentation, enhancement, Team:Docs
