Repository elastic/integrations, pull requests merged in 2023-12, with the labels that each got.

#8615 [apache_tomcat.access] Restructure Grok pattern and ingest pipeline to improve performance
  packages/apache_tomcat/changelog.yml
  packages/apache_tomcat/data_stream/access/elasticsearch/ingest_pipeline/default.yml
  packages/apache_tomcat/manifest.yml
Labels: enhancement

#8547 sonicwall_firewall: log host identity and syslog priority
  packages/sonicwall_firewall/changelog.yml
  packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-drizzthacker.log-expected.json
  packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-general.log-expected.json
  packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-nat.log-expected.json
  packages/sonicwall_firewall/data_stream/log/_dev/test/pipeline/test-sonicos70-aws.log-expected.json
  packages/sonicwall_firewall/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/sonicwall_firewall/data_stream/log/fields/ecs.yml
  packages/sonicwall_firewall/data_stream/log/sample_event.json
  packages/sonicwall_firewall/docs/README.md
  packages/sonicwall_firewall/manifest.yml
Labels: enhancement, Team:Security-External Integrations, integration:Sonicwall

#8556 [ti_opencti] Fix processing of externalReferences
  packages/ti_opencti/changelog.yml
  packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-domain-name-with-external-reference.json
  packages/ti_opencti/data_stream/indicator/_dev/test/pipeline/test-domain-name-with-external-reference.json-expected.json
  packages/ti_opencti/data_stream/indicator/elasticsearch/ingest_pipeline/default.yml
  packages/ti_opencti/manifest.yml
Labels: Team:Security-External Integrations, bugfix, Integration:OpenCTI

#8604 Adopt Secrets in Cloud Posture Management
  packages/cloud_security_posture/changelog.yml
  packages/cloud_security_posture/data_stream/findings/manifest.yml
  packages/cloud_security_posture/manifest.yml
Labels: enhancement

#8624 Add null and ignore_missing check to handle event.original field.
  packages/activemq/changelog.yml
  packages/activemq/data_stream/audit/elasticsearch/ingest_pipeline/default.yml
  packages/activemq/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/activemq/manifest.yml
  packages/coredns/changelog.yml
  packages/coredns/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/coredns/manifest.yml
  packages/ibmmq/changelog.yml
  packages/ibmmq/data_stream/errorlog/elasticsearch/ingest_pipeline/default.yml
  packages/ibmmq/manifest.yml
  packages/mongodb/changelog.yml
  packages/mongodb/data_stream/log/elasticsearch/ingest_pipeline/pipeline-json.yml
  packages/mongodb/manifest.yml
  packages/salesforce/changelog.yml
  packages/salesforce/data_stream/apex/elasticsearch/ingest_pipeline/default.yml
  packages/salesforce/data_stream/login_rest/elasticsearch/ingest_pipeline/default.yml
  packages/salesforce/data_stream/login_stream/elasticsearch/ingest_pipeline/default.yml
  packages/salesforce/data_stream/logout_rest/elasticsearch/ingest_pipeline/default.yml
  packages/salesforce/data_stream/logout_stream/elasticsearch/ingest_pipeline/default.yml
  packages/salesforce/data_stream/setupaudittrail/elasticsearch/ingest_pipeline/default.yml
  packages/salesforce/manifest.yml
  packages/spring_boot/changelog.yml
  packages/spring_boot/data_stream/audit_events/elasticsearch/ingest_pipeline/default.yml
  packages/spring_boot/data_stream/http_trace/elasticsearch/ingest_pipeline/default.yml
  packages/spring_boot/manifest.yml
  packages/vsphere/changelog.yml
  packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/vsphere/manifest.yml
Labels: bugfix

#8381 [O11y][Oracle] Add custom number formatting to visualisations
  packages/oracle/changelog.yml
  packages/oracle/img/Oracle-overview-dashboard.png
  packages/oracle/img/Oracle-performance-dashboard.png
  packages/oracle/img/Oracle-sysmetrics-dashboard.png
  packages/oracle/img/Oracle-system_statistics-dashboard.png
  packages/oracle/img/Oracle-tablespace-dashboard.png
  packages/oracle/kibana/dashboard/oracle-55661160-08c7-11ed-9abf-15e60715cfab.json
  packages/oracle/kibana/dashboard/oracle-59eeb380-08d7-11ed-9abf-15e60715cfab.json
  packages/oracle/kibana/dashboard/oracle-6b4866c0-1599-11ed-9607-2ba0819b3835.json
  packages/oracle/kibana/dashboard/oracle-9e19fb00-08e1-11ed-9abf-15e60715cfab.json
  packages/oracle/kibana/dashboard/oracle-b6b2c9f0-13a7-11ed-9607-2ba0819b3835.json
  packages/oracle/manifest.yml
Labels: enhancement, Integration:Oracle, dashboard

#8494 O365 | Add permissions to docs
  packages/o365/_dev/build/docs/README.md
  packages/o365/changelog.yml
  packages/o365/docs/README.md
  packages/o365/manifest.yml
Labels: documentation, Team:Security-External Integrations, Integration:o365

#8653 [cloud_security_posture] Azure rule templates
  packages/cloud_security_posture/changelog.yml
  packages/cloud_security_posture/kibana/csp_rule_template/05676b4e-3274-5984-9981-6aa1623c24ec.json
  packages/cloud_security_posture/kibana/csp_rule_template/05c4bd94-162d-53e8-b112-e617ce74f8f6.json
  packages/cloud_security_posture/kibana/csp_rule_template/43d5538c-17a3-5e04-9c06-ad4323bfd188.json
  packages/cloud_security_posture/kibana/csp_rule_template/4a130791-cdb3-5524-b45d-1f3df79e2452.json
  packages/cloud_security_posture/kibana/csp_rule_template/50da62ee-4099-5950-ba1e-984794749f28.json
  packages/cloud_security_posture/kibana/csp_rule_template/62b717ac-bb8f-5274-a99f-5806dc4427a5.json
  packages/cloud_security_posture/kibana/csp_rule_template/6e6481f1-5ede-552b-84e5-cceed281052a.json
  packages/cloud_security_posture/kibana/csp_rule_template/7c908585-ec93-52dc-81bb-ceb17cd4c313.json
  packages/cloud_security_posture/kibana/csp_rule_template/94fbdc26-aa6f-52e6-9277-094174c46e29.json
  packages/cloud_security_posture/kibana/csp_rule_template/aa4374f0-adab-580c-ac9d-907fd2783219.json
  packages/cloud_security_posture/kibana/csp_rule_template/cd05adf8-d0fe-54b6-b1a0-93cf02bcec72.json
  packages/cloud_security_posture/kibana/csp_rule_template/d7011f2f-cd60-58cf-a184-eb2d5fb7339a.json
  packages/cloud_security_posture/manifest.yml
Labels: enhancement

#8651 Universal Profiling: add privileges section
  packages/universal_profiling_agent/changelog.yml
  packages/universal_profiling_agent/manifest.yml
Labels: enhancement

#8657 [integrations][Exchange Online Message Trace] - Fixed an issue in the httpjson template that caused the integration to break after sometime.
  packages/microsoft_exchange_online_message_trace/_dev/deploy/docker/files/config.yml
  packages/microsoft_exchange_online_message_trace/changelog.yml
  packages/microsoft_exchange_online_message_trace/data_stream/log/agent/stream/httpjson.yml.hbs
  packages/microsoft_exchange_online_message_trace/manifest.yml
Labels: integration, bugfix, 8.11 candidate

#8314 [GCP] Add dimensions for metrics data streams
  packages/gcp/changelog.yml
  packages/gcp/data_stream/cloudrun_metrics/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/cloudrun_metrics/fields/ecs.yml
  packages/gcp/data_stream/cloudrun_metrics/fields/package-fields.yml
  packages/gcp/data_stream/cloudsql_mysql/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/cloudsql_mysql/fields/ecs.yml
  packages/gcp/data_stream/cloudsql_mysql/fields/package-fields.yml
  packages/gcp/data_stream/cloudsql_postgresql/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/cloudsql_postgresql/fields/ecs.yml
  packages/gcp/data_stream/cloudsql_postgresql/fields/package-fields.yml
  packages/gcp/data_stream/cloudsql_sqlserver/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/cloudsql_sqlserver/fields/ecs.yml
  packages/gcp/data_stream/cloudsql_sqlserver/fields/package-fields.yml
  packages/gcp/data_stream/compute/_dev/test/pipeline/test-gcp-compute.json-expected.json
  packages/gcp/data_stream/compute/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/compute/fields/ecs.yml
  packages/gcp/data_stream/compute/fields/package-fields.yml
  packages/gcp/data_stream/dataproc/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/dataproc/fields/ecs.yml
  packages/gcp/data_stream/dataproc/fields/package-fields.yml
  packages/gcp/data_stream/firestore/fields/ecs.yml
  packages/gcp/data_stream/gke/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/gke/fields/ecs.yml
  packages/gcp/data_stream/gke/fields/package-fields.yml
  packages/gcp/data_stream/loadbalancing_metrics/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/loadbalancing_metrics/fields/ecs.yml
  packages/gcp/data_stream/loadbalancing_metrics/fields/package-fields.yml
  packages/gcp/data_stream/pubsub/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/pubsub/fields/ecs.yml
  packages/gcp/data_stream/pubsub/fields/package-fields.yml
  packages/gcp/data_stream/redis/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/redis/fields/agent.yml
  packages/gcp/data_stream/redis/fields/ecs.yml
  packages/gcp/data_stream/redis/fields/package-fields.yml
  packages/gcp/data_stream/storage/elasticsearch/ingest_pipeline/default.yml
  packages/gcp/data_stream/storage/fields/ecs.yml
  packages/gcp/data_stream/storage/fields/package-fields.yml
  packages/gcp/data_stream/storage/manifest.yml
  packages/gcp/docs/README.md
  packages/gcp/docs/cloudrun.md
  packages/gcp/docs/cloudsql.md
  packages/gcp/docs/compute.md
  packages/gcp/docs/dataproc.md
  packages/gcp/docs/gke.md
  packages/gcp/docs/loadbalancing.md
  packages/gcp/docs/pubsub.md
  packages/gcp/docs/redis.md
  packages/gcp/docs/storage.md
  packages/gcp/manifest.yml
Labels: Integration:GCP

#8661 [cloud_security_posture] 8.12 version bump
  packages/cloud_security_posture/changelog.yml
  packages/cloud_security_posture/manifest.yml
Labels: enhancement

#8659 [IIS Access Log]: Update documentation for custom log processing
  packages/iis/_dev/build/docs/README.md
  packages/iis/changelog.yml
  packages/iis/docs/README.md
  packages/iis/manifest.yml
Labels: enhancement

#8487 Add `cribl` integration package
  .github/CODEOWNERS
  packages/cribl/_dev/build/build.yml
  packages/cribl/changelog.yml
  packages/cribl/data_stream/logs/elasticsearch/ingest_pipeline/default.yml
  packages/cribl/data_stream/logs/fields/base-fields.yml
  packages/cribl/data_stream/logs/fields/ecs.yml
  packages/cribl/data_stream/logs/manifest.yml
  packages/cribl/docs/README.md
  packages/cribl/img/catalog-cisco-asa.png
  packages/cribl/img/cribl-source-fields.png
  packages/cribl/img/custom-pipeline-reroute-processor.png
  packages/cribl/img/install-assets.png
  packages/cribl/img/logo.svg
  packages/cribl/img/sample-event-dataset-name.png
  packages/cribl/manifest.yml
Labels: enhancement, Team:Security-External Integrations, New Integration

#8667 [Bug] fix missing reference for filter in dashboard
  packages/azure_billing/changelog.yml
  packages/azure_billing/kibana/dashboard/azure_billing-d3efeb30-c1c7-11ea-b7e7-0f48178cdb3c.json
  packages/azure_billing/manifest.yml
Labels: bug, Integration:AWS

#8675 infoblox_nios: fix handling of messages containing view field
  packages/infoblox_nios/changelog.yml
  packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log
  packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
  packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
  packages/infoblox_nios/data_stream/log/fields/fields.yml
  packages/infoblox_nios/docs/README.md
  packages/infoblox_nios/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Infoblox_nios

#8608 [EDR Workflows] Adjust Sentinel One Cloud Funnel mappings to support Analyzer - entity_id
  packages/sentinel_one_cloud_funnel/changelog.yml
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-command-script.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-cross-process.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-dns.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-file.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-indicator.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-login.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-module.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-network-action.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-process.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-registry.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-scheduled-task.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-threat-intelligence-indicator.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/_dev/test/pipeline/test-url.log-expected.json
  packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/default.yml
  packages/sentinel_one_cloud_funnel/data_stream/event/elasticsearch/ingest_pipeline/pipeline-process.yml
  packages/sentinel_one_cloud_funnel/manifest.yml
Labels: Team:Security-External Integrations, Integration: SentinelOne Cloud Funnel

#8679 [Cloud Security] Remove disabled fields
  packages/cloud_security_posture/changelog.yml
  packages/cloud_security_posture/data_stream/findings/fields/resource.yml
  packages/cloud_security_posture/data_stream/findings/fields/result.yml
  packages/cloud_security_posture/manifest.yml
Labels: Team:Cloud Security

#8681 [trendmicro] Add better ECS categorization for `event.type` and `event.category`
  packages/trendmicro/changelog.yml
  packages/trendmicro/data_stream/deep_security/_dev/test/pipeline/test-trendmicro.json-expected.json
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/application-control-event.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/default.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/firewall-event.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/integrity-monitoring-event.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/intrusion-prevention-event.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/log-inspection.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/malware-event.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/system-event.yml
  packages/trendmicro/data_stream/deep_security/elasticsearch/ingest_pipeline/web-reputation.yml
  packages/trendmicro/data_stream/deep_security/sample_event.json
  packages/trendmicro/manifest.yml
Labels: bug, Integration:TrendMicro

#8678 network_traffic: add process.parent.pid remapping to compatibility pipelines
  packages/network_traffic/changelog.yml
  packages/network_traffic/data_stream/amqp/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/cassandra/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/dhcpv4/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/dns/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/flow/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/http/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/icmp/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/memcached/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/mongodb/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/mysql/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/nfs/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/pgsql/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/redis/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/sip/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/thrift/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/data_stream/tls/elasticsearch/ingest_pipeline/compatibility.yml
  packages/network_traffic/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Network Packet Capture

#8666 Azure Logs - Extend storage account settings
  packages/azure/_dev/build/docs/README.md
  packages/azure/changelog.yml
  packages/azure/docs/README.md
  packages/azure/manifest.yml
Labels: documentation, enhancement

#8673 Azure metrics - Expand OS guest metrics section
  packages/azure_metrics/_dev/build/docs/compute_vm.md
  packages/azure_metrics/changelog.yml
  packages/azure_metrics/docs/compute_vm.md
  packages/azure_metrics/manifest.yml
Labels: documentation, enhancement

#8629 [cloudflare_logpush] Fix logic on http_request rename processors
  packages/cloudflare_logpush/changelog.yml
  packages/cloudflare_logpush/data_stream/http_request/_dev/test/pipeline/test-pipeline-http-request.log
  packages/cloudflare_logpush/data_stream/http_request/_dev/test/pipeline/test-pipeline-http-request.log-expected.json
  packages/cloudflare_logpush/data_stream/http_request/elasticsearch/ingest_pipeline/default.yml
  packages/cloudflare_logpush/data_stream/http_request/fields/fields.yml
  packages/cloudflare_logpush/docs/README.md
  packages/cloudflare_logpush/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Cloudflare Logpush

#8701 [Apache Tomcat]: Improve wording on milliseconds
  packages/apache_tomcat/changelog.yml
  packages/apache_tomcat/data_stream/connection_pool/fields/fields.yml
  packages/apache_tomcat/docs/README.md
  packages/apache_tomcat/manifest.yml
Labels: documentation, enhancement

#8704 [MongoDB]: Improve wording on milliseconds
  packages/mongodb/changelog.yml
  packages/mongodb/data_stream/status/fields/fields.yml
  packages/mongodb/docs/README.md
  packages/mongodb/manifest.yml
Labels: documentation, enhancement

#8705 [PostgreSQL]: Improve wording on milliseconds
  packages/postgresql/changelog.yml
  packages/postgresql/data_stream/statement/fields/fields.yml
  packages/postgresql/docs/README.md
  packages/postgresql/manifest.yml
Labels: documentation, enhancement

#8706 [System]: Improve wording on milliseconds
  packages/system/changelog.yml
  packages/system/data_stream/diskio/fields/fields.yml
  packages/system/docs/README.md
  packages/system/manifest.yml
Labels: documentation, enhancement

#8702 [Auth0]: Improve wording on milliseconds
  packages/auth0/changelog.yml
  packages/auth0/data_stream/logs/fields/fields.yml
  packages/auth0/docs/README.md
  packages/auth0/manifest.yml
Labels: documentation, enhancement

#8695 cisco_secure_email_gateway: handle and record log host origin filepaths
  packages/cisco_secure_email_gateway/_dev/deploy/docker/sample_logs/authentication.example.com.@123456789.s
  packages/cisco_secure_email_gateway/changelog.yml
  packages/cisco_secure_email_gateway/data_stream/log/_dev/test/system/test-logfile-config.yml
  packages/cisco_secure_email_gateway/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_secure_email_gateway/data_stream/log/fields/fields.yml
  packages/cisco_secure_email_gateway/docs/README.md
  packages/cisco_secure_email_gateway/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:CiscoSecureEmailGateway

#8670 [Fortigate] Fix startsWith for null value and add support for login events
  packages/fortinet_fortigate/changelog.yml
  packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet.log
  packages/fortinet_fortigate/data_stream/log/_dev/test/pipeline/test-fortinet.log-expected.json
  packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/event.yml
  packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/login.yml
  packages/fortinet_fortigate/data_stream/log/fields/ecs.yml
  packages/fortinet_fortigate/data_stream/log/fields/fields.yml
  packages/fortinet_fortigate/docs/README.md
  packages/fortinet_fortigate/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Fortinet

#8726 Add CIS Azure 6.1 Rule Template
  packages/cloud_security_posture/kibana/csp_rule_template/b4133ca4-32f1-501e-ad0a-a22700208a4f.json
Labels: enhancement

#8122 [VMware] Add more vSphere/ESXi logs
  packages/vsphere/_dev/build/build.yml
  packages/vsphere/_dev/deploy/docker/Dockerfile
  packages/vsphere/_dev/deploy/docker/docker-compose.yml
  packages/vsphere/changelog.yml
  packages/vsphere/data_stream/datastore/elasticsearch/ingest_pipeline/default.yml
  packages/vsphere/data_stream/host/elasticsearch/ingest_pipeline/default.yml
  packages/vsphere/data_stream/log/_dev/test/pipeline/test-format-common.log
  packages/vsphere/data_stream/log/_dev/test/pipeline/test-format-common.log-expected.json
  packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/dns.yml
  packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/file.yml
  packages/vsphere/data_stream/log/elasticsearch/ingest_pipeline/login.yml
  packages/vsphere/data_stream/log/fields/ecs.yml
  packages/vsphere/data_stream/log/fields/fields.yml
  packages/vsphere/data_stream/virtualmachine/elasticsearch/ingest_pipeline/default.yml
  packages/vsphere/docs/README.md
  packages/vsphere/manifest.yml
Labels: enhancement, bugfix

#8716 auditd: handle ENRICHED auditd format
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-enriched.log
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-enriched.log-expected.json
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/data_stream/log/fields/fields.yml
  packages/auditd/docs/README.md
  packages/auditd/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Auditd

#8648 [azure_application_insights] Enable TSDB
  packages/azure_application_insights/changelog.yml
  packages/azure_application_insights/data_stream/app_insights/manifest.yml
  packages/azure_application_insights/data_stream/app_state/manifest.yml
  packages/azure_application_insights/manifest.yml
Labels: Integration:Azure

#8736 [AWS Guardduty] Update expired certificate in system test
  packages/aws/data_stream/guardduty/_dev/deploy/docker/files/certificate.crt
  packages/aws/data_stream/guardduty/_dev/deploy/docker/files/private.key
  packages/aws/data_stream/guardduty/_dev/test/system/test-default-config.yml
  packages/aws/data_stream/guardduty/sample_event.json
  packages/aws/docs/guardduty.md
Labels: Integration:AWS

#8715 crowdstrike: allow aidmaster metadata to be retained after host enrichment
  packages/crowdstrike/changelog.yml
  packages/crowdstrike/data_stream/fdr/agent/stream/aws-s3.yml.hbs
  packages/crowdstrike/data_stream/fdr/agent/stream/stream.yml.hbs
  packages/crowdstrike/data_stream/fdr/manifest.yml
  packages/crowdstrike/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Crowdstrike

#8465 [Enhancement] [integration] Add EclecticIQ Advanced CSV Outgoing feed integration
  .github/CODEOWNERS
  packages/ti_eclecticiq/_dev/build/build.yml
  packages/ti_eclecticiq/_dev/build/docs/README.md
  packages/ti_eclecticiq/_dev/deploy/docker/config.yml
  packages/ti_eclecticiq/_dev/deploy/docker/docker-compose.yml
  packages/ti_eclecticiq/changelog.yml
  packages/ti_eclecticiq/data_stream/threat/_dev/test/pipeline/test-outgoing-feed-event.json
  packages/ti_eclecticiq/data_stream/threat/_dev/test/pipeline/test-outgoing-feed-event.json-expected.json
  packages/ti_eclecticiq/data_stream/threat/_dev/test/system/test-default-config.yml
  packages/ti_eclecticiq/data_stream/threat/agent/stream/input.yml.hbs
  packages/ti_eclecticiq/data_stream/threat/elasticsearch/ilm/default_policy.json
  packages/ti_eclecticiq/data_stream/threat/elasticsearch/ingest_pipeline/default.yml
  packages/ti_eclecticiq/data_stream/threat/fields/base-fields.yml
  packages/ti_eclecticiq/data_stream/threat/fields/ecs.yml
  packages/ti_eclecticiq/data_stream/threat/fields/fields.yml
  packages/ti_eclecticiq/data_stream/threat/manifest.yml
  packages/ti_eclecticiq/data_stream/threat/sample_event.json
  packages/ti_eclecticiq/docs/README.md
  packages/ti_eclecticiq/elasticsearch/transform/latest_ioc/fields/base-fields.yml
  packages/ti_eclecticiq/elasticsearch/transform/latest_ioc/fields/ecs.yml
  packages/ti_eclecticiq/elasticsearch/transform/latest_ioc/fields/fields.yml
  packages/ti_eclecticiq/elasticsearch/transform/latest_ioc/manifest.yml
  packages/ti_eclecticiq/elasticsearch/transform/latest_ioc/transform.yml
  packages/ti_eclecticiq/img/logo_RGB.svg
  packages/ti_eclecticiq/manifest.yml
Labels: Team:Security-External Integrations, New Integration

#8612 [Cisco ASA] Fix GROK to add support for spaces and special characters in usernames
  packages/cisco_asa/changelog.yml
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sample.log-expected.json
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sgt-tag-name.log
  packages/cisco_asa/data_stream/log/_dev/test/pipeline/test-sgt-tag-name.log-expected.json
  packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_asa/manifest.yml
Labels: Team:Security-External Integrations, Integration:CiscoASA, bugfix

#8709 [aws][cloudwatch_metrics] Fix the issue with the fingerprint field
  packages/aws/changelog.yml
  packages/aws/data_stream/cloudwatch_metrics/elasticsearch/ingest_pipeline/default.yml
  packages/aws/data_stream/cloudwatch_metrics/fields/package-fields.yml
  packages/aws/docs/cloudwatch.md
  packages/aws/manifest.yml
Labels: bug

#8740 [Cisco IOS] Add support for BADAUTH events
  packages/cisco_ios/changelog.yml
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-badauth.log
  packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-badauth.log-expected.json
  packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ios/data_stream/log/fields/fields.yml
  packages/cisco_ios/docs/README.md
  packages/cisco_ios/manifest.yml
Labels: enhancement, Integration:CiscoIOS

#8748 auditd: relax field_split pattern and handle AVC header
  packages/auditd/changelog.yml
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log
  packages/auditd/data_stream/log/_dev/test/pipeline/test-auditd-raw.log-expected.json
  packages/auditd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/auditd/data_stream/log/fields/fields.yml
  packages/auditd/docs/README.md
  packages/auditd/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:Auditd

#8746 [Cribl] Updating setup guidance for Cribl field
  packages/cribl/docs/README.md
  packages/cribl/img/cribl-source-fields.png
  packages/cribl/img/custom-pipeline-reroute-processor.png
Labels: docs

#8744 [ti_opencti] Support OpenCTI 5.12.X by removing filters parameter
  packages/ti_opencti/_dev/build/docs/README.md
  packages/ti_opencti/changelog.yml
  packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
  packages/ti_opencti/docs/README.md
  packages/ti_opencti/manifest.yml
Labels: enhancement, bugfix, Integration:OpenCTI

#8760 misp: parse URIs for URI type threats
  packages/ti_misp/changelog.yml
  packages/ti_misp/data_stream/threat_attributes/_dev/test/pipeline/test-misp-sample-ndjson.log
  packages/ti_misp/data_stream/threat_attributes/_dev/test/pipeline/test-misp-sample-ndjson.log-expected.json
  packages/ti_misp/data_stream/threat_attributes/elasticsearch/ingest_pipeline/default.yml
  packages/ti_misp/data_stream/threat_attributes/sample_event.json
  packages/ti_misp/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:MISP

#8768 [Rapid7 InsightVM] Split vulnerability categories into array
  packages/rapid7_insightvm/changelog.yml
  packages/rapid7_insightvm/data_stream/vulnerability/_dev/test/pipeline/test-vulnerability.log-expected.json
  packages/rapid7_insightvm/data_stream/vulnerability/elasticsearch/ingest_pipeline/default.yml
  packages/rapid7_insightvm/data_stream/vulnerability/sample_event.json
  packages/rapid7_insightvm/docs/README.md
  packages/rapid7_insightvm/manifest.yml
Labels: Team:Security-External Integrations, bugfix

#8767 [Infoblox NIOS] Update timestamp parsing logic
  packages/infoblox_nios/changelog.yml
  packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_audit.yml
  packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
  packages/infoblox_nios/manifest.yml
Labels: Team:Security-External Integrations, Integration:Infoblox_nios, bugfix

#6954 [Arista NG Firewall] Add Dashboards to Beta Integration
  packages/arista_ngfw/changelog.yml
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-090e6d40-1dc4-11ee-b346-5b9e0073e798.json
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-0f3dafe6-c66a-4d1e-a9e9-fa3fb418bfaf.json
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-2b026f60-1cf1-11ee-b346-5b9e0073e798.json
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-3565dc44-1886-49aa-b8d3-523623e605dc.json
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-86b139ff-92ab-4aae-b0d8-c33e3be132f1.json
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-93596b63-d808-4a2f-9cbf-d0e9c4003079.json
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-a4bb8521-b9d4-4d33-be52-b4ccefb2eee1.json
  packages/arista_ngfw/kibana/dashboard/arista_ngfw-c61b1eb0-1cf7-11ee-b346-5b9e0073e798.json
  packages/arista_ngfw/kibana/search/arista_ngfw-6cf3b505-142c-436a-9625-97800660e36f.json
  packages/arista_ngfw/kibana/search/arista_ngfw-746674eb-991f-47d4-a42b-b7b205db4b9b.json
  packages/arista_ngfw/kibana/search/arista_ngfw-78edcde0-20ee-11ee-8ab3-fb5b73d7bd73.json
  packages/arista_ngfw/kibana/search/arista_ngfw-b0ac29e8-0a25-4f59-a59d-10065bb70af3.json
  packages/arista_ngfw/kibana/search/arista_ngfw-b0ca4590-1cf7-11ee-b346-5b9e0073e798.json
  packages/arista_ngfw/kibana/search/arista_ngfw-da69ba6a-8008-4b1c-9fa9-fde67de3d129.json
  packages/arista_ngfw/kibana/visualization/arista_ngfw-ffee4a67-2bf6-4c3a-881a-026232d2e8c3.json
  packages/arista_ngfw/manifest.yml
  packages/arista_ngfw/validation.yml
Labels: Team:Security-External Integrations, Integration:Arista NGFW

#8397 Infoblox cannot deal with broken DNS data due to long message
  packages/infoblox_nios/changelog.yml
  packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log
  packages/infoblox_nios/data_stream/log/_dev/test/pipeline/test-dns.log-expected.json
  packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/infoblox_nios/data_stream/log/elasticsearch/ingest_pipeline/pipeline_dns.yml
  packages/infoblox_nios/manifest.yml
Labels: bug, enhancement, Team:Security-External Integrations, Integration:Infoblox_nios

#8131 [GitHub] [Dependabot] event duration was in seconds, should be in nanos
  packages/github/changelog.yml
  packages/github/data_stream/dependabot/_dev/test/pipeline/test-ghas-dependabot-json.log-expected.json
  packages/github/data_stream/dependabot/elasticsearch/ingest_pipeline/default.yml
  packages/github/manifest.yml
Labels: bug, Team:Security-External Integrations, Integration:Github, bugfix

#8404 [O11Y] [GCP Billing] Update Legacy metrics in GCP Billing overview dashboard
  packages/gcp/changelog.yml
  packages/gcp/img/gcp-billing.png
  packages/gcp/kibana/dashboard/gcp-76c9e920-e890-11ea-bf8c-d13ebf358a78.json
  packages/gcp/manifest.yml
  packages/gcp/validation.yml
Labels: enhancement, Integration:GCP, dashboard

#8797 Rollback Cloud Security Posture Secrets Adoption
  packages/cloud_security_posture/changelog.yml
  packages/cloud_security_posture/data_stream/findings/manifest.yml
  packages/cloud_security_posture/manifest.yml
Labels: bug

#8798 [Cisco FTD] Fix the handling of spaces in 113005 messages
  packages/cisco_ftd/changelog.yml
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log
  packages/cisco_ftd/data_stream/log/_dev/test/pipeline/test-ftd-fix.log-expected.json
  packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/cisco_ftd/manifest.yml
Labels: Team:Security-External Integrations, Integration:CiscoFTD, bugfix

#8799 [cloud_security_posture] Rollback CIS Azure rules 9.3 and 9.10
  packages/cloud_security_posture/changelog.yml
  packages/cloud_security_posture/kibana/csp_rule_template/43d5538c-17a3-5e04-9c06-ad4323bfd188.json
  packages/cloud_security_posture/kibana/csp_rule_template/6e6481f1-5ede-552b-84e5-cceed281052a.json
  packages/cloud_security_posture/manifest.yml
Labels: bugfix

#8791 Tolerate suffixes on the OpenCTI instance URL
  packages/ti_opencti/changelog.yml
  packages/ti_opencti/data_stream/indicator/agent/stream/cel.yml.hbs
  packages/ti_opencti/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:OpenCTI

#8795 [o365] Add note about Token URL in the setup guide
  packages/o365/_dev/build/docs/README.md
  packages/o365/changelog.yml
  packages/o365/docs/README.md
  packages/o365/manifest.yml
Labels: documentation, enhancement, Team:Security-External Integrations, Integration:o365

#8806 [vectra_detect] Add Support for New Event Type vectra_json
  packages/vectra_detect/_dev/deploy/docker/sample_logs/vectra_detect.log
  packages/vectra_detect/changelog.yml
  packages/vectra_detect/data_stream/log/_dev/test/pipeline/test-host-detection.log
  packages/vectra_detect/data_stream/log/_dev/test/pipeline/test-host-detection.log-expected.json
  packages/vectra_detect/data_stream/log/elasticsearch/ingest_pipeline/default.yml
  packages/vectra_detect/data_stream/log/sample_event.json
  packages/vectra_detect/docs/README.md
  packages/vectra_detect/manifest.yml
Labels: enhancement, Team:Security-External Integrations, Integration:VectraDetect

#8782 Disable otherBucket option in the panels of ingest pipeline details
  packages/elasticsearch/changelog.yml
  packages/elasticsearch/kibana/dashboard/elasticsearch-ea5b81a0-7fbf-11ed-8509-ddabeb9daeaf.json
  packages/elasticsearch/manifest.yml
Labels: bug
